### ISSUE TITLE
ldap_connect() host with port signature deprecated for PHP 8.3

### ISSUE THREAD

**Issue by andrewnicols** [ADOdb/ADOdb#1009]
### Description
The secondary signautre for `ldap_connect()` which explicitly provides a host and port has been deprecated from PHP 8.3 onwards.
A Uri should be used instad.

https://wiki.php.net/rfc/deprecations_php_8_3#deprecate_calling_ldap_connect_with_2_parameters

### Environment
- ADOdb version: master (478c9cfea84b94ed2e8f131b6d6eb453bfda5db0)
- Driver or Module: ldap
- Database type and version: any
- PHP version: 8.3
- Platform: any

* [ ] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / **master** branch / **hotfix** branch  
  ⚠️ Keep only the applicable option(s), i.e. where you actually tested and remove the others)

### Steps to reproduce
See use of `@ldap_connect()` with multiple arguments here: https://github.com/ADOdb/ADOdb/blob/478c9cfea84b94ed2e8f131b6d6eb453bfda5db0/drivers/adodb-ldap.inc.php#L71
```
			$this->_connectionID = @ldap_connect( $conn_info[0], $conn_info[1] );
```

**Comment by dregad** [comment]
@andrewnicols out of curiosity, are you actually using the LDAP driver, or is this coming out of some static analysis ?

**Comment by andrewnicols** [comment]
No, we're not using it outselves, but I went through all of the RFC changes for the PHP 8.3 release and hunted for potential issues across our codebase. We do let our users configure a wide range of ADOdb database types for their use, but it turns out that ldap isn't one of them.

I should add that I misread the RFC and that one isn't targetted until PHP 8.4. The RFC was identified as PHP 8.3 but many of the changes are only intended for 8.4 and I missed that in my initial assessment.

**Comment by dregad** [comment]
Thanks for the feedback.

I was just checking because since I took over ADOdb maintenance back in 2013 I think this is the first time anyone ever opened an issue about the LDAP driver so I was curious to find out whether someone was actually using it.

> I misread the RFC and that one isn't targetted until PHP 8.4. The RFC was identified as PHP 8.3 but many of the changes are only intended for 8.4 and I missed that in my initial assessment.

You're confusing me here... I see no mention of 8.4 in the RFC

**Comment by andrewnicols** [comment]
Then I'm confused too!

The vote for the proposal to deprecate it lists this as being targetted at 8.4 -- see the header of the vote table here:
https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#ldap_connect

But as you say it landed in PHP 8.3.

**Comment by dregad** [comment]
@andrewnicols actually there are 2 distinct RFCs around ldap_connect()

- [Deprecate calling ''ldap_connect'' with 2 parameters](https://wiki.php.net/rfc/deprecations_php_8_3#deprecate_calling_ldap_connect_with_2_parameters) targets PHP 8.3
- [Deprecate functions with overloaded signatures](https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#ldap_connect) targets PHP 8.4 and targets the rarely-used and undocumented 5 parameters version, which is only available when PHP is compiled with OracleLDAP. We don't use that signature in ADOdb.

**Comment by dregad** [comment]
@mnewnham I see you assigned this issue to yourself and created a branch, but it does not contain any commits... did you forget to push your changes ?

**Comment by mnewnham** [comment]
@dregad, I'm building an Active Directory server to test with, haven't yet had time to complete changes......

**Comment by dregad** [comment]
I could use my work's AD to test if you want to spare yourself the trouble of setting that up. The fix should be quite straightforward, but I don't want to step on your toes, so let me know if you want me to fix this otherwise I'll just wait for your PR.

**Comment by mnewnham** [comment]
Thats OK It's done now.

**Comment by dregad** [comment]
Great, let me know when it's ready to review, I'll give it a test run.

I see that you've updated the [documentation page](https://adodb.org/dokuwiki/doku.php?id=v5:database:ldap) - that's great, I was actually considering doing it. Thanks.

> The following usage method is deprecated in PHP8.2 and will not work with PHP 8.3

I fully agree that this crappy array format for options initialized via a global variable needs to go away, but I'm a bit confused by the reference to PHP 8.2/8.3, what's the relationship ?

> From ADOdb 5.22.7, default values set are as follows

Good idea to preset LDAP_OPT_PROTOCOL_VERSION and LDAP_OPT_REFERRALS to sensible 2023 values.

That would be 5.22.8 or 5.23.0 though.
