### ISSUE TITLE
adodb.org PHP warnings

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#1022]
Do you updated the PHP version there and current Dokuwiki release not yet ready for that PHP version?

For instance

`Warning: Trying to access array offset on value of type bool in /xxx/dokuwiki/inc/Ui/Recent.php on line 166`
or 

```
Warning: Undefined array key "htmlmetatags" in /xxx/dokuwiki/lib/plugins/htmlmetatags/syntax/syntax.php on line 121

Warning: Undefined array key "keywords" in /xxx/dokuwiki/lib/plugins/htmlmetatags/syntax/syntax.php on line 121
```

**Comment by dregad** [comment]
Thanks for the heads up. Maybe the hosting provider upgraded PHP, I need to check.

**Comment by dregad** [comment]
Yep, it appears PHP was automatically upgraded to 8.1 by the provider, as 8.0 went out of support end 2023.
I forced a downgrade to 8.0 (as it was before) and the warnings went away.

When I have some spare time, I'll upgrade DokuWiki to the latest version 2024-02-06a Kaos, which hopefully will have fixes for those compatibility issues. But this requires careful testing to ensure all the plugins we use are compatible.

**Comment by dregad** [comment]
Actually, it would appear that 8.0 also shows those warnings, but not all the time... I set PHP version to 7.4.

I reported the issues with htmlmetatags plugin upstream, https://github.com/heikoS2C/htmlmetatags/issues/6.

**Comment by Neustradamus** [comment]
@peterdd: Good news, the @dregad PR has been merged in upstream.

I think that https://www.dokuwiki.org/plugin:htmlmetatags can be updated now...

**Comment by dregad** [comment]
> I think that https://www.dokuwiki.org/plugin:htmlmetatags can be updated now...

Thank you but it already was, I patched it manually back in March.

**Comment by Neustradamus** [comment]
@dregad: I think it is needed to create tag/release version in upstream, what do you think?
