### ISSUE TITLE
mysqli driver ADODB_FETCH_DEFAULT unexpected results

### ISSUE THREAD

**Issue by nephifey** [ADOdb/ADOdb#1023]
### Description

Is the current way the ADODB_FETCH_DEFAULT mode works expected, specifically for the ADODB_mysqli driver? It seems like the implementation has driver specific code within the recordset that indicates it should pull data similar to ADODB_FETCH_BOTH (MYSQLI_BOTH - numerical and field name):

**ADORecordSet_mysqli::__construct**
```
switch ($mode) {
	case ADODB_FETCH_NUM:
		$this->fetchMode = MYSQLI_NUM;
		break;
	case ADODB_FETCH_ASSOC:
		$this->fetchMode = MYSQLI_ASSOC;
		break;
	case ADODB_FETCH_DEFAULT:
	case ADODB_FETCH_BOTH:
	default:
		$this->fetchMode = MYSQLI_BOTH;
		break;
}
```

The main recordset code has an exception in the code if the mode is ADODB_FETCH_BOTH that will return an associative array as expected, so ADODB_FETCH_BOTH works great, but there is not an exception in the code if the mode is ADODB_FETCH_DEFAULT. If the below code is removed and you are using ADODB_FETCH_BOTH it acts the same way as ADODB_FETCH_DEFAULT. 

**ADORecordSet::getAssoc**

```
if ($fetchMode == ADODB_FETCH_BOTH) {
	/*
	* If we are using BOTH, we present the data as if it
	* was in ASSOC mode. This could be enhanced by adding
	* a BOTH_ASSOC_MODE class property
	* We build a template of numeric keys. you could improve the
	* speed by caching this, indexed by number of keys
	*/
	$testKeys = array_fill(0,$numberOfFields,0);
}

...

if ($fetchMode == ADODB_FETCH_BOTH) {
        /*
        * extract the associative keys
        */
        $myFields = array_diff_key($myFields,$testKeys);
}
```

I understand ADODB_FETCH_DEFAULT is driver specific, but the driver uses MYSQLI_BOTH when ADODB_FETCH_DEFAULT is used, but then getAssoc does not return an associative array as you would expect. A basic fix/workaround for me as of now is setting the fetch mode upfront to ADODB_FETCH_ASSOC. Maybe that is just what I should do now and this isn't really an issue?

### Environment
- ADOdb version: 5.22.7
- Driver or Module: ADODB_mysqli
- Database type and version: MySQL 8.0.32
- PHP version: 7.4.33
- Platform: Centos Linux

### Steps to reproduce

Create a connection and leave the fetch mode set to the default (ADODB_FETCH_DEFAULT). Execute getAssoc directly on the connection or on the recordset and an unexpected result is returned compared to older versions of ADOdb.

```
// connect
$db = ADONewConnection("mysqli");
$db->connect(DB_SERVER, DB_USER, DB_PASS, DB_SCHEMA);

// output some details
$fetchModeMap = [
	ADODB_FETCH_DEFAULT => "default (driver specific)",
	ADODB_FETCH_NUM => "numeric",
	ADODB_FETCH_ASSOC => "associative",
	ADODB_FETCH_BOTH => "both",
];

$extension_yn = !empty($GLOBALS["ADODB_EXTENSION"]) ? "yes" : "no";
$php_version = phpversion();
echo "extension: {$extension_yn}\n";
echo "fetchmode: {$fetchModeMap[$GLOBALS["ADODB_FETCH_MODE"]]}\n";
echo "php version: {$php_version}\n\n";

// temp table for example
$tmp_table = $db->execute("
	CREATE TEMPORARY TABLE `lookup_example` (
	  `name` VARCHAR(45) NOT NULL,
	  `value` VARCHAR(45) NULL,
	  `id` INT NOT NULL AUTO_INCREMENT,
	  PRIMARY KEY (`id`)
    ) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4
");

// populate temp table with dummy results
foreach ([
	 "NAME1" => "Name1 description",
	 "NAME2" => "Name2 description",
	 "NAME3" => "Name3 description",
] as $name => $value) {
	$db->execute("INSERT INTO `lookup_example` (`name`, `value`) VALUES ({$db->qstr($name)}, {$db->qstr($value)})");
}

// normal execution and access of associative values
$results = $db->execute("SELECT `name`, `value` FROM `lookup_example`");
foreach ($results as $result) {
	echo "{$result["name"]}: {$result["value"]}\n";
}

// move back to start and pull associative on recordset
$results->move(0);
echo "\n";
print_r($results->getassoc());
```

**Output from above snippet on 5.22.7:**
```
extension: no
fetchmode: default (driver specific)
php version: 7.4.33

NAME1: Name1 description
NAME2: Name2 description
NAME3: Name3 description

Array
(
    [NAME1] => NAME1
    [NAME2] => NAME2
    [NAME3] => NAME3
)
```

### Expected behavior

The system this is impacting is currently running on ADOdb 5.19, which does not have have the above behavior and instead produces the result that we expect. I've experienced the same behavior above in other versions above 5.19 as well. I know there have been other issues in the past with getAssoc that I've seen, so maybe this is related.

**Output from above snippet on 5.19:**
```
extension: no
fetchmode: default (driver specific)
php version: 7.4.33

NAME1: Name1 description
NAME2: Name2 description
NAME3: Name3 description

Array
(
    [NAME1] => Name1 description
    [NAME2] => Name2 description
    [NAME3] => Name3 description
)
```

**Comment by dregad** [comment]
Thanks for the detailed bug report; providing a script to reproduce is particularly appreciated 😃.

> A basic fix/workaround for me as of now is setting the fetch mode upfront to ADODB_FETCH_ASSOC

That is indeed a valid workaround; I actually do this systematically in my code; I never liked the default of returning both numeric and associative. I guess that's why I never noticed this issue :wink:

Anyway this sounds like a bug, as the behavior of ADODB_FETCH_DEFAULT is not consistent with that of ADODB_FETCH_BOTH, and they're supposed to be the same.

According to git bisect, the new (wrong) behavior was introduced in commits 
- 2b1d3e66532e6ef6a07d65ac8d3533185f7fe00b (#350) for 5.21 branch 
- 32a479a182c86f4b15c337ca6b1d3f4b967e37a8 (#101) for 5.20 branch

I can't analyze what those commits changed and why at the moment, but will do as time allows.
