### ISSUE TITLE
html not rendered on adodb.org

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#1025]
![adodb_htmlext](https://github.com/ADOdb/ADOdb/assets/1839154/3ad3ad5c-b2a1-4368-8b38-4874b93c9321)

On several pages it seems that pure html in the wiki pages is used.
Used some of the dokuwiki html extensions before? And now removed or deactivated? Or the priority of the extensions is messed up?

**Comment by dregad** [comment]
Thanks for the report. 

I think the latest version of dokuwiki is not allowing  embedded html anymore, but I'm not sure about the original contents of that t page. I will have a look at it. 

Let me know if you notice any other pages with such problems.

**Comment by mnewnham** [comment]
This is just stuff I scraped from the original documentation when I built the site. No need to retain it, we should just clean it up

**Comment by peterdd** [comment]
I changed now the formatting to dokuwiki syntax on

https://adodb.org/dokuwiki/doku.php?id=v5:performance:expensivesql

and 

https://adodb.org/dokuwiki/doku.php?id=v5:performance:suspicioussql

at least.

**Comment by dregad** [comment]
I replaced the HTML output by sample screenshots.
