### ISSUE TITLE
ADOdb-5.22.0 and newer do not work correctly with databases pretending to be MySQL and not supporting prepared statements

### ISSUE THREAD

**Issue by pakud** [ADOdb/ADOdb#1028]
### Description

ADOdb-5.22 introduced 'mysql: Support bound variable statements #655'

this made ADOdb no longer usable with database engines speaking MySQL wire protocol but not implementing prepared statements - e.g. [ClickHouse](https://github.com/ClickHouse/ClickHouse) and [Manticore Search](https://github.com/manticoresoftware/manticoresearch).

could you please provide a feature-switch allowing to fall back to the old implementation where ADOdb does not use bound variables?

### Environment
- ADOdb version: 5.22.7
- Driver or Module: mysqli
- Database type and version: ClickHouse 24.3.2.23-lts, Manticore search 6.2.12
- PHP version:  8.2.18
- Platform: Debian 12, x64

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) 

### Steps to reproduce
Detailed, step-by-step instructions to reproduce the behavior, including:

for manticore:
```
require_once('ADOdb-5.22.7/adodb.inc.php'); // this one does not either     
$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;                                      
$ADODB_COUNTRECS=false;                                                     
$db=adoNewConnection('mysqli://u:p@127.0.0.1/db?port=9306');                
                                                                            
$db->debug = false;                                                         
print_r($db->GetArray('select * from mantisrt where id=? limit 1',[10]));   
```

results in:
```
SQL Statement failed on preparation: select * from mantisrt where id=? limit 1'
```

for clickhouse:
```
require_once('ADOdb-5.22.7/adodb.inc.php'); // this one does not either                                                 
$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;                                                                                  
$ADODB_COUNTRECS=false;                                                                                                 
$db=adoNewConnection('mysqli://login:pass@host/db?port=9004');
$db->debug = false;                                                                                                           
print_r($db->GetArray('select * from table where month=? and name=? limit 1',['2020-01','fofi'])); 
```
results in:
```
Input array has 2 params, does not match query: 'select * from table  where month=? and name=? limit 1'
```

### Expected behavior
query executed without errors

### Additional context 

could you please consider adding a feature flag that's off by default and having this at the very beginning of drivers/adodb-mysqli.inc.php - method execute:

```
public function execute($sql, $inputarr = false)        
{                                                       
  if ($this->doNotUseBoundVariables)
    return parent::execute($sql, $inputarr );       

  // intact version of the execute method follows
```

thanks a lot for considering this one and maintenance of ADOdb!

**Comment by mnewnham** [comment]
1. I didn't realize such databases existed!
2. Emulated bind statements in the ADOdb MySQL driver were raised as a serious security issue over a number of years. The usage in public facing sites is strongly discouraged.

That being said, as you have effectively built out the changes, you can just branch the code and create a pull request.

**Comment by pakud** [comment]
@mnewnham thanks a lot for quick feedback! i've created [PR ](https://github.com/ADOdb/ADOdb/pull/1029)

thanks in advance for reviewing it!

**Comment by pakud** [comment]
@dregad , @mnewnham - thanks a lot for quick review and merging it!
