### ISSUE TITLE
Missing extension for firebird

### ISSUE THREAD

**Issue by Aphyxia** [ADOdb/ADOdb#1038]
### Description
I have installed and required the latest ADOdb with composer. First I got fatal errors of IBASE_WAIT, IBASE_REC_VERSION and IBASE_COMMITTED constants not being defined. I assigned random values to those and afterwards was able to test the connection, however I got the error "Missing extension for firebird".
What extension am I meant to have been installed?

Looking at the documentation for the firebird driver https://adodb.org/dokuwiki/doku.php?id=v5:database:firebird
I read that there are native drivers for PHP 7.4+ and that ADOdb uses their own driver. That's cool but as an instructional manual is very unclear as to what the user needs to do.

### Environment
- ADOdb version: 5.22.7
- Driver or Module: firebird
- PHP version: 8.3 / 8.2
- Platform: Ubuntu

### Steps to reproduce
`define('IBASE_WAIT', 300);
define('IBASE_REC_VERSION', 3);
define('IBASE_COMMITTED', 3);
$driver = 'firebird';
$db = newAdoConnection($driver);
$db->connect('<snip>database.fdb', 'user', 'password');`

**Comment by mnewnham** [comment]
You need to install the appropriate Firebird PHP driver. ADODb sits on top of this driver. You can find the appropriate driver at  [https://github.com/FirebirdSQL/php-firebird/](https://github.com/FirebirdSQL/php-firebird/)

**Comment by Aphyxia** [comment]
That's what I thought. Thank you for the reply.
Unfortunately the server I'm working with does not allow installing those packages.
