### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [ADOdb/ADOdb#1041]
Dear @ADOdb team, @dregad, @heyjohnlim,

It will be nice to remove old parts like:
- https://sourceforge.net/p/adodb/mailman/
- https://sourceforge.net/p/adodb/_list/tickets

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/adodb/

To disable/delete tabs, go here: https://sourceforge.net/projects/adodb/
To add a new tab, go here: https://sourceforge.net/projects/adodb/
To change informations, go here: https://sourceforge.net/p/adodb/admin/overview
To export, go here: https://sourceforge.net/p/adodb/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/adodb/admin/overview

Thanks in advance.

**Comment by dregad** [comment]
Thanks, but we will not be doing this.

The Project has not "moved", only the source code and issue tracker is now on GitHub; SourceForge is still the official download location, and the home page is https://adodb.org as indicated pretty much everywhere.

- SourceForge tickets are kept, read-only, for historical / archiving reasons
- Mailing lists, while not actively used nowadays, are still operational

**Comment by Neustradamus** [comment]
@dregad: Thanks for your quick answer.

Can you add the "move" box?

**Comment by dregad** [comment]
Sorry, but no. As mentioned before *The Project has not "moved"*.
