### ISSUE TITLE
Session Connection Object Persistance Clarification

### ISSUE THREAD

**Issue by mariobernheim** [ADOdb/ADOdb#1046]
Hello - does the default connection configuration of Adodb for sessions default to persist or to not persist?

**Comment by dregad** [comment]
Connections are not persistent, unless specifically opened as such using the pConnect() method.

**Comment by dregad** [comment]
Thanks for the clarification, I'm sorry I did not realize you were referring to the Sessions module.

Connections for ADODB_Sessions are persistent by default. You can change this by calling 
```php
ADOdb_Session::persist(false);
```
Before starting the session, as explained in [the documentation](https://adodb.org/dokuwiki/doku.php?id=v5:session:session_index#non-persistent_connections).
