### ISSUE TITLE
PHP 8.4.x support

### ISSUE THREAD

**Issue by Neustradamus** [ADOdb/ADOdb#1051]
Dear @ADOdb team, @dregad,

It is possible to add the PHP 8.4.x support?

2024-11-21: PHP 8.4.1 has been released.
- https://www.php.net/

Thanks in advance.

**Comment by dregad** [comment]
Of course we will support PHP 8.4.

Did you notice any specific compatibility issues other than #1036 ? If so, please open specific issues with the details (e.g. deprecation messages, errors, etc. 

Thanks

**Comment by Neustradamus** [comment]
@dregad: I wish you a Happy New Year 2025!

Have you progressed on this ticket?
