### ISSUE TITLE
MySQL AutoExecute fails on YEAR field

### ISSUE THREAD

**Issue by NyroTheCat** [ADOdb/ADOdb#113]
Hello Everyone,

i'm experiencening an issue. One of my tables contains a YEAR Field. On `AutoExecute` the value isn't saved proberly. Here's an example.
```php
// PHP
$array = array('year' => 1990);
$conn -> AutoExecute('Table', $array, 2, 'id = 1');
```

The sql statement will be
```sql
# MySQLi
UPDATE Table SET YEAR='1970-01-01' WHERE id = 1
```

The resulting statement always sets the YEAR to 1970, not matter if the given PHP value is string or int.

**Comment by dregad** [comment]
I'm not able to reproduce this on latest master (or v5.19 for that matter). 

``` sql
CREATE TABLE a (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  year int(11) NOT NULL,
  UNIQUE KEY `id` (`id`)
);
INSERT INTO a (year) VALUES (2015);
```

``` php
<?php
include('adodb.inc.php');
$db = ADONewConnection('mysqli');
$db->Connect('localhost', 'root', '', 'test');
$fields = array('year' => 1990);
$db->debug = true;
$db->AutoExecute('a', $fields, 2, 'id = 1');
```
Generated SQL is as follows, and AutoExecute works just fine:

```
(mysqli): UPDATE a SET YEAR=1990 WHERE id = 1
```
