### ISSUE TITLE
GetAssoc no longer works properly

### ISSUE THREAD

**Issue by CreatrixTeam** [ADOdb/ADOdb#114]
The commit at "https://github.com/ADOdb/ADOdb/commit/32a479a182c86f4b15c337ca6b1d3f4b967e37a8" has broken the behavior of GetAssoc.

When calling the function on an expected two column data, we used to get:
Array 
(
    [colA_1] => colB_1 
    [colA_2] => colB_2 
)
which is the correct behavior per the documentation. Now we get:
Array 
( 
    [colA_1] => colA_1 
    [colA_2] => colA_2 
)

**Comment by dregad** [comment]
can you please provide sample code

**Comment by CreatrixTeam** [comment]
We are currently investigating the issue, and shall attempt to give you an example. So far we think the error is due to the newest code assuming that an array is either associate or numerically index, where in fact it could be both, and the old code we tracked would treat an array that is at least numeric to be numeric. The newer code appears to only detect fully numeric arrays as numeric. We are of course talking about the logical condition.

**Comment by dregad** [comment]
> code assuming that an array is either associate or numerically indexed, where in fact it could be both

Ah yes that makes sense. 

Well if you can come up with a better solution, that addresses both this issue and the one described in #101 (and fixed by 32a479a182c86f4b15c337ca6b1d3f4b967e37a8), your fix will be welcome.

Looking forward to your feedback.

**Comment by CreatrixTeam** [comment]
Thank you for the reply. We shall get back to you with a suggestion as soon as we can.

**Comment by CreatrixTeam** [comment]
This problem is multi layered, and fixing that boolean line is not enough. The following is the fix for the boolean line only:
Add the following function to the class:

/*
 * returns true if current row is numeric or false otherwise.
 * warning: can return true if the associative keys happens to be exactly named as the
 *		numeric keys. Solving this is logically impossible from just examining
 *		the $this->fields array.
 */
function IsCurrentRowNumeric()
{
	$vAssociativeKeys = array();
	$vNumericKeys = array();
	$vAssociativeSubset = array();
	$vNumericSubset = array();
	$vAssociativeKeysCount = -1;
	$vNumericKeysCount = -1;

	foreach($this->fields as $tKey => $tValue)
	{
		if(ctype_digit(trim($tKey)))
		{
			$vNumericKeys[] = $tKey;
			$vNumericSubset[$tValue] = $tValue;
		}
		else
		{
			$vAssociativeKeys[] = $tKey;
			$vAssociativeSubset[$tValue] = $tValue;
		}
	}

	$vAssociativeKeysCount = count($vAssociativeKeys);
	$vNumericKeysCount = count($vNumericKeys);

	if(($vNumericKeysCount === $this->_numOfFields) && 
			($vNumericKeysCount === $vAssociativeKeysCount))
		{return true;}
	else if($vNumericKeysCount > $vAssociativeKeysCount)
	{
		if($vNumericKeysCount != range(0, $this->_numOfFields - 1))
			{return false;}
		foreach($vAssociativeSubset as $tValue)
		{
			if(!array_key_exists($tValue, $vNumericSubset))
				{return false;}
		}
		return true;
	}
	else
		{return false;}
}

And replace the boolean line:
$numIndex = array_keys($this->fields) == range(0, count($this->fields) - 1);

With:
$numIndex = $this->IsCurrentRowNumeric();


Notes:
- History of the issue (ordered oldest to newest):
   - http://phplens.com/lens/lensforum/msgs.php?id=19190
   - http://sourceforge.net/p/adodb/bugs/130/
   - https://github.com/ADOdb/ADOdb/issues/101
   - https://github.com/ADOdb/ADOdb/issues/114

- This only fixes one part of the problem. However this is guaranteed to return true on an array that is at least numerically indexed.

- The second part of the problem is that the rest of the code needs to account for the following:
   1- An array could be completely numerically indexed.
   2- An array could be completely numerically indexed, but is associative in truth. The keys simply happen to match expected numeric indices. This can not be solved by looking at the array only. However it should be a very unlikely cause to problems in practice.
   3- An array could be completely associative.
   4- An array could be both associative and numerically keyed. In this case there are two sub cases:
        4a - The array was built by filing the numeric keys then the associative keys.
        4b - The array was built by filling the associative keys then the numeric keys.

- The function given above is clearly computationally expensive. To speed things up is another problem.

- Note that the function returns the correct result for the issues in the history, but the rest of the code is not guaranteed to. You can test this by simply replacing the line with:
$numIndex = true; 
test and then replace again with:
$numIndex = false;
and test. You shall find both returning wrong results, at least for the first problem in the history.

- You might want to change the code styling on the function to meet your styles.

**Comment by CreatrixTeam** [comment]
There was an error in the proposed code above. Update the comment above with the fix.

**Comment by CreatrixTeam** [comment]
@dregad 

We apologize if you are getting a second notification on this issue, but we are unsure what triggers notifications on github, therefore we are trying the "at" notation. We are hoping to get you to take a look at the proposed fix.

**Comment by dregad** [comment]
I got it the first time, don't worry. Just too busy these days to spend any time on ADOdb.

I would recommend, instead of posting random code snippets like this, that you create feature branches in your fork and commit your changes there, then submit pull requests. This will not only ensure we have a clear referential to reviewing the code, but also facilitate the review process and eventual merging. Thanks in advance.

**Comment by CreatrixTeam** [comment]
Thank you for the confirmation. We shall look into creating multiple forks.

**Comment by dregad** [comment]
> We shall look into creating multiple forks.

Branches, not forks...


-- 
*Damien Regad*
Ch. de Trémessaz 4, 1222 Vésenaz, Suisse
Mobile: +41 79 615 3403
e-mail: damien@regad.org

**Comment by CreatrixTeam** [comment]
Thank you for the clarification. We are still new at this as you can see.

**Comment by mnewnham** [comment]
@dregad asked me to review this for possible inclusion of a fix by @CreatrixTeam into 5.20.0. I ran the following test case against the DB2 driver:
```php
$db->setFetchMode(ADODB_FETCH_ASSOC);

$sql = "SELECT 'test', NULL, 'should be element 1' from sysibm.sysdummy1 ";
$a = $db->GetAssoc($sql);
print_r($a);
```
The following output was produced:
```php
[test] => Array
        (
            [2] =>
            [3] => should be element 1
        )
```
As can be seen, the element numbering is off by 2, not 1. I'm not sure that the proposed fix would work in this case. I also have no idea why the numeric offsets are working like that. I have suggested that we do not include this patch for the imminent next release.

**Comment by mnewnham** [comment]
In the test scenario I referenced above, I was browsing the code of the current master, and came upon a small issue. 
```php

 @@ -3424,8 +3424,8 @@ function GetAssoc($force_array = false, $first2cols = false) {
 						$keys = array_slice(array_keys($this->fields), 1);
 						$sliced_array = array();
 
-						foreach($keys as $key) {
-							$sliced_array[$key] = $this->fields[$key];
+						foreach($keys as $index=>$key) {
+							$sliced_array[$index] = $this->fields[$key];
 						}
 
 						$results[trim(reset($this->fields))] = $sliced_array;
```
Once changed, the scenario now works correctly in MySQL:
```php
SELECT 'test', NULL, 'should be element 1'
```
Oracle:
```php
SELECT 'test', NULL, 'should be element 1' FROM dual
```
DB2:
```php
SELECT 'test', NULL, 'should be element 1' from sysibm.sysdummy1
```
The mssqlnative driver should be able to execute:
```php
SELECT 'test', NULL, 'should be element 1'
```
But the statement actually crashes in associative mode elsewhere in the driver. I will address this later.

Thoughts and comments please.

Mark

The commit is here: https://github.com/ADOdb/ADOdb/commit/fd4f85bfe7607b4704c0416dc984393b9b7b9c77

**Comment by CreatrixTeam** [comment]
Thank you @mnewnham  for your investment in this matter. 

Please keep in mind that we do most of what we are doing with ADODB through code analysis. For example, the premise of this commit is that the original line

$numIndex = is_array($this->fields) && array_key_exists(0, $this->fields);

was to "determine whether the recordset's fields was a numerically 0-based indexed array" per the wording of https://github.com/ADOdb/ADOdb/commit/32a479a182c86f4b15c337ca6b1d3f4b967e37a8, which was the original commit that lead to this report. A fix was issued through that commit given this premise. However, simple analysis reveals that that line, and avoiding full contradiction of the same premise, was to detect if an array is at least numerically indexed.

Now you could challenge whether our fix meets the premise. 
Or you could accept the fix meets the premise and go up one step, and challenge whether the premise is true. 
Or you could accept the premise is true and go up one step and challenge whether the premise should be true. At this level and higher, however, analysis no longer pertain to this commit. In simple terms the problem is much deeper; the entire history of this issue has been that line and this is what the scope of our commit is. 


Please reread the following from our previous comments, and our code comments. We are posting some snippets here for convenience:

----1----
(From our jun 6 comment above)
2- An array could be completely numerically indexed, but is associative in truth. The keys simply happen to match expected numeric indices. This can not be solved by looking at the array only. However it should be a very unlikely cause to problems in practice.
----------


----2----
(From our jun 6 comment above)
This only fixes one part of the problem. However this is guaranteed to return true on an array that is at least numerically indexed.
----------

----3----
(From our jun 6 comment above)
Note that the function returns the correct result for the issues in the history, but the rest of the code is not guaranteed to. You can test this by simply replacing the line with:
 $numIndex = true; 
 test and then replace again with:
 $numIndex = false;
 and test. You shall find both returning wrong results, at least for the first problem in the history.
----------

----4----
(From the code comments for the introduced function "IsCurrentRowNumeric", commit https://github.com/CreatrixTeam/ADOdb/commit/9d21aa39b9b2a19295a400f9d5af557af19fea56)
* returns true if current row is at least numericaly indexed or false otherwise. 
* warning: can return true if the associative keys happens to be exactly named as the 
*		numeric keys. Solving this is logically impossible from just examining 
*		the $this->fields array. 
* note: can return false when the array is both associative and numerically indexed, but  
*		the numericaly indexed portion is corrupt. This happens when the original array is 
*		created with numeric indices, then associative indices, and some of the associative 
*		indices are the same as the numeric indices. 
----------



A number of notes to draw from the above:
1- The fix itself is not sufficient.
2- No sufficient fix can exist for fixing the problem at this scope.


If your suggestion to include not this fix on the next release is out of caution, we can not argue with that.
If your suggestion to include not this fix on the next release is out of believe that this fix is wrong, you would have to challenge the logic. Needles to say, if the logic is correct, it matters not whether the rest of the code works or breaks. It would simply mean the problem is else where.



Regarding your latest note above, we can not help at this time, but a quick look of what you posted immediately raised alarm bells.


Thank you again for your investment in this matter.

**Comment by mnewnham** [comment]
From a results-orientated perspective:  The code did not work before, and now it does. I do not wish to appear flippant about this, but for many of us, this is sufficient. however, as I am prepared to invest more time in this:

As I indicated in my posting, I offered the snippet up for 'comments and suggestions', not as closure to this problem. What I am trying to reinforce with this tweak to the code is that a number of complex fixes have been proposed for this issue, but they are all based around layering further levels of data analysis and restructuring on top of what is clearly a flawed procedure.  This particular code set is clearly one that has suffered the classic patches  of patches of patches through the years, and it's efficiency and functionality have suffered.  

What we really need to do is 'burn down' this function, simplify it, and then we can make sure that it is robust enough to handle the most obscure data sets. without reliance on another layer of if-then-else, array_slices and array_keys

**Comment by mnewnham** [comment]
I was trying to debug the SQL Server native driver, the results of which you can find here - [https://github.com/Azure/msphpsql/issues/62] and that got me thinking about the function itself - trying to 'guess' what type of array the data is is always going to have some margin of error, so what if we eliminated the entire requirement altogether. So I cooked up this 15 minute prototype for a replacement, maybe we should think about it this way?

```php
function getAssoc($force_array = false, $first2cols = false) {

        global $ADODB_EXTENSION;
        
		  if ($this->_numOfFields < 2)
			  return;
        
		/*
         * Key is always value of first element
		 * Value is a numeric array of fields
         */
		$showArrayMethod = 0;
		
        if ($this->_numOfFields == 2)
            /*
            * Key is always value of first  element
			* Value is alway value of second element
            */
            $showArrayMethod = 1;
        
        if ($force_array)
            $showArrayMethod = 0;
        
		if ($first2cols)
            $showArrayMethod = 1;

        $results = array();
        
        while (!$this->EOF){
        
            $myFields = $this->fields;
             /*
              * key is value of first element, rest is data,
			  * casing is already handled by the driver
              */
            $key = array_shift($myFields);
            			
            switch ($showArrayMethod){
            case 0:
                
				/*
                 * Don't care whether its assoc or numeric, 
                 * I want the values in a numeric array,
				 * nicely re-indexed from zero
                 */
                $results[$key] = array_values($myFields);
                break;
            
			case 1:
                
				/*
                 * Don't care how long the array is,
                 * I just want value of second column
                 */
                $results[$key] = array_shift($myFields);
                break;
            }
   
            if ($ADODB_EXTENSION)
				/*
			     * Don't really need this either except for 
				 * old version compatibility
				 */
                adodb_movenext($this);
            else
               $this->MoveNext();
        }        
        /*
		 * Done
		 */
        return $results;
    }
```

**Comment by CreatrixTeam** [comment]
Thank you for your continued effort @mnewnham .

It appears that we are now agreeing on what we said earlier. As for the proposed solutions, we have not enough knowledge at this point to help. Our efforts are currently concentrated elsewhere. However I am looking at your implementation, and it does not appear sufficiently equivalent to the the previous implementation. In this discussion, sufficient equivalence is defined as follows:

Given the function F such as it maps the space S to T, and the transformed function F' such as it maps the space S' to T';
F:  S -> T
F': S' -> T'

then F' is sufficiently equivalent to F if, and only if, F'(s) = F(s) for all s in S.

It should be noted that the spaces S, S', T and T' also include error input and thrown errors. Sufficient equivalence can be difficult to achieve to impossible. However there are fuzzy ways to relax the requirement, but this is outside the scope of this discussion. It should also be noted that sufficient equivalence is only truly needed on public methods/exposed API. On large enough projects, it would also be needed on protected methods.

The point is, if an introduced change does not meet the requirement of sufficient equivalence, something will break. Another important point, is that the four spaces mentioned earlier need to be well defined. Common runtime errors, and security problems arise due to the lack of enforcement of well defined source and target spaces.

Regarding this particular matter, If I remember correctly, the conclusion arrived at at the time was that the problem was outside the scope of the entire GetAssoc() function, and not just the scope of that line our commit addressed. There were also theoretical situations where no solution could exist at any scope. 

Of course, we could be wrong about the entire thing.

**Comment by mnewnham** [comment]
The getassoc method has been completely rewritten for 5.21, which should address these issues. See 9f84f5bec4ecda734ebe5df20575527701acbf3d

**Comment by tyronx** [comment]
@mnewnham you say it has been rewritten for 5.21, but there is no such version to download from https://adodb.org - am i missing something?

I ran into the same problem after upgrading adodb. getAssoc() no longer works as intended.
