### ISSUE TITLE
Broken FetchField function in adodb-pdo.inc.php

### ISSUE THREAD

**Issue by CreatrixTeam** [ADOdb/ADOdb#121]
The commit https://github.com/ADOdb/ADOdb/commit/a36f5c4276f7bbf8fc79039a950b0c68d06d2099 which was intended for coding guidelines broke the FetchField method. The commit replaced:

if (ADODB_ASSOC_CASE == 0) $o->name = strtolower($o->name);
else if (ADODB_ASSOC_CASE == 1) $o->name = strtoupper($o->name);
return $o;

with 

switch(ADODB_ASSOC_CASE == 0) {
	case ADODB_ASSOC_CASE_LOWER:
		$o->name = strtolower($o->name);
		break;
	case ADODB_ASSOC_CASE_UPPER:
		$o->name = strtoupper($o->name);
		break;
	default:
		return $o;
}

which are not equivalent. The function now returns nothing sometimes.

**Comment by dregad** [comment]
Should have been `switch(ADODB_ASSOC_CASE) {` and move the return out of the switch statement. Sorry about that.

**Comment by dregad** [comment]
Proposed fix in PR #122
