### ISSUE TITLE
GetAssocKeys and GetRowAssoc

### ISSUE THREAD

**Issue by EyeAndTea** [ADOdb/ADOdb#131]
The API of these two functions is misleading. Two consecutive calls to these functions with different parameters will give wrong results. You might also want to refer to our comment for https://github.com/ADOdb/ADOdb/issues/20. Either:
- The parameters to these functions should be removed, which, according to our examination of the entire code, should be safe.
- Or the current behavior of caching in _bind should be fixed, and fields should likely need to always retain the associative keys in their native format. (Such conversions should only happen on call time.) 

The second approach above is our preferred approach as it would be in line with the original documentation. If we are misunderstanding something perhaps, we appreciate a clarification.

**Comment by dregad** [comment]
> Two consecutive calls to these functions with different parameters will give wrong results. 

Example ?

**Comment by CreatrixTeam** [comment]
Define $Return as the non boolean, non empty, return from the function "Execute" for a database select statement. The second call below returns the wrong result:

$Return->GetRowAssoc(ADODB_ASSOC_CASE_LOWER);
$Return->GetRowAssoc(ADODB_ASSOC_CASE_UPPER);

The second call would behave like the first due to the caching; the returned array would not be keyed with upper cases variables.

**Comment by mnewnham** [comment]
This patch is outdated and needs rebasing if you are still interested in working with this. In addition it appears to break the case insensitivity of the DB2 driver. It needs to be rethought and re-discussed. If you want to restart the discussion feel free to re-open the discussion

**Comment by EyeAndTea** [comment]
Thank you. But to be fair, the patch must be tested with the fork on eyeandtea. Under the hood, things have changed much with that fork, and the code is much more stable than the main fork when I last checked. Also the issues opened under this account, including this issue, were all fully resolved in that fork, if I remember correctly, especially this particular issue. I would be happy to work at some point with you, and submit the entire fork as one big patch, but I make no promises as to when. Let me know.
