### ISSUE TITLE
Unwanted replacement of '?' within strings in ocipo driver

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#132]
As reported by @mnewnham by e-mail.

Issue with the adodb-oci8po.inc.php driver,  the scenario is this:

An SQL statement is sent that contains a ? character in a string field, e.g. 

```
SELECT * FROM users WHERE user_code = 'ABC?DEF'
```

adodb sees the ? field, and assumes it is for a bind variable. The number of variables then no longer matches the number passed, and crashes the function. I recognize it's pretty obscure (I've been using the driver for more than 10 years and this is the first time i've seen it) There may however be some security repercussions as it may allow bind variables to be passed in via fillin fields.

**Comment by CreatrixTeam** [comment]
One could perhaps check the immediate previous and after characters of ? and act accordingly. If the following assumption holds, this should likely work for most scenarios:
- The ? character is followed and preceded by either a space, a comma, a bracket, an operation, or nothing.

A full solution would require encoding of any inputs, processing of the ? characters, and then decoding.
