### ISSUE TITLE
Incorrect behavior of MetaColumns on some drivers

### ISSUE THREAD

**Issue by CreatrixTeam** [ADOdb/ADOdb#133]
Looking at code we found that the function MetaColumns is expected  to return an array such as the keys of the array are all upper cased. This is evident by the code of ADODB_DataDict::ChangeTableSQL in the file "adodb-datadict.inc.php", which would return bad results if MetaColumns does not uppercase the keys. All drivers were examined and it was found that indeed all of them uppercase the keys of the returned array. with the following exceptions:

- "adodb-postgres64.inc.php", and "adodb-pdo_pgsql.inc.php": These two drivers incorrectly check the normalize parameter, which is meant to indicate whether to normalize the table name, not the keys on the returned array.
- "adodb-netezza.inc.php": Same problem as above.
- "adodb-sapdb.inc.php": This driver does not upper case the keys at all.
- "adodb-informix72.inc.php": This driver lower cases the keys instead of upper casing them. However further analysis is required to confirm whether this is a bug, a potential bug, or not a bug at all.

Fixing the above should be easy for the first three drivers mentioned , however we can not currently release a new proposal because our branches are piling up. We hope this gets fixed as quickly as possible.

**Comment by mnewnham** [comment]
Is this behavior not controllable by the definition of `ADODB_ASSOC_CASE` constant?

**Comment by CreatrixTeam** [comment]
No, and it should not be. If keys are associate, they should be upper cased. This has been the case with all drivers except the exceptions we mentioned, as well as the expectations of calling libraries, mainly ADODB Data Dictionary, and failure on ADODB Data Dictionary causes failure with AXMLS.

**Comment by mnewnham** [comment]
I'm not sure why you think that associative keys must be upper cased. I have 1.8 million lines of code that expect associative keys to be lower cased. That is what the constants are for, to provide the adodb results in the way somebody wants to use them. 

For any change to the product that affects the **default** behavior of the product, the first issue to consider is always backwards compatibility. If the functions currently return, by default, the values in lower case, then a user has created code that relies on that, and we cannot break that functionality. If the project was in beta, the idea of introducing a standard could be considered. But it's not, so lets not go down any path that might cause an issue to any of the thousands of people who've downloaded this product.

So,the question again: does ADODB_ASSOC_CASE control the casing of the keys correctly? If it does, then we must consider the issue closed. If not, then lets add an issue to the bugtracker related to that.

**Comment by dregad** [comment]
> For any change to the product that affects the default behavior of the product, the first issue to consider is always backwards compatibility. If the functions currently return, by default, the values in lower case, then a user has created code that relies on that, and we cannot break that functionality.

Couldn't have said it better, thanks @mnewnham

**Comment by CreatrixTeam** [comment]
Please examine the code yourself, and re read what we said carefully. The first three drivers we mentioned use a parameter in a wrong manner. This makes it a flow regardless of upper or lower casing. 

As for lower or upper casing, we explicitly said:
    "Fixing the above should be easy for the first three drivers mentioned "
and for the driver "adodb-informix72.inc.php", which is the only driver that lower cases, we said:
    "However further analysis is required to confirm whether this is a bug, a potential bug, or not a bug at all."

If we not clear in the original comment, we examined all drivers, and they all upper case. ADODB Data Dictionary, which is part of ADODB, expects upper casing. This is clearly a flow. Making the casing dependent on ADODB_ASSOC_CASE would make it a new feature for that function. Please examine the code yourself.

**Comment by mnewnham** [comment]
We seem to be going in circles here. From a product support perspective, if there has been an unreported inconsistency for 15+ years, then anyone who has used the driver without forcing the casing of the result  using ADODB_ASSOC_CASE expects the **default behavior** of the function to return the result in lower case.  It matters not whether you feel that is incorrect behavior, we must continue to provide that. 

The whole point of the ADODB_ASSOC_CASE constant is to override the default behavior of the function, so that a developer can use a consistent cross-database behavior.

**Comment by CreatrixTeam** [comment]
Have you even taken a look at the return of MetaColumns? We are talking about the keying of the returned array, not the actual names of the columns. Please examine the code yourself. ADODB_ASSOC_CASE is not relevant here.

**Comment by mnewnham** [comment]
Well, as I personally wrote the MetaColumns function for the mssqlnative driver, the entire sapdb driver and completed the function for db2, I suppose I must have done. What I haven't done, however, is looked at the function for the database you are complaining about, as I've never used it. As a community effort, we rely on people like yourself to present comprehensible descriptions of problems, with examples and suggested solutions. 

so this is what works:

1. Identify a problem
2. Post the issue, with a code snippet and a description of what is being returned and what is wrong with it.
3. If you have a fix, post a snippet for that. If the fix looks ok to the community, post a pull request
4. If a discussion starts with feedback that you don't like, don't start flaming. If the person that has responded has misunderstood what you are trying to show, improve your explanation. Treat an issue here just as you treat an issue at your place of work

This is what doesn't work

Increasingly strident demands to 'read the code'.  You clearly have expertise and have already done some excellent work for the project, but every posting should not turn into a confrontation if there is a response that is not 100% in immediate agreement with you. 

So back to the issue at hand,,,,,

1. Yes, I agree some of the metacolumns functions do not respect the $normalize argument. 
2. Again, we must respect users who have coded their applications expecting the returned data of this function to be keyed lower case.
3. I would suggest perhaps that we should consider branching the code for a major release which might include this and other suggested changes, which includes **well documented** behavioral changes to defaults . @dregad , what is your opinion on this?

**Comment by CreatrixTeam** [comment]
Suggestion to read the code is to ensure the person fully understands the issue before speaking. If the person does not, how would you suggest we deal with it. We are very busy, and spend considerable amount of time investigation before commenting. The least we can expect is the one responding responds with knowledge. We do not want to spend time re explaining things. However, if we have offended you, one apologies. It is never the intention of our comments to offend.

Elsewhere you spoke about AXMLS, and to make one thing clear, we are yet to make any changes to AXMLS, but we are indeed getting AXMLS to be more and more stable. This is a consequence, not the aim.

The issue is bugs in the underlying core code. This particular issue is one such example. Try using ADODB itself, not AXMLS, and see if you can get it working fully on multiple databases with full usage of the API. You simply can not. The first three drivers mentioned before give different semantic to the same function parameters, not simply not respect the arguments! Different to implementations in other drivers and documentation. ADODB Data Dictionary itself would fail and has with our work on it.

This seems to be a situation where a bug has become a feature

**Comment by mnewnham** [comment]
A few points

1. This is a community project. 
2. There are no service level agreements.
3. Everyone associated with the support of this is simply volunteering their time to help you, within their expertise and limits of the time they have available.
4.  There may be no-one currently in the community who knows anything about the databases you are working, in which case, you are already the expert,
5. You may be busy, but remember that to write this response, I am diverting time from the work I am paid to do. 
6. If the work you are doing is so critical that it is imperative to have responses and fixes in shortened timescales, perhaps you should consider offering a financial incentive to have this done. Currently, you are demanding that we provide time-critical support to your business at no cost.
7.  I recognize that English is not your first language, and I understand that non-technical conversations like this can be difficult . Nuance is everything, and perhaps you do not recognize how critical you appear.

However, let me make a single definitive statement:
It is absolutely possible to use ADODB as an extraction layer across multiple distinct databases. My company sells software to the US Government that runs ***unmodified** across MySQL, Oracle, SQL Server and IBM DB2. We have delivered more than 100 units,  and the software contains around 9000 adodb Execute statements, without a single database specific construction. 

**This cross-database compatibility was achieved by me personally contributing the fixes necessary to the adodb project for the drivers we wanted to use.**

If the databases you wish to use do not have this cross-compatibilty, this is your opportunity to  contribute and improve the product. You can work with us and be recognized for your contributions. 

Alternatively, and this is the beauty of the open source model, you can simply fork the code and make it work exactly the way you want it. There are already more than 50 forks of the project, so obviously there are many people out there who wanted something out of the project that was not available.

**Comment by CreatrixTeam** [comment]
Thank you. We made no demands nor spoke with the tone suggested. Please follow carefully the progression of this conversation. We appreciate whatever contributions you yourself made, are thankful to them, and do not deny your experience. However the project's maintainer himself made a commit few days back fixing a glaring bug, yet he had not experienced it for many years as he said so himself. Further more, the databases you mentioned can not be the very drivers we mentioned because they are for different databases. What errors we experienced, we experienced. We do not deny your experience and we can not deny ours.

This shall be our last response to such comments from you.

**Comment by dregad** [comment]
@CreatrixTeam 

I understand that English is probably not your primary language, but you have to consider that you *do* occasionally come across as arrogant even if I'm sure it is not your intention.

> the project's maintainer himself made a commit few days back fixing a glaring bug, yet he had not experienced it for many years as he said so himself

Assuming you're referring to eb9d83915fcfdcd4a4fb3f65a586e6c60be598f7, please note that despite the fact that I opened the issue and committed the patch, it was in fact reported *and* fixed by @mnewnham, who has been an important contributor to ADOdb for many years. He has demonstrated his knowledge and competence, and I would appreciate civil and respectful behavior here.

> What errors we experienced, we experienced. 

I am not denying that you may have experienced errors or found bugs, or obviously spent a large amount of time researching issues and fixing them (and I'm sure neither did Mark). In fact I truly appreciate your contributions.

Yet the fact is that you often fail to provide reproducible evidence for the issues you report. The suggestion in [Mark's note above](https://github.com/ADOdb/ADOdb/issues/133#issuecomment-116768603) is exactly what is expected in a good issue report for an open-source project.

And if I may make an unrelated comment - you present yourself as a Company, yet the e-mail address you provide in git commits (it@creatrixonline.com) refers to a non-existent domain... I find that unprofessional, and I personally would appreciate knowing whom I'm talking to.

/end of rant

**Comment by CreatrixTeam** [comment]
This has been a very unusual experience for me the commentator. We are a small team at the moment. Our web site is creatrix dot ca. We are experiencing problems with our domain, creatrixonline. However, from whomever it came, truth is true.

This started out as a an issue report, to a discussion of lines of code, to a discussion of one's own disposition, to a discussion of one's own command of the English language. Since when is truth and brevity broken language and arrogance. One shall not defend himself, let those who read this, read it in full and judge. If right, then a right for our team. And if wrong, then a wrong on me.

**Comment by mnewnham** [comment]
I hope this discussion will not deter you from submitting bug reports and fixes. I believe that every contribution to a community projext is values.
