### ISSUE TITLE
Strange decimal issue 

### ISSUE THREAD

**Issue by Woklet** [ADOdb/ADOdb#134]
Hi,

I'm experiencing a strange decimal issue. Setup:

- Latest ADODB5 running within an xampp instance
- Access (MDB) and MS SQL databases

Here's an example:

1) SELECT * from Learners
2) For each row and for each field (retrieved using metacolumnnames), build an insert statement. 
3) Execute all insert statements into ms sql

At some point, the number changes from say 211308511 to 211308511.0. This happens whether I use ->GetRows() or plain while(!$rs->EOF). Although the field in access is a double, the decimal point setting is set to auto (0) which means there are no decimals. The data within access has no decimal and a straight copy/paste of the value from access to anywhere else shows no decimal.

Is there some processing going on with ADODB where it changes these values to include a decimal?

**Comment by mnewnham** [comment]
You don't explain why this is a problem, after all, the two numbers are the same, and you will end up with the correct result in your database. 

Perhaps some code that explains the point at which the value has changed might allow us to help you better.

**Comment by Woklet** [comment]
Thanks for replying :)

Aah, fair enough - the reason is that the values go into a SQL database (whose structure I have no control over whatsoever) and into a VARCHAR(250) field for reasons I'm sure someone, somewhere knows. 

This means that while it may start off as the same number (0.0 = 0), when it goes into the varchar field, it stays 0.0 - and that's functionally not the same thing when they do the reporting on the other side. They essentially reject any number which is not:

1) a nine digit number
2) Null

I can write code to change the number on the fly but that seems silly as I don't know where else this may be occurring. I've done some tests and this only occurs with ADODB, not if I use for example, COM("ADODB.Connection") and not if I use c# or feed the mdb file directly into excel so I presume that somewhere, the .0 is being added because the field type is a double and it's disregarding the setting for decimal places.

**Comment by dregad** [comment]
> I presume that somewhere, the .0 is being added because the field type is a double and it's disregarding the setting for decimal places.

It's quite likely, but again, without knowing exactly what you're doing, it's kind of difficult to determine where that *somewhere* might be... Please post a code snippet to reproduce the problem.

You can also try to cast the field's value as (int) as you insert it into the target db.

**Comment by Woklet** [comment]
Here you go, complete code snippet: http://pastebin.com/LwF38uPU
All you need is adodb, this in a php file and a blank access database called "test.mdb" in the same path and you'll see results similar to this:

Expected value: 694308810 but got 694308810.0
Expected value: 861762152 but got 861762152.0
Expected value: 155843098 but got 155843098.0
Expected value: 752332899 but got 752332899.0
Expected value: 478054470 but got 478054470.0
Expected value: 456705729 but got 456705729.0

The "expected value" has been cast while the "actual value" is straight from the database.

In particular, Microsoft reinforces the expected behaviour (that there would be no decimal points) here:
https://msdn.microsoft.com/en-us/library/bb215600(v=office.12).aspx

and 

https://support.office.com/en-us/article/Specify-how-data-displays-by-using-predefined-formats-e1a9b7c7-fd85-44d8-970f-33370c40ebd5

**Comment by mnewnham** [comment]
Could you please post the result of 

`$db->MetaColumns('test_table')`

so that we can see what datatype adodb thinks the field is

**Comment by Woklet** [comment]
Array ( [A_NUMBER] => ADOFieldObject Object ( [name] => a_number [max_length] => 4 [type] => I [not_null] => 1 [scale] => 0 ) )

**Comment by Woklet** [comment]
Sorry, that's wrong! Wrong database :D Please forgive me for that one.

Array ( [A_NUMBER] => ADOFieldObject Object ( [name] => a_number [max_length] => 8 [type] => N [not_null] => 1 [scale] => ) )

**Comment by mnewnham** [comment]
I see nothing in the code to suggest that adodb is doing anything but dumping the results of the php function `odbc_fetch_into` into the ->fields array.

A couple of suggestions:

1. Type something like *SELECT CAST(a_number) AS INT"
2. Put some debugging into the adodb-odbc driver in the `MoveNext()` function

**Comment by dregad** [comment]
I had a quick look at this, and as @mnewnham already pointed out, this is AFAICT not caused by ADOdb at all - as evidence here is the output of a plain `odbc_columns()` call for your test table:
```
Array
(
    [TABLE_CAT] => C:\temp\test
    [TABLE_SCHEM] =>
    [TABLE_NAME] => test_table
    [COLUMN_NAME] => a_number
    [DATA_TYPE] => 8
    [TYPE_NAME] => DOUBLE
    [COLUMN_SIZE] => 15
    [BUFFER_LENGTH] => 8
    [DECIMAL_DIGITS] =>
    [NUM_PREC_RADIX] => 10
    ...
)
```

So the primitive is giving us a number(15,8) and does not specify the decimal digits regardless of how it's set in Access. I'm afraid there's nothing we can do here.
