### ISSUE TITLE
Connect to Postgresql socket via ADO

### ISSUE THREAD

**Issue by basti12203** [ADOdb/ADOdb#137]
Hello,
is it possible to connect to Postgresql socket instead of use localhost?
Socket connections have a better performence I think.

**Comment by mnewnham** [comment]
Could you please provide:
1. What driver you are using e.g. postrgres, postgres7, postgres8
2. What operating system, e.g. Windows, Linux, Unix

**Comment by basti12203** [comment]
First of all OS is Linux.
postgres8 I would guess is preferred for Postgres 9.x ?
It's a general question if it would work?
If Yes, how should I implement this (code example, man page)?

**Comment by ipso** [comment]
Just don't specify a hostname to connect to at all, or make it blank, ie: $host = '';, that should cause it to attempt to connect over the default socket:

http://php.net/manual/en/function.pg-connect.php#93837

**Comment by basti12203** [comment]
Thanks a lot.
