### ISSUE TITLE
Announcement: Improved IBM DB2 driver

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#140]
There is a new version of drivers/adodb-db2,inc.php in the db2-fixes branch of the master. This version addresses the following issues:
1. Data not returned correctly if the driver was initialized then immediately set to ADODB_FETCH_ASSOC.
2. Fetching associative arrays is no longer emulated. There should be some performance improvement.
3. ServerInfo() no longer crashes if used in ADODB_FETCH_ASSOC mode.
4. Fetchfield no longer fails if an offset is not passed.

The file is a drop-in replacement for the existing version, but should be considered beta quality. If you wish to test, just leave comments in this thread.

**Comment by mnewnham** [comment]
This will pulled into the master in version 5.21

**Comment by dregad** [comment]
Don't you want to keep this open until it's actually merged ?
