### ISSUE TITLE
Superfluous query parameters get tacked onto the end of the query

### ISSUE THREAD

**Issue by orcinus** [ADOdb/ADOdb#146]
In 5.19, if you pass Execute $params that are superfluous (i.e. not covered by ? tokens in the query), they will get tacked onto the end of the query, then executed.

Putting aside the fact there should be no extra $params, this is a VERY dangerous behaviour.

No idea when this started, we were using a very very old release and only recently updated to 5.19, then noticed this behaviour.

**Comment by orcinus** [comment]
Correction after some testing...

It only happens if there are NO parametric tokens, but there are $params specified.
For example:

$db->Execute("SELECT * FROM foo WHERE id = '1'", "superfluous");

... will produce a query that looks like this:

SELECT * FROM foo WHERE id = '1'superfluous

However, this:

$db->Execute("SELECT * FROM foo WHERE id = ?", ["1", "superfluous"]);

... will produce the expected query:

SELECT * FROM foo WHERE id = '1'

**Comment by peterdd** [comment]
And what happens in this case?

```php
$db->Execute("SELECT * FROM foo WHERE id = '1'", array("superfluous"));
```

**Comment by orcinus** [comment]
Same thing.

**Comment by orcinus** [comment]
By the way, i know this is technically due to user error (i.e. using a non-parametric query, but specifying parameters), but it's still rather dangerous. The only reason i found it was because at some point, someone removed a few lines from a query in our codebase, resulting in completely superfluous (and empty) $params argument passed to Execute.

When i've pushed a branch with updated adodb to the production server today, the error rate suddenly jumped, i took a look and realized this was happening.

**Comment by peterdd** [comment]
Which database and database driver do you used? Happens this with every dbtype or just one?

I used 
```
grep -r 'ion _query('
```
to find where parts dbspecific querybuilding happens.

**Comment by orcinus** [comment]
MySQL DB, mysqli driver.

**Comment by peterdd** [comment]
Ok, my quick test with mysqli:

$db->Query('SELECT id FROM users');                         # OK, ACCEPTED
$db->Query('SELECT id FROM users', 1);                      # OK, REJECTED
$db->Query('SELECT id FROM users WHERE id=',  1 );          # BUGORFEATURE? , ACCEPTED
$db->Query('SELECT id FROM users WHERE id=',  "1" );        # BUGORFEATURE? , ACCEPTED
$db->Query('SELECT id FROM users WHERE id=',  "a1" );       # BUGORFEATURE? , ACCEPTED
$db->Query('SELECT id FROM users WHERE id=',  array('1') ); # BUGORFEATURE? , ACCEPTED
$db->Query('SELECT id FROM users WHERE id=1', array('1') ); # BUG , REJECTED
$db->Query('SELECT id FROM users WHERE id=');               # OK , REJECTED

I marked some with BUGORFEATURE. I would see it as bug. But maybe it was done this way and not changed for legacy app support  reasons?

( $db->Query() is a db wrapper in one of the apps where adodb is used, so should be identical to ->Execute())

**Comment by orcinus** [comment]
The thing is, we were running 5.09 until now (yes, yes, i know, it's 6 years old) and this behaviour hasn't been present. So i doubt it was due to legacy app support reasons - it seems like it's something new (or at least newer than the prehistoric 5.09 release).

**Comment by peterdd** [comment]
mmh, maybe this fixes it:
adodb.inc.php function Execute
line ~ 1078
```php
 if (!is_array($sql) && !$this->_bindInputArray) {
                                $sqlarr = explode('?',$sql);
                                $nparams = sizeof($sqlarr)-1;
                                # alert if someone tries to add params to a query without placeholders.
                                if($nparams==0){
                                        $this->outp_throw( "Input array exists, but no ? placeholders: ".htmlspecialchars($sql),'Execute');
                                }
```

But what I'm real wondering, that this drivers seems to not using the mysqli_stmt_* functions.
bindInputArray=false ...
and so falls back to this section where the query is build together from $sql and params to a final sql string.

The Prepare() in drivers/adodb-mysqli.inc.php is just a dead function, returns immediatly after function start. And there is no prepare()  (small 'p'!)

**Comment by dregad** [comment]
@orcinus 
> Putting aside the fact there should be no extra $params, this is a VERY dangerous behaviour.

I fully agree, good potential for silently getting incorrect query results, and possibly SQL injection too (did not investigate further in this direction).

IMO, we should not execute a query when the given parameters don't match what the query expects, period.

> we were running 5.09 until now (yes, yes, i know, it's 6 years old) and this behaviour hasn't been present

I don't have much time for archaeological research right now, but I ran a quick test on 5.09a:

``` php
include('adodb.inc.php');
$db=ADONewConnection('mysqli');
$db->debug=true;
$db->connect('localhost','user','password', 'db');
$db->query('select * from users where id=1', 1);
```

This gives me the exact *same results* as when using 5.19, i.e. execution of `select * from table where id=11`... 


@peterdd 
> $db->Query('SELECT id FROM users WHERE id=1', array('1') ); # BUG , REJECTED

This query gets executed as `SELECT id FROM users WHERE id=11`. 
Assuming it were indeed rejected, why would you consider this as a bug ? 

> But what I'm real wondering, that this drivers seems to not using the mysqli_stmt_* functions.

I don't know all of the history behind the mysqli driver, but AFAIK it was created many years ago as a clone of the mysql driver, so I'm guessing either these functions did not exist at the time, or no effort was spent to adapt the new driver to use them. Something for the Todo list...

> The Prepare() in drivers/adodb-mysqli.inc.php is just a dead function, returns immediatly after function start.

Which is the same behavior as ADOConnection::Prepare(). In its current state, we might as well remove the method in mysqli driver...

That being said, according to git blame, the function is exactly as John Lim checked it in 7 years ago, and I have no idea what he had in mind with the code after the first return statement.

> And there is no prepare() (small 'p'!)

FYI, function names are not case sensitive in PHP - [see Note in documentation](http://php.net/manual/en/functions.user-defined.php) - so `Prepare()` == `prepare()`

**Comment by orcinus** [comment]
> This gives me the exact same results as when using 5.19, i.e. execution of select * from table where id=11...

That's really bizarre, because i've just reverted our codebase back to 5.09 (pending a check for any more of needless / empty parameters) and it doesn't do the same thing. Oh well... ¯\_(ツ)_/¯

**Comment by dregad** [comment]
Any local patches, maybe ?

**Comment by orcinus** [comment]
Entirely possible. Tough to say, it's archaeology for me too.
A pretty significant part of the commit history has been lost in migration from SVN to git long time ago.

**Comment by dregad** [comment]
Ok let's leave it at that, then.
Let me know if the patch I committed resolves your issue to your satisfaction.

**Comment by peterdd** [comment]
tested again with 5.19:
$db->Query('SELECT id FROM users WHERE version_id=1', array('1') ); #REJECTED
$db->Query('SELECT id FROM users WHERE version_id=1', array(1) );  #ACCEPTED

assumption:
first example is treated as string by gettype() and gets extra quoting  by qstr() probably resulting in something like 1'1'
while second treated as it is and resulting in 11.

tested with php5.3.*

**Comment by dregad** [comment]
@peterdd I may have omitted the single quotes in my test script (which I've now deleted). Anyway, trying again with both options, 

**before (v5.19)**
```
-----<hr>
(mysqli): select * from mantis_user_table where id=11 
   
-----<hr>
-----<hr>
(mysqli): select * from mantis_user_table where id=1'1' 
   
-----<hr>
Query: select * from mantis_user_table where id=1'1' failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1'' at line 1
```
**after (git HEAD)**
```
Input array has 1 params, does not match query: 'select * from mantis_user_table where id=1'
Input array has 1 params, does not match query: 'select * from mantis_user_table where id=1'
```

So I guess the point is moot ;)

**Comment by peterdd** [comment]
Rechecked it just for completion to cool down my head,
 like  https://www.youtube.com/watch?v=Z3z_yZ1G1Og
;-)
