### ISSUE TITLE
MS SQL ODBC Driver CONCAT_NULL_YIELDS_NULL should default to ON

### ISSUE THREAD

**Issue by chenster** [ADOdb/ADOdb#148]
In MS SQL, composite primary key INSERT and DELETE throw error:

The error is from CONCAT_NULL_YIELDS_NULL settings: Microsoft][ODBC SQL Server Driver][SQL Server]DELETE failed because the following SET options have incorrect settings: 'CONCAT_NULL_YIELDS_NULL'  Based on what I read below, the value should always be ON http://blog.sqlauthority.com/2013/05/12/sql-server-interesting-observation-of-concat_null_yields_null-and-concat-in-sql-server-2012-onwards/

In this line:
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-odbc_mssql.inc.php#L45

I think CONCAT_NULL_YIELDS_NULL should always default to ON. It causes issues during INSERT/DELETE.

**Comment by mnewnham** [comment]
Just read this article, agree with the premise of the suggestion, but we need to implement the SQL server version detection that exists in the mssqlnative driver to make this work correctly. The behavior needs to remain as it was for pre-2012 installations.

**Comment by mnewnham** [comment]
The simplest approach is to extend the driver to allow addition of SQL server 2012 specific functionality
