### ISSUE TITLE
ADOdb PHP 7 Compatibility

### ISSUE THREAD

**Issue by ganeshlohia** [ADOdb/ADOdb#153]
On checking for minimum PHP7 Compatibility, I had the following errors using Zend PHP 7 Express:

The constant 'MYSQL_ASSOC' is no longer available in PHP 7	line 85	adodb-mysqlpo.inc.php	/Ado/drivers
The constant 'MYSQL_ASSOC' is no longer available in PHP 7	line 102	adodb-mysqlt.inc.php	/Ado/drivers
The constant 'MYSQL_ASSOC' is no longer available in PHP 7	line 121	adodb-mysqlpo.inc.php	/Ado/drivers
The constant 'MYSQL_ASSOC' is no longer available in PHP 7	line 138	adodb-mysqlt.inc.php	/Ado/drivers
The constant 'MYSQL_BOTH' is no longer available in PHP 7	line 89	adodb-mysqlpo.inc.php	/Ado/drivers
The constant 'MYSQL_BOTH' is no longer available in PHP 7	line 106	adodb-mysqlt.inc.php	/Ado/drivers
The constant 'MYSQL_BOTH' is no longer available in PHP 7	line 126	adodb-mysqlpo.inc.php	/Ado/drivers
The constant 'MYSQL_BOTH' is no longer available in PHP 7	line 143	adodb-mysqlt.inc.php	/Ado/drivers
The constant 'MYSQL_NUM' is no longer available in PHP 7	line 84	adodb-mysqlpo.inc.php	/Ado/drivers
The constant 'MYSQL_NUM' is no longer available in PHP 7	line 101	adodb-mysqlt.inc.php	/Ado/drivers
The constant 'MYSQL_NUM' is no longer available in PHP 7	line 120	adodb-mysqlpo.inc.php	/Ado/drivers
The constant 'MYSQL_NUM' is no longer available in PHP 7	line 137	adodb-mysqlt.inc.php	/Ado/drivers
The function 'mysql_fetch_array' is no longer available in PHP 7	line 98	adodb-mysqlpo.inc.php	/Ado/drivers
The function 'mysql_fetch_array' is no longer available in PHP 7	line 115	adodb-mysqlt.inc.php	/Ado/drivers

I am posting this here since the errors are popping on multiple files apart from the core mysql driver file (adodb-mysql.inc.php) which I know will no longer work. I am sure this will be addressed soon. Just wanted to get the focus on ADOdb PHP 7 Compatibility.

**Comment by mnewnham** [comment]
As you are likely aware, the php driver 'mysql' was removed in PHP 5.6 . Both the ADOdb drivers you mention are based on this. If you are still using the ADOdb drivers mysqlt or mysqlpo you should take steps to migrate to the mysqli driver. In the version of ADOdb that supports PHP 7.0, all drivers based on  the PHP mysql driver will be removed

**Comment by ganeshlohia** [comment]
Thanks for the update. Looking forward to the next release which is fully compatible with PHP 7...
