### ISSUE TITLE
Unable to count active records when using $db->Load('1=1');

### ISSUE THREAD

**Issue by circuitmamu** [ADOdb/ADOdb#156]
I just want to count the number of active records by passing the table name in class and using function load $db->Load('1=1');

**Comment by circuitmamu** [comment]
I think developers delete the below functions

function Count($whereGroupBy, $bindarr=false) {
		return  $this->intify( $this->Aggregate("count", "*", $whereGroupBy, $bindarr) );
	}

**Comment by mnewnham** [comment]
Could you give the version of ADOdb you are currently using? The function **intify()** has never been part of ADOdb version 5 ( first released Feb 2007). Perhaps this was a custom function written by your own developers?

**Comment by circuitmamu** [comment]
I used ADOdb 5.12 in past in that this kind of function is available but when I am update the vesion I'm noticed that this function is been removed from the file "adodb-active-record.inc.php"

You can also check that in 5.12 version this function is available but in 5.19 it is not

**Comment by dregad** [comment]
> You can also check that in 5.12 version this function is available 

Please point me to it. ` $ git log -S intify -i` returns no matches.

**Comment by circuitmamu** [comment]
then how can I count the records using adodb functions

**Comment by mnewnham** [comment]
Ideas for you,
 1. You could easily integrate your intify() method into a new version of ADOdb
 2. Use the hacking methods described in the documentation to extend the driver of your choice.
 3. If you think that your intify() method is useful, paste the whole thing into the thread, we might consider using it.
 4. Supply some samples of how you use it, we can probably provide some workarounds  that achieve the same goal

**Comment by circuitmamu** [comment]
@mnewnham @dregad 

please check code link that is adodb-active-record.inc.php that I modified
http://codeshare.io/HnlhQ

Check the line : 89 
static $_supportedAggregateFunctions = array ("avg", "count", "max", "min", "std", "sum");

Check the lines : 805 - 836
that is 4 functions I made are below and wrote between the Delete() and Find() function
protected function intify($ret) {.......}
function Aggregate($function, $column, $whereGroupBy, $bindarr=false) {.....}
function Count($whereGroupBy, $bindarr=false) {.......}
function CountDistinct($column, $whereGroupBy, $bindarr=false) {......}

Example of code that I used with class and these code returns me a number of users from the "user" table
class User extends ADOdb_Active_Record {
	var $_table = 'user';
	
}

$data = array();
$users = new User();
$data['totalUsers'] = $users->Count("1 = 1");

**Comment by dregad** [comment]
*intify()* function is probably not necessary, the same operation can be achieved much more efficiently by typecasting instead of relying on intval() function, e.g.

```
return  (int)$this->Aggregate("count", "*", $whereGroupBy, $bindarr) );
```

If I were you, to facilitate future maintenance, instead of modifying the ADOdb base class, I would create my own by extending ADODB_Active_Record and place the new functions there. This way, you can upgrade the library more easily.

**Comment by circuitmamu** [comment]
@dregad 
do you think that adodb is a huge class that support many types of database but there is no count function inside the class.

user have to put own function to calculate the active records by passing the parameters

**Comment by dregad** [comment]
I'm not sure such a function adds much value compared with simply executing a query like `select count(*) from xxx [where yyy]`

**Comment by dregad** [comment]
You have not provided any feedback, I assume this is no longer an issue and will therefore close this. Feel free to reopen if necessary.
