### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by andrewnicols** [ADOdb/ADOdb#157]
Any chance you can tag a new release please so that we can get some of those PHP7 fixes?

**Comment by dregad** [comment]
It's on my todo list but I have other priorities at the moment, sorry.

**Comment by marinaglancy** [comment]
Damien, do you have a planned date for the release? We need to update adodb library in Moodle, if you are planning to release soon we'll wait for it or otherwise we'll update to dev branch. TIA

**Comment by dregad** [comment]
You can expect it by this weekend.

**Comment by marinaglancy** [comment]
thank you!
