### ISSUE TITLE
ADOdb-extension

### ISSUE THREAD

**Issue by bugsoftware** [ADOdb/ADOdb#159]
Hi,

I was wondering if someone has successfully compiled the ADOdb-extension in PHP 5.4 or PHP.5. ?

I have been trying without much of a success. I was wondering if anyone can help?

Getting several errors about zend_get_parameters_ex . These are warnings. Not sure if the compile failed comes from here.

Anyone?

**Comment by dregad** [comment]
Assuming you're referring to the C extension here... If that's the case, please note that it is no longer supported.

**Comment by bugsoftware** [comment]
Yes. I am referring to the C extension and yes I understood it was no longer supported. Regardless still makes sense if someone could support it :)

**Comment by dregad** [comment]
> Regardless still makes sense if someone could support 

Not sure it really does actually. Anyway, are you volunteering ? 

For the record: #84

**Comment by bugsoftware** [comment]
Well, in version 5.3 makes a significant different in terms of performance. I am unable to compile it in 5.4 or 5.5

I would volunteer if I could but I lack the knowledge to fix it. I tried to replace several compile errors. I did some but I couldn't others. Is out of my league. adodb.c needs to be patched as some functions have been deprecated

**Comment by dregad** [comment]
As far as I know, none of the contributors have this knowledge, so unfortunately I don't think there's anything we can do to help.

Considering that the extension has not been maintained for more than 3 years, I see no point in keeping this issue open.

If you do find someone who is able and willing to fix it (and keep on maintaining it), feel free to reopen the issue.
