### ISSUE TITLE
error : missing extension for native

### ISSUE THREAD

**Issue by rsasoftware** [ADOdb/ADOdb#160]
Hi

Am trying to connect to Oracle 7.3 using the oracle driver and getting error

Any help would be appreciated

Thanks

**Comment by mnewnham** [comment]
Are you sure you are using oracle 7? Support for that product ended 13 years ago. 

Please enable the $db->debug and post the connection errors, also post the PHP Version you are using.

Remember that you must use the 'oracle' driver and not the 'oci8'.

**Comment by rsasoftware** [comment]
Hi

 

Thanks for getting back to me.

 

I realize the product is obsolete but that is what the client's software is using.

 

yes using oracle driver.

 

192.168.0.5 missing extension for native

 

(oracle) select * from fclients limit 25

 

call to undefined function ora_open() in adodb-oracle.inc.php line 186

 

php 5.3.3

 

Randy

**Comment by dregad** [comment]
> call to undefined function ora_open() in adodb-oracle.inc.php line 186 
> php 5.3.3

`ora_open()` - and more generally the oracle extension - was [removed in PHP 5.1](http://php.net/manual/en/migration51.extensions.php#migration51.extensions-gone)

I suggest you tell your customer to get to the next century... I'm afraid there's nothing we can do for you here.
