### ISSUE TITLE
ActiveRecord doesn't support advanced datatypes

### ISSUE THREAD

**Issue by ipso** [ADOdb/ADOdb#165]
When trying to use geometry datatypes ( 'POINT', 'LINE', 'LSEG', 'BOX', 'PATH', 'POLYGON',                       'CIRCLE') with active record and PostgreSQL, we noticed that you can't actually do that with ADODB, since drivers/adodb-postgres64.inc.php->MetaType() assumes any datatype it doesn't recognize to be numeric (based on the default case in the switch statement). 

This seems a little odd to me, as most advanced datatypes (ie: geometry, json, etc...) will likely be strings, so defaulting to numeric prevents any advance current or future datatypes from being used.

Any ideas why this is the default rather than string? Security reasons perhaps?

I'm happy to submit a PR to resolve this issue, just wondering what the best approach will be:

1. Add a global flag (ie: ADODB_DEFAULT_DATATYPE) to set the default datatype to whatever the user wants, defaulting to the current numeric ('N') of course. 

2. Continually submit PR requests and bloat the datatype list with more and more datatypes that could possibly be used now or in the future.

3. ???

**Comment by mnewnham** [comment]
I guess the first question would be: If all the datatypes you list were processed as strings, would they all be handled correctly within ADOdb

**Comment by mnewnham** [comment]
@ipso As we have not received any further on this request for a while, I'm assuming this is not an important issue for you right now, If you want to re-open this, feel free.

**Comment by ipso** [comment]
Sorry, somehow I missed your response. Yes, if they were processed as strings they would work fine, without any additional code. PGSQL also has the JSON and ARRAY datatypes, which are mostly processed as strings too. It seems to me that a string default would make the most sense.
