### ISSUE TITLE
PHP7 compatibility issues: PHP4 constructors, pcre '/e' modifier

### ISSUE THREAD

**Issue by marinaglancy** [ADOdb/ADOdb#168]
Hello,
I thought you might be interested in our experience when upgrading ADOdb in Moodle to version 5.21.
You can find full history on the issue in moodle tracker: https://tracker.moodle.org/browse/MDL-52286

First of all, one of our unittests failed on Mysql and it looks like an ADOdb bug when closing recordset. This line https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-mysqli.inc.php#L1060 produces a notice "mysqli_more_results() expects parameter 1 to be mysqli, boolean given".
*EDIT [dregad] this is covered in #170*

Second, there are still two places that php7cc picked up as incompatible with PHP7 (/e modifier is removed from PHP7 and forgotten old-style constructor):
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-db2ora.inc.php#L41
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-mysqlt.inc.php#L133

**Comment by dregad** [comment]
Hello Marina,

Many thanks for your feedback and contribution, it is greatly appreciated. I will look into these as soon as possible.

In future bug reports, may I kindly ask you to please keep things separate, i.e. 1 bug = 1 issue report ? TIA.

**Comment by marinaglancy** [comment]
oh, thank you. I was sure I read 5.21 in the latest tag but can't see it now. I corrected the version number in moodle
