### ISSUE TITLE
Fix Sqlite metaType mappings (map X to Blob instead of Varchar)

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#177]
Currently, the metaType 'X', which represents blob fields in all other databases, is mapped to a varchar(250) field in the sqlite3 driver. Whilst the flexible typing in the sqlite database means that this is not necessarily an issue , I believe for consistency with other databases, It should map to a blob field.

**Comment by dregad** [comment]
I think achieving consistency across drivers should be one of our goals.

Looks like sqlite/sqlite3 are in fact using the generic datadict driver (_adodb_getdriver) function. 

Maybe the generic driver needs to be changed ? That could cause backwards compatibility issues though.

**Comment by mnewnham** [comment]
I think we need to use an sqlite specific metaType function with the correct type mapping and leave the default one pointing to varchar which is pretty generic, as there is a bit of difference in the names of text fields across databases.

**Comment by dregad** [comment]
Fine with me.
