### ISSUE TITLE
charMax() and textMax() should not fail if used with unsupported driver

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#183]
The methods charMax() and textMax() are supported in mysql, postgres, oracle and mssql drivers. Because there is no base method in adodb.inc.php, when the method is called in an unsupported driver the adodb class fails.

The core methods were removed in ADOdb 3.92 for undisclosed reasons (see changelog)

**Proposal**
To ensure compatibility, re-implement both charMax() and textMax() in the base class. The base class should return a value of -1 to indicate that the methods are not implemented in the driver in use.
In addition, the methods should return -2 if there are no pre-defined limits e.g. for Sqlite

**Comment by dregad** [comment]
I suggest we define constants instead of using magic numbers.
Otherwise, I'm fine with your proposal.

**Comment by dregad** [comment]
Shouldn't this be categorized as *bug* instead of feature ?

**Comment by mnewnham** [comment]
Well.... The feature was deliberately removed, and the feature was re-implemented, so I would go with feature. Now if the feature had been accidentally removed, I would have gone with bug
