### ISSUE TITLE
Add support of setConnectionParameter to mysqli driver

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#188]
Driver should support standard parameter passing method instead of driver specific ``$optionFlags``

**Comment by dregad** [comment]
See my note in the commit.

To *deprecate* the $optionFlags feature, I'd sugest removing the empty array assignment, and instead add an information message to inform users they're relying on an obsolete feature, e.g. something like

```
if ($this->debug) {
    ADOConnection::outp("optionFlags is deprecated, please use setConnectionParameter() instead");
}
```

I would also add a docblock before the property definition to indicate its deprecated status.
