### ISSUE TITLE
mssqlnative driver now supports standard connection parameter passing

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#194]
mssqlnative driver now supports for ``setConnectionParameterkey,value)`` passing, This can be used to pass e.g. character sets:
````php
$db->setConnectionParameter('CharacterSet','UTF-8');
````

**Comment by dregad** [comment]
Is this a mistake ? That feature was implemented in v5.20.0 (commit 2e72fe524694d30a97a760a43b6d1554d8d84e0a) see #158

**Comment by mnewnham** [comment]
Yes, I was reading the wrong side of a diff when I wrote the issue
