### ISSUE TITLE
Call to undefined function mysql_connect() in PHP 5.6

### ISSUE THREAD

**Issue by mrsnax** [ADOdb/ADOdb#195]
Dear

Ive update my PHP from 5.4 to 5.6 but when executing a web its show errors

Call to undefined function mysql_connect() 

Whats going on ?

**Comment by atrol** [comment]
The mysql PHP extension is [deprecated ](http://php.net/manual/de/migration55.deprecated.php) since PHP 5.5 and will be removed.
