### ISSUE TITLE
Offline docs: Link on ADOdb logo on each page

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#196]
The link on the ADOdb logo on top of each page is going to http://adodb.org. I would expect it to point to the local index.html file instead, to make navigation easier.

This is with adodb-5.21-documentation-20160207.zip from SF.net download page

**Comment by mnewnham** [comment]
I have changed the link to point to base page, and added a separate link on the right hand side of the header to point to the main website. This is in adodb-5.21-documentation-20160210.zip
