### ISSUE TITLE
Offline docs: "Edit" links should be removed

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#197]
I noticed there are DokuWiki "Edit" links throughout all pages in the offline docs. 

Most of these are harmless (they are pointing to the page being viewed), but some of them - at least those on `file:///C:/Temp/documentation/index.html`, but I didn't test all pages - are broken. 

Since it does not make much sense to edit a local version of the doc, these links are useless, so they should ideally be removed, if possible.

This is with adodb-5.21-documentation-20160207.zip from SF.net download page

**Comment by mnewnham** [comment]
Must remember to log out of dokuwiki before generating the pages. I am going to build a dokuwiki howto page, I will add that to the list of items.

Fixed in adodb-5.21-documentation-20160210.zip
