### ISSUE TITLE
Possibly broken modification to Class ADORecordSet function GetAssocKeys V5.19  23-Apr-2014

### ISSUE THREAD

**Issue by clarumedia** [ADOdb/ADOdb#20]
Hi,

Many thanks to everybody who has made this such a brilliant piece of kit which I have used in numerous projects :-)

Please excuse me if this is a duplicate or if I have overlooked something.

A problem appears to have been introduced into adodb.inc.php V5.19  23-Apr-2014 

Class ADORecordSet function GetAssocKeys 

I've had to change line 3505 in my production system

/*Change by Chris Barnes 2014-05-07 after problems with GetRowAssoc and function _fetch() in adodb-ibase.inc.php
*Previously: $this->bind[$key] = $val;
*Now: $this->bind[$val] = $i;
* This reflects the functionality of earlier versions of this function
* Take special note of the comment: "# This should not happen... trigger error ?" in GetRowAssoc
*/

Many thanks

Chris

**Comment by dregad** [comment]
I managed to install firebase and I'm now able to reproduce the problem.

**Comment by dregad** [comment]
@Illydth re 
> At minimum I'd suggest putting a "known issues" in the documentation / website somewhere...

This is now referenced in the [Readme file](https://github.com/ADOdb/ADOdb/blob/master/README.md) as well as in the changelog (although the latter is not yet published).

Chris, I'm still trying to figure out the proper way to fix this without breaking oci8... not quite there yet.

**Comment by CreatrixTeam** [comment]
@dregad 

We are proposing the following fix for GetRowAssoc. The function will become the following after the fix:

function GetRowAssoc($upper=ADODB_ASSOC_CASE_UPPER) {
	$record = array();
	if (!$this->bind) {
		$this->GetAssocKeys(ADODB_ASSOC_CASE_NATIVE);
	}
	foreach($this->bind as $k => $v) {
		$tKey = NULL;
		
		switch($upper) {
			case ADODB_ASSOC_CASE_LOWER:
				$tKey = strtolower($k);
				break;
			case ADODB_ASSOC_CASE_UPPER:
				$tKey = strtoupper($k);
				break;
			case ADODB_ASSOC_CASE_NATIVE:
			default:
				$tKey = $k;
				break;
		}

		if( array_key_exists( $v, $this->fields ) ) {
			$record[$tKey] = $this->fields[$v];
		} elseif( array_key_exists( $k, $this->fields ) ) {
			$record[$tKey] = $this->fields[$k];
		} else {
			# This should not happen... trigger error ?
			$record[$tKey] = null;
		}
	}
	return $record;
}

Notes:
- The class variable "fields" must always retain the associative keys in their native case. This is to be considered part of the fix. Drivers that disobey this need to be fixed.

- The following drivers are likely to be affected negatively:
    - ibase
    - ads
    - ado
    - sybase
    - postgres64
    - ado5
    - db2
    - odbc

- This fix may or may not fix this particular issue. However, it should fix a flow in the function and related algorithms and variables. The flow can appear with subsequent calls to it with different parameters, for example.

**Comment by dregad** [comment]
Removing milestone (this is referenced by #95)
