### ISSUE TITLE
oci8po driver broken with PHP7

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#202]
The current oci8po driver does not work correctly with PHP7 and instantclient 11.2. Symptoms include:

 - Random crashes using execute and selectlimit
 - incorrect results returned in getAll

the oci8 driver appears to work correctly.

**Comment by damyon** [comment]
The following script produces a reliable segfault with php7:

<pre>
// PHP OPEN TAG                                                                                                                                    
require_once('./lib/adodb/adodb.inc.php');                                                                                          
                                                                                                                                    
function test_adodb() {                                                                                                             
    $authdb = ADONewConnection('oci8po');                                                                                           
    $authdb->debug = true;                                                                                                          
                                                                                                                                    
    $authdb->Connect('', 'system', 'oracle', '//localhost:1521/XE', true);                                                          
    $authdb->SetFetchMode(ADODB_FETCH_ASSOC);                                                                                       
                                                                                                                                    
    $rs = $authdb->Execute('SELECT * from user_tables');                                                                            
                                                                                                                                    
    if ($rs) {                                                                                                                      
        $fields = $rs->GetArray();                                                                                                  
        $rs->close();                                                                                                               
    }                                                                                                                               
                                                                                                                                    
    $authdb->Close();                                                                                                               
}                                                                                                                                   
                                                                                                                                    
$tests = 10;                                                                                                                        
while ($tests > 0) {                                                                                                                
    test_adodb();                                                                                                                   
    $tests--;                                                                                                                       
}                          
</pre>

**Comment by damyon** [comment]
Pull request here: https://github.com/ADOdb/ADOdb/pull/259

**Comment by dregad** [comment]
@mnewnham having just merged @damyon's pull request into the 5.20.7 branch (see 58a2f2a80506520449dedb75fe6ab93dfd434b58), I'm closing this assuming his patch resolves the problems you faced. I'll let you reopen the issue if not.
