### ISSUE TITLE
ADODB_ASSOC_CASE_UPPER

### ISSUE THREAD

**Issue by bugsoftware** [ADOdb/ADOdb#203]
Error string: Use of undefined constant ADODB_ASSOC_CASE_UPPER - assumed 'ADODB_ASSOC_CASE_UPPER'

Error file adodb/adodb.inc.php

Anyone seeing this error? Constantly seeing this?

**Comment by mnewnham** [comment]
PHP Version? 
ADOdb Driver? 
Have you recently upgraded?

**Comment by bugsoftware** [comment]
PHP 5.3
5.20.2

**Comment by mnewnham** [comment]
The constant ``ADODB_ASSOC_CASE_UPPER`` is defined in adodb.inc.php at approx line 137. If you are getting this error, I would suspect that the files you are using are damaged in some way.

**Comment by mnewnham** [comment]
As you have not responded, I assume you have resolved the issue. Feel free to re-open this if you need further assistance on this problem.

**Comment by atrol** [comment]
Just a hint, one of our users told that the problem disappeared after upgrading PHP from 5.5 to 7.0
https://www.mantisbt.org/forums/viewtopic.php?f=3&t=24029#p60013

**Comment by peterdd** [comment]
Maybe similarity to #269 ?
There the hoster (all-inkl.com) loads extension ADOdb 5.04 for php5.2-5.6, but not php7.

Cite from https://www.mantisbt.org/forums/viewtopic.php?f=3&t=24029#p60013 : 
> "I've just changed the PHP Version at our provider's admin interface for our website hosting from Version 5.5 to 7.0 which solved the problem.."
