### ISSUE TITLE
permanent mysqli_more_result and mysqli_free_result PHP Warning from __destruct

### ISSUE THREAD

**Issue by ralfbecker** [ADOdb/ADOdb#213]
Running queries with mysqli driver using current ADOdb master gives following warnings:

```
PHP Warning: mysqli_more_results(): Couldn't fetch mysqli in ADOdb/drivers/adodb-mysqli.inc.php on line 1134
#1 ADOdb/drivers/adodb-mysqli.inc.php(1134): mysqli_more_results(Object(mysqli))
#2 ADOdb/adodb.inc.php(4025): ADORecordSet_mysqli->_close()
#3 ADOdb/adodb.inc.php(3341): ADORecordSet->Close()
#4 api/src/Db/Deprecated.php(106): ADORecordSet->__destruct()
PHP Warning: mysqli_free_result(): Couldn't fetch mysqli_result in ADOdb/drivers/adodb-mysqli.inc.php on line 1140
#1 ADOdb/drivers/adodb-mysqli.inc.php(1140): mysqli_free_result(Object(mysqli_result))
#2 ADOdb/adodb.inc.php(4025): ADORecordSet_mysqli->_close()
#3 ADOdb/adodb.inc.php(3341): ADORecordSet->Close()
#4 api/src/Db/Deprecated.php(106): ADORecordSet->__destruct()
```

This looks similar to #170, thought it is closed and mentions the issue is fixed.

We could quieten the the warning by wrapping calls in ADORecordSet_mysqli::_close() in:

```
    function _close()
    {
        //if results are attached to this pointer from Stored Proceedure calls, the next standard query will die 2014
        //only a problem with persistant connections

        $save_er = error_reporting(0);
        if($this->connection->_connectionID) {
            while(mysqli_more_results($this->connection->_connectionID)){
                mysqli_next_result($this->connection->_connectionID);
            }
        }

        if($this->_queryID) {
            mysqli_free_result($this->_queryID);
        }
        $this->_queryID = false;
        error_reporting($save_er);
    }
```

Or do that even a level up in ADORecordSet::__desctruct() for all drivers.

Ralf

**Comment by dregad** [comment]
@ralfbecker can you check if this is resolved with latest master ? Thanks

**Comment by ralfbecker** [comment]
I'm in holiday next 2 weeks, not sure I find time to check it in that time. 

Ralf
-- 
Ralf Becker
Director Software Development

Stylite AG

Isaac-Fulda-Allee 9 | Tel. +49 6131 32702-0
D-55124 Mainz | Fax. +49 6131 32702-70

Email: rb@stylite.de

www.stylite.de | www.egroupware.org

Managing Directors: Andre Keller | Ralf Becker | Gudrun Mueller
Chairman of the supervisory board: Prof. Dr. Birger Leon Kropshofer

VAT DE214280951 | Registered HRB 46224 Mainz Germany

**Comment by dregad** [comment]
Don't worry, there is no emergency. Enjoy your vacation !

**Comment by dregad** [comment]
@ralfbecker, Mark committed a change which may address this issue (see c0401866ebe908f0836f85694ebec86a6a3d97ff). Could you kindly test with the *hotfix/5.20.5* branch, whether it is indeed resolved ?Thanks

**Comment by dregad** [comment]
@ralfbecker v5.20.5 has been released in August, and the changes merged in master branch. Your feedback would be appreciated !

**Comment by dregad** [comment]
@ralfbecker without feedback from you, I'll assume that the previously mentioned patch does address the problem, and proceed with closure of this issue. Feel free to reopen it if the problem persists.
