### ISSUE TITLE
MySQL server has gone away.

### ISSUE THREAD

**Issue by PHPism** [ADOdb/ADOdb#216]
I don't know if it's an issue with the code or the server, but is there a way to check the MySQL connection before doing any execute then revive the connection and continue in case the MySQL service has closed the connection?
Best Regards

**Comment by mnewnham** [comment]
Are you using a persistent connection? If so you could check the wait timeout in the MySQL server configuration. This is useful background [here](http://dev.mysql.com/doc/refman/5.7/en/gone-away.html)

**Comment by barreirinha** [comment]
Em 09/03/16 15:39, Mark Newnham escreveu:

**Comment by PHPism** [comment]
Yes. I use persistent connection. I have tried NConnect() as well and the problem still exists. That's my entire code for connection.

require_once('libraries/adodb/adodb-errorhandler.inc.php');
require_once('libraries/adodb/adodb.inc.php');
define('ADODB_ERROR_LOG_TYPE', 3);
define('ADODB_ERROR_LOG_DEST', 'adodb_errors.log');

$dbconn = &ADONewConnection($DBTYPE);
$dbconn->PConnect($DBHOST, $DBUSER, $DBPASSWORD, $DBNAME);

**Comment by mnewnham** [comment]
Not really sure that this is an ADOdb problem then.  I would suggest that the answers in this [StackOverflow thread](http://stackoverflow.com/questions/1644432/mysql-server-has-gone-away-in-exactly-60-seconds) might have some pointers as to where your problem might be

**Comment by PHPism** [comment]
I guess it's not an ADOdb problem as well. But I think it can be overcome if ADOdb has "something like"
if( !mysql_ping($link) ) $link = mysql_connect("$MYSQL_Host","$MYSQL_User","$MYSQL_Pass", true);
That ping or check function will run within each execute() function to make sure the MySQL connection is still live or not. If the connection is still alive, then continue to execute the query, if not, revive the connection then execute the query.
That's exactly what I am trying to achieve.
Best Regards

**Comment by mnewnham** [comment]
I think you would likely have to add that yourself, as doing that for a non-persistent connection is going to add a huge overhead to connections. Also, I would say that identifying an obscure underlying dbms issue like this is not really the role of a database abstraction layer.

**Comment by bzoks** [comment]
For this purpose we use own driver that extends default one.
It catches just this specific error number/exception and then automatically reconnects (few times with sleeps between to survive longer mysql server restars) and re-executes original query. For reconnect we first needed to remember DB password, since originally it is not stored in object.
This way app doeesn't even notice that mysql server was "away".
We primarily use this with applications that run as daemons.

Best regards,
  Boštjan

**Comment by PHPism** [comment]
@bzoks Yes. That's exactly what I'm looking for. How can I activate that feature or driver?

**Comment by dregad** [comment]
Based on the discussion, I think we have an agreement that this is not really an ADOdb problem and that we shouldn't implement a fix/workaround for it.
