### ISSUE TITLE
mysqli: Using string for tablename in getInsertSql causes warning in __destruct

### ISSUE THREAD

**Issue by cm-mfc** [ADOdb/ADOdb#217]
A warning is triggered when getInsertSql is passed a string for the tablename.

PHP Warning:  mysqli_free_result() expects parameter 1 to be mysqli_result, integer given in /server/data/www/apache2.2/westfalia-misc/www/global/includes/classes/External/Adodb/drivers/adodb-mysqli.inc.php on line 1063

The statement if($this->_queryID) return true when $this->_queryID is -1, which it is in this case.

Fix:

		if($this->_queryID instanceof mysqli_result) {
			mysqli_free_result($this->_queryID);
		}

**Comment by dregad** [comment]
I can reproduce the error.

The real question is, why is _queryID == -1 ? This is hardcoded in [_adodb_getinsertsql()](https://github.com/ADOdb/ADOdb/blob/master/adodb-lib.inc.php#L830).

_queryID is supposed to store the return value of `_query()` which (at least for mysql, didn't check for all drivers), is only supposed to return *false*, *true* or a mysql_result object [1].

Maybe the proper fix is to do `$recordSet = new $rsclass(false,$zthis->fetchMode);`

[1] see http://php.net/manual/en/mysqli-stmt.execute.php and http://php.net/manual/en/mysqli.query.php

**Comment by cm-mfc** [comment]
Hm - I thought it was because $this->_queryID is set to default -1 in the class - I assumed it wasn't being set and didn't investigate further.

**Comment by dregad** [comment]
It does not make sense to me that _queryID is set to -1 in the base class either. IMO it should be *false* there too.

@mnewnham, any idea about the reason for using -1, and do you see any issue if we change that ?

**Comment by mnewnham** [comment]
I think it's set to -1 to distinguish it from a failed query returning false. Why it needs to do so is not obvious, and finding the true reason might be difficult to determine (it could be something driver specific, perhaps)

We've done  a bit of work on the close() methods in the mysql driver recently for PHP 7 and I think this is likely where the issue is coming from.  

I would suggest that the simplest fix is to change the line that says:
````php
if($this->_queryID)
{
    mysqli_free_result($this->_queryID);
}
````
to
````php
if(is_object($this->_queryID))
{
    mysqli_free_result($this->_queryID);
}
````
