### ISSUE TITLE
ADODB_mssql_n : unable to execute stored procedure

### ISSUE THREAD

**Issue by ricardask** [ADOdb/ADOdb#22]
Method _query in ADODB_mssql_n is unable to handle calls to stored procedures.

function _query($sql,$inputarr=false){
    $sql = $this->_appendN($sql);
    return ADODB_mssql::_query($sql,$inputarr);
}

It expects $sql to always be a string, but in case of a stored procedure it's an array.

The fix could be implemented in multiple ways. The simplest would be to call _appendN only if it's not an array:

function _query($sql,$inputarr=false){
    if (! is_array($sql)) {
        $sql = $this->_appendN($sql);
    }
    return ADODB_mssql::_query($sql,$inputarr);
}

or to change method _appendN to handle an array.

**Comment by mnewnham** [comment]
Fixed with commit [https://github.com/ADOdb/ADOdb/commit/9d023839986e7f5f54587f3f4f592969d5d52346]
