### ISSUE TITLE
SQL Server drivers do not return the correct value for charMax and textMax methods

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#220]
Under all types of drivers that attach to Microsoft SQL server databases, the charMax and textMax methods do not return the correct value

**Comment by dregad** [comment]
@mnewnham since you already pushed the changes to master branch, I'm not sure why you left the issue open.

**Comment by dregad** [comment]
Fixed in 7d941967aa1b81d636f5b6e1f3549b2fc95248b9 (see also 97372fc2ff5062ef805e65256706169e0d2cb751)
