### ISSUE TITLE
adodb date library uses deprecated call-by-reference for custom DST function

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#224]
The custom function adodb_daylight_sv() which can be used to implement DST functionality in the adodb date/time library uses the deprecated call-by-reference methodology to update the time information.

**Comment by dregad** [comment]
I don't see any instance of call-by-reference in the library... See results from `git grep adodb_daylight_sv` (irrelevant lines omitted from list below)

- `adodb-time.inc.php:315:function adodb_daylight_sv(&$arr, $is_gmt)`  
This is the example in the comment block, the reference is in the function declaration, so it's *pass*-by-reference, [which is OK](http://php.net/manual/en/language.references.pass.php).
- `adodb-time.inc.php:1093:    if ($daylight) adodb_daylight_sv($arr, $is_gmt);`  
No `&` here... it would be wrong if we had `adodb_daylight_sv(&$arr, $is_gmt)`

Am I missing something ?

**Comment by mnewnham** [comment]
Yeah, I've gone brain-dead with these by-reference errors, I've already fixed 10,000+ in my companies application and so I forget what I'm doing
