### ISSUE TITLE
ADODB_FETCH_ASSOC broken under mysqli

### ISSUE THREAD

**Issue by sandermarechal** [ADOdb/ADOdb#227]
It appears that ADODB_FETCH_ASSOC is broken under mysqli. Instead of MYSQLI_ASSOC it uses MYSQLI_NUM. It appears that ADODB fetch modes and MYSQLI fetch modes are mixed up somehow.

ADODB_FETCH_ASSOC = 2, which should correspond to MYSQL_ASSOC.

However, MYSQL_ASSOC is defined as '1'. If the MYSQLI fetch mode is read/tested, it matches up with ADODB_FETCH_NUM which is also defines as '1'.

**Comment by sandermarechal** [comment]
Note: I reverted back to 5.19 and the issue does not appear there.

**Comment by dregad** [comment]
Hello,

- Which version of ADOdb are you using ?
- Can you please provide sample code to reproduce the problem ?

**Comment by mnewnham** [comment]
As we have not heard from you on this issue, and given the apparent seriousness that has not been reported elsewhere, I'm assuming you have resolved your problem. If you need further help, feel free to re-open.

**Comment by sandermarechal** [comment]
I was using 5.20.4 but I can't reproduce it anymore. Sorry for the inconvenience.
