### ISSUE TITLE
CREATE XML FILE FROM DATABASE

### ISSUE THREAD

**Issue by xcdam** [ADOdb/ADOdb#228]
Hello,

with ADOdb , is it possible to generate an .xml file ( according to adodb-xmlschema03 ) from  database or lists a tables ?

thanks.

**Comment by dregad** [comment]
Is this what you're looking for http://adodb.org/dokuwiki/doku.php?id=v5:axmls:extractschema ?

**Comment by peterdd** [comment]
There is a file in Flyspray, updated a year ago, but not used. But you can use as a start..

https://github.com/Flyspray/flyspray/commits/master/setup/exportdb.php

**Comment by xcdam** [comment]
Thanks for these informations 
Hi Peter, I will try working a little on this subject !

**Comment by dregad** [comment]
@xcdam without further feedback from you, I assume you're OK with the provided information, and will close this issue.
