### ISSUE TITLE
AXMLS - Only variables should be passed by reference in adodb-xmlschema.inc.php on line 268

### ISSUE THREAD

**Issue by bugsoftware** [ADOdb/ADOdb#229]
AXMLS 

Only variables should be passed by reference in adodb-xmlschema.inc.php on line 268

**Comment by dregad** [comment]
@bugsoftware can you please tell us what version of PHP and ADOdb you're using ?

Also, it would be useful if you could provide sample code to reproduce the problem.

**Comment by bugsoftware** [comment]
PHP 7

Is a basic syntax. Basically when using  adoSchema we cannot pass object inside the parameter  adoSchema($db), thus probably need to pass it as a parameter and then open it inside  adoSchema class (just a wild guess)

$schema = new adoSchema($db);

**Comment by mnewnham** [comment]
1. I don't see anything in the current version of ADOdb that would cause that error to be thrown. Could you give the ADOdb version you are using please.  
2. xmlschema.inc.php has been deprecated for many years. You should be using xmlschema03.inc.php

**Comment by mnewnham** [comment]
As we haven't updated this in while I'm assuming that you have resolved the problem yourself. If your resolution included changes to the code you can help us by submitting patches

**Comment by dregad** [comment]
This is in fact the same issue as #260, and the problem has been resolved there (see attached commit) so I'm marking this one as duplicate.
