### ISSUE TITLE
Fatal error: Uncaught Error: 

### ISSUE THREAD

**Issue by zaisahil** [ADOdb/ADOdb#235]
I am getting an error while using adodb library for my project. It is throwing me an error which I am unable to understand. You help will be highly appreciated. 

-Saeed

**Error**:
Notice: Only variables should be assigned by reference in C:\xampp\htdocs\shipper.co.il\includes\ADb.inc.php on line 20

Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in C:\xampp\htdocs\shipper.co.il\adodb\drivers\adodb-mysql.inc.php:480 Stack trace: #0 C:\xampp\htdocs\shipper.co.il\adodb\adodb.inc.php(733): ADODB_mysql->_pconnect('localhost', 'root', '', 'tovalacoil') #1 C:\xampp\htdocs\shipper.co.il\includes\ADb.inc.php(22): ADOConnection->PConnect('localhost', 'root', '', 'tovalacoil') #2 C:\xampp\htdocs\shipper.co.il\sms.php(8): ADb->ADb() #3 {main} thrown in C:\xampp\htdocs\shipper.co.il\adodb\drivers\adodb-mysql.inc.php on line 480

**Comment by dregad** [comment]
Without any information about PHP or ADOdb version you're using, I'm guessing this could be due to your using the *mysql* driver; try with *mysqli* instead (mysql is deprecated as of PHP 5.5.0, and has been removed as of PHP 7.0.0).

**Comment by mnewnham** [comment]
As we have not heard from you regarding this, I'm assuming you have resolved it yourself. Feel free to re-open this issue if need further assistance
