### ISSUE TITLE
Invalid numeric literal on PHP 7.0.3 (32Bit) in _adodb_getdate

### ISSUE THREAD

**Issue by paduch** [ADOdb/ADOdb#255]
PHP Parse error:  Invalid numeric literal in adodb/adodb-time.inc.php on line 857

in PHP 7 (32Bit) the array assignment for $YRS 

1900 => -2208988800,

exceed the minimum signed integer value in an 32bit environment

**Comment by mnewnham** [comment]
Could you provide please:
1. Environment (Windows? Linux?)
2. A code snippet demonstrating the error.
3. Whether you know if the same code segment works correctly on PHP 5

Thanks

**Comment by paduch** [comment]
1) Environment ist Linux: 

$uname -a
Linux databox 2.6.32-5-686 #1 SMP Sat Jan 2 19:11:15 UTC 2016 i686 GNU/Linux

2) Code is an simple ADONewConnection:

$dbh = ADONewConnection('oci8');

3.) Code works correctly in PHP 5

maybe it depends on an different behavior in PHP 5 and PHP 7 for the follwing code (copied from adodb-time.inc.php), which will work in php5 (32Bit) but not in php7 (32Bit):

<?php

 $YRS = array(
                        1970 => 0,
                        1960 => -315619200,
                        1950 => -631152000,
                        1940 => -946771200,
                        1930 => -1262304000,
                        1920 => -1577923200,
                        1910 => -1893456000,
                        1900 => -2208988800,
                        1890 => -2524521600) ;
?>

**Comment by mnewnham** [comment]
I have tested this in PHP 7.0.7 under windows 64 and 32 bit , as well as 64 bit linux with no issue. I haven't had time to set up a 32 bit linux system. You seem to be experiencing [This Issue](https://bugs.php.net/bug.php?id=70193). 

Could you change either the key or the value to determine which number is causing the problem?

**Comment by mnewnham** [comment]
Here are my test results on 32bit linux:

### Platform
``
Linux centos-32 2.6.32-642.1.1.el6.i686 #1 SMP Tue May 31 20:41:01 UTC 2016 i686 i686 i386 GNU/Linux
``

### PHP

``
PHP 7.0.7 (cli) (built: May 28 2016 08:53:26) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
``
### Program

````php
$YRS = array(
1970 => 0,
1960 =>-315619200,
1950 =>-631152000,
1940 =>-946771200,
1930 =>-1262304000,
1920 =>-1577923200,
1910 =>-1893456000,
1900 =>-2208988800,
1890 =>-2524521600
);
print_r($YRS);
````
### Result
````php
Array
(
    [1970] => 0
    [1960] => -315619200
    [1950] => -631152000
    [1940] => -946771200
    [1930] => -1262304000
    [1920] => -1577923200
    [1910] => -1893456000
    [1900] => -2208988800
    [1890] => -2524521600
)
````

Maybe you have a platform issue? I cannot see an issue here that we can address in ADOdb, unless you have some suggestions.

**Comment by paduch** [comment]
you are right it seems to be a problem with our envrinonment or php itself. I can reduce the problem to the following: 

````
$ls -1
auto_prepend.inc.php
foo.php
php.ini
```

#### auto_prepend.inc.php
```php
<?php
setlocale(LC_ALL, 'de_DE.UTF-8');
?>
```

#### php.ini
```php
auto_prepend_file          = auto_prepend.inc.php
date.timezone              = Europe/Berlin
display_errors             = On
```

#### foo.php
```php

<?php

$YRS = array(
1970 => 0,
1960 =>-315619200,
1950 =>-631152000,
1940 =>-946771200,
1930 =>-1262304000,
1920 =>-1577923200,
1910 =>-1893456000,
1900 =>-2208988800,
1890 =>-2524521600
);
print_r($YRS);

?>
```

### and the execute
```
$ /opt/php-7.0/bin/php -v
PHP 7.0.3 (cli) (built: Feb 26 2016 13:50:58) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
$ /opt/php-7.0/bin/php -c php.ini foo.php
Parse error: Invalid numeric literal in /tmp/2206/foo.php on line 11

$ /opt/php-5.6/bin/php -v
PHP 5.6.12 (cli) (built: Aug 17 2015 11:18:59) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
$ /opt/php-5.6/bin/php -c php.ini foo.php
Array
(
    [1970] => 0
    [1960] => -315619200
    [1950] => -631152000
    [1940] => -946771200
    [1930] => -1262304000
    [1920] => -1577923200
    [1910] => -1893456000
    [1900] => -2208988800
    [1890] => -2524521600
)

```
can you reproduce this behavior

**Comment by mnewnham** [comment]
So, I can exactly duplicate the issue you see. The maximum value available to you (but only when using UTF8) is [-2147483647](https://en.wikipedia.org/wiki/2147483647_(number)), the maximum value of a 32bit unsigned integer, which makes a lot of sense. 

What doesn't make sense to me really, is why it works when not using UTF, and in PHP 5, but then, being anglophone, my experience with extended character sets is limited. @dregad , can you shed any light?

I'm going to have to suggest that your only course of action is to stick with PHP 5 until you can bring a 64bit PHP 7 system online, as it's unlikely that anyone is going to devote the time to fixing this (unless you yourself have the opportunity).

**Comment by mnewnham** [comment]
This might help you move forward with this issue, I'm not sure what problems it might cause.

````php
$YRS = array(
1970 => 0,
1960 =>-315619200,
1950 =>-631152000,
1940 =>-946771200,
1930 =>-1262304000,
1920 =>-1577923200,
1910 =>-1893456000,
1900 =>-2208988800.0,
1890 =>-2524521600.0
);
````

**Comment by julien-tt** [comment]
I confirm the error in  PHP 7.0.8 and Windows 32 bit with 
 setlocale (LC_ALL, 'french');

The workaround suggested by mnewhman seem to work (no more compilation error).
here is the complete array
 $YRS = array(
			1970 => 0,
			1960 => -315619200,
			1950 => -631152000,
			1940 => -946771200,
			1930 => -1262304000,
			1920 => -1577923200,
			1910 => -1893456000,
			1900 => -2208988800.0,
			1890 => -2524521600.0,
			1880 => -2840140800.0,
			1870 => -3155673600.0,
			1860 => -3471292800.0,
			1850 => -3786825600.0,
			1840 => -4102444800.0,
			1830 => -4417977600.0,
			1820 => -4733596800.0,
			1810 => -5049129600.0,
			1800 => -5364662400.0,
			1790 => -5680195200.0,
			1780 => -5995814400.0,
			1770 => -6311347200.0,
			1760 => -6626966400.0,
			1750 => -6942499200.0,
			1740 => -7258118400.0,
			1730 => -7573651200.0,
			1720 => -7889270400.0,
			1710 => -8204803200.0,
			1700 => -8520336000.0,
			1690 => -8835868800.0,
			1680 => -9151488000.0,
			1670 => -9467020800.0,
			1660 => -9782640000.0,
			1650 => -10098172800.0,
			1640 => -10413792000.0,
			1630 => -10729324800.0,
			1620 => -11044944000.0,
			1610 => -11360476800.0,
			1600 => -11676096000.0);

**Comment by paduch** [comment]
thank you for your feedback. we are going to migrate to 64bit next week, so we could solve this problem for us.

**Comment by mnewnham** [comment]
I'm not sure that it would be appropriate for this fix to go into trunk, but as long as this thread is available for research, I think that that is sufficient as a resolution to the problem.
