### ISSUE TITLE
Create table cannot handle ENUM field type

### ISSUE THREAD

**Issue by profhun** [ADOdb/ADOdb#26]
in adodb-datadict.inc.php _GenFields and _GetSize functions not handle ENUM options.

When you create a new table, and declare fields like this:
id int(10) unsigned PRIMARY NOT NULL AUTO_INCREMENT,
...
status enum('active','inactive') NOT NULL DEFAULT 'active'

_GenFields functions reparse the SQL, and drop the parts next to enum:
ENUM NOT NULL DEFAULT 'active'

Fix workaround:
_GetSize add new parameter: $enumops
/**
	 GENERATE THE SIZE PART OF THE DATATYPE
		$ftype is the actual type
		$ty is the type defined originally in the DDL
*/
function _GetSize($ftype, $ty, $fsize, $fprec, $enumops)
{
	if (strlen($fsize) && $ty != 'X' && $ty != 'B' && strpos($ftype,'(') === false) {
		$ftype .= "(".$fsize;
		if (strlen($fprec)) $ftype .= ",".$fprec;
		$ftype .= ')';
	}
    //ENUM FIX
    if(strtoupper($ftype) == 'ENUM'){
        $ftype .= "({$enumops})";
    }
	return $ftype;
}

_GenFields modify like this: (line 663)

			//-----------------
			// Parse attributes
			foreach($fld as $attr => $v) {

				if ($attr == 2 && is_numeric($v)) $attr = 'SIZE';
                //ENUM FIX
                elseif ($attr == 2 && strtoupper($ftype) == 'ENUM') $attr = 'ENUM';
				elseif (is_numeric($attr) && $attr > 1 && !is_numeric($v)) $attr = strtoupper($v);

... and place this for the end of the switch (line 700):
    				// let INDEX keyword create a 'very standard' index on column
    				case 'INDEX': $findex = $v; break;
    				case 'UNIQUE': $funiqueindex = true; break;
                    //ENUM FIX
                    case 'ENUM': $fenumops = $v; break;

place the new extra parameter into _GetSize parameters (line 726)
$ftype = $this->_GetSize($ftype, $ty, $fsize, $fprec, $fenumops);

And all working correctly

**Comment by dregad** [comment]
Can you please open a pull request for this ?
