### ISSUE TITLE
Fetchfield method has invalid reference 

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#261]
The mysqlnative method references a non-existent variable $fieldIndex . The error was introduced in the rewrite of this function in the 5.21 changes so does not affect 5.20.x

**Comment by dregad** [comment]
@mnewnham if you say `Fixes #xxx` instead of `see #xxx` in the commit message, Github will automatically close the issue for you. 

Reference: https://help.github.com/articles/closing-issues-via-commit-messages/
