### ISSUE TITLE
 odbc_exec(): SQL error: [unixODBC][FreeTDS][SQL Server]The cursor was not declared., SQL state 37000 in SQLExecDirect

### ISSUE THREAD

**Issue by jaiminmoslake7020** [ADOdb/ADOdb#262]
I am not able to get data for queries like this

 ```
 select min(fpr.PartnerCompanyId)+'' as PartnerCompanyId, fm.FileId, min(fm.OpenedDate)+'' as opened_date, min(fa.ReceivedDate)+'' as completed_date, 'Title_TAT'+'' as metric
	from FileMain fm
	inner join FileActions fa on fa.fileId = fm.fileid
		and fa.ActionDefID = 61 
	inner join FilePartnerRel fpr
		on fpr.FileId = fm.FileId
		and fpr.PartnerTypeId = 1 
  where fm.ActionListTransactionTypeID =  11
```

**Comment by mnewnham** [comment]
I believe this is an issue with the FreeTDS driver rather than ADOdb, have a look at this question on [Stackoverflow](http://stackoverflow.com/questions/1752548/invalid-cursor-state-sql-state-24000-in-sqlexecdirect)

**Comment by dregad** [comment]
As you have not provided any feedback, I'm closing this issue; feel free to reopen if you can provide additional information demonstrating that the issue indeed lies with ADOdb.
