### ISSUE TITLE
Adodb Session on PHP 7

### ISSUE THREAD

**Issue by ericbarnes** [ADOdb/ADOdb#264]
I am working on upgrading an app to PHP 7 and we are currently utilizing the ADOdb_Session. When I switch to a PHP 7 box I'm getting this error: 

```
session_start(): Failed to initialize storage module: user (path: /var/lib/php/sessions)
```

From my code I'm calling this: 

```php
include_once('/path/to/adodb/session/adodb-session2.php');
ADOdb_Session::config('mysql', $hostname, $user, $pass, $db_name, ['table'=>'Sessions']);
ADOdb_session::Persist($connectMode=false);
session_start();
```

Works fine on php 5.x but failing with the session_start error on php 7.  I am currently using this version: `v5.20.4  30-Mar-2016` 

Any thoughts or ideas on what could be the issue here?

**Comment by mnewnham** [comment]
It would appear that php is declining to set the ADOdb options for session_set_save_handler() ,which is done in ADOdb_Session::_init(). The session handler is then attempting to access /var/lib/php/sessions, which is either invalid or inaccessible. This value would be found in php.ini.

I've has no problems with ADOdb_Session and PHP 7, but I've only tested on windows.  Try adding 'debug'=>true to your ::config connection parameters.

**Comment by ericbarnes** [comment]
> It would appear that php is declining to set the ADOdb options for session_set_save_handler() ,which is done in ADOdb_Session::_init().

Yes, that seems accurate and passing debug doesn't give anything useful. 

> The session handler is then attempting to access /var/lib/php/sessions, which is either invalid or inaccessible.

That is not entirely true. I can go around Adodb and use the typical PHP `session_start()` which uses this same path from php.ini and it works fine. 

I am using Ubuntu and PHP Version 7.0.5-2+deb.sury.org~trusty+1

**Comment by mnewnham** [comment]
What database are you using on the backend

**Comment by ericbarnes** [comment]
I'm using MariaDB but the app I'm working on will support the following: MariaDB, MSSQL, MySQL, and Postgres.

**Comment by ericbarnes** [comment]
I believe I've tracked down the issue and it was hard to debug. Basically, I was passing `mysql` as the driver and that causes a PHP error because `mysql_connect` is removed in PHP 7. 

This was basically a user error, however, it appears you default to mysql here: 
https://github.com/ADOdb/ADOdb/blob/master/session/adodb-session2.php#L161

So it might be good to update that to default to `mysqli`.
