### ISSUE TITLE
AutoExecute error when fields contain the character ':'

### ISSUE THREAD

**Issue by lollolman** [ADOdb/ADOdb#27]
Hi All,

I think it may be a problem with method AutoExecute: when record fields contain unusual character like ':' you receve an SQL error.
I'm working with MySql and the autoexecute, debug string and the error are:

$DB_GN->AutoExecute('gn_tags', $record, 'INSERT')

Debug:
-----
-----
(mysqli): SELECT * FROM gn_tags LIMIT 1 
   
-----
-----
(mysqli): INSERT INTO gn_tags ( ID_URLS, TITLE, DESCRIPTION, KEYWORDS, H1, IMG, OG:TITLE, OG:DESCRIPTION, OG:IMAGE, OG:URL ) VALUES ( 1465, 'A Ferrara confronto su CCSVI e Sclerosi Multipla', 'Il seminario si è svolto in un aula straboccante, presenti oltre 300 persone, con il Direttore generale, una folta rappresentanza di medici e ricercatori dell'Ateneo e un centinaio tra studenti, specializzandi e dottorandi di ricerca', 'CCSVI,Paolo Zamboni,sclerosi multipla,Insufficienza venosa cronica cerebrospinale,Ettaro', 'A Ferrara confronto su CCSVI e Sclerosi Multipla', 'http://imgs2.site.it/img/arrow_vert.jpg||/img/meteo/sereno.gif||http://imgs1.site.it/img/login.gif', 'A Ferrara confronto su CCSVI e Sclerosi Multipla', 'Il seminario si Ã¨ svolto in un aula straboccante, presenti oltre 300 persone, con il Direttore generale, una folta rappresentanza di medici e ricercatori dell'Ateneo e un centinaio tra studenti, specializzandi e dottorandi di ricerca.', 'http://www.site.it/img/info_header_logo.gif', 'http://www.site.it/c/2E6745FC-1D2D-46C4-A0DC-30236F1C327F/A-Ferrara-confronto-su-CCSVI-e-Sclerosi-Multipla' ) 
   
-----
Query: INSERT INTO gn_tags ( ID_URLS, TITLE, DESCRIPTION, KEYWORDS, H1, IMG, OG:TITLE, OG:DESCRIPTION, OG:IMAGE, OG:URL ) VALUES ( 1465, 'A Ferrara confronto su CCSVI e Sclerosi Multipla', 'Il seminario si è svolto in un aula straboccante, presenti oltre 300 persone, con il Direttore generale, una folta rappresentanza di medici e ricercatori dell'Ateneo e un centinaio tra studenti, specializzandi e dottorandi di ricerca', 'CCSVI,Paolo Zamboni,sclerosi multipla,Insufficienza venosa cronica cerebrospinale,Ettaro', 'A Ferrara confronto su CCSVI e Sclerosi Multipla', 'http ://imgs2.site.it/img/arrow_vert.jpg||/img/meteo/sereno.gif||http ://imgs1.site.it/img/login.gif', 'A Ferrara confronto su CCSVI e Sclerosi Multipla', 'Il seminario si Ã¨ svolto in un aula straboccante, presenti oltre 300 persone, con il Direttore generale, una folta rappresentanza di medici e ricercatori dell'Ateneo e un centinaio tra studenti, specializzandi e dottorandi di ricerca.', 'http://www.site.it/img/info_header_logo.gif', 'http://www.site.it/c/2E6745FC-1D2D-46C4-A0DC-30236F1C327F/A-Ferrara-confronto-su-CCSVI-e-Sclerosi-Multipla' ) failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':TITLE, OG:DESCRIPTION, OG:IMAGE, OG:URL ) VALUES ( 1465, 'A Ferrara confronto s' at line 1

Error:
1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':TITLE, OG:DESCRIPTION, OG:IMAGE, OG:URL ) VALUES ( 1465, 'A Ferrara confronto s' at line 1
Error inserting: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':TITLE, OG:DESCRIPTION, OG:IMAGE, OG:URL ) VALUES ( 1465, 'A Ferrara confronto s'at line 1
--------------------------------------------------------------------------------

Could you verify in same way? May I help you?

Thank you all!

L.

**Comment by mnewnham** [comment]
The quoting issue appears as it can be resolved by use of the `$ADODB_QUOTE_FIELDNAMES` parameter. This should provide you with the field name quoting you need

**Comment by mnewnham** [comment]
The function `autoExecute()` does not support passing a recordset as the first parameter. The first parameter must be a string containing a table name. Passing a recordset as the first parameter  is only available in `getInsertSQL()` and `getUpdateSQL()`
