### ISSUE TITLE
adodb.org wrong links to netezza and sybase in left navbar

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#272]
On the left menu of supported databases on http://adodb.org/dokuwiki/doku.php
the links to Netezza and Sybase link to postgresql and sap_ase .

**Comment by dregad** [comment]
> links to Netezza and Sybase link to postgresql and sap_ase

I suppose this was intentional since the Netezza driver is derived from the postgres driver, and likewise the sap_ase is related to Sybase since it's based on it.

Anyway I moved them to their own pages now.

> Sybase link to postgresql and sap_ase .
