### ISSUE TITLE
How can I connect with remote MySQL Database?

### ISSUE THREAD

**Issue by pdctpa** [ADOdb/ADOdb#277]
How can I connect with remote MySQL Database? I have been trying to connect with remote mysql but with no luck. I always get following error.

`Warning: mysql_real_escape_string(): A link to the server could not be established in /home/username/public_html/libraries/adodb/drivers/adodb-mysql.inc.php on line 59

Warning: mysql_real_escape_string(): Access denied for user 'root'@'localhost' (using password: NO) in /home/username/public_html/libraries/adodb/drivers/adodb-mysql.inc.php on line 59`

my connection code in php

$DBTYPE = 'mysql';
$DBHOST = 'example.com';
$DBUSER = 'cpanelusername_dbusername';
$DBPASSWORD = '*****';
$DBNAME = 'cpanelusername_dbname';

$cn = &ADONewConnection($DBTYPE);
$cn->Connect($DBHOST, $DBUSER, $DBPASSWORD, $DBNAME);

**Comment by dregad** [comment]
You mention connecting remotely, but the error message says your user is _root@localhost_. I believe this is either an issue with how you specify the user in your code, or how users are setup in your MySQL server. 

Suggested reading
- https://dev.mysql.com/doc/refman/5.7/en/problems-connecting.html
- https://dev.mysql.com/doc/refman/5.7/en/adding-users.html

**Comment by pdctpa** [comment]
Perfectly worked after mentioning the right term for users in MySQL server. Thank you so much for the suggested reading links.

**Comment by dregad** [comment]
Thanks for the feeback, glad to hear you solved your problem.
