### ISSUE TITLE
Missing extension for mssql

### ISSUE THREAD

**Issue by birender** [ADOdb/ADOdb#280]
I am Using Linux Server and When I Try Connect
include('adodb.inc.php');
$database ="database_2016";
$db = ADONewConnection("mssql");  
$db->debug = true;
$connection = $db->Connect("Server_IP:1443", $user, $password, $database);
print "<pre>";
print_r($connection);
print "</pre>";

---------------------
Error: Missing extension for mssql

**Comment by dregad** [comment]
This is not an ADOdb issue. You need to install the PHP extension for the driver(s) you wish to use.
