### ISSUE TITLE
Adodb and sqlite3 - AutoExecute returns error 5 (SQLITE_BUSY)

### ISSUE THREAD

**Issue by JG24** [ADOdb/ADOdb#286]
I have a little problem. I try execute couple of queries using AutoExecute:

    <?php
    $sql = array(
    	array(
    		"text" => md5(rand(1,999)),
    		"value" => rand(1,999)
    	),
    	array(
    		"text" => md5(rand(1,999)),
    		"value" => rand(1,999)
    	),
    	array(
    		"text" => md5(rand(1,999)),
    		"value" => rand(1,999)
    	)
    	/* [... and 10 more ...] */
    );
    
    if ($db->AutoExecute("test", $sql, "INSERT"))
    {
    	echo "Done";
    }
    else 
    {
    	echo "Error";
    }
    ?>

and I got error code number 5. How to handle multiple queries using Adodb and AutoExecute?

**Comment by dregad** [comment]
`autoExecute()` only handles a single record. Try with 

``` php
foreach($sql as $row) {
    $db->autoExecute('test', $row, 'INSERT');
}
```

As a side note, due to the overhead of autoExecute(), it is probably more efficient do do this with a prepared statement.
