### ISSUE TITLE
mssqlnative: drop/alter column not working if column has default constraint

### ISSUE THREAD

**Issue by obmsch** [ADOdb/ADOdb#290]
With MSSQL it is not possible to drop or alter a column with an existing constraint.
This constraint has to be removed before the drop or alter takes place. 
In 'datadict-mssqlnative.inc.php' AlterColumnSQL is commented out and DropColumnSQL
doesn't care.

The attached patch tries to remedy this with the smallest possible impact.

 - Fix DropColumnSQL, to allow the drop even with a constraint on that given column.
   We drop so any default doesn't matter.
   
 - Fix AlterColumnSql, to allow changes if and only if(!) either a 'new' default is
   given for an existing default, or there is no existing one at all. So something
   like 'ALTER TABLE t ALTER COLUMN c INT NOT NULL' with an existing constraint on c
   will still fail. I can't decide, if keep or remove the constraint is implied here.

[datadict-mssqlnative.inc.php.patch.txt](https://github.com/ADOdb/ADOdb/files/585675/datadict-mssqlnative.inc.php.patch.txt)

**Comment by dregad** [comment]
@obmsch Thanks for your contribution. If you can, it would be more convenient for us if you could provide your patch as a pull request instead of an attachment.

For the record: this originated from discussion at https://www.mantisbt.org/bugs/view.php?id=21883

@mnewnham it would be great if you could take a look at this.

**Comment by obmsch** [comment]
Revised patch attached, with handles altering the column with no 'new' default and
an existing default constraint on that column. The existing constraint is dropped now.

[datadict-mssqlnative.inc.php.patch.txt](https://github.com/ADOdb/ADOdb/files/588843/datadict-mssqlnative.inc.php.patch.txt)

**Comment by mnewnham** [comment]
As @dregad  mentioned, if you could provide us a pull request it would be great. I don't have the means to work with this patch file at the moment.
