### ISSUE TITLE
Using ADODB Active Record Find() method with MSSQL Native Driver Returns No Results

### ISSUE THREAD

**Issue by jmrieger** [ADOdb/ADOdb#298]
Load()ing objects seems to work, but Find()ing objects always returns false, even if there are valid rows.

Example:
```
// This works
$rec = new ADOdb_Active_Record("product");
$rec->load("id=1");
var_dump($rec); // product data

// This doesn't
$rec = new ADOdb_Active_Record("product");
$rec->Find("id=?",array(1));
var_dump($rec); // $rec === false
```

I think I've traced this issue to https://github.com/ADOdb/ADOdb/blob/v5.21-pull/drivers/adodb-mssqlnative.inc.php#L485 - the native driver returns an error code of -1, but https://github.com/ADOdb/ADOdb/blob/v5.21-pull/adodb-active-record.inc.php#L1133 expects a false-like value (0).

All of the non-MSSQL drivers seem to return 0 if there's no error.

**Comment by mnewnham** [comment]
@dregad , is this worth a hotfix? It seems to have been incorrect since the beginning of the driver

**Comment by dregad** [comment]
No problem for me. I'm working on 5.20.8 (was actually hoping to finalize it this week-end, but didn't manage to), so I can include this in the scope if you want to - just change the target milestone if yes.
