### ISSUE TITLE
Issue on Sequence managment on mssqlnative

### ISSUE THREAD

**Issue by laurent-n** [ADOdb/ADOdb#300]
Hello,

on adodb-mssqlnative.inc.php Method GenID do not transfert the parameter to GenID2008 and GenID2012 which can receive it.
It cause only one sequence is handled and forcely named 'adodbseq'
Here the existing code.
```function GenID($seq='adodbseq',$start=1) {
		if (!$this->mssql_version)
			$this->ServerVersion();
		switch($this->mssql_version){
		case 9:
		case 10:
			return $this->GenID2008();
			break;
		case 11:
		case 12:
			return $this->GenID2012();
			break;
		}
	}
```

**Comment by mnewnham** [comment]
What version of SQL Server are you using?

**Comment by laurent-n** [comment]
Hello,
Issue is on SQL Server 2012, but on 2005/2008 it was buggy too.
I've submitted a patch to fix them.
