### ISSUE TITLE
Proposal to use convert on MSSQL sqldate (Native driver)

### ISSUE THREAD

**Issue by laurent-n** [ADOdb/ADOdb#304]
SQLDate generate quite verbose string format date
d/m/y ==> replace(str(day(testdate),2),\' \',\'0\')+\'/\'+replace(str(month(testdate),2),\' \',\'0\')+\'/\'+datename(yyyy,testdate)
But SQL server provide more compact  notation for some common format using convert
d/m/y ==> convert (varchar ,testdate,103)

I propose to integrate code like this in sqldate before the for loop, in order to have a more readable an more efficient code. Convert is avaible for long time, including SQL 2005
```
$ConvertableFmt=array(
	       "m/d/Y"=>101,"m/d/y"=>101 // US
	      ,"Y/m/d"=>102,"y/m/d"=>102 // ANSI
	      ,"d/m/Y"=>103,"d/m/y"=>103 // French /english
	      ,"d.m.Y"=>104,"d.m.y"=>104 // German
	      ,"d-m-Y"=>105,"d-m-y"=>105 // Italian
    );
if(key_exists($fmt,$ConvertableFmt))
  return  "convert (varchar ,$col,".$ConvertableFmt[$fmt].")";

```

**Comment by dregad** [comment]
That's fine with me. @mnewnham any objections ?

**Comment by mnewnham** [comment]
Its not really explained here what happens if the database is running in a character set not supported by this method. @laurent-n could you post your full function please

**Comment by laurent-n** [comment]
Hello,
If the requested format is not Handled by the convert approach, the old method is used as is.
```
function SQLDate($fmt, $col=false)
	{
		if (!$col) $col = $this->sysTimeStamp;
		$s = '';

 $ConvertableFmt=array(
	    "m/d/Y"=>101,"m/d/y"=>101 // US
	   ,"Y/m/d"=>102,"y/m/d"=>102 // ANSI
	   ,"d/m/Y"=>103,"d/m/y"=>103 // French /english
          ,"d.m.Y"=>104,"d.m.y"=>104 // German
          ,"d-m-Y"=>105,"d-m-y"=>105 // Italian
    );
		if(key_exists($fmt,$ConvertableFmt))
		  return  "convert (varchar ,$col,".$ConvertableFmt[$fmt].")";

		$len = strlen($fmt);
		for ($i=0; $i < $len; $i++) {
			if ($s) $s .= '+';
			$ch = $fmt[$i];
			switch($ch) {
			case 'Y':
			case 'y':
				$s .= "datename(yyyy,$col)";
				break;
			case 'M':
				$s .= "convert(char(3),$col,0)";
				break;
			case 'm':
				$s .= "replace(str(month($col),2),' ','0')";
				break;
			case 'Q':
			case 'q':
				$s .= "datename(quarter,$col)";
				break;
			case 'D':
			case 'd':
				$s .= "replace(str(day($col),2),' ','0')";
				break;
			case 'h':
				$s .= "substring(convert(char(14),$col,0),13,2)";
				break;

			case 'H':
				$s .= "replace(str(datepart(hh,$col),2),' ','0')";
				break;

			case 'i':
				$s .= "replace(str(datepart(mi,$col),2),' ','0')";
				break;
			case 's':
				$s .= "replace(str(datepart(ss,$col),2),' ','0')";
				break;
			case 'a':
			case 'A':
				$s .= "substring(convert(char(19),$col,0),18,2)";
				break;
			case 'l':
				$s .= "datename(dw,$col)";
				break;
			default:
				if ($ch == '\\') {
					$i++;
					$ch = substr($fmt,$i,1);
				}
				$s .= $this->qstr($ch);
				break;
			}
		}
		return $s;
	}
```

**Comment by mnewnham** [comment]
Ok, that makes more sense, it's more of a shortcut than a replacement. Should we add Y-m-d to the shortcut list? otherwise i'm fine with it

**Comment by mnewnham** [comment]
@dregad , can we pull this?

**Comment by laurent-n** [comment]
Y-m-d is not available on the convert format list.
I just saw an error while I read back the doc
,"Y/m/d"=>102,"y/m/d"=>102 // ANSI
should be 
,"Y.m.d"=>102,"y/m/d"=>102 // ANSI
whith . instead of /
Starting on SQL 2012 there's also the most versatile FORMAT function available, but it's slower.
It could be an alternative for non managed by convert

**Comment by dregad** [comment]
@laurent-n thanks for the feedback. Would you be able to update the pull request accordingly ?

**Comment by laurent-n** [comment]
I've just checked, the pull request was OK, the mistake was only on this discussion thread.
