### ISSUE TITLE
Connect mssql2008 R2 64bit Fail?

### ISSUE THREAD

**Issue by tonyguan1981** [ADOdb/ADOdb#306]
error_reporting(E_ALL);
include('../adodb.inc.php');
include('../tohtml.inc.php');

$conn = ADONewConnection("mssql");  // create a connection
$conn->Connect('127.0.0.1','adodb','natsoft','northwind') or die('Fail');// here return fail 

/*
Php ver:5.6.21
Php Server:windows 64bit R2
Db server: :windows 64bit R2
Db : Sql2008R2 64bit 

*/

pls callback as soon as possible.
gj_cong@qq.com

**Comment by dregad** [comment]
Which ADOdb version ?
Did you try with `$conn->debug = true;` ?

**Comment by dregad** [comment]
Closing since you have not provided any feedback.
