### ISSUE TITLE
Uncaught Error: Call to undefined function mysql_connect()

### ISSUE THREAD

**Issue by tolalur** [ADOdb/ADOdb#308]
Hello.
I apologize for maybe stupid question, but
I receive an error

Uncaught Error: **Call to undefined function _mysql_connect()_** in _address to adodb_\adodb\adodb-php\drivers\adodb-mysql.inc.php:461
I use PHP: 7.0.6
As far as I know mysql_connect() is off in php from version 5.5.
I need to downgrade php version to use your library?

**Comment by dregad** [comment]
Use the *mysqli* driver. http://adodb.org/dokuwiki/doku.php?id=v5:database:mysql

**Comment by tolalur** [comment]
Thank you!!!

**Comment by mnewnham** [comment]
@dregad , do you think it would make sense for us to prevent use of the mysql driver itself now? This is still a popular issue that could be resolved by a die() in the base constructor.

**Comment by dregad** [comment]
@mnewnham what about automatically switching to mysqli if PHP version is >= 7.0 instead of dying ? 

For reference, this issue had already been reported, see #195.

**Comment by mnewnham** [comment]
I would go with whatever is easiest. If the class is loaded as mysql, how would we switch to mysqli , given that mysqli extends mysql?

**Comment by dregad** [comment]
Considering that the documented way to initialize an ADOdb connection is by calling `ADONewConnection()`, it should be fairly easy to handle this in there. Of course if someone does `$db = new ADODB_mysql` it will not be possible to switch. In that case overriding the mysql constructor and throwing an error / dying if PHP >= 7 would be the way to go.

**Comment by AbiuBelo** [comment]
Halo goodmorning i am from Timor Leste
i want to ask some thing about php error like that 
Fatal error: Call to undefined function mysql_connect() in /var/www/html/fardamento/db.php on line 6
I hope have anybody help me to give solution...
Thank You

**Comment by AbiuBelo** [comment]
I used php 5.6
