### ISSUE TITLE
Insert_ID method with MSSQL Native Driver Returns null when table name in square brackets

### ISSUE THREAD

**Issue by meeck** [ADOdb/ADOdb#313]
References: [185](https://github.com/ADOdb/ADOdb/issues/185)  [299](https://github.com/ADOdb/ADOdb/issues/299)

In version 5.20.8 and 5.20.9 regular expression searching "insert values" does not match when the table name is in square brackets.
insert into **[tablename]** (field) values ('value')   - not match, not work
insert into **tablename** (field) values ('value') - match

Square brackets are commonly used by SQL Management Studio and you can't simple copy-paste queries into php code.

**Comment by dregad** [comment]
Would changing the regex to simply allow `[` and `]` be sufficient to solve the problem ?

```
^\W*insert[\s\w()[\]",.]+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$
```

(sorry I don't use MSSQL so I can't check)

**Comment by jeremiahmegel** [comment]
@dregad Yes, that change does seem to fix it for me. Shall I submit a pull request, or have you got this?

**Comment by dregad** [comment]
@jeremiahmegel thanks for the feedback. All I needed was a confirmation that the updated regex fixes the issue.

**Comment by dregad** [comment]
I don't think so based on @jeremiahmegel's feedback, but you're welcome to give the updated regex an additional spin

**Comment by mnewnham** [comment]
@dregerd, I've tested this and it seems ok,  you can pull it
