### ISSUE TITLE
Bug in GetAssoc()

### ISSUE THREAD

**Issue by bjoernboldt** [ADOdb/ADOdb#321]
I run 
`$db->GetAssoc("SELECT name, 1 from mytable");`
no results, but E_NOTICE: Undefined offset: 0 in /adodb5/adodb.inc.php Zeile 3549
The error is on line 3481
 `$numIndex = array_keys($this->fields) == range(0, count($this->fields) - 1);`
because (array(0,1) == array('name',1)) is true (in PHP 5.5.9).
I replaced it with
`$numIndex = empty(array_diff(array_keys($this->fields), range(0, count($this->fields) - 1)));`

**Comment by mnewnham** [comment]
What version of ADOdb are you using?
What database driver?

**Comment by bjoernboldt** [comment]
ADODB-Version is v.5.20.9, driver  = 'mysqli' and I use $db->SetFetchMode(ADODB_FETCH_ASSOC);

**Comment by mnewnham** [comment]
There have been numerous threads on the subject of the problems with getAssoc [See here](https://github.com/ADOdb/ADOdb/issues?utf8=%E2%9C%93&q=getAssoc), to that end, the method has been completely re-written for version 5.21. I would recommend you pull the current development source if this is a serious problem for you
