### ISSUE TITLE
Retrieving Data from Store Procesure

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#323]
I am unable to get data when I use a store procedure to get data from database.  IT NEVER RETURNS. I get and max execution error.  What am I doing wrong??  Thank you

==MYSQL
PROCEDURE `sp_get_data`(p_id INT)
BEGIN
    SELECT A,B,C,D,E FROM table WHERE id= p_id;
END

===CODE
$sql = 'CALL sp_get_data (?)';
$stmt = $cn->Prepare($sql);
$row = $cn->GetRow($stmt,array($id));
var_dump($row);

BTW, The store procedure works if I run direction on mysql command line

**Comment by mnewnham** [comment]
You seem to confusing [prepare](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:prepare), which prepares SQL statements and binds parameters,  with [prepareSp](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:preparesp), which accesses existing stored procedures, You might find the [Stored Procedure Guide](http://adodb.org/dokuwiki/doku.php?id=v5:userguide:stored_procedure) helpful,

Here is some (untested) code that might meet your needs
````
$stmt = $cn->PrepareSP('sp_get_data');
$val1 = 'p_id';
$par1 = $id;
$cn->InParameter($stmt,$val1,$par1);
$row = $stmt->fetchRow();
````

**Comment by stccorp** [comment]
Thank you

This worked.  I think I basically needed to use Execute instead of GetRows
            $stmt = $this->cn->Prepare('call sp_get_data (?,?)');
            $rs = $this->cn->Execute($stmt,array($val1,$val2));
            $rows = $rs->GetRows();
