### ISSUE TITLE
Prevent removal of write connection in by removeConnection

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#327]
Could we add a way of preventing the write connection (or last connection) being removed from the pool, or fail gracefully if we don't have a write connection available

**Comment by ipso** [comment]
We have a use case where we try to continue operating in read-only mode if the write connection goes down, so I'm not sure we want to mess with connection logic much more than we already are...

When you say fail gracefully, could you elaborate more? Do you mean throwing an exception directly from the load balancer?

**Comment by mnewnham** [comment]
I think that we should try to bring it into line with existing adodb design, if it fails then it should return false, and if debug is on it should push some kind of message down stdout

**Comment by ipso** [comment]
I looked at the code more closely and when a connection failure happens we return the ADODB object itself and simply *rethrow* any existing ADODB exception that was caught.

If no ADODB objects are available, we throw an exception and return FALSE.

Therefore I'm confused as to what you are actually referring to or wanting "fixed". Can you please provide sample code showing the error case?
