### ISSUE TITLE
ClusterExecute has inconsistent parameter behavior when connection fails

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#330]
ClusterExecutes 3rd parameter **returnAllResults** should indicate whether all results from the command are returned as an array or just the first valid result, but if one of the connections in the cluster fails, the parameter is ignored and all results are always returned. In this example, we have 4 nodes in the cluster, with all hosts available
````php
$ok = $db->clusterExecute('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE',false,true,false);
print_r($ok);
````
The result is
````
Array
(
    [0] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )

    [1] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )

    [2] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )
		
    [3] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )

)
````
Then if we change the command to
````php
$ok = $db->clusterExecute('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE',false,false,false);
print_r($ok);
````
The result is
````
ADORecordSet_empty Object
(
    [dataProvider] => empty
    [databaseType] => 
    [EOF] => 1
    [_numOfRows] => 0
    [fields] => 
    [connection] => 
)
````
**But if one of the connection fails, then the parameter is always treated as _true_**
````
Array
(
    [0] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )

    [1] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )

    [2] => 
		
    [3] => ADORecordSet_empty Object
        (
            [dataProvider] => empty
            [databaseType] => 
            [EOF] => 1
            [_numOfRows] => 0
            [fields] => 
            [connection] => 
        )

)
````

**Comment by ipso** [comment]
That is correct, the idea with this function/parameter is that if all query results are the same, it makes sense to only return a single result if thats the case, as they are all the same anyways.

However if there are any differences (ie: errors) in the results, its impossible to pick the "proper" result to return that the user may be interested in (Just the success? Just the failures? Just the first result? Just the last result?), we can never know for sure, so instead just return all the results and let the user decide themselves.

If we didn't do this and kept the behavior "consistent" as you described, it would just return the first result, which could hide the error from the user if it happened to be the 2nd result. How would they be expected to handle a error or bad result then?
