### ISSUE TITLE
GetAssoc now cuts off first column

### ISSUE THREAD

**Issue by Rubber-Telly-Media** [ADOdb/ADOdb#341]
Hi again,
I got the newest commit form GitHub, adodb-master, and getAssoc sorta works, but now it ignores the first numerical element. I can get around this by SELECTing it twice, but thought I should report this anyway;
e.g.
Record;
Names: ID, First_Name, Last_Name
Values: 1, 'Ben', 'Murphy'

becomes

array (First_Name -> 'Ben', Last_Name->'Murphy')

**Comment by dregad** [comment]
@mnewnham can you please have a look ?

**Comment by mnewnham** [comment]
ok

**Comment by dregad** [comment]
@Rubber-Telly-Media since you have not provided any feedback, I'm closing this issue; feel free to reopen with additional information as requested.

**Comment by Rubber-Telly-Media** [comment]
Sorry, I have been ill. The first column used to be included in the Sub Arrays as associative Key=>Value, this has changed...It broke my old project that relied on the First Column being in the Sub Array.

**Comment by Rubber-Telly-Media** [comment]
I rewrote the old project to not use this function any more due to this change in functionality.

**Comment by Rubber-Telly-Media** [comment]
By the way, the Old Functionality would have produced;
`
Array
(
    [10001] => Array
        (
            [EMP_NO] => 10001
            [FIRST_NAME] => Georgi
            [LAST_NAME] => Facello
        )

    [10002] => Array
        (
            [EMP_NO] => 10002
            [FIRST_NAME] => Bezalel
            [LAST_NAME] => Simmel
        )

    [10003] => Array
        (
            [EMP_NO] => 10003
            [FIRST_NAME] => Parto
            [LAST_NAME] => Bamford
        )
)
`

**Comment by dregad** [comment]
Thanks for the feedback. Hope you're feeling better now.

> due to this change in functionality.

The function's documentation has always mentioned *The first column is treated as the key and is not included in the array*, as far back as the initial version of the adodb5 code goes (over 10 years ago). I did not actually test whether the code actually did though.

Can you clarify what exact version you refer to as *Old Functionality*, that produced the above output ?

**Comment by Rubber-Telly-Media** [comment]
Thanks for the clarification, the "Ye Olde" project I am maintaining is very old and badly coded...so, I'm not sure if it ever worked as expected, it works now that I have changed the code to not use getAssoc(). I am only expecting one record set anyway, but later code expects a numerical array containing associative arrays...like I said before, badly written code...

It's just too bad I can't recode the whole PHP project...

ADOdb is excellent and I will continue to use it.

Feel free to close this thread.

**Comment by dfaure57** [comment]
I allways used `$rs->getAssoc(false)`. Now I have to recode with `$rs->GetAssoc(true)` in order to have all columns in the result array

**Notice** that there is a lack of documentation with the getAssoc method. Both connection object and recordset object has a getAssoc method, but they are different and for different purposes. On the wiki we only have the documentation for the first one
