### ISSUE TITLE
SAP HANA

### ISSUE THREAD

**Issue by manuelhz** [ADOdb/ADOdb#343]
Hi,

I have an web aplication that works on MSSQL, but now i need migrate the aplication to SAP HANA.
I tried using PHP without ADOdb and it works (I take the code from: https://blogs.sap.com/2013/01/21/php-rocks-on-sap-hana-too/)
The code that I'm trying for ADOdb:
````php
include("adodb5/adodb.inc.php");
$db = NewADOConnection('odbc');
$db->Connect("Driver={HDBODBC32};Server=[IP]:[Port];Database=[DatabaseName];", '[USER]','[Password]');
$result = $db->Execute("select * from [DatabaseName].[Table]");
if ($result === false) die("failed");
while (!$result->EOF) {	
echo $result->fields[0];
$result->MoveNext();
}
````

When I execute the code my error is:

Warning: odbc_connect() [function.odbc-connect]: SQL error: [SAP AG][LIBODBCHDB32 DLL][HDBODBC32] Communication link failure;-10709 Connect failed (no reachable host left), SQL state 08S01 in SQLConnect in C:\AppServ\www\adodb5\drivers\adodb-odbc.inc.php on line 66
failed

Nowhere seid that ADOdb works with HANA, but I'm trying.
Thank you.

**Comment by mnewnham** [comment]
Are you sure that this is not an issue as described [here](https://www.stechies.com/getting-error-rootcause-reachable-host-left/)

**Comment by manuelhz** [comment]
I'm sure that it is not the problem.

**Comment by dregad** [comment]
You say it works with PHP, but not ADOdb, but the error you reported is triggered by the odbc_connect() call, with the given parameters, not by ADOdb itself.

As you pointed out, SAP HANA is not an officially supported database. I do not have access to an environment for testing (and I don't think @mnewnham does either), so it would be difficult to provide any help, so I'm afraid there is not much more we can do for you.
