### ISSUE TITLE
getAssoc() does not respect ADODB_FETCH_ASSOC

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#350]
The following code snippet
``` php
$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;
$db = ADOnewConnection('mysqli');
$db->connect('localhost',$user, $password,$database);
$sql = "SELECT emp_no,first_name,last_name from employees" limit 1;
$r = $db->getAssoc($sql);
```

Produces
```
Array
(
    [10001] => Array
        (
            [0] => Georgi
            [1] => Facello
        )
)
```

instead of the expected output
```
Array
(
    [10001] => Array
        (
            [first_name] => Georgi
            [last_name] => Facello
        )
)
```

**Comment by dregad** [comment]
Probably due to difference in mysqli vs adodb fetch mode constant values :
- ADODB_FETCH_ASSOC = 2
- MYSQLI_ASSOC = 1
- ADODB_FETCH_NUM = 1

To fix this, getAssoc() should use `$this->adodbFetchMode` instead of `$this->fetchMode` ? But I  the former is not defined for all drivers IIRC

**Comment by mnewnham** [comment]
getAssoc reads $db->fetchMode, which i believe is modified by the mysql driver as the records are retrieved
replacing it with a globalised $ADODB_FETCH_MODE fixes the problem.  I think this is another problem with competing uses for the same variable, as well as competing variables for the same use, I have a patch available for this

**Comment by OliverLeitner** [comment]
i can confirm the problem (still exists?):

windows 2008 server
xampp latest (version from 30.06.2017)
php 7.1.6
mariadb 10.1.24-MariaDB
adodb: 6cafd5579929c6e7f5ad8a5dadc33ad2a3d87c9a (06.06.2017)

do you guys know of any workaround?
