### ISSUE TITLE
Help with OutParameter

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#351]
I cant get outParameter to work, Any idea Why?

My procedure:
PROCEDURE myprocedure (IN `p_one` int,IN `p_two` int,OUT `p_three` int)

CODE
 ```
$parameter1Name = 'p_one';
            $parameter1Value = "1";

            $parameter2Name = 'p_two';
            $parameter2Value = "1";

            $parameter3Name = 'p_three';
            $parameter3Value = '';

               $procedure = $db->prepareSp('myprocedure');

                if (!$procedure)
                    die ('Invalid or inaccessible stored procedure name');

                $db->inParameter($procedure,$parameter1Value,$parameter1Name);
                $db->inParameter($procedure,$parameter2Value,$parameter2Name);
                $db->outParameter($procedure,$parameter3Value,$parameter3Name);
                $rs = $db->execute($procedure);
```

ERROR
Query: myprocedure  failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'myprocedure ' at line 1
`

**Comment by dregad** [comment]
Stored Procedures (and prepared statements) are currently not supported with MySQL 
http://adodb.org/dokuwiki/doku.php?id=v5:database:feature_comparison

**Comment by stccorp** [comment]
Thanks you .  Is this something that is almost impossible to do? I guess my question is if there are some technical challenges or is it just a matter of time to develop the functionality? Any thing we could do to help develop this?

**Comment by dregad** [comment]
> Is this something that is almost impossible to do?

I didn't say that... I only stated that ADOdb currently does not support it for MySQL, most likely because no one ever took the time to implement this functionality; there might be technical challenges, but as long as the underlying native php driver supports it, I'm sure it can be done.

In other words, if you are willing to spend the time and develop this functionality, your contribution (in the form of a pull request) will be very welcome.

**Comment by stccorp** [comment]
If I tried to do this.  Do you have a document explaining the architecture or is just start looking at code?

**Comment by dregad** [comment]
All the documentation we have is at http://adodb.org and in the code itself.
If you have questions, feel free to ask on our [Gitter channel](https://gitter.im/ADOdb)
