### ISSUE TITLE
Problems with placeholders

### ISSUE THREAD

**Issue by CrazyHackGUT** [ADOdb/ADOdb#352]
```
$data = array(); // <-- problematic var
$db->Execute("UPDATE `mytable` SET `value` = ? WHERE `name` = ?", array($data, "some_setting"));
```
`Execute` generates a SQL query:
```
UPDATE `mytable` SET `value` = Array WHERE `name` = 'some_setting'
```

**Comment by dregad** [comment]
I'm not sure what you are trying to do here. You can't use a PHP array as a query parameter.

**Comment by CrazyHackGUT** [comment]
One system, which I am forced to use because of the lack of analogues, do not filter input vars.
Because of this ordinary ordinary user can simply take and turn the entire web-panel, or make XSS-injection (the system logs all unsuccessful requests without proper screening) for admins.
Yes, i understand, that this is a problem of the system I use, but Developers have not released updates for 10 years! They simply update third-party libraries (including ADOdb) every six months.

**Comment by dregad** [comment]
Well I'm sorry to hear that, but I'm afraid there is not much that I can do about it.
