### ISSUE TITLE
Missing CSV legacy documentation

### ISSUE THREAD

**Issue by PSF1** [ADOdb/ADOdb#356]
Hi,

In the CSV Driver documentation say:

http://adodb.org/dokuwiki/doku.php?id=v5:database:csv
> The syntax required and necessary file formats have not yet been identified from the legacy documentation. Can you help?

Is this the required documentation? https://web.archive.org/web/20030708131050/http://php.weblogs.com:80/adodb_csv

Thxs

**Comment by mnewnham** [comment]
Its certainly helpful. I've bookmarked that page and will review it ASAP

Thanks!

**Comment by mnewnham** [comment]
Well, that was not at all what I expected this driver to be. I've updated the documentation to reflect actual usage, and I'm preparing a list of enhancements that the product requires

**Comment by PSF1** [comment]
I remembered something about that, I use adoDB since about 2004, but I don't used that driver never.

I has code to do so simple queries over JSON files, of course, only in read mode. A CSV version maybe be useful?
 
And now I'm working on a noSQL query library, but using SQL :D... mmm a !noSQL? gg the last one is so early versión and it's not public, for now.
