### ISSUE TITLE
documentation GetCommentSQL()

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#358]
http://adodb.org/dokuwiki/doku.php?id=v5:dictionary:getcommentsql

Typo in the usage example: There is no adodb function getColumnSql() , only GetCommentSQL().

Also GetCommentSQL() seems to be unused, maybe deprecate and instead have this available that does  the real work:

getTableComment($table)
setTableComment($table, $comment)

getColumnComment($table,$column)
setColumnComment($table,$column,$comment);

Column comment handling differs between databases. Some have extra queries for that (oracle), some require to be set with the full column definition (ALTER/MODIFY in mysql)

**Comment by mnewnham** [comment]
I have fixed the typo and emphasized that the function is only available for Oracle databases. I am closing this issue, but if you wanted to expand your suggestion out a little further, perhaps with some protoype code, feel free to open it up as a new issue that we can tag as an enhancement.
