### ISSUE TITLE
Resource ID#23 used as offset …

### ISSUE THREAD

**Issue by mckeller** [ADOdb/ADOdb#360]
Hi,

I'm new to a company, which website is having a problem with ADOdb. On every page it says: 

`Strict Standards: Resource ID#23 used as offset, casting to integer (23) in /mnt/web020/c3/27/5865527/htdocs/komplettbestattungen/xtFramework/library/adodb/drivers/adodb-mysql.inc.php on line 487 Strict Standards: Resource ID#23 used as offset, casting to integer (23) in /mnt/web020/c3/27/5865527/htdocs/komplettbestattungen/xtFramework/library/adodb/drivers/adodb-mysql.inc.php on line 487 Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /mnt/web020/c3/27/5865527/htdocs/komplettbestattungen/xtFramework/library/adodb/drivers/adodb-mysql.inc.php:487) in /mnt/web020/c3/27/5865527/htdocs/komplettbestattungen/xtFramework/database_handler.php on line 94 Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /mnt/web020/c3/27/5865527/htdocs/komplettbestattungen/xtFramework/library/adodb/drivers/adodb-mysql.inc.php:487) in /mnt/web020/c3/27/5865527/htdocs/komplettbestattungen/xtFramework/database_handler.php on line 94`

And when you want to continue from a recent subpage to another subpage you'll see only this error message without any content. Sorry, but I didn't worked before with ADOdb, so I'm quite helpless in this case. It's a quite old page and it used to run before.

Thanks in advance!

Marvin

**Comment by dregad** [comment]
Can you please provide additional information
- ADOdb version
- PHP version
- Sample code snippet to reproduce the problem

**Comment by peterdd** [comment]
Seems to be a xt:c veyton shop, uses ioncube encrypted php: https://xtcommerce.atlassian.net/wiki/spaces/MANUAL/pages/2555920

**Comment by mckeller** [comment]
> Can you please provide additional information

PHP version: 5.6
ADOdb version: In the "license.txt" ist says: "GNU LESSER GENERAL PUBLIC LICENSE
Version 2.1, February 1999"

Which kind of code snippet do you need?


> Seems to be a xt:c veyton shop, uses ioncube encrypted php

Yes, it uses ioncube and a xt:c shop. But I thought there is a problem with some ADOdb files.

**Comment by dregad** [comment]
Closing due to lack of feedback. Feel free to reopen with requested information.
