### ISSUE TITLE
Cant include adodb.inc.php

### ISSUE THREAD

**Issue by deepx** [ADOdb/ADOdb#365]
Hi.

I want to include the adodb.inc.php, but the resurt is an error. If i rename it to "adodb.php"
it works. Someone got a clue here?

greets
DeepX

The line of code: `$result = include "adodb/adodb.inc.php";`

**Comment by dregad** [comment]
You say the result is an error, but did not specify what the error message is.
Anyway, I'm not able to reproduce this. This is most likely not an ADOdb issue.

**Comment by Eternal-Infinity** [comment]
If you can provide what the error says, we might be able to help.
Though this really doesn't sound like a adodb issue.

However, the include could crash for several reasons....for example if you already included the adodb.inc.php before.
You can't include the same classfile twice (use include_once for this)
It's just a guess.
Consult http://php.net/manual/en/function.include.php for more informations on what might have gone wrong here.

**Comment by dregad** [comment]
> for example if you already included the adodb.inc.php before.

This can't happen, the file has an include guard.
