### ISSUE TITLE
Wrong replacement '?' in oci8po driver

### ISSUE THREAD

**Issue by Benjaminhu** [ADOdb/ADOdb#370]
I would update the driver but broke my many queries!

```sql
SELECT * FROM users WHERE user_code = 'AB?CE' OR id = ? OR user_mobile = 'AB?CD' 
```
Regular expression explanation: https://regex101.com/r/dNXqxo/3

Related issue: #132 and commit:  eb9d83915fcfdcd4a4fb3f65a586e6c60be598f7

**Comment by mnewnham** [comment]
Which version are you updating from and to?

**Comment by Benjaminhu** [comment]
From: version V5.18 3 Sep 2012
To: version   v5.20.9  21-Dec-2016
[Changelog](https://github.com/ADOdb/ADOdb/blob/v5.20.9/docs/changelog.md) 5.20.0 - 28-Nov-2015:
oci8po: Prevent replacement of '?' within strings, thanks to Mark Newnham. See Github #132

**Comment by Benjaminhu** [comment]
Please look at the regular expression explanation (https://regex101.com/r/dNXqxo/3), the error (wrong regexp) is clearly visible!

**Comment by dregad** [comment]
@Benjaminhu This is certainly not perfect but maybe you can try with `"(?:\\"|[^"])*"|'(?:\\'|[^'])*'` which, at least on your provided test string, yields the correct results.

I can't run an actual test as I don't have access to an Oracle instance, but I think it should handle escaped single quotes `''` correctly; I'm not sure what other kind of edge cases could trick it.

**Comment by Benjaminhu** [comment]
Thanks for the modified regexp! But we do not want to risk breaking SQL in the future.
Could it be possible to control this operation with a switch (in adodb-oci8po.inc.php)? 
Example: $questionmarkreplace = true / false; // default: true
Thanks! If I help you make the pull request!

**Comment by Benjaminhu** [comment]
@dregad ping

**Comment by Benjaminhu** [comment]
@dregad ping

**Comment by mnewnham** [comment]
@dregad , any chance you could get that regexp converted to php flavour? I've got a chance to test this, and it's sheer laziness on my part that I don't want to sit down and do all the escaping necessary to make it work.
