### ISSUE TITLE
Connecting to Microsoft Sql Server with PHP 7 from Linux (mssql and/or sqlsrv drivers) ms sqlserver

### ISSUE THREAD

**Issue by wesyah234** [ADOdb/ADOdb#372]
I don't typically connect to MS Sql Server databases but I need to now (from Linux).  So, in researching my options I've found that ADOdb recommends mssql, so i installed FreeTDS and the mssql php extensions and it works fine. However, the PHP.net website states that mssql support is being removed from PHP 7.

http://php.net/manual/en/intro.mssql.php
"Warning: This feature was REMOVED in PHP 7.0.0. "

More research led to a page on Microsoft's website and a corresponding github project:
https://www.microsoft.com/en-us/download/details.aspx?id=20098&e6b34bbe-475b-1abd-2c51-b5034bcdd6d2=True&fa43d42b-25b5-4a42-fe9b-1634f450f5ee=True

https://github.com/Microsoft/msphpsql

This is a project to provide a newly named driver for connecting to MS Sql Server databases from PHP 7 and it also supports Linux environments.   Full Ubuntu and Redhat instructions are available.

So, my question is:  Are the ADOdb developers planning to provide abstraction for this new driver from microsoft so that we can continue to connect after upgrading to php 7?  I'm not on 7 yet but I'm sure we will be moving there soon and I am wondering if I will have to rewrite all my code or if I will be able to just flip from 'mssql' to 'sqlsrv' and pick up this new driver while still using ADOdb.

Thanks!

**Comment by mnewnham** [comment]
Note that we only recommend php_mssql for non-windows platforms. 

This new project seems to implement the PDO driver for SQL server, which we have, but the status of it is unknown. Obviously if this is going to be preferred mechanism instead of freetds we would need to test and improve it

I think that as long as the php functions are named the same, and the data returned is the same there should be no problem. That is how ADOdb works. If they change the names however, then we would need to modify the driver.  

Would you be interested in putting in some to test it?

**Comment by wesyah234** [comment]
I would certainly be able to test.  But now I'm a bit more confused.  What do you mean by "we only recommend php_mssql for non windows"  What is php_mssql?  The driver names mentioned on your page:
http://adodb.org/dokuwiki/doku.php?id=v5:database:microsoft_sql_server
are mssql_native, mssql, and mssql_po

Also, as far as the function names changing, it seems they certainly will be changing.  Currently, ADODB using 'msssql' as the driver name, ends up using these functions:
http://php.net/manual/en/book.mssql.php

However, the new project from Microsoft seems to be implementing a differently named set of functions, specifically the ones under the 'sqlsrv' driver, which also has a page on php.net:
http://php.net/manual/en/book.sqlsrv.php

Also, they are implementing both their sqlsrv driver and their pdo_sqlsrv driver, as shown here in their examples:
https://github.com/Microsoft/msphpsql/tree/master/sample
they have both pdo and non pdo.

**Comment by mnewnham** [comment]
When I said php_mssql, I did mean  pdo_mssql.

The drivers seem to be using the native mode driver, mssqlnative, so any work on this would need to be based on that driver. For non pdo drivers it's likely to be usable as is. Not sure what kind of work we would need to do for the pdo driver

**Comment by dregad** [comment]
@mnewnham I'm not sure what the status on this is. Are you working on some fixes ? Should the issue remain open ?

**Comment by mnewnham** [comment]
Should be left open I think, but right now I'm not working on anything.  The problem that I see with this development thread is 
1. It needs both sql server, pdo and linux/php expertise (quite a rare combination)
2. The driver usage is likely to be very low
3. PDO driver usage is also much lower

I do realize that microsoft are pushing SQL Server into the Linux platform (I'm using it myself quite successfully) but right now the effort/takeup on this driver is going to be pretty minimal so lets just sit on it for the moment

**Comment by thewolft** [comment]
disculpen necesito conectarme a una base de datos sql server desde ubuntu usando php 7 si pueden explicarme paso a paso el proceso de configuracion y la sintaxis que deberia usar nunca he hecho conecciones a sql server y es urgente si saben como porfavor expliquenme

**Comment by dregad** [comment]
Thanks @gohanman for the follow-up. Based on your feedback, I'm closing this issue. 

Feel free to reopen if necessary.
