### ISSUE TITLE
PHP7: Call to undefined function mysqli_query()

### ISSUE THREAD

**Issue by CristianNunes** [ADOdb/ADOdb#374]
After update to  php 7, this problem began to appear, i have the latest ADOdb version
The problem is only executing on php_cli

after:
$conn = ADONewConnection('mysqli');
on execute:
$conn->PConnect('ip_addr','user','pass','db') ;

Stack trace:
#0 /var/www/adodb/adodb.inc.php(1251): ADODB_mysqli->_query('SELECT\n        ...', false)
#1 /var/www/adodb/adodb.inc.php(1229): ADOConnection->_Execute('SELECT\n        ...', false)
#2 /var/www/IspControl/ScriptsUBNT/updateFirmware.php(126): ADOConnection->Execute('SELECT\n        ...')
#3 {main}
  thrown in /var/www/adodb/drivers/adodb-mysqli.inc.php on line 786

**Comment by mnewnham** [comment]
You do not have the mysqli driver enabled in php. If you are on windows, you need to enable 
``
extension=php_mysqli.dll
``

**Comment by CristianNunes** [comment]
I had installed php7, but my apache was loading the 5 still, I removed the 5 and it worked, it's strange that in the browser it was working normal, only the cli did not
