### ISSUE TITLE
adodb_validdate: expression is always false

### ISSUE THREAD

**Issue by AppChecker** [ADOdb/ADOdb#375]
Hi!
This expression:

https://github.com/ADOdb/ADOdb/blob/6cafd5579929c6e7f5ad8a5dadc33ad2a3d87c9a/adodb-time.inc.php#L819

is always false.

Probably it should be:
`if ($y < 1000 || $y > 3000) return false;`

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by dregad** [comment]
Thanks for your contribution
