### ISSUE TITLE
ODBC connection UTF-8 issue

### ISSUE THREAD

**Issue by Arananetwork** [ADOdb/ADOdb#377]
I am using ADODB ODBC connection to Sql Server.
The problem is reading/writing Arabic characters from data base returns ???????

In ADO connection i can set charPage=65001 which resolves the issue but I need ODBC because  my shared hosting supports ODBC.

Is there any settings for ODBC to set the connection code page?

**Comment by dregad** [comment]
I am sorry but I have no idea. Maybe someone else will be able to help you.

**Comment by mnewnham** [comment]
You can try something like this in the DSN string:
````
$dsn = "DRIVER={ODBC Driver 11 for SQL Server};SERVER=$server_address};CHARSET=UTF-8";
````
But there seems to be issues with this under windows 10. for more on this problem, see [this thread](https://stackoverflow.com/questions/34205727/set-dsn-encoding-for-odbc-driver-11-for-sql-server-on-windows-10) on stackoverflow.
