### ISSUE TITLE
include pdo_firebird driver

### ISSUE THREAD

**Issue by mawouzo** [ADOdb/ADOdb#378]
since php 7.0.03 the firebird extension can't be used with ADOdb. It woud be good to include the pdo_firebird driver in ADOdb.

**Comment by gohanman** [comment]
I was looking into this and it seems like the existing Interbase extension driver (`drivers/adodb-ibase.inc.php`) works fine and the Interbase extension is available in PHP7. I'm testing against Firebird 2.5.4.

Is there anything `pdo_firebird` can do that `interbase` can't? If not it seems like adding another Firebird driver is just creating extra maintenance work.

**Comment by mawouzo** [comment]
Yes, it is. Please look at this thread:
https://bugs.php.net/bug.php?id=72175

**Comment by mnewnham** [comment]
I've added a PDO driver for Firebird, this is an initial release. If you have the time to help testing, please do

**Comment by dregad** [comment]
@mnewnham not sure why you closed this, the branch with the new driver was not actually merged into master.
