### ISSUE TITLE
pgsql: incorrect resetting of query parameters counter

### ISSUE THREAD

**Issue by globetrotterxxl** [ADOdb/ADOdb#380]
Hello,

I have issues with complex postgres queries, because the parameter counter (_pnum) get's confused.
When I reset the parameter count with `$db->Param(false);`, it creates an sql statement like 
`select * from t where param = $2` instead of `select * from t where param = $1`.

suggestion:
```
615c615
<                       $this->_pnum = 1;
---
>                       $this->_pnum = 0;
```

Original issue title:
drivers/adodb-postgres64.inc.php (614) reset of _pnum to 1 instead of 0

**Comment by dregad** [comment]
I suppose you're doing something like

``` php
$db->Param(false);
$sql = "SELECT * FROM table WHERE col = " . Param();
```

I think the function was meant to be called like this:

``` php
$sql = "SELECT * FROM table WHERE col = " . Param(false);
```

While I agree that it makes sense to be able to reset the parameter counter separately from assigning a new parameter, I'm reluctant to implement such change, because it would break existing code relying on the original behavior and standard usage of Param().

I believe it would be better to define a new, distinct method to reset the parameter count.

**Comment by globetrotterxxl** [comment]
Ok, I understand. To have the code portable among databases I used to pass a real $name to the function:

```PHP
$db->Param(false);
$sql = "SELECT * FROM table WHERE col = " . $db->Param("COL");
```
I agree that it's better to have a distinct function for parameter reset.

**Comment by dregad** [comment]
After a bit of research, it appears that the function to reset the parameter count was only introduced in the PostgreSQL driver's relatively recent history (5.19, 842c39d879349852811f3dbd6d55df1638ca15a6).

Based on your last update, I'm now thinking the implementation is fact incorrect - and so is my earlier note, as it failed to consider the case of drivers actually using named parameters (I mostly work with mysql these days and tend to forget about other use cases); it makes more sense to use *Param()* as you described it. 

I would therefore propose the following fix as an improvement over your original suggestion, let me know what you think:

```patch
diff --git a/drivers/adodb-postgres64.inc.php b/drivers/adodb-postgres64.inc.php
index 99d6d04..393c980 100644
--- a/drivers/adodb-postgres64.inc.php
+++ b/drivers/adodb-postgres64.inc.php
@@ -634,12 +634,12 @@ class ADODB_postgres64 extends ADOConnection{
    function Param($name,$type='C')
    {
        if ($name) {
-           $this->_pnum += 1;
+           $pnum = $this->_pnum++;
        } else {
            // Reset param num if $name is false
-           $this->_pnum = 1;
+           $pnum = $this->_pnum = 1;
        }
-       return '$'.$this->_pnum;
+       return '$' . $pnum;
    }
 
    function MetaIndexes ($table, $primary = FALSE, $owner = false)
```

Note to self: documentation needs to be updated too
http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:param

**Comment by dregad** [comment]
Not sure if it's still worth implementing a new function to reset the parameter count anymore.

**Comment by globetrotterxxl** [comment]
don't know if I understand correctly. But if you initialize _pnum with 1 and increment if $name is true, 
then the first parameter would be $2?

**Comment by dregad** [comment]
The *_pnum* property is an internal counter, holding the value of the *next* parameter to be assigned.

The method returns its value *before* it is incremented (`$pnum = $this->_pnum++;`)

**Comment by mnewnham** [comment]
@dregad , Is this something you need left open?
