### ISSUE TITLE
Incorrect Postgres ALTER TABLE Syntax (xmlschema)

### ISSUE THREAD

**Issue by boshrin** [ADOdb/ADOdb#383]
On 5.20.9 (and prior versions), if I change a column definition in my schema file, eg

`<field name="bar" type="C" size="512" />`

to

`<field name="bar" type="C" size="1024" />`

incorrect SQL is generated for Postgres. Specifically, something like

`ALTER TABLE foo ALTER COLUMN bar VARCHAR(1024)`

instead of

`ALTER TABLE foo ALTER COLUMN bar TYPE VARCHAR(1024)`

The problem appears to be in `adodb-datadict.inc.php::ChangeTableSQL()`, which reimplements its own ALTER TABLE syntax rather than using the (potential) database specific syntax. A simple fix (though perhaps not the correct one?) is to use `$this->AlterColumnSQL()` instead. Here's a sample patch:

```--- a/app/Vendor/adodb5/adodb-datadict.inc.php
+++ b/app/Vendor/adodb5/adodb-datadict.inc.php
@@ -996,33 +996,8 @@ class ADODB_DataDict {
                        $flds = $holdflds;
                }

-
-               // already exists, alter table instead
-               list($lines,$pkey,$idxs) = $this->_GenFields($flds);
-               // genfields can return FALSE at times
-               if ($lines == null) $lines = array();
-               $alter = 'ALTER TABLE ' . $this->TableName($tablename);
-               $sql = array();
-
-               foreach ( $lines as $id => $v ) {
-                       if ( isset($cols[$id]) && is_object($cols[$id]) ) {
-
-                               $flds = Lens_ParseArgs($v,',');
-
-                               //  We are trying to change the size of the field, if not allowed, simply ignore the request.
-                               // $flds[1] holds the type, $flds[2] holds the size -postnuke addition
-                               if ($flds && in_array(strtoupper(substr($flds[0][1],0,4)),$this->invalidResizeTypes4)
-                                && (isset($flds[0][2]) && is_numeric($flds[0][2]))) {
-                                       if ($this->debug) ADOConnection::outp(sprintf("<h3>%s cannot be changed to %s currently</h3>", $flds[0][0], $flds[0][1]));
-                                       #echo "<h3>$this->alterCol cannot be changed to $flds currently</h3>";
-                                       continue;
-                               }
-                               $sql[] = $alter . $this->alterCol . ' ' . $v;
-                       } else {
-                               $sql[] = $alter . $this->addCol . ' ' . $v;
-                       }
-               }
-
+               $sql = $this->AlterColumnSQL($tablename, $flds);
+
                if ($dropOldFlds) {
                        foreach ( $cols as $id => $v )
                            if ( !isset($lines[$id]) )```

**Comment by dregad** [comment]
Thanks for your contribution. Next time please consider submitting a pull request instead of pasting a diff, it makes the review process easier. I'll have a look at this as time allows (hopefully after Xmas).

**Comment by mnewnham** [comment]
I think this needs to go into the datadict-postgres.inc.php file, not adodb-datadict

**Comment by boshrin** [comment]
@dregad Submitted as PR #385 .

@mnewnham As I understand it, datadict-postgres.inc.php already has the correct logic in AlterColumnSQL(). However, in adodb-datadict ChangeTableSQL() basically implements its own ALTER TABLE code generation, missing out on the dialect specific version. Replacing the local code with a call to AlterColumnSQL appears to generate the correct SQL for Postgres (at least in my testing).

**Comment by asmecher** [comment]
I've also run into this issue. @boshrin (and others), what's the status of the closed PR? Is there any further progress?

**Comment by mnewnham** [comment]
Apparently @boshrin was unable to complete the fix due to lack of time. The original issue remains, if it you interested in providing a fix.

**Comment by asmecher** [comment]
I've been maintaining a modified older copy of ADODB that addresses this; I'll see what I can do.

**Comment by boshrin** [comment]
Coincidentally, I had just asked one of our other developers (@tomzeller) to take this up again. We'd be happy to coordinate work/testing/etc.

**Comment by asmecher** [comment]
I posted a comment on the PR that I actually intended to post here: https://github.com/ADOdb/ADOdb/pull/385#issuecomment-404231930

**Comment by asmecher** [comment]
@tomzeller/@boshrin, sorry to ping you, but do you expect you'll have a chance to look at the change proposed in https://github.com/ADOdb/ADOdb/issues/383#issuecomment-404235947 anytime soon?

**Comment by mnewnham** [comment]
I am currently reviewing **every** issue and pull request.  There, unfortunately more than 20 of each to review, and postgres has my lowest level of expertise. Reviewing the thread above, it looked like you were asking to implement postgres-specific code into the core adodb-datadict.inc.php, which I'm not keen on. There may be no alternative so its not a definite no. Just bear with me a little while and I'll get to it.

**Comment by asmecher** [comment]
@mnewnham, thanks for looking at this.

> could you expand upon, and provide a scenario where the original change failed?

Do you mean where @boshrin's proposal (https://github.com/ADOdb/ADOdb/pull/385) failed, but my proposal (https://github.com/asmecher/ADOdb/commit/d3b3b3ebfcd76e52689e625f3973c204e3828aa4) didn't?

**Comment by mnewnham** [comment]
Yes, in your proposal, there are a couple of issues that I see that would be addressed if @boshrin 's proposal had worked:

1.  The SQL statements don't support items like name quoting.

2. The use of the $recreate fallback, which is well understood in the postgres driver, but which might have unexpected results in other drivers

So what I'm trying to understand is if this is a postgres only issue, in which case we need to perhaps attack the postgres driver and make fixes there, then use @boshrin 's solution, or if in fact this is a non-database specific error, In which case we should make sure the code in your solution is cross-database compatible and enhance it to ensure that it fully supports name quoting etc

**Comment by boshrin** [comment]
I think this is superficially a postgres only issue, due to the variant of the ALTER TABLE syntax it uses. I guess what struck me as odd though was that ChangeTableSQL() reimplemented a lot of the logic in AlterColumnSQL(), though the latter was more robust. But I'm certainly not an expert in the codebase, so I'm not sure what the right direction here is...

**Comment by mnewnham** [comment]
I'm afraid that reimplementation of code with ever-decreasing levels of robustness is a persistent problem with the codebase, as might be expected with a product 20ish years old. Do you think that refactoring the postgres code so that the above-mentioned methods actually share the altercolumnsql() code might get us most of the way to resolving this?

**Comment by tomzeller** [comment]
Here is a datadict-postgres that works for us :

https://github.com/tomzeller/comanage-registry/blob/CO-1570/app/Vendor/adodb5/datadict/datadict-postgres.inc.php
 
It is a copy of :

https://github.com/Flyspray/flyspray/blob/master/setup/upgrade/1.0/datadict-postgres.inc.php

which was referenced in :

https://github.com/ADOdb/ADOdb/issues/124

plus fixes for handling REFERENCES and SERIAL.
