### ISSUE TITLE
cut a release?

### ISSUE THREAD

**Issue by chadxz** [ADOdb/ADOdb#384]
We're running into #347 and I see there has already been a fix put into place for it. The last release was December of last year. Would you mind cutting a release so we can upgrade our ADOdb to pull the fix in?

I'd rather not have our application pointing at a git commit, but rather a tagged release.

Thanks for all you do. We appreciate ADOdb!

**Comment by dregad** [comment]
@chadxz I started working on 5.20.10 release a few weeks ago but unfortunately didn't have time to finish things. I have a few days off after Xmas, and I'm planning to complete this task then. 

Thanks for your understanding.
