### ISSUE TITLE
How a MySQL statement turns into a MSSQL statement with ADOdb??

### ISSUE THREAD

**Issue by arturcesarmelo** [ADOdb/ADOdb#386]
I'm working with a system which uses different DataBases, but a single custom PHP framework which write pure SQL.

 i've tried this:

```php
$sql = "SELECT * FROM table ORDER BY column DESC LIMIT 1";
$handler = $this->conn->prepare($sql);
$this->conn->_Execute($handler);
```

The **problem**  is the `LIMIT` keyword. In MSSQL it's uses `TOP` instead of `LIMIT` and right after `SELECT` declaration, not at the end as we use to do in MySQL or PostgreSQL.

Any solution?

Best regards.

**Comment by mnewnham** [comment]
Please use [SelectLimit](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:selectlimit) instead of execute. This provides the necessary database independence you require
