### ISSUE TITLE
AutoExecute does not store time into timestamp/datetime fields (mysql)

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#387]
I have a mysql table with a datetime field. When I do INSERT/UPDATE via AutoExecute the date is inserted, but the time isn't:

$dbconn->AutoExecute('testtable', array('fld_datetime'=>date()) ,'INSERT');
I get the following: 2018-01-19 00:00:00

So the time is set to midnight regardless of the actual time information. Same for fields of type "timesamp"

**Comment by geri777** [comment]
I think AutoExecute expects strings only. So I have to convert my PHP Date into a string: 
date('Y-m-d H:i:s')

**Comment by dezertdezine** [comment]
I'm finding this broken even with a string:

Inserting: '2012-12-12 12:12:12'
Saved: ''2012-12-12 00:00:00'
