### ISSUE TITLE
AutoExecute for MySQLi failed

### ISSUE THREAD

**Issue by MariaKlik** [ADOdb/ADOdb#388]
function AutoExecute for driver MySQLi failed.
Error: "2014: Commands out of sync; you can't run this command now"
In the current version ADOdb (v5.20.9) function AutoExecute does not work, 
because preliminary request is not closed.
Manual adding of $rs->Close(); before $this->Execute ($sql); only helps.
Or adding $rs->Close(); in functions GetUpdateSQL/GetInsertSQL before return.
The same situation with a separate launch of GetUpdateSql/GetUpdateSQL before Execute.

Mysql Server: 5.5.44-MariaDB - MariaDB Server 
MySQL Error Reference:
https://dev.mysql.com/doc/refman/5.7/en/commands-out-of-sync.html

**Comment by mnewnham** [comment]
This seems to be random, but has been seen before, mysqlt allowed it, but mysqli does not:
**Where an ADOdb command is executed but the recordset never retrieved**
````php
$result = $db->execute('SOME SQL STATEMENT');

/*
* Immediately followed by
*/
$result = $db->execute('SOME OTHER STATEMENT');
while ($r = $result->fetchRow())
.......
````
Check for orphaned statements

**Multiple Nested Loop Scenario**
````php
$result = $db->execute('SOME  STATEMENT');
while ($r = $result->fetchRow())
{ 
     /*
     * Some loop processing, includes...
     */
     $result2 = $db->execute('SOME OTHER STATEMENT');
      while ($r2 = $result2->fetchRow())
}
````
Change To:
````php
result = $db->execute('SOME  STATEMENT');
$ar = $result->getAll();
foreach ($ar as $r)
{ 
     /*
     * Some loop processing, includes...
     */
     $result2 = $db->execute('SOME OTHER STATEMENT');
      while ($r2 = $result2->fetchRow())
}
````

**Comment by MariaKlik** [comment]
I already know the problem and changed the code where possible...
But I want to use ADOdb function AutoExecute.
I do not want to remove AutoExecute from my code.
I want developers to make changes.. Thank you.

**Comment by dregad** [comment]
Since there is a workaround available, I suggest you do that. If you really _want* to use AutoExecute, then by all means send us a pull request with the necessary changes to the code to fix the code.
