### ISSUE TITLE
How to use PDO driver with Session Management

### ISSUE THREAD

**Issue by KorbenDallas2** [ADOdb/ADOdb#395]
It seems only 'mysqli' driver is supported for this. 

```
include 'adodb/session/adodb-cryptsession2.php';
$driver = 'pdo'; 
$host = 'localhost';
$user = 'auser'; 
$pwd = 'secret'; 
$database = 'sessiondb';
 
ADOdb_Session::config($driver, $host, $user, $password, $database,$options=false);
session_start();
```

The above fails unless $driver = 'mysqli';

_Fatal error: session_start(): Failed to initialize storage module:_

I am using PDO connections and want to use them here as well. 
If this cannot use $driver = 'pdo' is there a way to get this to use my existing DB connection:  $conn which is using PDO?

**Comment by KorbenDallas2** [comment]
A colleague fixed this and committed a PR

[https://github.com/ADOdb/ADOdb/pull/396](url)

uses  $driver = 'pdo_mysql';

Eet verks!

**Comment by mnewnham** [comment]
@KorbenDallas2 , I reviewed this PR, some extended character set text appears to have been introduced into the file at line 582. Could you ask your colleague to review the code, and if possible re-test the changes **not** using the pdo driver. We can move forward on this once this has been done

**Comment by KorbenDallas2** [comment]
Not sure what you are asking. I have been using this code successfully
(daily) since it was created, and I am not seeing any extended character
set info in the version I have, or in the commit at:

https://github.com/ADOdb/ADOdb/pull/396/commits/9b40399825dd572524baf1802381ca334f5b4b2b

Perhaps github is doing whatever it is you are seeing?
