### ISSUE TITLE
SQL Injection vulnerability in MySQLi driver

### ISSUE THREAD

**Issue by jedi58** [ADOdb/ADOdb#400]
Repeat of #311 but for MySQLi - this likely affects other drivers also

**Comment by jedi58** [comment]
attempted to contribute by pushing a new branch to fix this, but don't have permissions to :(

**Comment by dregad** [comment]
@jedi58 
> this likely affects other drivers also

It would be greatly appreciated if you could go through and provide a patch for other drivers as well.

> attempted to contribute by pushing a new branch to fix this, but don't have permissions to :(

Please fork, and push to your own repo, then create a PR from there - see https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by jedi58** [comment]
thanks - will get this done today :)

**Comment by dregad** [comment]
Thank you
