### ISSUE TITLE
$php_errormsg deprecated in PHP 7.2

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#405]
http://php.net/manual/en/reserved.variables.phperrormsg.php

**Comment by jrfnl** [comment]
@dregad *grin* I was actually just fixing this. Expect a pull request in a little while.

**Comment by jrfnl** [comment]
@dregad Your fix in unfortunately buggy. You are using the `error_clear_last()` function, however, that function isn't available until PHP 7, so breaks compatibility with any PHP versions before that.

Please see my alternative implementation in PR #409

**Comment by dregad** [comment]
Oops thanks for the heads up, I should have taken the time to check with PHP 5.x.

**Comment by jrfnl** [comment]
@dregad As PR #409 has been merged, I think this can now be closed again ;-)

**Comment by dregad** [comment]
Indeed.
