### ISSUE TITLE
mssqlnative / insert_ID() fails if server returns more than 1 row

### ISSUE THREAD

**Issue by gitjti** [ADOdb/ADOdb#41]
okay, msssqlnative (5.19) driver's insert_id() mechanism has some issues if server returns
more than requested SELECT SCOPE_IDENTITY(). In my case, insert trigger outputs rows affected info.

Current code expects to get only one result -> error

	// retrieve the last insert ID (where applicable)
	sqlsrv_next_result($rez);
	sqlsrv_fetch($rez);
	$this->lastInsertID = sqlsrv_get_field($rez, 0);

**Comment by dregad** [comment]
Can you please submit a pull request for this ?

**Comment by gitjti** [comment]
Done.


-Jarkko
