### ISSUE TITLE
This number (99--) expression, all data has been changed

### ISSUE THREAD

**Issue by raindy29** [ADOdb/ADOdb#410]
I use Postgresql,Find this problem
UPDATE mytable  SET qty=1-- where  ikey='123456'

**Comment by joebordes** [comment]
AFAIK -- is a [single line comment](https://www.w3schools.com/sql/sql_comments.asp), so your SQL above is actually:

```
UPDATE mytable SET qty=1
```

which effectively changes all rows.

In other words, it is working correctly.

**Comment by dregad** [comment]
@joebordes is correct. You will actually experience the same behavior if you run your SQL from psql.

This is not an ADOdb issue, so I'm closing this.
