### ISSUE TITLE
cachePageExecute does not work

### ISSUE THREAD

**Issue by vd4** [ADOdb/ADOdb#413]
ADODB version v5.20.12
Database type: mssqlnative  (SQLEXPRESS)
cachePageExecute will not create any cache
Example code:

$query = "CREATE TABLE test1 (
   ENA   INT NOT NULL,
   DYO   INT NOT NULL,
   PRIMARY KEY (ENA, DYO)
   )";
if (!$db->Execute($query))
{
   echo $db->ErrorMsg();
}

$query = "TRUNCATE TABLE test1";
if (!$db->Execute($query))
{
   die( $db->ErrorMsg() );
}
$query = "INSERT INTO test1 (ENA, DYO) VALUES(?,?)";
for ($i=0;$i<25;$i++) 
{
   for ($j=0;$j<4;$j++)
   {
      $data=array($i, $j);
      if (!$db->Execute($query, $data))
      {
         die( $db->ErrorMsg() );
      }
   }   
}

$db->debug = true;
$query = "SELECT ENA, COUNT(*) FROM test1 WHERE ENA>=? GROUP BY ENA ORDER BY ENA";
$data = array(1);
$rs= $db->cachePageExecute(3600, $query, 15, 1, $data);   
if ($rs===false) 
{
   die( $db->ErrorMsg() );
}
while ($row=$rs->FetchRow()) {
   print_r($row);
}
$rs->Close();

**Comment by mnewnham** [comment]
You have confused the construction of [cachePageExecute](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:cachePageExecute) with [cacheSelectLimit](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:cacheselectlimit)

Apart from that, I have tested your code on both MySQL and SQL server databases and can confirm that they work correctly. I am assuming that you are using file caching and not memcached

**Comment by dregad** [comment]
@vd4 since you did not provide any feedback, I assume that with Mark's note you were able to solve your problem.

**Comment by vd4** [comment]
Thank you very much for your replies.
However Mark's reply does not make any sense.
I will send you detailed description of the problem, as soon as I have the
time.

Thank's again for your time.

Vassilis Dimitriadis

2018-05-03 15:42 GMT+03:00 Damien Regad <notifications@github.com>:
