### ISSUE TITLE
Why MySQL and SQL Server (mssql) give me different fields?

### ISSUE THREAD

**Issue by mickyp** [ADOdb/ADOdb#431]
Hi,

When I use query result row and get fields, the value is different from mysql and mssql connection, could someone tell me why or how to fix it?

Here is my code
```php
    $database->SetFetchMode(ADODB_FETCH_ASSOC);
    $sql = "SELECT id, CodeValue, CodeName FROM pubcode WHERE CodeKind='eWBookTP3' AND deleteChk = 0";
    $row = $database->Query($sql);
    while ($row && !$row->EOF) {
        error_log("try to print row content");
        error_log(print_r($row->fields, true););
        $dataArr[] = $row->fields;
        $row->MoveNext();
    }
```

When my database is MySQL, the print content is 
```
[25-Jun-2018 00:19:21 Asia/Taipei] Array
(
    [0] => 782
    [1] => 3
    [2] => 13－15岁
)
```

When my database is SQL Server (mssql), the print content is 
```
[25-Jun-2018 00:18:07 Asia/Taipei] Array
(
    [0] => 782
    [id] => 782
    [1] => 3
    [CodeValue] => 3
    [2] => 13－15岁
    [CodeName] => 13－15岁
)

```

What the big different I got...
I can't get the fields name  when I use MySQL database which I use mysqli as connection type.

Currently, I am working on transfer my project from MS SQL Server to MySQL database, so I need to figure out why this happened since I never expected.

Please help me, thank you all in advance.

**Comment by atrol** [comment]
Have a look at the doc of [$ADODB_FETCH_MODE](http://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_fetch_mode) especially the hint for `ADODB_FETCH_DEFAULT`
> Use of this value is not recommended if writing cross-database applications

**Comment by mickyp** [comment]
Hi, I didn't write cross-database application. I just need to transfer database from one to another and encounter this problem.

My old sql server database use features `$dataArr[] = $row->fields;` to compose $dsataArr and will use it like $dataArr[CodeValue] to retrieve its content.

But the new MySQL database use same code `$dataArr[] = $row->fields;`, instead return the correct value, it  return $dataArr[CodeValue] as null or empty....

**Comment by mickyp** [comment]
I print_r the $row object, it shows mysql content
```
ADORecordSet_mysqli Object
(
    [databaseType] => mysqli
    [dataProvider] => native
    [fields] => Array
        (
            [0] => 780
            [1] => 1
            [2] => 6岁以下
        )

    [fetchMode] => 2
...
  
    [_numOfRows] => 4
    [_numOfFields] => 3
    [_queryID] => mysqli_result Object
        (
            [current_field] => 0
            [field_count] => 3
            [num_rows] => 4
        )
...
    [adodbFetchMode] => 1
)
```

I noticed that the object has two different fetch mode, one is fetchMode (2), the other is adodbFetchMode(1), why different?

and here is my sql server version $row content
```
ADORecordSet_array_mssqlnative Object
(
    [_array] => Array
        (
            [0] => Array
                (
                    [0] => 780
                    [id] => 780
                    [1] => 1
                    [CodeValue] => 1
                    [2] => 6岁以下
                    [CodeName] => 6岁以下
                )
...
        )

    [_fieldobjects] => Array
        (
            [0] => ADOFieldObject Object
                (
                    [name] => id
                    [max_length] => 
                    [type] => 4
                )

            [1] => ADOFieldObject Object
                (
                    [name] => CodeValue
                    [max_length] => 100
                    [type] => 12
                )

            [2] => ADOFieldObject Object
                (
                    [name] => CodeName
                    [max_length] => 600
                    [type] => -9
                )

        )

    [fetchMode] => 1
    [connection] => ADODB_mssqlnative Object
        (
            ...
            [fetchMode] => 1
            ...
        )
...
)
```

In Sql Server database version, the fetchModes are the same as 1.

Hope any one can tell me how to fix it? how should I use adodb correctly?

**Comment by atrol** [comment]
I am no ADOdb specialist and have no time to have a deeper look at it.
This might be a regression introduced by https://github.com/ADOdb/ADOdb/commit/2b1d3e66532e6ef6a07d65ac8d3533185f7fe00b

A workaround could be to set
`$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC; `
instead of
`
$database->SetFetchMode(ADODB_FETCH_ASSOC);
`

**Comment by mickyp** [comment]
Thanks for your help.

I already set $ADODB_FETCH_MODE directly, but seems it's not working in my case, so sad.

My ADODB version is since 2012, I try to upgrade to currently version, but very warnings/errors show up in web page.

So I just turn back and stay in 2012 year version..., try to see source code to figure out where is the problem codes.

**Comment by dregad** [comment]
@mickyp I am not able to reproduce the problem in ADOdb 5.20.x or later. Setting fetch mode either via global `$ADODB_FETCH_MODE` or on the connection with setFetchMode() method effectively sets it as expected.

> My ADODB version is since 2012

We only support 5.20.0 or later. 

> I try to upgrade to currently version, but very warnings/errors show up in web page.

Feel free to reopen the issue if you are able to reproduce the problem in a more recent version of ADOdb.
