### ISSUE TITLE
 Undefined variable: ok in adodb in adodb-pdo.inc.php

### ISSUE THREAD

**Issue by reportico-web** [ADOdb/ADOdb#437]
$ok needs defining at start of function to prevent test on this variable if isnt set when the prepare statement on line 479 fails.

**Comment by mnewnham** [comment]
Which version of ADOdb are you using?

**Comment by reportico-web** [comment]
Hi, thanks for the swift reply..

My composer entry is

        "adodb/adodb-php": "^5.20",

And im currently running with 5.20.12

**Comment by mnewnham** [comment]
While it is true that this is an undeclared variable, and I'll put a fix in, It only occurs when there is a problem with the code that you are trying to execute, i.e., you are passing an empty SQL statement, or are passing in a prepared SQL call that is is failing. Were you aware of this?

**Comment by reportico-web** [comment]
Hi thanks very much ..as well as executing an sql i am actually using this function to also test the validity of an sql that a user has entered..im not sure if there is a better function to use but this works fine for me. The error has only started happening in certain platforms where perhaps the php is stricter..but the fix will help immensely

**Comment by mnewnham** [comment]
Would you be interested in explaining what you are doing with that? perhaps a code snippet?

**Comment by mnewnham** [comment]
To get the latest version of the file, before we do a hotfix, grab it from patch above. If you would like to continue the conversation, feel free to reopen the thread.

**Comment by reportico-web** [comment]
Thank you very much for the fix .. im sorry, i went on holiday for ten days and didnt do any work so apologies for responding ..

If i want to actually allow people to download my project with composer which depends on adodb ( ^5.20 ) should i wait until you create  5.20.13 or would you recommend fork off the fix and make my project depend on that?

**Comment by dregad** [comment]
@reportico-web I will cut 5.20.13 in the next few days (as time allows). If you can wait it will probably be less of a hassle for you.

**Comment by reportico-web** [comment]
Thank you so much, i can wait !
