### ISSUE TITLE
Error message on logging slow queries with mysqli driver

### ISSUE THREAD

**Issue by oburk** [ADOdb/ADOdb#439]
Hi,

I switched our application from mysql to mysqli driver for running it on PHP 7. Now I got an error messages each time when the application tries to write a slow query into table adodb_logsql . 

Error message:
```
LOGSQL Insert Failed: insert into adodb_logsql (created,sql0,sql1,params,tracer,timer) values( NOW(),?,?,?,?,?)
Commands out of sync; you can't run this command now

``` 

First try to solve this problem was to set global variable $ ADODB_COUNTRECS = true. This covers many occurrences,  but for several functions (SelectLimit, GetOne, GetArray, CacheGetArray and GetRow) this will not work, because in this functions the variable was overwritten.  

Code in adodb.inc.php:
```
function GetOne($sql,$inputarr=false) {
		global $ADODB_COUNTRECS,$ADODB_GETONE_EOF;

		$crecs = $ADODB_COUNTRECS;
		$ADODB_COUNTRECS = false;

		$ret = false;
		$rs = $this->Execute($sql,$inputarr);

```

**Enviroment**
PHP: 7.1.14
MariaDB: 10.1.33
Adodb:	5.20.12

Is there a solution to write slow queries by using mysqli driver?

**Comment by mnewnham** [comment]
Please review this closed issue #388 about the "command out of sync" error.

It seems clear that the logging system is doing exactly what is described in the first explanation in the linked issue.

1. You are executing an SQL statement and preparing a result set
2. Before you retrieve any records, the logging system is issuing a second command before you start retrieving records on the first result.
3. mysqli is telling you that you can't do that.
 
I'm not sure what we can offer as a response, as this appears to be a well known, [PHP and MySQL](https://www.google.com/search?q=mysqli+commands+out+of+sync&oq=mysqli+comm&aqs=chrome.3.0j69i57j0l4.5183j0j7&sourceid=chrome&ie=UTF-8) issue, not just ADOdb

**Comment by oburk** [comment]
Problematic for me is that mysqli driver in Adodb is using variable $ADODB_COUNTRECS to set if mysqli_query should store or use the result. In my eyes that are different things which should be handle by two separate variables:

```
	function _query($sql, $inputarr)
	{
	global $ADODB_COUNTRECS;

	…

		} else {
			$rs = mysqli_query($this->_connectionID, $sql, $ADODB_COUNTRECS ? MYSQLI_STORE_RESULT : MYSQLI_USE_RESULT);

			if ($rs) return $rs;
		}
	…
```

**Comment by oburk** [comment]
In driver "adodb-mysqli.inc.php" the bug was fixed for function "GetOne" and "SelectLimit". I fixed the problem by overwriting the _query function:

<pre>
    function _query($sql, $inputarr)
    {
        global $ADODB_COUNTRECS;

        $savec = $ADODB_COUNTRECS;
        $ADODB_COUNTRECS = true;
        $res = parent::_query($sql, $inputarr);
        $ADODB_COUNTRECS = $savec;
        return $res;
    }
</pre>

When you run a search on Google with the error message from comment #1 you will found several websites which have the same problem. I am not alone :)

**Comment by dregad** [comment]
Duplicate of #463
