### ISSUE TITLE
What to do about MS Access in PHP in Unix?

### ISSUE THREAD

**Issue by EnnexMB** [ADOdb/ADOdb#440]
I need to pull data from MS Access 2007 (both mdb and accdb files) for a website written in PHP 7. The pages don't need to be dynamic or interactive. They just need to present data stored in the database.

Local development environment: Windows 7, IIS 7.5
Online server: A2 Hosting, Linux (CloudLinux Server release 6.9), Apache/2.2.34

The [ADOdb webpage for Access](http://adodb.org/dokuwiki/doku.php?id=v5:database:access) says "Windows Yes, Unix No". I presume this means I can use ADOdb to connect to Access in my local environment, but not on the online server. I suppose I have the following options:

- StackOverflow has some questions on this ([1](https://stackoverflow.com/questions/19807081/how-to-connect-php-with-microsoft-access-database), [2](https://stackoverflow.com/questions/2222684/connecting-to-ms-access-2007-using-odbc-connect-error-in-driver), [3](https://stackoverflow.com/questions/48339856/warning-odbc-connect-sql-error-microsoftodbc-driver-manager-data-source)) with answers that give code for connecting to Access in PHP. Although the answers don't say so, I am guessing that that code will only work in Windows because if it were that easy to connect to Access in PHP in Unix, then ADOdb would do it! So if I'm right about this, then this is not a workable option.
- The PHP Manual has a page on [Database issues](http://php.net/manual/en/faq.databases.php) that says PHP can access Access, but it seems to only apply to either running in Windows or "running PHP on a Unix box and want to talk to MS Access on a Windows box". So this also does not appear to offer a workable solution for running the website online on a Linux server.
- Extract the parts of the database needed into something else that can be accessed in Unix, such as CSV files, and use that as the database for the website. If I do this with CSV, I suppose I don't need ADOdb, but would just use [fgetcsv()](http://php.net/manual/en/function.fgetcsv.php). This is an inelegant solution, but may be the best thing to do if there's not a way to access Access directly in Unix. (I could use MySQL instead of CSV, but that seems like a lot of unnecessary overhead.)
- Run the pages on my Windows machine using ADOdb to access Access. Save the parts of the pages that come from the database as separate HTML segment files and [include()](http://php.net/manual/en/function.include.php) them when the pages run online. (The script could detect which environment it's running in and if it's local, then access the database, and if online, then include() the HTML segment files.)
- Move the online website from Linux to a Windows server, so PHP can access Access directly using ADOdb.
- Convert the entire database from Access to something else, such as MySQL. This is not practical at this time, although that may be an option in the future.

Have I understood my options correctly? I've listed them in what seems to me to be the order of preference, so unless someone suggests otherwise, I guess I'll go with the third one (extract to CSV, use fgetcsv(), no ADOdb) since the first two won't work.

Thanks for your help.

**Comment by dregad** [comment]
I think your list is exhaustive. You can't use Access' native ODBC driver on Unix, so you'd need to use an alternate driver (e.g. https://github.com/brianb/mdbtools/blob/master/README#L29) but I've never tried this myself so don't ask about the details :wink: 

I would definitely skip the CSV and HTML generation options, sounds like crap architecture and a support/maintenance nightmare. Just my 2 cents.

**Comment by mnewnham** [comment]
If you could, maybe a migration to an SQLite database? the setup and footprint of this is much simpler than MySQL and it seems that it would be a more appropriate solution to your requirements.

**Comment by dregad** [comment]
@EnnexMB Since you have provided any feedback, I assume that you are happy with the above answers, and will close this issue. Feel free to reopen if needed.
