### ISSUE TITLE
class_exists generates error when using autoload or spl_autoload_register

### ISSUE THREAD

**Issue by blackscorpionster** [ADOdb/ADOdb#446]
adodb.inc.php line 1316:
"class_exists" attemps to initialize the class 'ADORecordSet_assoc_empty' which does not exists.
By adding false as a second argument, the class will only be checked and no error will be triggered when using autoload or spl_autoload_register.

Suggestion1: $rs = (class_exists($rsclass, false)) ? new $rsclass():  new ADORecordSet_empty();
Suggestion2:  $rs = new ADORecordSet_empty(); // I like this one better as "ADORecordSet_assoc_empty" does not exists anyehre

**Comment by mnewnham** [comment]
As you have not responded, I assume you have identified the issue. If you need further help feel free to reopen this issue.
