### ISSUE TITLE
adodb-session2 : session_module_name('user') throws an error for PHP 7.2

### ISSUE THREAD

**Issue by UrvishSSPL** [ADOdb/ADOdb#449]
The `session_module_name('user')` code on line 467 in the `session/adodb-session2` file throws below error for PHP 7.2 on windows platform (not sure about linux):

```php
session_module_name(): Cannot set 'user' save handler by ini_set() or session_module_name() 
```

The same code works in PHP 5.6 on both the Windows and Linux platform.

**Comment by dregad** [comment]
A quick Google search shows quite a few occurences of this error. 

It would appear that calling session_module_name() is not necessary, as it is automatically set to `user` by session_set_save_handler().

@UrvishSSPL Would you be able to test and confirm that removing line 467 fixes the problem in PHP 7.2,, and does not introduce a regression on older PHP versions ? Thanks in advance

**Comment by UrvishSSPL** [comment]
Sure, I'll check.

**Comment by dregad** [comment]
For the record: same issue reported by another user https://gitter.im/ADOdb/ADOdb?at=5b7ec9501d3a5711b689a596

**Comment by dregad** [comment]
@UrvishSSPL did you get a chance to test to confirm that removing the line fixes the problem ?

**Comment by cachius** [comment]
There is a test for this in the PHP source that seems related.

https://github.com/php/php-src/blob/d679f02295ea079338f029b7f5f4cb65b37f190c/ext/session/tests/bug73100.phpt

**Comment by mattsimpson** [comment]
I have just submitted a PR to remove the `session_module_name()` reference.
