### ISSUE TITLE
adodb-mysqli.inc.php function ErrorMsg() and ErrorNo() not properly enclosed

### ISSUE THREAD

**Issue by shoulders** [ADOdb/ADOdb#450]
I am not a professional programmer but while trying to get $db->ErrorMsg() to work I used xdebug to follow the process. When the 'pointer' gets to reading 'function ErrorMsg()' in adodb-mysqli.inc.php it skips straight to the return statement basically ignoring the empty() test. It should also be noted that when I run 'function ErrorNo()' that the pointer actually jumps back to 'function ErrorMsg()'.

I believe this is caused by the 2 functions not being enclosed with curley braces. The other option is that the statements should be on the same line as the 'if'/'else' commands.

I am running v5.20.9 but this is also present in the Master.

**Suspect Functions**
````
	/*	Returns: the last error message from previous database operation	*/
	function ErrorMsg()
	{
		if (empty($this->_connectionID))
			$this->_errorMsg = @mysqli_connect_error();
		else
			$this->_errorMsg = @mysqli_error($this->_connectionID);
		return $this->_errorMsg;
	}
	/*	Returns: the last error number from previous database operation	*/
	function ErrorNo()
	{
		if (empty($this->_connectionID))
			return @mysqli_connect_errno();
		else
			return @mysqli_errno($this->_connectionID);
	}
````
Solution 1 - same line
````
	/*	Returns: the last error message from previous database operation	*/
	function ErrorMsg()
	{
		if (empty($this->_connectionID)) $this->_errorMsg = @mysqli_connect_error();
		else $this->_errorMsg = @mysqli_error($this->_connectionID);
		return $this->_errorMsg;
	}

	/*	Returns: the last error number from previous database operation	*/
	function ErrorNo()
	{
		if (empty($this->_connectionID)) return @mysqli_connect_errno();
		else return @mysqli_errno($this->_connectionID);
	}
````
Solution 2 - Enclosed with curley braces
````
	/*	Returns: the last error message from previous database operation	*/
	function ErrorMsg()
	{
		if (empty($this->_connectionID)) {
			$this->_errorMsg = @mysqli_connect_error();
                } else {
			$this->_errorMsg = @mysqli_error($this->_connectionID);
                }
		return $this->_errorMsg;
	}

	/*	Returns: the last error number from previous database operation	*/
	function ErrorNo()
	{
		if (empty($this->_connectionID)) {
			return @mysqli_connect_errno();
                } else {
			return @mysqli_errno($this->_connectionID);
	}
````

**Comment by dregad** [comment]
That does not make any sense, PHP ignores whitespace, so 
``` php
if ($cond) blah();
``` 
is semantically identical as 
``` php
if ($cond) 
    blah();
```
Adding curly braces just creates a statement group containing a single statement, which is also identical.

There is nothing wrong with this code. I suspect the "problem" is with whatever debugger you're using.

**Comment by shoulders** [comment]
i can send you a video of xdebug (in netbeans/xampp)  going funny with it, if this would be of any use.?

It might be an xdebug thing but I only discovered this because the $db->errormsg()  is not working for me, possibly because i am using it within a class context. (i will play with this more before logging an issue)
