### ISSUE TITLE
convert all Tabs to spaces (psr-0 psr-1)

### ISSUE THREAD

**Issue by shoulders** [ADOdb/ADOdb#451]
Hi

I would like to see all of the tabs replaced by 4 spaces. This is the prefered method for a lot of programmers now.

Perhaps also parse the rest fo the code to match psr-0 and psr-1 layout. I am going to use the symphony code rules.

Thanks

**Comment by dregad** [comment]
It will happen eventually.
Closing as duplicate, since this is covered by #193.
