### ISSUE TITLE
No method to check if load() found the record.

### ISSUE THREAD

**Issue by llagerlof** [ADOdb/ADOdb#453]
Doesn't exist any method to check if load() found the record or not.

Eg: 
```lang=php
    $ActiveRecord->load("id = ?", array(123));
```

The only way I found is testing if some not null unique field is null or not. Don't should exist a method like found(), exists(), empty() or something like that?

**Comment by mnewnham** [comment]
From [the documentation](http://adodb.org/dokuwiki/doku.php?id=v5:activerecord:load), load()  returns false if no records are found
````php
$found = $ActiveRecord->load("id = ?", array(123));
if (!$found)
    do something......
````

**Comment by llagerlof** [comment]
Oops, I did read in the same documentation that this method returns false if an error occurs. I really should have continued the reading. Thanks.
