### ISSUE TITLE
ClassBelongsTo() only work with inverted parameters and the table name as second parameter.

### ISSUE THREAD

**Issue by llagerlof** [ADOdb/ADOdb#455]
I have two classes, a parent and a child class, on for each table. I want to load the child record (I already do it) and have access to the parent record automatically using the method ClassBelongsTo(). 

My tables:
```
parenttable
  id
  description

childtable
  id
  somefield
  id_parent
```

Just for the sake of completion, this is my 2 models:

```lang=php
class ParentModel extends ADOdb_Active_Record
{
    var $_table = 'parenttable';
}

class ChildModel extends ADOdb_Active_Record
{
    var $_table = 'childtable';
}
```

Looks like the method ClassBelongsTo() has inconsistent parameters. The docs show me this:

```
void ADODB_Active_Record::classBelongsTo(
   string $parentClass, 
   string $childClass, 
   string $foreignKey, 
   optional string $parentPrimaryKey = 'id', 
   optional string $parentClass = 'ADODB_Active_Record'
   )
```

But when I try to use this setting:
```lang=php
// DON'T WORK
ADODB_Active_Record::$_changeNames = false; // my table names are in singular form
ADODB_Active_Record::ClassBelongsTo('ParentModel','ChildModel','id_parent','id','ParentModel');
```

I receive this error:
```
Warning: mysqlt error: [1146: Table 'database.ChildModel' doesn't exist] in EXECUTE("SHOW COLUMNS FROM `ChildModel`") in /adodb5/adodb-errorhandler.inc.php on line 77
```
This implies he is trying to load some metadata from ChildModel table, however this is the class name, not the table name.

I tried to change the second parameter to the table name and the error is gone, but the parent data is not in $ChildModel instance:

```lang=php
// DIDN'T WORK
ADODB_Active_Record::$_changeNames = false;
ADODB_Active_Record::ClassBelongsTo('ParentModel','childtable','id_parent','id','ParentModel');
$ChildModel = new ChildModel();
$ChildModel->load('id = ?', 1);
```

But if I invert the first two parameters and keep the second one with the table name, it works! The child record is loaded correctly and the parent record exist in 'parenttable' property:

```lang=php
// IT WORKED!
ADODB_Active_Record::$_changeNames = false;
ADODB_Active_Record::ClassBelongsTo('ChildModel','parenttable','id_parent','id','ParentModel');
$ChildModel = new ChildModel();
$ChildModel->load('id = ?', 1);
```

This is very strange because I have my both classes declared and working, and I was using them until now, but creating this relationship using both classes as parameters (and not a class and a table) is proving to be a tough process.

**Comment by mnewnham** [comment]
Unfortunately, this appears to be an error in the documentation. Whilst the definition in the documentation shows parent class, child class, the example below it shows child class, parent class.

The documentation has been updated to show the correct format.
