### ISSUE TITLE
PHP Warning: pg_fetch_array() on MoveNext method when $ADODB_COUNTRECS is false

### ISSUE THREAD

**Issue by WiXSL** [ADOdb/ADOdb#456]
Using:
PostrgreSql v9.6.
PHP v7.0.24.
ADODB master branch (but i think is the same in v5.20.13).

Using a function like the one below i get a PHP Warning trying to access the last  row of the RecordSet every single time.

```
function testMoveNextBug($myOdbc, $myUsr, $myPass, $myDatabase) {
    global $ADODB_COUNTRECS;
    $temp = $ADODB_COUNTRECS;

    // Tested with 'postgres' and 'mssqlnative'
    $Conn = ADONewConnection('postgres'); # Create a connection
    $res = $Conn->Connect($myOdbc, $myUsr, $myPass, $myDatabase);
    
    $sql = 'SELECT * FROM mytable';

    $ADODB_COUNTRECS = false; // Setting $ADODB_COUNTRECS
    $rs = $Conn->Execute($sql);
    $ADODB_COUNTRECS = $temp; // Reestablishing $ADODB_COUNTRECS

    if ($rs) {
        while (!$rs->EOF) {
            // PHP Warning: pg_fetch_array(): Unable to jump to row X on PostgreSQL result index 154104792 in ../adodb/drivers/adodb-postgres7.inc.php on line 359
            $rs->MoveNext();
        }
    }

    return $rs;
}
```

**Comment by mnewnham** [comment]
You should use [postgres9](adodb.org/dokuwiki/doku.php?id=v5:database:postgresql) as your ADOdb connector. I used your code and had no problems with it

**Comment by dregad** [comment]
@WiXSL I am also not able to trigger the warning using the given code snippet (tried with both master and 5.20.13), so I'll close this issue for now. Feel free to reopen with additional information to help us understand / reproduce the problem.

> You should use postgres9 as your ADOdb connector

@mnewnham considering we currently default _postgres_ driver to `postgres8`, we should probably change this to `postgres9` in master branch, what do you think ?

**Comment by mnewnham** [comment]
@dregad , totally agree
