### ISSUE TITLE
E_NOTICE in getMenu() with more than 2 columns and ADODB_FETCH_ASSOC

### ISSUE THREAD

**Issue by hschletz** [ADOdb/ADOdb#460]
https://github.com/ADOdb/ADOdb/blob/a51a426b6344fd26d4a1f7bc2d2671ed13231014/adodb-lib.inc.php#L268

produces E_NOTICE: "Undefined index: 2" if the recordset contains more than 2 columns and ADODB_FETCH_ASSOC is in effect.

The evaluated variable is never used (the following lines that used it are commented out), so the code could simply be removed unless it is intended to be reactivated.

**Comment by mnewnham** [comment]
There is a small note In the code of getMenu() that the method is only supported with a fetch mode of ADODB_FETCH_NUM. This needs cleaning up
