### ISSUE TITLE
Help Please, how to limit of record number (Find Method)

### ISSUE THREAD

**Issue by enzolepe** [ADOdb/ADOdb#461]
hi, i need know how limit of record number (Find method), only need last 100 record of my table, now gets more than 10000 record, it's too much
thank for your response
best regards
Enzo

**Comment by mnewnham** [comment]
The method is defined as 
````
function Find($whereOrderBy,$bindarr=false,$pkeysArr=false,$extra=array());
````
The paramter $extra may contain the paramters **offset**and **limit**. For more on this, see [selectLimit
](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:selectlimit).

Please note that the Active Record method **Find** is currently undocumented at adodb.org.
