### ISSUE TITLE
Waring: Declaration of perf_mysql::Tables() should be compatible with adodb_perf::Tables

### ISSUE THREAD

**Issue by ivanbogomoloff** [ADOdb/ADOdb#462]
I get release from here https://github.com/ADOdb/ADOdb/releases/tag/v5.20.12 
And here https://github.com/ADOdb/ADOdb/blob/hotfix/5.20/perf/perf-mysql.inc.php.

Declaration of perf_mysql::Tables() should be compatible with adodb_perf::Tables($orderby = '1')
adodb/perf/perf-mysql.inc.php
must be
```php
function Tables($orderby='1')
{
}
```

**Comment by mnewnham** [comment]
The master had already been updated

**Comment by dregad** [comment]
Duplicate of #435
