### ISSUE TITLE
LOGSQL Insert Failed: insert into adodb_logsql Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by ivanbogomoloff** [ADOdb/ADOdb#463]
Here https://github.com/ADOdb/ADOdb/blob/hotfix/5.20/adodb-perf.inc.php#L169
I get error if my driver is ADODB_mysqli
```
LOGSQL Insert Failed: insert into adodb_logsql (created,sql0,sql1,params,tracer,timer) values( NOW(),?,?,?,?,?)
Commands out of sync; you can't run this command now
```
Error fixed after add this code
```php
if ($errN != 0 || $time >= $ADODB_PERF_MIN) {
			//
			if($conn instanceof ADODB_mysqli && $conn->_queryID){
				mysqli_free_result($conn->_queryID);
            }
			$ok = $conn->Execute($isql,$arr);
		} else
			$ok = true;
```

**Comment by aga112b** [comment]
Hi,
Unfortunately solution added by ivanbogomoloff causes that there is displayed warning: 
`Warning: mysqli_free_result(): Couldn't fetch mysqli_result`  
when the function ADORecordSet_mysqli->_close( ) is run.
I don't know why in function `_close`, `$this->_queryID` is instance of mysqli_result but couldn't be fetched. I found out that warning occurs when mysqli_result is empty (when I cast it to array and var_dump it looks:
```
array (size=5)
  'current_field' => null
  'field_count' => null
  'lengths' => null
  'num_rows' => null
  'type' => null
```
I've tried to find solution how to change mentioned code to not caused warnings but still resolve problem with displaying error 
```
'LOGSQL Insert Failed: insert into adodb_logsql (created,sql0,sql1,params,tracer,timer) values( NOW(),?,?,?,?,?)
Commands out of sync; you can't run this command now'.
```

I found out that if in adodb-mysqli.inc.php in function `_close` we use 
`if($this->_queryID instanceof mysqli_result && (!empty(implode('',(array)$this->_queryID)))) {`
instead
`if($this->_queryID instanceof mysqli_result) {`
then warning will not be displayed.
