### ISSUE TITLE
Denial of service in adodb-time.inc.php adodb_date()

### ISSUE THREAD

**Issue by Mike-Benoit** [ADOdb/ADOdb#467]
Calling $db->BindTimeStamp( 9999999999999999 ) or adodb_getdate( 9999999999999999 ); will take days to finish. Therefore passing a value such as that to many applications that use ADODB will bring the server to its knees almost instantly.

The ADODB time documentation does mention:
> The maximum is billions of years in the future, but this is a theoretical limit as the computation of that year would take too long with the current implementation of adodb_mktime().

I think it might be a good idea to put some kind of maximum limit (as a variable perhaps?) to prevent possible DoS situations. I would imagine the percent of users that need more than 100 years in the future is quite low.

There are some undefined variable notices that appear in PHP as well, so I'm not even sure the handling of billions of years into the future is even correct.

**Comment by mnewnham** [comment]
Adding a constraint for future (and possibly past) years seems a good idea. I've updated the time functions to control the maximum allowed date using a new constant [ADODB_FUTURE_DATE_CUTOFF_YEARS](http://adodb.org/dokuwiki/doku.php?id=v5:datetime:adodb_last_date_status)
