### ISSUE TITLE
adodb.org SSL cert invalid

### ISSUE THREAD

**Issue by PikMaster** [ADOdb/ADOdb#468]
Hi. When you try to use SSL connection to https://adodb.org the name in the SSL certificate does not match

The certificate verification failed due to a common name mismatch. 

Host: adodb.org
Common name: *.preview.infomaniak.website
Alternative subject names: *.preview.infomaniak.website, preview.infomaniak.website
Valid from July 27, 2017 to July 27, 2020
Serial Number: b297368508cd56b5592fe2c96a545722
Signature Algorithm: sha256WithRSAEncryption
Issuer: COMODO RSA Domain Validation Secure Server CA

See:
https://www.sslshopper.com/ssl-checker.html#hostname=adodb.org

**Comment by dregad** [comment]
Thanks for letting me know. I never actually setup SSL on that site, I'm surprised it's even responding on 443. The hosting provider must have changed something.

I'll look into it.

**Comment by dregad** [comment]
There is a DNS issue with www.adodb.org alias, that needs to be resolved before SSL can be setup.

**Comment by dregad** [comment]
SSL certificate has been deployed.
