### ISSUE TITLE
PDO driver: add support for $options array in PDO contructor

### ISSUE THREAD

**Issue by f7h** [ADOdb/ADOdb#476]
Some driver specific connection options like MYSQL_ATTR_FOUND_ROWS can only be set in PDO::__construct and not later via PDO::setAttribute().

We need the ability to pass an options array to ADOConnection::Connect which is used in ADODB_pdo::_connect as follows `new PDO($argDSN, $argUsername, $argPassword, $options)`.

**Comment by mnewnham** [comment]
Per the [Documentation](http://adodb.org/dokuwiki/doku.php?id=v5:database:pdo), the [setConnectionParameter](http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter) option is supported under PDO from version 5.21. Whilst the is currently no release,  you can simply drop in the code from a zip file of the master branch

**Comment by tkhamez** [comment]
I didn't see ADOConnection::setConnectionParameter, but it uses PDO::setAttribute.

As I said, there are options that cannot be changed.

Example:

This works:
```
new PDO($argDSN, $argUsername, $argPassword, [\PDO::MYSQL_ATTR_FOUND_ROWS => true]) 
```

This doesn't work:
```
$pdo = new PDO($argDSN, $argUsername, $argPassword);
$pdo->setAttribute(\PDO::MYSQL_ATTR_FOUND_ROWS, true);
```

I tested this with PHP 5.6 and 7.2.

The latter even shows a warning with PHP 7.2, MySQL 5.7: `Warning: PDO::getAttribute(): SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute in ...`

**Comment by f7h** [comment]
I didn't see ADOConnection::setConnectionParameter, but it uses PDO::setAttribute.

As I said, there are options that cannot be changed.

Example:

This works:
```
new PDO($argDSN, $argUsername, $argPassword, [\PDO::MYSQL_ATTR_FOUND_ROWS => true]) 
```

This doesn't work:
```
$pdo = new PDO($argDSN, $argUsername, $argPassword);
$pdo->setAttribute(\PDO::MYSQL_ATTR_FOUND_ROWS, true);
```

I tested this with PHP 5.6 and 7.2.

The latter even shows a warning with PHP 7.2, MySQL 5.7: `Warning: PDO::getAttribute(): SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute in ...`

**Comment by mnewnham** [comment]
MYSQL_ATTR_FOUND_ROWS is a MySQL option, not a PDO option, and as such needs to be passed as a database connection. This [StackOverflow](https://stackoverflow.com/questions/18683471/pdo-setting-pdomysql-attr-found-rows-fails) thread explains how to do this

**Comment by mnewnham** [comment]
It's true, you cannot pass these parameters to the PDO driver, but looking at the _connect() method in ''adodb-pdo.inc.php" , you could maybe look to see if $argDatabasename was an array, unpack it, then pass it to the new PDO class as an additional argument.

This would be a useful contribution to the project

**Comment by f7h** [comment]
Okay, I implemented your suggestion and created a PR.

Tell me what you think or if you want something to be changed.

**Comment by mnewnham** [comment]
I'll check this out in the next day or two

**Comment by f7h** [comment]
Another use case is PDO::MYSQL_ATTR_SSL_CA for encrypted connections.
