### ISSUE TITLE
mssqlnative: BLOB NOT NULL and DEFAULT support

### ISSUE THREAD

**Issue by obmsch** [ADOdb/ADOdb#478]
@mnewnham. Any reason why support for mssqlnative is missing on the "blob-not-null" branch?
I'd say:
	public $blobAllowsDefaultValue = true;
	public $blobAllowsNotNull = true;
for datadict-mssqlnative.inc.php.
I'am not able to check for SQLServer <2012 , but I guess you would not merge into 5.20 anyway.
And for 5.21 I would drop support for <=2012 entirely. I know versions of 2008/2012 are stiil on
extended support. And if necessary, a fix could be provided on the hotfix/5.20 branch.

**Comment by mnewnham** [comment]
@obmsch ,Simply a lack of time on my part. This would, however be a simple contribution for you to add and test.

**Comment by obmsch** [comment]
@mnewnham. Fair point. And while I'm at it, shouldn't the blob checks
in adodb-datadict.inc.php have "|| $ty == 'XL'" too?

**Comment by obmsch** [comment]
pr #480

Tested with SQLServer 2016 and an install of MantisBT 2.19.0 with a patched version of ADOdb.
Additionally created a table with all variants (b,x,x2,xl) x (null,notnull,null_default,notnull_default)
and verified that an INSERT with non default cols only, set all others to the defaults.

Can't check other versions of SQLServer, but AFAIK blobs haven't changed for a while (<=2005?).

Mapping 'X', 'X2', 'XL' -> 'TEXT', and 'B' -> 'IMAGE' BTW is deprecated for a while (not dropped in
v2017), and should be replaced by their varchar(max)/varbinary(max) variants.
But that's another story.

**Comment by mnewnham** [comment]
Question of semantics on the XL , given that it represents a CLOB rather than a BLOB. Should we differentiate, as in clobNotNull , or whether we use 'blob' as a generic identifier for these types of fields.
