### ISSUE TITLE
Segfault using mssql native

### ISSUE THREAD

**Issue by federicoemartinez** [ADOdb/ADOdb#481]
We found that a particular query like this one:

SELECT col "0" from table where col2 = value 
(in our case the query returned only one row)

generates a crash in php.

We are using the fetchmode = ADODB_FETCH_BOTH, PHP 7.2 (ts and nts) x86, the drivers are 5.3
This happened in 5.20.12 and 5.20.14

` Trace:

    0.2026    9386240             -> ADODB_mssqlnative->_Execute() PATH_TO_PROJECT\adodb\adodb.inc.php:1246

    0.2027    9386240               -> ADODB_str_replace() PATH_TO_PROJECT\adodb\adodb.inc.php:1258

    0.2027    9386240                 -> str_replace() PATH_TO_PROJECT\adodb\adodb.inc.php:183

    0.2027    9386240               -> ADODB_mssqlnative->_query() PATH_TO_PROJECT\adodb\adodb.inc.php:1268

    0.2027    9386240                 -> preg_match() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:572

    0.2027    9386240                 -> sqlsrv_query() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:579

    0.2031    9386664               -> ADORecordset_mssqlnative->__construct() PATH_TO_PROJECT\adodb\adodb.inc.php:1297

    0.2031    9386664                 -> ADORecordset_mssqlnative->__construct() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:855

    0.2031    9386664               -> ADORecordset_mssqlnative->Init() PATH_TO_PROJECT\adodb\adodb.inc.php:1299

    0.2031    9386664                 -> ADORecordset_mssqlnative->_initrs() PATH_TO_PROJECT\adodb\adodb.inc.php:3377

    0.2032    9386664                   -> sqlsrv_field_metadata() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:867

    0.2032    9388336                   -> ADORecordset_mssqlnative->_FetchField() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:876

    0.2032    9388336                     -> sqlsrv_field_metadata() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:945

    0.2032    9388792                     -> array_change_key_case() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:956

    0.2033    9388200                 -> ADORecordset_mssqlnative->_fetch() PATH_TO_PROJECT\adodb\adodb.inc.php:3384

    0.2033    9388200                   -> sqlsrv_fetch_array() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:1028

    0.2033    9388720                   -> array_key_exists() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:1049

    0.2033    9388744               -> ADODB_mssqlnative->_rs2rs() PATH_TO_PROJECT\adodb\adodb.inc.php:1309

    0.2034    9388744                 -> ADORecordset_mssqlnative->FieldCount() PATH_TO_PROJECT\adodb\adodb.inc.php:1621

    0.2034    9388744                 -> ADORecordset_mssqlnative->FetchField() PATH_TO_PROJECT\adodb\adodb.inc.php:1622

    0.2034    9389016                 -> ADORecordset_mssqlnative->GetArrayLimit() PATH_TO_PROJECT\adodb\adodb.inc.php:1625

    0.2034    9389016                   -> ADORecordset_mssqlnative->GetArray() PATH_TO_PROJECT\adodb\adodb.inc.php:3498

    0.2034    9389288                     -> ADORecordset_mssqlnative->MoveNext() PATH_TO_PROJECT\adodb\adodb.inc.php:3468

    0.2034    9389288                       -> ADORecordset_mssqlnative->_fetch() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:1012

    0.2034    9389288                         -> sqlsrv_fetch_array() PATH_TO_PROJECT\adodb\drivers\adodb-mssqlnative.inc.php:1028

    0.2035    9389288                 -> ADORecordset_mssqlnative->Close() PATH_TO_PROJECT\adodb\adodb.inc.php:1628

    0.2035    9389288                   -> ADORecordset_mssqlnative->_close() PATH_TO_PROJECT\adodb\adodb.inc.php:3986
`

**Comment by mnewnham** [comment]
Here is what I found. There is an issue with the[ sql server driver](https://github.com/Microsoft/msphpsql/issues/62), that I reported a few years ago which may be the cause of your problems. Which reminds me, have you tried this query bypassing ADOdb and writing using straight php driver code?

**Comment by federicoemartinez** [comment]
We have not tried honestly. The query works like a charm removing the "0" and using an alias and we had a due date

**Comment by mnewnham** [comment]
I have tried your code on both the windows and linux version 7 clients and have been unable to reproduce your problem
