### ISSUE TITLE
getMenu() not working with version v5.20.14

### ISSUE THREAD

**Issue by b247** [ADOdb/ADOdb#482]
In version v5.20.14, getMenu() is using only first column for both value and description of the returning html.
ex: `$res = $db->Execute("select id, name as description from foo"); echo $res->GetMenu();` returns:
`<option value='id'>id</option>` instead of `<option value='id'>description</option>`
I have temporary bypass this issue by replacing adodb-lib.inc.php from the 5.20.13 branch.

**Comment by dregad** [comment]
Issue most likely introduced by 61c5a8cf0ea9df2777eed7d1bb7935593aa93545 (fix for #460).

**Comment by danehrlich1** [comment]
Assigned

**Comment by dregad** [comment]
@danehrlich1 are you still planning to submit a fix for this ?

**Comment by benben159** [comment]
i have the same issue. @dregad's fix worked for me.

**Comment by dregad** [comment]
@benben159 thanks for the feedback. I have been busy with other priorities, but this should hopefully be merged soon.
