### ISSUE TITLE
Memcache(d): use prefix

### ISSUE THREAD

**Issue by asdfklgash** [ADOdb/ADOdb#485]
We had a problem using the memcached caching with the same server in both live (named server) and integration system (localhost). Best should be to be able to use a Prefix - for "old" `Memcache` directly in ADOdb, for new `Memcached` directly with `Memcached::OPT_PREFIX_KEY` (http://php.net/manual/de/memcached.constants.php) optionally.

**Comment by dregad** [comment]
@asdfklgash I'm not really sure what you meant by this, or if whatever problem you had is still an issue.

Considering it's been 2.5 years without activity, I'm going to close this now with apologies for the lack of an earlier response. Feel free to reopen if needed.

**Comment by mnewnham** [comment]
Let's leave this closed. I've got some brand new stuff for memcache ( if I ever get it finished) that includes this feature
