### ISSUE TITLE
Improve/fix function docblocks to be IDE "friendly"

### ISSUE THREAD

**Issue by wonderboyjon** [ADOdb/ADOdb#488]
While I'm hoping this request would aid other IDEs, I will say that I'm writing this request as someone who uses PHPStorm (in case that matters).

One of the main things the IDE does to aid development is highlight issues when it thinks that code is attempting to use the value returned from an object/function call in a way that it shouldn't be used, based on the expected return type(s) of that function. For example, trying to use a returned value as an array when the function says it only returns boolean values would be incorrect.

However, due to the way most of the function docblocks are currently written, the IDE flags up warnings all over the place and cannot provide useful hints to developers.

As an example of what I mean:
```
adodb.inc.php

       /**
	* Fetch a row, returning false if no more rows.
	* This is PEAR DB compat mode.
	*
	* @return false or array containing the current record
	*/
	function FetchRow() {
		if ($this->EOF) {
			return false;
		}
		$arr = $this->fields;
		$this->_currentRow++;
		if (!$this->_fetch()) {
			$this->EOF = true;
		}
		return $arr;
	}
```
When written like this, as far as the IDE is concerned, this function can only ever return `false`, and displays a warning when you try to treat the returned value as an array. 

The kind annotation I would expect it to have would be:

```
@return false|array The current record, or false if there is no current record.
```

The IDE then knows exactly which two types the function can return, and code issue highlighting and hinting works as expected.

Obviously a lot of dockblocks would need changing to accommodate this style, so maybe there's a better way to break this issue down, but it would be a big help and mean I no longer have to go in and modify the blocks manually every time there's an update.

**Comment by dregad** [comment]
@wonderboyjon we are aware of this issue of course, it has been reported before (see #136, #138). 

The main problem is that, as you can imagine, this is no small undertaking, there are dozens of classes and hundreds of functions that need to be documented, not to mention file-level docblocks... And I don't have the time or motivation to go through it all myself. 

If you're willing to do the legwork and submit a pull request with phpdoc blocks fixes, we'll gladly review & merge them.

**Comment by wonderboyjon** [comment]
I can certainly give it a go. Would your preference be one massive PR with "everything" done or break things down a bit (e.g. by class) and submit multiple PRs?

**Comment by wonderboyjon** [comment]
I'll start with #490 and then hopefully do more once I'm happy that you're happy with the way it's being done.

**Comment by dregad** [comment]
> Would your preference be one massive PR with "everything" done or break things down a bit (e.g. by class) and submit multiple PRs?

I'm fine either way, but if going for a single PR, then break it down into several commits.

As far as I know, noone's actively working on this with the exception of #136 but that's stale.

Thank you.

**Comment by dregad** [comment]
PHPDoc blocks are being updated incrementally; I don't see the point in keeping this issue open but feel free to submit PRs to improve them.
