### ISSUE TITLE
mssqlnative 5.6 workaround with sqlsrv_field_metadata

### ISSUE THREAD

**Issue by Bill1000** [ADOdb/ADOdb#492]
The recent release of the PHP mssql native driver (5.6) has introduced an issue that causes ADODB/PHP to crash on any query that returns no fields/data.

They are working on a fix, but in the meantime, it seems a workaround is replacing two lines in adodb-mssqlnative.inc.php function _initrs()

```
$fieldmeta = sqlsrv_field_metadata($this->_queryID);
$this->_numOfFields = ($fieldmeta)? count($fieldmeta):-1;
```
to one line:
```
$this->_numOfFields = sqlsrv_num_fields($this->_queryID) ? sqlsrv_num_fields($this->_queryID) : -1;
```

Assuming this doesn't break anything else, it may be worth a look as a permanent change?

**Comment by dregad** [comment]
@Bill1000 I don't think your proposed workaround would break anything.

However, considering that _initrs() executes _fetchField() method which sets $this->_numOfFields after calling sqlsrv_field_metadata(), I'm wondering if the proper fix would not be to simply drop the 2 lines from _initrs() altogether, initialize `$this->_numOfField = -1` instead and delegate setting it to _fetchField().

@mnewnham thoughts ?

**Comment by cproensa** [comment]
Watching this...
I'm positive that a fix in ADOdb will have a faster turnaroud than the ms driver.

**Comment by cproensa** [comment]
FYI.  This issue seems to be fixed with the release of driver version 5.6.1
https://github.com/Microsoft/msphpsql/releases/tag/v5.6.1

**Comment by mnewnham** [comment]
As this seems to have been resolved internally at PHP no further action required

**Comment by dregad** [comment]
I had a fix for this issue applied to the master branch locally, realizing now that I never actually pushed it... sorry :blush: 

It does not backport cleanly though, but considering that the problem has been fixed, I guess it's not an issue anymore.
