### ISSUE TITLE
PDO MySQL - $fmtTimeStamp

### ISSUE THREAD

**Issue by dezertdezine** [ADOdb/ADOdb#531]
As per issue #387 AutoExecute does not store time into timestamp/datetime fields (mysql)

I believe the problem is caused by an incorrect $fmtTimeStamp in adodb-pdo_mysql.inc.php - line 26

Currently this:
```var $fmtTimeStamp = "'Y-m-d, H:i:s'";```

Should be this:
```var $fmtTimeStamp = "'Y-m-d H:i:s'";```

**Comment by ooglek** [comment]
Agreed -- this is broken
