### ISSUE TITLE
ADOConnection instance is not accessible when handling output

### ISSUE THREAD

**Issue by 3b-fly** [ADOdb/ADOdb#539]
Is it possible to make ADOConnection::outp method non-static or to add connection reference as its third argument?

**Comment by dregad** [comment]
The purpose of outp() is just to print a message. It is used in contexts where a connection object is not available, hence its definition as static.

What is your use case for needing a connection reference ?

**Comment by 3b-fly** [comment]
I need to access output configuration which may differ per ADOConnection instance.

**Comment by mnewnham** [comment]
Theres a discussion of debugging in #550 , this might get rolled in there
