### ISSUE TITLE
ADOConnection triggers odbc_db2 on PHP 7.2

### ISSUE THREAD

**Issue by suwidadi** [ADOdb/ADOdb#541]
While not using DB2 connection, ADOConnection still executing the ADODB_db2 resulting in a Warning "The old ODBC based DB2 driver has been renamed 'odbc_db2'. This ADOdb driver calls PHP's native db2 extension which is not installed " 

Temporarily fixed by installing DB2 Driver. 

Adodb Version v5.20.14, 
PHP 7.2, 
OS : Ubuntu 18.04.02

**Comment by dregad** [comment]
The DB2 driver has undergone major changes in 5.21 (_master_ branch), see  #442. 

Could you please test and confirm if the problem persists with the latest version ?

**Comment by suwidadi** [comment]
Hi,
The Problem persists in 5.21 Branch. I'm not even using DB2 Drivers. 
but the warning becomes "DB2 extension not installed"

**Comment by suwidadi** [comment]
Hi,

Sorry for the confusing, it turns out I'm using db2 drivers. and the 5.21 Branch working perfectly.

**Comment by dregad** [comment]
Thanks for the feedback.
