### ISSUE TITLE
autoExecute UPDATE and forceUpdate false is not worrking

### ISSUE THREAD

**Issue by dirtyren** [ADOdb/ADOdb#542]
Hello,

I am using the latest ADBdb and I noticed that autoExecute on UPDATE is not comparing the fields correcly, not updating varchar and text fields on mysql.
   If I set forceUpdate to true, it works correctly.

**Comment by dregad** [comment]
Latest, meaning 5.20.14, or unreleased code from *master* branch ?

Can you please provide a code snippet to reproduce the problem ?

**Comment by dirtyren** [comment]
This @version   v5.20.14  06-Jan-2019. Latest stable.

**Comment by dirtyren** [comment]
I just wrote a code snippet and could not replicate the problem I am having on the production code, so I assume there is something wrong there that I am not seeing, in spite the fact that on the production, with the flag for autoexecute true, it works.
   I will close this issue and dig deeper on the problem. If I find anything , I will let you know.
   Tks a lot @dregad
