### ISSUE TITLE
Reference Manual • prepare documentation

### ISSUE THREAD

**Issue by DeWillem78** [ADOdb/ADOdb#543]
The documentation for the prepare method seems to be in error.
http://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:prepare

The below code didn't give me any results.
$result = $db->execute(array($handle,$bindVariables));

This works as expected:
$result = $db->execute($handle, $bindVariables);

Cheers

**Comment by dregad** [comment]
Fixed. Thanks for the heads up !
