### ISSUE TITLE
mssqlnative: ColumnEncryption

### ISSUE THREAD

**Issue by unijohn** [ADOdb/ADOdb#544]
Currently using v.5.20.14

re:  Using Always Encrypted with the PHP Drivers for SQL Server
Source:  https://docs.microsoft.com/en-us/sql/connect/php/using-always-encrypted-php-drivers?view=sql-server-2017

I'm now using a SQL Server database that requires the use of the "ColumnEncryption" field, and I'm encountering the following error in 

```
Fatal error: Uncaught exception 'ADODB_Exception' with message 'mssqlnative error: 
[
21: SQLState: 08001 Error Code: 21 Message: [Microsoft][ODBC Driver 11 for SQL Server]Encryption not supported on the client. SQLState: 08001 Error Code: -2146893007

Message: [Microsoft][ODBC Driver 11 for SQL Server]SSL Provider: The client and server cannot communicate, because they do not possess a common algorithm. SQLState: 08001 Error Code: 21 

Message: [Microsoft][ODBC Driver 11 for SQL Server]Client unable to establish connection SQLState: 08001 Error Code: -2146893007 

Message: [Microsoft][ODBC Driver 11 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. 
] 
```

If I use this PHP code in PHP's `sqlsrv_connect()` directly, it allows me to connect to the database:

```
  $connectionInfo = array(
     "Database" => $db_name,
     "UID" => $db_user,
     "PWD" => $db_pass,
     "ColumnEncryption" => "Enabled"
  );
  $server = $db_host;
  $conn = sqlsrv_connect($server, $connectionInfo );
```

If I add `$connectionInfo["ColumnEncryption"]="Enabled";` to `_connect()` in `adodb-mssqlnative.inc.php`, I get this error:

`errors: Array ( [0] => Array ( [0] => IMSSP [SQLSTATE] => IMSSP [1] => -1 [code] => -1 [2] => Invalid option ColumnEncryption was passed to sqlsrv_connect. [message] => Invalid option ColumnEncryption was passed to sqlsrv_connect. ) ) `

I looked through the master branch, and I don't see any code in `adodb-mssqlnative.inc.php` to handle this optional parameter.  Did I overlook it in the documentation or source code?  Is this issue something that needs to be reviewed and patched into the current code?

**Comment by unijohn** [comment]
I was wrong about sqlsrv_error() working vs. adodb not working.  Currently, both sets of calls are returning `$conn == false` when using the `ColumnEncryption` parameter.

**Comment by dregad** [comment]
Thanks for the feedback. and do let us know if this turns out to be an issue in ADOdb in the end.
