### ISSUE TITLE
Function adodb_strip_order_by() strips incorrectly if the SQL statement contains multiple order by statements

### ISSUE THREAD

**Issue by mustafa-soner-acar** [ADOdb/ADOdb#549]
**Problem :**
In the function "adodb_strip_order_by" (adodb-lib.inc.php), the _order by_ expression which is found first by regex is stripped down. If a subselect or row_number function containing _order by_ is used, this operation yields a malformed query.

**Solution :**
This can be averted by stripping the **last** _order by_ instead of the first one found.

In [line 22 of adodb-lib.inc.php](https://github.com/ADOdb/ADOdb/blob/a3410de7c9397046564936e7dc81b7a6143a9e7f/adodb-lib.inc.php#L22)

```
$rez = preg_match('/(\sORDER\s+BY\s(?:[^)](?!LIMIT))*)/is', $sql, $arr);
```

can be replaced by

```
$rez = preg_match_all('/(\sORDER\s+BY\s(?:[^)](?!LIMIT))*)/is', $sql, $arr);
if ($arr) {
	$tmp = array_pop($arr);
	$arr = [1=>array_pop($tmp)];
}
```

Here I basically replaced **preg_match** with **preg_match_all**, and reduced the output to the last match. A better approach could be found though, this does the job.

**Comment by mnewnham** [comment]
Taking a simple statement such as 
````php
select * from table_a 
           where description in (select top 5 description from table_b order by name) 
      order by description desc 
````
Returns
````php 
select * from table_a 
            where description in (select top 5 description from table_b) 
       order by description desc
````
When it should return
````php
select * from table_a 
           where description in (select top 5 description from table_b order by name) 
````
