### ISSUE TITLE
Needless output in ADODB_mssqlnative with activated debugging

### ISSUE THREAD

**Issue by BillX** [ADOdb/ADOdb#55]
When debugging is activated, this class not only gives the sql-statements to the output handler, like the other drivers do. Also the returned values of a lot of print_r- and adodb_backtrace-calls are given.
I think, using the backtrace here might be useful while developing the ADOdb-driver-class, but it's completely absurd for debugging an application which only uses ADOdb. In this case only the processed statements are relevant.

ADOdb allows you to define your own output and error handler. I use this feature to have the ability to write the errors and the output to separate logfiles, instead of sending them to the browser.
This is very useful while you are developing an application and it's also useful if you are searching for errors on a live-system. You can log all the "real-live" statements and errors without affecting the system.

Unfortunately the logfile gets flooded with debug-messages, by this driver.
Nearly 2500 lines for a simple script with only two insert- and one select-statement. And 10000 lines for a little bit more complex script. At every single request!
This not only bloats the output-log, it also slows down the application.

It would be nice if this class could behave like all the other driver-classes.

Greetings

Bill

**Comment by dregad** [comment]
Any update on which debug statements need to be removed ?

**Comment by dregad** [comment]
Closing this since you did not provide any feedback.
