### ISSUE TITLE
undocumented debug settings

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#550]
If `$conn->debug` set to true, the queries are divided by hr tag as documented on 
https://adodb.org/dokuwiki/doku.php?id=v5:userguide:debug&s[]=debug

But there are also other values except true/1 or false/0 that have effects within ADOdb php code:

```
99
-1
-99
```

Stumbled over it as it outputs hr tag, but format of sql is lost when viewed in webbrowser.
* Set debug to -1 outputs br tag instead of hr tag but makes it not better IMHO.
* Set debug to -99 omits output in webbrowser.
* Set debug to 99 outputs additional debug data

See adodb-lib.inc.php

**Comment by dregad** [comment]
The [original ADOdb documentation](https://github.com/ADOdb/ADOdb/blob/v5.20.0/docs/docs-adodb.htm#L3938) says:

_debug: Set to true to make debug statements. Set to -99 to only display errors. Set to 99 to display debug statements and add a backtrace._

This was not taken over properly during the migration of the docs to DokuWiki.

Anyway, that gives us the original intent; only `-1` is never documented, but as you say it only replaces `<hr>` by `<br>`.

> format of sql is lost when viewed in webbrowser
> makes it not better IMHO

Not very clear what you mean by that. What would be your expectation ?

> Set debug to -99 omits output in webbrowser.
> Set debug to 99 outputs additional debug data

The behavior of `-99` is not consistent IMO.  Sample output :

## 99
<hr>
(mysqli): select a from table
    where a.id = 1 &nbsp; 
<hr>
Query: select a from table
    where a.id = 1 failed. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'table
    where a.id = 1' at line 1<br>
1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'table
    where a.id = 1' at line 1<br>
<pre align=left></pre><pre align=left><font face="Courier New,Courier">ADOConnection._Execute(select a from table     where a.id = 1, false)</font><font color=#808080 size=-1> % line 1267, file: <a href="file:/C:\cygwin64\home\Regad\dev\adodb\adodb.inc.php">adodb.inc.php</a></font>
<font face="Courier New,Courier">ADOConnection.Execute(select a from table     where a.id = 1)</font><font color=#808080 size=-1> % line   16, file: <a href="file:/C:\cygwin64\home\Regad\dev\adodb\test.php">test.php</a></font>
</pre>

## -99
Query: select a from table
    where a.id = 1 failed. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'table
    where a.id = 1' at line 1<br>
<hr>
(mysqli): select a from table
    where a.id = 1 &nbsp; 
<hr>
1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'table
    where a.id = 1' at line 1<br>

**Comment by peterdd** [comment]
topic: `function _adodb_debug_execute(&$zthis, $sql, $inputarr)`

>> format of sql is lost when viewed in webbrowser

> Not very clear what you mean by that. What would be your expectation ?

Instead of putting a `<hr>` in front and end of debug output, it seems more natural to me to wrap it into `<pre></pre>` for `$inBrowser` debug view as `pre`-tag has CSS property `white-space:pre` by default. Maybe set a `<pre class="adodbdebug">` or something like that to distinguish from normal pre-tags of the app to debug.

Also `<hr>` without closing tag and `<br>` is only valid for html(4) or html5, but not for xhtml output. (minor problem)

I also saw in code you can set a variable `$ADODB_OUTP`  to set a function for debug output that could do that wrapping too, see function outp() in adodb.inc.php 

Also not sure why they put `<hr>` into the nonbrowser debug output in adodb-lib.inc.php: `ADOConnection::outp("-----<hr>\n($dbt): ".$sqlTxt." $ss\n-----<hr>\n",false);`
Maybe to view the debugfile in webbrowser? But I think this is not needed there.

**Comment by mnewnham** [comment]
I'm not sure anyone realized that there were different types of debug levels. I certainly never spotted it when i was doing the documentation, and have never instituted it when making massive changes to either the mssql drivers or DB2 drivers. Given the existence of monolog, I would suggest defining some standards for that and using it.

**Comment by dregad** [comment]
This was fixed by @mnewnham, see https://github.com/ADOdb/ADOdb/pull/856#issue-1345623850

https://adodb.org/dokuwiki/doku.php?id=v5:userguide:debug#special_options
