### ISSUE TITLE
Oracle, Oci8, query result in windows and linux has decimal separator

### ISSUE THREAD

**Issue by priatmoko** [ADOdb/ADOdb#551]
Hi, 
I am using adodb for connecting to oracle database. I develop web apps on windows OS, but the server production is on linux server (ubuntu). There is a different result  on query result (decimal separator), in windows decimal separator using comma (,) but in linux using point (.). 

Example in win 2,3. in linux 2.3

I want to set both on win and linux use point (.) as standart decimal separator.

Example in win 2.3, in linux 2.3

How can I find the configuration to set it in windows ?

FYI: I have tried to change setlocale and some methods but it doesn't work.

Thank you in advance for helping me.

**Comment by dregad** [comment]
Are you sure the DB server's locale settings (NLS) are the same on both machines ? 

Check Oracle documentation.
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/nlspg/setting-up-globalization-support-environment.html#GUID-D5C74C82-8622-46F4-8760-0F8ABA28A816

If that does not help, then please provide detailed steps to reproduce.

**Comment by priatmoko** [comment]
@dregad  thank you so much, you saved my day. I forgot to set up NLS locale on my windows environtment variable. 
after setting up the locale setting (NLS_Lang = American_america.UTF8)  on windows environtment variable, everything run well.

Thank you..

**Comment by dregad** [comment]
Glad I could help.
