### ISSUE TITLE
mssqlnative: wrong date format, hard-coded UTC timezone

### ISSUE THREAD

**Issue by pgusak** [ADOdb/ADOdb#552]
adodb-mssqlnative.inc.php, lines 1063-1065:
```
if (is_object($value) && method_exists($value, 'format')) {//is DateTime object
	$this->fields[$key] = $value->format("Y-m-d\TH:i:s\Z");
}
```
hard-coded `Z` means UTC time zone, which is incorrect, should be:
```
if (is_object($value) && method_exists($value, 'format')) {//is DateTime object
	$this->fields[$key] = $value->format("Y-m-d\TH:i:s");
}
```
https://www.php.net/manual/en/datetime.format.php

**Comment by dregad** [comment]
ADORecordset_mssqlnative::_fetch() has been significantly changed in 39e0c1dd2fe0476595a1ca2254bd255eb8476b47. Can you please check, whether the problem persists in master branch.

As for the `Z`, it was added by @mnewnham (see https://github.com/ADOdb/ADOdb/commit/abe05d8949ff260a6d048f4b44e8f737dcea3867#diff-5f880e0824d7dd21bee7e18f6e54c4f8L841) and I'm sure he did that for a reason .

**Comment by mnewnham** [comment]
So there's multiple issues with the date formatting in the sql server driver. When I rewrote the driver close to 10 years ago for SQL Server 2008 and the native mode driver, there was no 'date' type in the database, just datetime, and my prime concern at the point was to get the cross-compatibility 'D' metatype aspect working, with other databases that did have that. When I did this commit (6 years ago?) I was trying to get the best mix for earlier and later types.

I'd push back slightly against a blanket statement that it's "wrong", after all, its been in use for 6 years without any feedback, and SQL server is a pretty popular ADOdb driver, but I'd agree that feature-wise, it's thin. I cannot remember why I changed it to UTC, but frankly it would have been for no other reason than to get the thing working correctly when doing cross database compatibility testing. But I'm  in the USA and using datetime as a date field still so I've no reason to change anything.
Given that the older databases without the date type field should gone now, what should be happening is this:

1. All of the meta code that maps a 'D' field to a datetime field should be mapped to a date field in SQL Server, with the appropriate I8N.
2. datetime fields should be mapped purely to 'T' metatypes.
3. We could add a legacy flag to allow D to map to datetime fields
4. **_For simplicity's and quickness sake, you should turn that date format into a class variable, then override it to whatever you want._** 

But what we shouldn't do is just change it, and hope that it doesn't break the last 6 years worth of installations.

**Comment by pgusak** [comment]
Understood, thank you for the answer. I used ADODB with *mssql* driver for
about 15 years, and when I switched to *mssqlnative* I found all my dates
are one day off in US, because 2020-01-01T00:00:00Z is December 31, 2019 in
US. So, my software simply stopped working correctly because of that new
logic. I think it is simply wrong when two drivers read two different
values from exactly the same database cell.
So, I had to add yet another database abstraction layer on top of ADODB
just because of that change. I had to set 'ReturnDatesAsStrings' to true
because otherwise I had wrong objects in PHP. Then I cut the first 10 chars
and ignore that Z timezone sign. It is a pain.

Sincerely,
Pavel Gusak

**Comment by mnewnham** [comment]
Are you saying that the mssql driver and mssqlnative driver return different dates from the same field because the timezone that it is recorded in is different from the timezone of the server? (or something like that). 

The returnDatesAsStrings issue is a problem but not completely an ADOdb issue, if you are using timestamp fields as date, my own solution to this (if you are using a recent version of SQL Server)

1. Migrate the timestamp fields that you are using as dates to the SQL Server date format.
2. Change the metaType in ADOdb to point type 'D' to that.

This is likely to be our preferred approach in the future,

**Comment by mnewnham** [comment]
I'm wondering what version of ADOdb you are using, because that section of code no longer exists. I would recommend upgrading to the current master branch to see if the problem disappears.

**Comment by pgusak** [comment]
I was using v5.20.14, updated to 5.20.15, will check

Sincerely,
Pavel Gusak

**Comment by mnewnham** [comment]
I think you'll need to pull a copy of the master

**Comment by pgusak** [comment]
We are using composer with *"adodb/adodb-php": "*"* setting. It gives us
and our customer at least some level of assurance. Using the latest
available version is too dangerous.

Sincerely,
Pavel Gusak

**Comment by dregad** [comment]
@pgusak I understand not wanting to run unreleased code in production. 

That being said., it would be nice if you could confirm whether the problem still exists in the master branch (in a test environment). We're planning to release 5.21.0 soon.

You can get master the branch with `composer require adodb/adodb-php dev-master`

**Comment by pgusak** [comment]
good news! `dev-master` works better than 5.20.* -- all the timestamps are
precise with ReturnDatesAsStrings set to false. Can't wait for 5.21 release!

Sincerely,
Pavel Gusak

**Comment by dregad** [comment]
Thanks for testing and your feedback.

**Comment by peterdd** [comment]
> We're planning to release 5.21.0 soon
@dregad,@mnewnham : Any chance to review xml schema related open pull requests? :-)

**Comment by dregad** [comment]
@peterdd you're off topic.

**Comment by mnewnham** [comment]
But you're forgiven in you excitement....
