### ISSUE TITLE
problems using adodb 5.20.14 on CakePHP 2.10 / PHP 7.1

### ISSUE THREAD

**Issue by fuzzler** [ADOdb/ADOdb#554]
Hi!

I've got problems using adodb 5.20.14 in my webapp devoloped inCakePHP 2.10. My PHP version is 7.1. This is error generated:

2019-10-08 07:45:06 Error: [Error] Call to undefined function mysql_pconnect()
Request URL: /Cake210/prodotti/search/?s=mouse
Stack Trace:
#0 /var/www/html/Cake210/app/Lib/adodb/adodb.inc.php(496): ADODB_mysql->_pconnect('host', 'usr', 'pw', 'db')
#1 /var/www/html/Cake210/app/Controller/Component/AdoDBComponent.php(20): ADOConnection->PConnect('host', 'usr', 'pw', 'db')

How I can solve it? I've to modify something inside code?

Thank you.

**Comment by dregad** [comment]
Looks like you're using the old _mysql_ driver, based on the eponymous PHP extension which is deprecated as of PHP 5.5.0, and has been removed as of PHP 7.0.0 [[1]].

Please use the _mysqli_ driver instead. Other than changing your connection parameters, there should not be any other impact on your code.

[1]: https://www.php.net/manual/en/intro.mysql.php

**Comment by fuzzler** [comment]
Thank you for your time!

I'll try it and I'll give you a report

Bye!

Il Mer 9 Ott 2019, 09:54 Damien Regad <notifications@github.com> ha scritto:

**Comment by fuzzler** [comment]
Hi!

I checked for driver in line with your suggestions...but it's all regular.
I've forgot to say you I'm using *docker*, this is conf file:

RUN apt-get update && apt-get install -y \
wget \
sendmail \
joe \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
libpng-dev \
        libssl-dev \
        libxml2-dev \
libmcrypt-dev \
libxslt-dev \
        libmagickwand-dev \
zlib1g-dev libicu-dev g++ \
wkhtmltopdf \
&& docker-php-ext-install intl \
&& docker-php-ext-configure intl \
&& docker-php-ext-install exif \
&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/
--with-jpeg-dir=/usr/include/ \
&& docker-php-ext-install -j$(nproc) iconv gd mbstring* pdo pdo_mysql
mysqli *soap zip bcmath xsl \
&& apt-get install -y --no-install-recommends msmtp

 as you can see it's all ok with drivers...no mysql installed but mysqli
and pdo too...
so the problem maybe it's adodb doesn't recognize it...

Any other suggestions?

Thank you again!

F

Il giorno mer 9 ott 2019 alle ore 16:58 Fabrizio Ugo <fazione33@gmail.com>
ha scritto:
