### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by contactashish13** [ADOdb/ADOdb#556]
Do you intend to add support for MongoDB and other similar NoSQL databases?

**Comment by dregad** [comment]
There is currently no plan for this, but contributions are welcome.

**Comment by mnewnham** [comment]
This would really only make sense if a product like nosqlbooster was available as a PHP built-in, as the existing PHP infrastructure does not allow the execution of SELECT type queries against MongoDb databases, and that is effectively the building block of almost all of  ADOdb
