### ISSUE TITLE
STRICT_TRANS_TABLES error

### ISSUE THREAD

**Issue by swtinkle** [ADOdb/ADOdb#557]
Perhaps when mysql error 1364 "Field doesn't have a default value" occurs an exception could be thrown? My inserts were failing and took quite a while to figure it out.  This is a new default mode in MySQL 5.7.6

**Comment by mnewnham** [comment]
Are you referring to when the table is built, using createTableSql, or at run-time inserting a record?

**Comment by mnewnham** [comment]
As there has been no response on this, I am closing it. I hope you found your own solution. If you need help, feel free to re-open
