### ISSUE TITLE
How to use sockets to connect App Engine running PHP and Google Mysql?

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#561]
I am trying to connect a Google App Engine to Google Mysql.

I found a posting saying that you could by using sockets

$cn  = mysqli_connect(null, //dont use host
                                     $user,
                                     $pwd,
                                     $dbname,
                                     null,  // no port
                                    '/cloudsql/' .  $google_mysql_instance_name);

How can I do the same with adodb?

Thank you

**Comment by dregad** [comment]
I have never tried to connect via sockets myself, but I believe you should be able to do so by using a _DSN connection string_ with the `unix_socket` parameter - see [documentation for adoNewConnection](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:adonewconnection#dsn_usage).

**Comment by stccorp** [comment]
I was able to do it like this

 $cn = newADOConnection('mysqli');
 $cn->socket = '/cloudsql/' . $instance_connection_name;

**Comment by dregad** [comment]
Thanks for the feedback.
