### ISSUE TITLE
php lens dot com captured

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#564]
That domain is showing now ads for spyware.

Definitely not something I would like to promote by having the links in ADOdb sources.

There are currently 84 appearances of that domain within ADOdb 5.20.15 
```bash
grep -rin 'phplens\.com' | wc -l 
```

How to handle that? Ideas:

* replace the links with a prefix like https://web.archive.org/web/2011101/http://phplens.com/lens/faq/faq.php
 (I see permission denied response stuff starting within 2012, dunno if just setting a date in 2011 is intended working of web.archive.org)
* setup a readonly mirror like oldforum.adodb.org (either from collecting each last working page from webarchive.org or by contacting original webmasters to provide a backup?)
* completely get rid of that links, but it is sometimes interesting to see why something was done in history and compare it to the current world of php and databases.

**Comment by mnewnham** [comment]
I've removed all references to phplens from the documentation. @dregad , any chance you could just stream edit this out of the code. I see no reason to keep links that old around.

**Comment by mnewnham** [comment]
Now removed from Readme in master
