### ISSUE TITLE
Auto-increment feature in Oracle driver problematical with long table names

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#565]
Oracle does not provide a native method of implementing an auto-increment column, so ADOdb provides an alternative method, via an insert trigger and a sequence.

In order to distinguish the name of the trigger and the sequence, the strings //**TRIG_**// and //**SEQ_**// are prepended to the name of the table to obtain the name of the trigger and sequence respectively.

This approach provides uniqueness, but also provides an easy method of obtaining the trigger and sequence associated  with a table.

The feature is robust and and well-understood, but a problem arises as the length of the table name approaches 30 characters. A table name "EMPLOYEES", would have a trigger created, named "TRIG_EMPLOYEES", falling well within the maximum characters available. However a table named "EMPLOYEE_HOURLY_PAY_RATES", already 26 characters long, would exceed the maximum name size when prepended with "TRIG_". When an attempt is made to create the trigger an error **ORA-00972: identifier is too long** occurs

**Comment by dregad** [comment]
@mnewnham This is [not necessary with Oracle 12cR2 and later](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/Database-Object-Names-and-Qualifiers.html#GUID-75337742-67FD-4EC0-985F-741C93D918DA), as that release allows **128 chars** for identifiers (as long as [COMPATIBLE parameter](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/COMPATIBLE.html) is set to 12.2.0 or higher).

**Comment by mnewnham** [comment]
I know, but my government clients are short on money and resources (I'm still supporting Microsoft SQL Server 2008 as well). I'd like to get it in there as it's pretty trivial and I'm trying to get my companies version of ADOdb back in line with master. It's drifted as we weren't able to get 5.21 out.
