### ISSUE TITLE
PHP 7.3 PostgreSQL Update Statement Issues

### ISSUE THREAD

**Issue by sweigand** [ADOdb/ADOdb#568]
When we are running PHP 7.3, we are running into issues with PostgreSQL Update statements. 

While I have read that issues related to PHP 7.3 will be fixed in 5.21+, PHP 7.3 was released December 2018, PHP 7.4 was just released, and PHP 7.2 is going to be End of Life November 2020. 

Is there a roadmap/timetable for releasing ADOdb 5.21+? 

Thank you,
Scott Weigand

**Comment by mnewnham** [comment]
5.21 is currently being built as we speak. If you are able, please download a copy of master to see if it resolves the issues you are having, because if it does not we obviously need to deal with them promptly.

**Comment by sweigand** [comment]
Our devs downloaded a copy of the master and it is looking promising! They will be doing more testing this week. Please leave this issue open a little longer.

**Comment by sweigand** [comment]
I talked further with our devs and this release fixes our issues! Please consider this resolved.
