### ISSUE TITLE
problem using ssl, it works with pdo

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#569]
This works using PDO

$options = array(
        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
        PDO::MYSQL_ATTR_SSL_CA => 'cacert.pem',
        PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT =>true
);
$dsn = "mysql:host={$hostname};dbname={$database};port={$port}";
$mysqli = new PDO($dsn, $username, $password, $options);

//-------------------------------------
I tried this using adodb and is not working

 $cn = newADOConnection('mysqli');
 $cn->port = $port;
 $cn->ssl_cert   = "cert.pem";
 $cn->optionFlags = array(array(MYSQLI_OPT_SSL_VERIFY_SERVER_CERT,true));
 $cn->connect($hostname,$username,$password,$database);

Any ideas?

**Comment by mnewnham** [comment]
Could you provide a little more information on what doesn't work?

 + I'm assuming the certificate name in the second statement is just a typo. In the first you use `cacert.pem` but in the second you use `cert.pem` 
+  Try setting **$cn->debug = true** before you issue the `connect` statement
+ Are there any errors in the mysql logs?

**Comment by stccorp** [comment]
I got some addition info.
the hostname is a long private ip hostname(X means my database name)

I get this error:
Could not connect :
private-db-mysql-XXXXXXXXXXXXXXXXXXXXXXXX.com: php_network_getaddresses: getaddrinfo failed: Name or service not known

If I am using the same hostname on PDO, it should(???) work the same on adodb, right?

**Comment by mnewnham** [comment]
1. You could try using the DSN string instead of the hostname, that works for the ADOdb PDO driver.
2. The  `php_network_getaddresses: getaddrinfo` isn't an ADOdb error, in fact it's not really even a PHP issue. It means that the hostname you've provided can't be resolved by your local DNS server. I would look very carefully at the hostname you've put into the connection parameters.

Try copying it and pasting into the command line and see if you can ping it.

**Comment by stccorp** [comment]
Very interesting thing.

That database is a managed database. I get a private and a public hostname.

I can ping the public hostname, but my user has access denied. And I CANT ping the private.
ping: XXXXXXXXXXXXX: Name or service not known

So
1. I am not sure I am supposed to connect my webserver to the database using the public hostname. The firewall will block it on production  even if I can make it work on testing.
2. why PDO does not seem to care?

**Comment by stccorp** [comment]
Apparently it was some-kind if incorrect configuration in the network zone I was.  It works now
