### ISSUE TITLE
Ojs INSTALLATION FAILED

### ISSUE THREAD

**Issue by Hamza12-ab** [ADOdb/ADOdb#571]
I'm installing ojs in windows 7 using xammp. 
i'm following this guide.
https://pkp.sfu.ca/ojs/docs/userguide/2.3.1/systemAdministrationInstallProcess.html

but at the 4th last step i get an error that:

Errors occurred during installation
The form was not submitted properly.

i'm unable to fix this issue.
i won't be able to proceed to login in it unless this issue is there.

waiting for positive response.

**Comment by mnewnham** [comment]
Is ADOdb bundled with this product? If so, what version?
Operating System? Version of PHP?

**Comment by mnewnham** [comment]
As I have not had a response for a while, I'm assuming you resolved this by yourself. Feel free to re-open if this is still a problem

**Comment by Hamza12-ab** [comment]
yes ADOdb is bundled with this product and i am try ubuntu or windows boht operating systems but i could not resolve this issue and version of phr is '7'.kindly help me thanku.

**Comment by davidsneighbour** [comment]
The support forum for OJS is here: https://forum.pkp.sfu.ca/

**Comment by Hamza12-ab** [comment]
Okay Thanks
