### ISSUE TITLE
SAP SQL Anywhere PHP7

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#576]
Just a note as I saw the notice by @mnewnham on

https://adodb.org/dokuwiki/doku.php?id=v5:database:sap_sqlanywhere

It seems there is still driver support for PHP7+:

https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module

**Comment by mnewnham** [comment]
I'll modify the unsupported comment but realistically until we get a single request about it, it's not worth the time of setting up an sql anywhere database server and client, and rebuilding an updated driver.
