### ISSUE TITLE
connection to mssql with Port fails

### ISSUE THREAD

**Issue by schmanat** [ADOdb/ADOdb#58]
Hi

Yesterday i tried to connect to an mssql (Microsoft Server 2005) with the following dsn string.
`mssql://user:password@10.10.10.19:63341/database`

I couldn't connect to the database because in the drivers/adodb-mssql.inc.php there is a function called

    function _connect($argHostname, $argUsername, $argPassword, $argDatabasename,$newconnect=false)
	{
		if (!function_exists('mssql_pconnect')) return null;
		$this->_connectionID = mssql_connect($argHostname,$argUsername,$argPassword,$newconnect);
		if ($this->_connectionID === false) return false;
		if ($argDatabasename) return $this->SelectDB($argDatabasename);
		return true;
	}

The parameter `$argHostname` holds only the hostname (10.10.10.19) and ignore the port.
So it's not possible to connect to an mssql server with a port.

**Comment by dregad** [comment]
I don't use mssql so I can't test. Can you please check if this is still an issue in latest master ? Maybe #63 changes this behavior.

**Comment by mnewnham** [comment]
Is this a connection from a windows machine? If so the correct syntax is:

`hostname, port`  and not `hostname:port`

Please let me know if it is a freetds connection and I will set up a test

**Comment by dregad** [comment]
@schmanat you have not provided any feedback, so I'm closing this; feel free to reopen with the requested information.
