### ISSUE TITLE
3 letter acronym SQL function names

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#580]
I would like to suggest that function names containing the string SQL the 'SQL' is explicitely allowed uppercase and the default by the ADOdb code style.

Functions names related to a specific driver name like
 ```
adodb-error.inc.php:225:function adodb_error_mssql(), 
adodb-error.inc.php:244:function adodb_error_mysql(), 
tests/tmssql.php:5:function tmssql()
```
are excluded from the general suggestion.

```bash

~/test/git/ADOdb>egrep -rn 'function\s+\w+SQL\(' * |wc -l
      83
~/test/git/ADOdb>egrep -rn 'function\s+\w+Sql\(' * |wc -l
       1
~/test/git/ADOdb>egrep -rn 'function\s+\w+sql\(' * |wc -l
      11

~/test/git/ADOdb>egrep -rn 'function\s+\w+sql\(' * 
adodb-error.inc.php:225:function adodb_error_mssql()
adodb-error.inc.php:244:function adodb_error_mysql()
adodb-lib.inc.php:647:function _adodb_getupdatesql(&$zthis,&$rs, $arrFields,$forceUpdate=false,$magicq=false,$force=2)
adodb-lib.inc.php:828:function _adodb_getinsertsql(&$zthis,&$rs,$arrFields,$magicq=false,$force=2)
adodb-lib.inc.php:1073:function _adodb_column_sql(&$zthis, $action, $type, $fname, $fnameq, $arrFields, $magicq, $recurse=true)
adodb-perf.inc.php:69:function adodb_log_sql(&$connx,$sql,$inputarr)
adodb-perf.inc.php:671:	function clearsql()
drivers/adodb-odbtp.inc.php:555:	function MetaIndexes_mssql($table,$primary=false, $owner = false)
perf/perf-oci8.inc.php:679:	function clearsql()
tests/test4.php:19:function testsql()
tests/tmssql.php:5:function tmssql()

~/test/git/ADOdb>egrep -n 'function\s+\w+SQL\(' *.php
adodb-datadict.inc.php:199:	function GetCommentSQL($table,$col)
adodb-datadict.inc.php:204:	function SetCommentSQL($table,$col,$cmt)
adodb-datadict.inc.php:443:	function CreateIndexSQL($idxname, $tabname, $flds, $idxoptions = false)
adodb-datadict.inc.php:467:	function AddColumnSQL($tabname, $flds)
adodb-datadict.inc.php:498:	function AlterColumnSQL($tabname, $flds, $tableflds='',$tableoptions='')
adodb-datadict.inc.php:529:	function RenameColumnSQL($tabname,$oldcolumn,$newcolumn,$flds='')
adodb-datadict.inc.php:553:	function DropColumnSQL($tabname, $flds, $tableflds='',$tableoptions='')
adodb-datadict.inc.php:565:	function DropTableSQL($tabname)
adodb-datadict.inc.php:570:	function RenameTableSQL($tabname,$newname)
adodb-datadict.inc.php:578:	function CreateTableSQL($tabname, $flds, $tableoptions=array())
adodb-datadict.inc.php:878:	function _IndexSQL($idxname, $tabname, $flds, $idxoptions)
adodb-datadict.inc.php:912:	function _TableSQL($tabname,$lines,$pkey,$tableoptions)
adodb-datadict.inc.php:990:	function ChangeTableSQL($tablename, $flds, $tableoptions = false, $dropOldFlds=false)
adodb-perf.inc.php:431:	function InvalidSQL($numsql = 10)
adodb-perf.inc.php:453:	function _SuspiciousSQL($numsql = 10)
adodb-perf.inc.php:516:	function SuspiciousSQL($numsql=10)
adodb-perf.inc.php:521:	function ExpensiveSQL($numsql=10)
adodb-perf.inc.php:532:	function _ExpensiveSQL($numsql = 10)
adodb-perf.inc.php:1000:	function SplitSQL($sql)
adodb-xmlschema.inc.php:1597:	function PrintSQL( $format = 'NONE' ) {
adodb-xmlschema.inc.php:1611:	function SaveSQL( $filename = './schema.sql' ) {
adodb-xmlschema.inc.php:2118:	function clearSQL() {
adodb-xmlschema.inc.php:2130:	function addSQL( $sql = NULL ) {
adodb-xmlschema.inc.php:2172:	function getSQL( $format = NULL, $sqlArray = NULL ) {
adodb-xmlschema03.inc.php:1754:	function printSQL( $format = 'NONE' ) {
adodb-xmlschema03.inc.php:1768:	function saveSQL( $filename = './schema.sql' ) {
adodb-xmlschema03.inc.php:2300:	function clearSQL() {
adodb-xmlschema03.inc.php:2312:	function addSQL( $sql = NULL ) {
adodb-xmlschema03.inc.php:2354:	function getSQL( $format = NULL, $sqlArray = NULL ) {
adodb.inc.php:2280:	function GetUpdateSQL(&$rs, $arrFields,$forceUpdate=false,$magicq=false,$force=null) {
adodb.inc.php:2306:	function GetInsertSQL(&$rs, $arrFields,$magicq=false,$force=null) {
adodb.inc.php:2381:	function LogSQL($enable=true) {
pivottable.inc.php:33: function PivotTableSQL(&$db,$tables,$rowfields,$colfield, $where=false,
peter:~/test/git/ADOdb>
```

So for example 
```function GetCommentSQL($table,$col)```
gets

```function getCommentSQL($table, $col)``` 
in source and documentation (function page and their examples)

The current documenation uses the camelCase also for the 3 letter SQL acronym which I find  .. mmh .. not the best choice.
![adodb_org_sql](https://user-images.githubusercontent.com/1839154/71711112-c6984600-2dff-11ea-953b-73bca22f09ed.png)

**Comment by dregad** [comment]
The way the function names are currently defined on the wiki, complies with [Google's camelCase definition](https://google.github.io/styleguide/jsguide.html#naming-camel-case-defined).

While I understand where you're coming from with using the SQL acronym as upper case, I personally would rather stick to strict camelCase, because using upper-cased acronyms can sometimes be confusing and make the identifier more difficult to read, especially when it occurs is in the middle of the word (although I'll grant you that this is not the case here as SQL is consistently used at the end of the identifier).

Also, I'd like to point out that mass-updating the wiki to comply would be a tedious, time-consuming manual task. 

@mnewnham thoughts ?

For reference:
- list of unique function names with _SQL_ or _Sql_ (32 occurences)
    ``` bash
    git grep -P 'function\s+\w+S[Qq][Ll]\s*\(' |sed -r "s/^.*function\s+(\w+)\s*\(.*$/\1/" |sort -fu
    ```
- occurences of above-function names where case does not match definition (123 hits)
    ``` bash
   for f in $(git grep -P 'function\s+\w+S[Qq][Ll]\s*\(' |sed -r "s/^.*function\s+(\w+)\s*\(.*$/\1/" |sort -fu); do git grep -i $f |grep -v $f; done
    ```

**Comment by peterdd** [comment]
> Also, I'd like to point out that mass-updating the wiki to comply would be a tedious, time-consuming manual task.

That would be the smallest problem as I volunteer to do that 24 manual edits on the wiki for the peace of my mind.

**Comment by mnewnham** [comment]
Given that the documentation if already 1000% better than 98% of open source projects on the internet, I'm not sure I could raise an opinion on it one way or the other. If it was part of some other documentation project, sure,  make it consistent one way or the other. But as a specific task? There are many pressing issues requiring attention in this project but that isn't one of them. 

That being said, I'm all in favor of any form of contribution to projects, and some people aren't necessarily comfortable diving into code and those other contributions shouldn't be trivialized. I therefore propose this: @dregad , you are much better informed on standards than I, if you make a decision one way or the other I will accept that, no discussion. @peterdd, If you want to standardize the documentation, go ahead, but it should be based on the above decision by @dregad. I won't participate further in this.

**Comment by dregad** [comment]
For the record, [PSR1](https://www.php-fig.org/psr/psr-1/#43-methods) dictates that 
> Method names MUST be declared in camelCase().

Looking at the list of ADOdb functions containing the term _SQL_①, there is for example

- _adodb_column_sql 
- _adodb_getinsertsql 
- DoSQLForm 
- sqlDate
- etc

@peterdd how would your propose to handle these cases ?

You could argue that the first 2 examples are not _methods_ but regular functions so PSR1 does not apply. Also, since there is no "official" standard defining camelCase (that I know of) there is some room for interpretation.

But for sure, using `SQLDate` would be non-compliant. 

① Reference: full list of function names containing the term *SQL*
```bash
git grep -Pi "function\s+\w*sql\w*\s*\(" |sed -r "s/^.*function\s+(\w+).*$/\1/" |sort -u
```

**Comment by peterdd** [comment]
> _adodb_column_sql()
> _adodb_getinsertsql()
> _adodb_getupdatesql()

These are internal functions in snake_case. No need to bother.

I even wonder if adodb_getinsertsql() and adodb_getupdatesql() are required as they are only called by getInsertSQL() and getUpdateSQL(). But that's another topic.

> DoSQLForm()

I not yet dived into adodb_perf.inc.php and seems only used for internal test page.

> sqlDate()

SQLDate()
Well, a more appropriate name could maybe getSQLDateFormat(), but that's too late to change for ADOdb IMHO.

There are also other areas like the 'constructor functions' ADONewConnection()/NewADOConnection(),..
```
egrep -rn 'function\s+[A-Z][A-Z]'
```
but this issue is just about 'SQL'.

My main reason to open this issue was that the wiki documentation applied a 'strict camelCase' rule while the ADOdb source where everything is about SQL never 'breathe' that idea. The 'SQL' string is a trained 'eye pattern' for people working with SQL while reading 'Sql' not.

But even if @dregad decides against, I would accept. (with a little tear) But no hurry to decide as there are sure things with higher priority.

@mnewnham
> 1000% better than 98% of open source projects

I appreciate that, no offence intended by me.

**Comment by dregad** [comment]
> Well, a more appropriate name could maybe getSQLDateFormat(), 

I think _getFormattedDate()_ would be more like it, as the function actually returns a date, not a format.

> but that's too late to change for ADOdb IMHO.

It can always be done in 2 steps
1. provide new function, deprecate the old one and make it a stub calling the new
2. remove the old function in a future release

> There are also other areas like the 'constructor functions' ADONewConnection()/NewADOConnection()

True, but they are not methods so PSR1 does not apply. 
That being said, at some point I'd like to replace those functions somehow (with a class).

**Comment by dregad** [comment]
We'll stick to camelCase for this.
