### ISSUE TITLE
Numerous drivers make unneeded PHP4 version checks

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#584]
The following drivers  check for PHP version 4.0.5 and higher
ads, firebird, ibase, mssl, mssqlnative, mysql,  oci8, oci8po odbc, postgres64, sybase

**Comment by dregad** [comment]
@mnewnham Great minds think alike ! I noticed some occurences of this yesterday, and added this to my todo list too :smiley: Since you assigned the issue to yourself I assume you're working on it, so I'll wait for your patch.

I would suggest to get rid of the ADODB_PHPVER constant (defined in adodb.inc.php lines 181-190) entirely, and just leave a check to die if PHP < 5.0.

Note that there are also several checks on PHP_VERSION, which should be reviewed as part of this work item too.

**Comment by mnewnham** [comment]
Could you take a look at the mssql driver for me, the way I read it is that if the php version > 4.3 then the global ''ADODB_mssql_mths'' is never declared correctly. If the inbound date passed to unixDate() was in the format "M d y", then the function would crash.

Either:
  a. I'm not reading it correctly
  b. Its never been used like that and we should drop the special handling for this driver and make it consistent with the others which would allow us to also remove the ``AutoDetect_MSSQL_Date_Order()`` function as well (incidentally I never knew this function existed before, definitely not documented).

**Comment by dregad** [comment]
> the global ''ADODB_mssql_mths'' is never declared correctly

In this context, the `global $ADODB_mssql_mths;` is needed in the _else_ block so it can be initialized. It is also declared everywhere the constant is used so there wouldn't be any scope problem here.

That being said, I don't know enough about MSSQL and how the drivers work in later versions of PHP to be able to reply with absolute certainty, but it looks like this whole $ADODB_mssql_xxx is only needed for PHP <4.3.

**Comment by mnewnham** [comment]
In that case I'm going to strip all of it out.

**Comment by mnewnham** [comment]
I've just seen [This](https://www.php.net/manual/en/intro.mssql.php). I was not aware of this (having migrated my own stuff to mssqlnative years ago), but I thought that it was still active.  I would say then deprecate mssql in 5.21. I'm going to open a new thread about removing a whole bunch of drivers in 5.22 and I'll add that to the list

**Comment by dregad** [comment]
> I've just seen This. I was not aware of this

Didn't notice either, as I don't use MSSQL at all...

> deprecate mssql in 5.21. I'm going to open a new thread about removing a whole bunch of drivers in 5.22 and I'll add that to the list

Sounds good.

I'm starting to think that with all the removed stuff, maybe the next release should be 6.0, and include namespacing and refactoring of the library into individual classes (one per file), to be PSR4 compliant.
