### ISSUE TITLE
Proposal to remove the public function Transpose() and assorted sub-functions 

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#586]
The undocumented public method **transpose()** (adodb.inc.php approx line 1894) is first mentioned in release notes for version 4,92 (29 Aug 2006) but never after, nor is it documented either at adodb.org or in the code itself.  The function appears to do some kind of row to column conversion.

The following functions are also only used by Transpose() and the proposal is to also delete them.

  * private method **_transpose()**  called by **Transpose()**
  * public function **adodb_transpose** called by **_transpose()** 
 * public function **adodb_probetypes** called by **_transpose()**

The proposal is to deprecate these methods/functions in ADOdb V5.21, and remove them in the next version after.

If you use these functions or can explain their use please comment

**Comment by mnewnham** [comment]
This is what Transpoace does. Assuming a table with three cols col_a, col_b, col_c. 
The first 2 rows are A,B,C and 1, 2, 3

If we use transpose,

````php
Array(
0=>array('col_a','A',1);
1=>array(col_b','B',2),
2=>arrat(col_c,','C',3)
);
````
This might be used for spreadsheet generation

**Comment by dregad** [comment]
This is the very definition of transposition in maths - a matrix obtained from a given matrix by interchanging each row and the corresponding column.

I don't personnally use this myself so I don't care much if it is removed.
