### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by BoBMrTD** [ADOdb/ADOdb#589]
The parameter "unix_socket" indicated as **Additional Parameters To DSN connection** in page [https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:adonewconnection](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:adonewconnection) is not working, is working the parameter "socket" (using mysqli driver).

**Comment by mnewnham** [comment]
The connection string should just pass through to the DSN. Could you provide a sample to test it please. Also ADOdb version, PHP version, platform helps too

Thanks

**Comment by BoBMrTD** [comment]
The working connection string is:
     $dsn = 'mysqli://'.$username.":".$password."@localhost/".$aliasdb."?socket=".$socket;
     $dbm = ADONewConnection($dsn);

Using the information provided by the page
https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:adonewconnection
the string should be
    $dsn = 'mysqli://'.$username.":".$password."@localhost/".$aliasdb."?unix_socket=".$socket;
but in this format the connection fail and when I look in the file adodb.inc.php at line 4930 I find:
    #mysqli
    case 'socket': $obj->socket = $v; break;

ADOdb version: 5.20.15
PHP version: 7.3.12
platform: CentOS 6.10

Best regards

**Comment by dregad** [comment]
I did not actually test this, but `unix_socket` is what is documented at https://www.php.net/manual/en/ref.pdo-mysql.connection.php

**Comment by BoBMrTD** [comment]
@dregad 
Hi,
pdo in adodb is not workink on unix using mysql as driver, I don't know if this can be related.
[https://adodb.org/dokuwiki/doku.php?id=v5:database:pdo](https://adodb.org/dokuwiki/doku.php?id=v5:database:pdo)

My report is that using "unix_socket" with the mysqli driver doesn't work.
Best regard

**Comment by mnewnham** [comment]
I have cleaned up this grid, 

1. Added a column that indicates what driver the parameter relates to
2. Removed options that only relate to obsolete items
3. Replaced ''unix_socket'' with ''socket''

@BoBMrTD , thanks for your information
