### ISSUE TITLE
mssqlnative query are not correctly closed

### ISSUE THREAD

**Issue by laurent-n** [ADOdb/ADOdb#590]
In  drivers/adodb-mssqlnative.inc.php
method _close() contains a bug causing this method do nothing
`if(is_object($this->_queryID)) {`
is wrong because $this->_queryID is not an object but a resource (probable copy/paste from PDO version) 
it should be 
`if(is_resource($this->_queryID)) {`
It cause extra cursor left open, and if there's multiple big query on the same DB blocs through a getrow it can cause a deadlock, it's not common on normal operation but I've spend hours on a such bug due to a bugged query. Could be an issue on long worker too.

**Comment by mnewnham** [comment]
I apologize. I thought that there was a different issue to what we have originally discussed. I have pushed a fix directly into master and 5.20 for the next hotfix. if there are no other issues, please close this.

**Comment by laurent-n** [comment]
Thanks
