### ISSUE TITLE
wiki: supported drivers, tagging and categorization

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#596]
@mnewnham I noted the change you made to the [wiki's sidebar](https://adodb.org/dokuwiki/doku.php?id=sidebar) at the end of 2019, adding the notion of Support Tiers. That's a great idea, thanks !

I think the way we document the notion of (un)supported drivers on the wiki could be improved; the information is found in multiple places, and is not always consistent.

- sidebar
- [feature comparison matrix](https://adodb.org/dokuwiki/doku.php?id=v5:database:feature_comparison) page
- [Unsupported drivers](https://adodb.org/dokuwiki/doku.php?id=v5:database:unsupported) page
- Database drivers [index page](https://adodb.org/dokuwiki/doku.php?id=v5:database:index)
- description blocks on each specific driver page

The first 3 use static references to list the pages.

Since the individual drivers page already make use of the _tag_ plugin, I thought we could use that information to improve this by generating the page lists dynamically.

Here's what I did :
1. Added new `tier1` and `tier2` tags to the corresponding drivers (based on categorization defined in _sidebar_)
2. Added missing tags to driver pages that didn't have them
3. Created a new [Supported Databases](https://adodb.org/dokuwiki/doku.php?id=v5:database:supported) reference page, that leverages the tags to build the pages list.

Criteria for the _Unsupported drivers_ list is defined as follows:  `obsolete deprecated dormant -tier1 -tier2` (i.e. all pages having one of the first 3 tags, excluding those specically tagged as one of the support tiers). This is necessary, because some tier2 drivers are marked as _obsolete_.

Please review and let me know your feedback. If you're OK with the approach, I will amend the sidebar.

**Comment by mnewnham** [comment]
See my comment on #597 about the data provider tag.  This is a real oddity about the design, (which i would say needs to go away eventually)

**Comment by dregad** [comment]
I'm OK with that.

You have not really answered my question, i.e. are you OK with the approach, and can I apply the same to the _sidebar_ page ?

**Comment by mnewnham** [comment]
Yes, sure, I find no issue with your approach to documentation of the tier1,tier2 and unsupported drivers

**Comment by dregad** [comment]
OK thanks for the feedback, I'll update accordingly.

**Comment by dregad** [comment]
Sidebar has been modified to use `{{topic}}`, so the list of drivers is now built dynamically.
