### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#598]
Has not been updated for over 3 years...

According to [SourceForge download stats](https://sourceforge.net/projects/adodb/files/Documentation/stats/timeline?dates=2019-01-01%20to%202020-01-01&period=monthly), for the past year there is an average of ~70 download/month so considering the recent wave of changes on the wiki, I think it would be worth updating the ZIP.

@mnewnham I think the last time it was generated, we were still on the old server. Not sure if the process you documented back then is still valid. Could you please check ? Let me know if I can help.

**Comment by mnewnham** [comment]
The plugin I originally used that we did not install that is needed for this is [xcom](https://www.dokuwiki.org/doku.php?id=plugin:xcom). This allowed me to mirror the wiki on a regular basis onto a local machine. I could then run multiple tasks against the wiki without needing shell access to the server running it. Getting that set up would be the first item.

**Comment by dregad** [comment]
> The plugin I originally used that we did not install that is needed for this is [xcom](https://www.dokuwiki.org/doku.php?id=plugin:xcom)

I don't mind installing a new plugin, but can you please confirm this is indeed what you need, because it does not match what you originally [documented](https://adodb.org/dokuwiki/doku.php?id=admin:offline_docs_build). Did you change the build process ?

**Comment by mnewnham** [comment]
Those are the ones that are installed on the mirror machine (i.e. my internal server). I obviously didn't add the one to extract the data from the website (xcom) to the notes.

**Comment by dregad** [comment]
According to the [sync plugin's documentation](https://www.dokuwiki.org/plugin:sync#usage), it should indeed be installed on the local DokuWiki instance only (your server) and not on the remote one (adodb.org).

It does not mention installing the _xcom_ plugin though, only to activate the _remote_ setting (I that it is).

Wouldn't it work to simply enable and configure the siteexport plugin directly on adodb.org, so you one could just run the post-processing script on the generated ZIP file ?

**Comment by mnewnham** [comment]
Don't know. If you remember, there were severe restrictions on what we could run on the server, which is why we moved it over. A lot of the plugins didn't work because they relied on uninstallable php extensions. PHP5.2? If you can get siteexport working on your server, I can certainly try it out like that, see if there are any issues.

**Comment by dregad** [comment]
Site export is installed and enabled, feel free  to tweak the settings as needed.

**Comment by mnewnham** [comment]
So it wasn't **xcom**, it was **sync** (mentioned in the documentation). Anyway, its hopeless trying to work using the online database. I remember doing a lot of command line work to fix permissions and stuff. Let's get sync installed and I'll rebuild it offline

**Comment by dregad** [comment]
> Let's get sync installed 

As mentioned (https://github.com/ADOdb/ADOdb/issues/598#issuecomment-574567089) it looks like Sync should be installed on the local copy. I believe the _remote_ side (XML-RPC) is already and correctly setup.

**Comment by mnewnham** [comment]
Yes, I'm connected in and attempting to duplicate the database. The pull failure rate is about 60% so it'll take a while to get a first valid copy

**Comment by mnewnham** [comment]
Just wondering if I've crashed adodb.org or your system has maybe put a block on my ip as I can't reach adodb.org at all (19:18 GMT+7)

**Comment by dregad** [comment]
The site is up as far as I can tell, and I don't see anyhting untowards in the apache logs.
There are a lot of xmlrpc calls from 73.181.92.xxx (denver.comcast.net) throughout the last 10-12 hours which I assume is you, but they all have a HTTP 200 status code.

Maybe you can try to download a dump of the site via your FTP account, if that would make things easier ? Sorry I can't give you SSH, as I run multiple sites on that host, and the provider does not allow restricting SSH access to subdirectories.

**Comment by mnewnham** [comment]
I've built a new image and uploaded it to sourceforge
