### ISSUE TITLE
ADO Driver Php 5.x Connection

### ISSUE THREAD

**Issue by rsmereka** [ADOdb/ADOdb#60]
Hi,

I am working on a data bridge project that will transfer data between SalesLogix (OLEDB), Sqlite 3 and Pick/D3. To complete the project, I am looking at ADODB. The vendor that we are dealing with wants me to use Visual Studio 2013 and a .NET language. Most of the business intelligence is already in Php.

Here is my test Php ADODB CLI program:
``` php
<?php
// ADO/OLEDB test using the Saleslogix provider.
require 'adodb/adodb-exceptions.inc.php';
require 'adodb/adodb.inc.php';

$crlf = "\r\n";
   
// connection string
$cs = 'Provider=SLXOLEDB.1;Password=**;Persist Security Info=True;';
$cs .= 'User ID=admin;Initial Catalog=PRIDE;Data Source=CRMAP;';
$cs .= "Extended Properties='PORT=1706;LOG=ON;CASEINSENSITIVEFIND=ON;";
$cs .= "AUTOINCBATCHSIZE=1;SVRCERT=;'";

try
   {
   $db = ADONewConnection('ado');
   $db->debug = true;
   }
catch(exception $e)
   {
   print "ADONewConnection failed$crlf";
   var_dump($e);
   adodb_backtrace($e->gettrace());
   }

try
   {
   $db->Connect($cs);
   }
catch(exception $e)
   {
   print "connect failed$crlf";
   var_dump($e);
   adodb_backtrace($e->gettrace());
   }
?>
```

I am running this on a Windows 7 PC with Php 5.3.10 installed and the most recent release of ADODB. I am trying to connect to the SalesLogix application server. SalesLogix has an OLE provider and I am attempting to use the ADO generic driver on top of that. I should also say that VB .NET is able to connect to the SalesLogix application server using the same connection string as above. When I run my Php program, I get:

```
Host=Provider=SLXOLEDB.1;Password=**;Persist Security Info=True;User ID=admin;Initial Catalog=PRIDE;Data Source=CRMAP;Extended Properties='PORT=1706;LOG=ON;CASEINSENSITIVEFIND=ON;AUTOINCBATCHSIZE=1;SVRCERT=;'
 version=6.1
cs=Provider=SLXOLEDB.1;Password=**;Persist Security Info=True;User ID=admin;Initial Catalog=PRIDE;Data Source=CRMAP;Extended Properties='PORT=1706;LOG=ON;CASEINSENSITIVEFIND=ON;AUTOINCBATCHSIZE=1;SVRCERT=;'
<pre>Provider=SLXOLEDB.1;Password=password;Persist Security Info=True;User ID=admin;Initial Catalog=PRIDE;Data Source=CRMAP;Extended Properties='PORT=1706;LOG=ON;CASEINSENSITIVEFIND=ON;AUTOINCBATCHSIZE=1;SVRCERT=;'
exception 'com_exception' with message 'Source: Microsoft OLE DB Service Components
Description: Format of the initialization string does not conform to the OLE DB specification.' in C:\wamp\www\CRM\Php\adodb\drivers\adodb-ado5.inc.php:117
Stack trace:
#0 C:\wamp\www\CRM\Php\adodb\drivers\adodb-ado5.inc.php(117): com->Open('Provider=SLXOLE...')
#1 C:\wamp\www\CRM\Php\adodb\adodb.inc.php(550): ADODB_ado->_connect('Provider=SLXOLE...', '', '', '')
#2 C:\wamp\www\CRM\Php\crm-test1.php(28): ADOConnection->Connect('Provider=SLXOLE...')
```

My question is: What form does the ADODB connection string have to be in and how can I get this working?

TIA,
Rick

**Comment by dregad** [comment]
Hello and sorry for the delayed response. 

The error message you're seeing is not produced by ADOdb, it is coming from the OLE driver itself. I can't really explain why it works with your .NET client client and not from PHP though (assuming all else being equal of course).

That being said, looking at your connection string, it appears there is a trailing `'`, maybe that's your problem ?

**Comment by Eternal-Infinity** [comment]
@dregad I think that trailing ' it not the problem, it seems to close the "Extended Properties" one line before.

**Comment by dregad** [comment]
Right. Nevermind the quote then. Still, I don't think it's an ADOdb issue.
