### ISSUE TITLE
How to INSERT/UPDATE POINT column

### ISSUE THREAD

**Issue by dezertdezine** [ADOdb/ADOdb#602]
How best to insert/update POINT data? 
e.g.
```mysql
INSERT INTO point_data SET coordinates = POINT(-0.71651, 37.64129);
```
This doesn't work...
```php
$data['coordinates'] = 'POINT(-0.71651, 37.64129)'; 
autoExecute('point_data ', $data, 'INSERT');
```

...is there a work-around?

**Comment by mnewnham** [comment]
Database? ADOdb Version? PHP Version?

**Comment by dezertdezine** [comment]
...sorry - should have said:

Database: MariaDB 10.3
PHP: 7.2
ADOdb: 5.20.14
Driver: PDO

**Comment by mnewnham** [comment]
Is it throwing an error when you do it or is it failing silently?

**Comment by dezertdezine** [comment]
With XDebug and ADOdb debug...
```php
	public function testAutoExecute($data) {
        try {
            $this->db_adodb->debug = true;
            $this->db_adodb->autoExecute('point_data', $data, 'INSERT');
            return $this->db_adodb->Insert_ID();
        } catch (Exception $ex) {
            echo 'Caught exception: ', $ex->getMessage(), "\n";
        }
    }


$data['coordinates'] = 'POINT(-0.72999, 37.12345);';
$imp->testAutoExecute($data);
```

(pdo-): SELECT * FROM point_data LIMIT 1 
 
>( ! ) Warning: Creating default object from empty value in E:\home\dev\lib\adodb\drivers\adodb-pdo.inc.php on line 484
>Call Stack
>###	Time	Memory	Function	Location
>1	0.0111	133040	{main}( )	..\xml_add_property.php:0
>2	0.1689	6869112	import_xml_properties->testAutoExecute( )	..\xml_add_property.php:9
>3	0.1689	6869328	ADOConnection->AutoExecute( )	..\class_import_xml_properties.php:1589
>4	0.1689	6869632	ADODB_pdo->SelectLimit( )	..\adodb.inc.php:2158
>5	0.1689	6869720	ADODB_pdo_mysql->SelectLimit( )	..\adodb-pdo.inc.php:233
>6	0.1689	6870168	ADOConnection->Execute( )	..\adodb-pdo_mysql.inc.php:215
>7	0.1689	6870456	ADOConnection->_Execute( )	..\adodb.inc.php:1246
>8	0.1708	7027832	_adodb_debug_execute( )	..\adodb.inc.php:1266
>9	0.1708	7028336	ADODB_pdo->_query( )	..\adodb-lib.inc.php:1133

>(pdo-mysql): INSERT INTO point_data ( COORDINATES ) VALUES ( 0 )   1416: Cannot get geometry object from data you send to the GEOMETRY field

>ADOConnection._Execute(INSERT INTO point_data ( COORDINATES ) VALUES ( 0 ), false) % line 1246, file: adodb.inc.php
>ADOConnection.Execute(INSERT INTO point_data ( COORDINATES ) VALUES ( 0 )) % line 2182, file: adodb.inc.php
>ADOConnection.AutoExecute(point_data, Array[1], INSERT) % line 1589, file: class_import_xml_properties.php
>import_xml_properties.testAutoExecute(Array[1]) % line    9, file: xml_add_property.php


Way back with Zend Framework 1 you used to be able to do something like this:
```php
$data['coordinates'] = new Zend_Db_Expr("POINT(-0.72999, 37.12345)");
```
...I guess we need something like that for ADOdb

Meanwhile, I suppose I'll need to go with Execute which works OK - e.g.

```php
$sql = "INSERT INTO point_data SET coordinates = POINT(:lng, :lat)";
$data['lng'] = -0.7299;
$data['lat'] = 37.12345;

    function testExecute($sql, $data) {
        try {
            $this->db_adodb->debug = true;
            $this->db_adodb->execute($sql, $data);
            return $this->db_adodb->Insert_ID();
        } catch (Exception $ex) {
            echo 'Caught exception: ', $ex->getMessage(), "\n";
        }
    }
```
	
(pdo-mysql): INSERT INTO point_data SET coordinates = POINT(:lng, :lat)   [ (lng=>'-0.7299') (lat=>'37.12345') ]

**Comment by Mike-Benoit** [comment]
This might be related to #165?
