### ISSUE TITLE
mssqlnative driver has multiple method failures in PHP7.4

### ISSUE THREAD

**Issue by xfnevado1** [ADOdb/ADOdb#608]
when using mssqlnative and when no records are returned, the fetchobj() function returns an error.

**Comment by mnewnham** [comment]
Using Northwnd, with either the current production release or master:

````php
$SQL = "SELECT * FROM orders WHERE shipcountry='CORONA'";
$result = $db->execute($SQL);
print_r($result->fetchObj());
````
Returns an empty recordset which is the expected behavior. Could you post a code snippet with the results please.

**Comment by xfnevado1** [comment]
this code generates error:

$db = NewADOConnection('mssqlnative');
$hostname = "192.XXX.XXX.XXX";
$dbUser = "micros12";
$dbPass = "micros12";
$dbName = "northwind";

$db->Connect($hostname, $dbUser, $dbPass, $dbName);

$category = "";
$sql = "SELECT * FROM categories where CategoryID = ?";
$result = $db->Execute($sql,array($category))->fetchObj();

if ($result === false) 
    die("failed");

echo $result->CategoryName;

**Comment by mnewnham** [comment]
Here are my results using both 5.20 and master, with debug enabled
````php
userid or password supplied, attempting connection with SQL Server Authentication
connecting to host: 192.168.86.100 params: array (
  'ReturnDatesAsStrings' => true,
  'Database' => 'NORTHWIND',
  'UID' => 'user',
  'PWD' => 'password',
  'characterSet' => 'UTF-8',
)
-----<hr>
(mssqlnative): SELECT * FROM categories where CategoryID = ? 
   [ (0=>'')  ]
-----<hr>
running query: 'SELECT * FROM categories where CategoryID = ?'input array: array (
  0 => '',
)result: NULL
````

**Comment by xfnevado1** [comment]
the version used was:
---------------------------------
@version   v5.20.16  12-Jan-2020
@copyright (c) 2000-2013 John Lim (jlim#natsoft.com). All rights reserved.

The code was:
------------------------------
$category = "";
$sql = "SELECT * FROM categories where CategoryID = ?";
$result = $db->Execute($sql,array($category))->fetchObj();

Error generated:
--------------------------------
PHP Notice:  Trying to access array offset on value of type bool in C:\Servidor\PhpProject1\adodb-5.20.16\drivers\adodb-mssqlnative.inc.php on line 897
PHP Stack trace:
PHP   1. {main}() C:\Servidor\PhpProject1\index.php:0
PHP   2. ADORecordset_mssqlnative->FetchObj() C:\Servidor\PhpProject1\index.php:14
PHP   3. ADORecordset_mssqlnative->FetchObject() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4153
PHP   4. ADORecordset_mssqlnative->Fields() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4189
PHP Notice:  Trying to access array offset on value of type bool in C:\Servidor\PhpProject1\adodb-5.20.16\drivers\adodb-mssqlnative.inc.php on line 897
PHP Stack trace:
PHP   1. {main}() C:\Servidor\PhpProject1\index.php:0
PHP   2. ADORecordset_mssqlnative->FetchObj() C:\Servidor\PhpProject1\index.php:14
PHP   3. ADORecordset_mssqlnative->FetchObject() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4153
PHP   4. ADORecordset_mssqlnative->Fields() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4189
PHP Notice:  Trying to access array offset on value of type bool in C:\Servidor\PhpProject1\adodb-5.20.16\drivers\adodb-mssqlnative.inc.php on line 897
PHP Stack trace:
PHP   1. {main}() C:\Servidor\PhpProject1\index.php:0
PHP   2. ADORecordset_mssqlnative->FetchObj() C:\Servidor\PhpProject1\index.php:14
PHP   3. ADORecordset_mssqlnative->FetchObject() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4153
PHP   4. ADORecordset_mssqlnative->Fields() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4189
PHP Notice:  Trying to access array offset on value of type bool in C:\Servidor\PhpProject1\adodb-5.20.16\drivers\adodb-mssqlnative.inc.php on line 897
PHP Stack trace:
PHP   1. {main}() C:\Servidor\PhpProject1\index.php:0
PHP   2. ADORecordset_mssqlnative->FetchObj() C:\Servidor\PhpProject1\index.php:14
PHP   3. ADORecordset_mssqlnative->FetchObject() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4153
PHP   4. ADORecordset_mssqlnative->Fields() C:\Servidor\PhpProject1\adodb-5.20.16\adodb.inc.php:4189

**Comment by xfnevado1** [comment]
the PHP Version was : 
----------------------------------------------
PHP Version 7.4.3

**Comment by mnewnham** [comment]
I think your problem is PHP 7.4. We've done no formal testing on that release yet

**Comment by dfaure57** [comment]
if $category is empty ($category = "";) this will lead to a database error (should be integer? I dont know)

So, $db->Execute($sql,array($category)) does not return recordset object, but false.

Check it before calling a recordset method.

**Comment by mnewnham** [comment]
I've just installed php7.4 the driver is failing on multiple methods
