### ISSUE TITLE
Unexisting file ADORecordSet_assoc_empty.php

### ISSUE THREAD

**Issue by blackscorpionster** [ADOdb/ADOdb#609]
In 2018 I opened this issue:
https://github.com/ADOdb/ADOdb/issues/446#issue-348920033

It was closed because I never responded but I had stopped working on that project anyway.

Recently I started a new project and I wanted to use the library again and found the same issue I  had found in 2018.

The issue occurs in:
adodb.inc.php line 1285
$rs = (class_exists($rsclass)) ? new $rsclass():  new ADORecordSet_empty();

$rsclass contains ADORecordSet_assoc_empty.php but this class does not exists at all.

My proposed solution is: add false as second parameter to class_exists
$rs = (class_exists($rsclass, false)) ? new $rsclass():  new ADORecordSet_empty();

My project is using Autoload and Namespaces.

**Comment by mnewnham** [comment]
There appears to be a way in the way you are initializing the product, as your installation is attempting to load a driver called "assoc", which does not exist.

Could you provide a code snippet, which starts from these lines 
````php
$db = newAdoConnection($driver);
$db->connect($parameters.....);
````
And includes the statement that is generating the error. 

You mention that you are using autoload and spl_autoload_register. Could you explain a little more about how you are trying to use it with ADOdb? be aware that ADOdb really isn't constructed in a way to enable successful autoloading (although we would love it to happen).

**Comment by blackscorpionster** [comment]
Hi, here is an example of how I am using the library:

```
<?php
declare(strict_types=1);

namespace app;

if(!defined('ADODB_ASSOC_CASE')){
	define('ADODB_ASSOC_CASE',1); // 1 UpperCase, 0 LowerCase, 2 As written on the SQL sentence
}

require_once('vendor/adodb/adodb-php/adodb.inc.php');

class Db {
    var $db = null;
    var $host = 'yourHost';
    var $user = 'postgres';
    var $pass = 'yourPass';
    var $driver = 'postgres';
    var $defaultDb = 'yourDb';

    public function __construct() {
        $dbconexion = ADONewConnection($this->driver);
        $dbconexion->setFetchMode(ADODB_FETCH_ASSOC);
        $dbconexion->Connect($this->host, $this->user, $this->pass, $this->defaultDb);
        $dbconexion->EXECUTE("set names 'utf8'");
        $this->db = $dbconexion;
    }
}

```

**Comment by mnewnham** [comment]
This won't work. Because of it's legacy design, you will need to instantiate ADOdb at root level. So

````php


class Db {
    var $db = null;
    var $host = 'yourHost';
    var $user = 'postgres';
    var $pass = 'yourPass';
    var $driver = 'postgres';
    var $defaultDb = 'yourDb';

    public function __construct() {
        
        global $dbconexion;
        $dbconexion->setFetchMode(ADODB_FETCH_ASSOC);
        $dbconexion->Connect($this->host, $this->user, $this->pass, $this->defaultDb);
        $dbconexion->EXECUTE("set names 'utf8'");
        $this->db = $dbconexion;
    }
}
$dbconexion = ADONewConnection($Db::driver);
$db = new Db;
````
Would probably work

**Comment by blackscorpionster** [comment]
Hi, like I said, the issue happens when I do
```
if(!defined('ADODB_ASSOC_CASE')){
	define('ADODB_ASSOC_CASE',1); // 1 UpperCase, 0 LowerCase, 2 As written on the SQL sentence
}
```
The way I instantiate the class works perfectly fine. The issue only occurs here: define('ADODB_ASSOC_CASE',1);

**Comment by mnewnham** [comment]
I've checked your example on multiple databases/php versions and it works fine. I notice that the error messages don't match the code example you provided (line 5 is empty in your example).

The class **_ADORecordSet_empty_** is preloaded in adodb.inc.php, so must exist. In addition it is only called as a fallback if _execute() cannot find a different class.  So in your example. the actual code is failing to find **_ADORecordSet_assoc_empty_**, **then** failing to find **_ADORecordSet_empty_** (adodb.inc.php method _execute(), around line 1285


 One suggestion would be to check that your autoloader can find classes that are pre-loaded by include files. and that these classes are actually in the global scope.

**Comment by mnewnham** [comment]
As we have not heard from you on this, we assume you have resolved it yourself. Feel free to re-open if you need further assistance
