### ISSUE TITLE
ADODB_Active_Record::UpdateActiveTable fails with mixed case column names in ADODB_CASE_NATIVE mode

### ISSUE THREAD

**Issue by f7h** [ADOdb/ADOdb#610]
After the change in #536, some of my code that uses Active Record objects with MySQL and PDO fails.

In `ADODB_pdo_mysql::MetaColumns` column names are converted to upper case. The result of that function is used in `ADODB_Active_Record::UpdateActiveTable`, where the value of `ADODB_ASSOC_CASE` is used to determine the column name of primary keys.

With `ADODB_ASSOC_CASE` = `ADODB_ASSOC_CASE_NATIVE`, the default, this fails now if the actual column name is in lower or mixed case.

Test case `tests/test-pdo-mysql-active-record-update-active-table.php`:
```php
<?php

error_reporting(E_ALL);

include_once __DIR__ . '/../adodb.inc.php';
include_once __DIR__ . '/../adodb-active-record.inc.php';

define('ADODB_ASSOC_CASE', ADODB_ASSOC_CASE_NATIVE);
#define('ADODB_ASSOC_CASE', ADODB_ASSOC_CASE_LOWER);

$db = ADOnewConnection('pdo_mysql://root:@localhost/northwind');
ADOdb_Active_Record::SetDatabaseAdapter($db);

$db->Execute("CREATE TEMPORARY TABLE `people` (`id` int(10) unsigned NOT NULL)");

class Person extends ADOdb_Active_Record{}

new Person('people', array('id'));

var_dump($_ADODB_ACTIVE_DBS[0]->tables['people']->keys);
/*
Expected:
array(1) {
  'id' => string(2) "id"
}

Actual:
array(1) {
  'id' => NULL
}
*/
```

The same problem exists with `ADODB_mysql`, I did not check other drivers.

**Comment by mnewnham** [comment]
In the slightly modified example above, if we set:
````php
$db->Execute("CREATE TEMPORARY TABLE `people` (`idNumber` int(10) unsigned NOT NULL)");
class Person extends ADOdb_Active_Record{}
new Person('people', array('idNumber'));
````
##### ADODB_CASE_NATIVE
Our response should be
````
array(1) {
  'idNumber' => string(2) "idNumber"
}
`````
**This currently fails**
##### ADODB_CASE_LOWER
Our response should be
````
array(1) {
  'idnumber' => string(2) "idnumber"
}
````
**This succeeds**
##### ADODB_CASE_UPPER
Our response should be
````
array(1) {
  'IDNUMBER' => string(2) "IDNUMBER"
}
````
**This succeeds**
