### ISSUE TITLE
Support for UTF-8 in Access

### ISSUE THREAD

**Issue by ThorkilG12** [ADOdb/ADOdb#611]
An Access-table with the value of t.ex. the polish city name Łódź  or the euro sign € is not handled correct. The text is converted to CodePage 1252. I must be UTF-8

With the same driver and the same access-file, it is correct if you go through PowerShell/ODBC

**Comment by dregad** [comment]
Could you provide detailed steps to reproduce the problem, including a code snippet

**Comment by ThorkilG12** [comment]
Hi
My server is Windows 2012r2 - 64bit

Try to echo this in a piece of PHP
echo `bin2hex('*€*Ł*ó*d*ź*');`
You will see that some of the chars is multibyte. The Euro sign is triple-byte.

Hex: 2ae282ac2ac5812ac3b32a642ac5ba2a  ('2a' is the asterix)

Try this in PHP: `strlen('€Łódź');` and this: `mb_strlen('€Łódź'); `
OK ?  (All the mb_<some function> is created by PHP to handle UTF-8 multibyte.)

Now create an access file (extension .accdb) and create a table with a row containing this value: `'€Łódź'`
Read that access-file using the 64bit ODBC driver from Microsoft

Read that data from the access-file into PHP using your ADODB. 

You will only get single-byte characters back. All chars in the data returned, is belonging to codepage 1252 - all the UTF-8 multi-byte chars will be stripped of... :-(

Let me know if you need more details ?

Have a nice weekend :-)

/T

**Comment by mnewnham** [comment]
This needs the setConnectionParameter feature to be added to the odbc driver to call [odbc_setoption](https://www.php.net/manual/en/function.odbc-setoption.php)

**Comment by mnewnham** [comment]
Actually, just thinking about it, you simply need to specify a DSN style connection, something like:

````php
 
$dsn = "Driver={Microsoft Access Driver (*.mdb)};Dbq=d:\\northwind.mdb;Uid=Admin;Pwd=;Client_CSet=UTF-8";
$db->Connect($dsn);
````

**Comment by ThorkilG12** [comment]
You are using an old driver. I cannot read .accdb files.
Setting the ClientCSet does not help.
Please have a look here: https://stackoverflow.com/questions/32213506/how-to-use-php-pdo-odbc-with-sql-server-and-unicode-characters/60996874#60996874

**Comment by mnewnham** [comment]
The issue you pointed us to clearly states that the problem is with PHP

> OK... The 'Advanced Query Tool' also proved that it is possible to get the MS Drivers to deliver the double-byte UTF-8 polish characters through ODBC.

> It is so sad to realize, that the mighty PHP 7.4 is unable to treat ODBC correct :-(

So if PHP cannot do it, then ADOdb cannot, because it is simply an abstraction layer over the top of PHP. Once PHP can provide this capability, then we can see if there is any feature enhancement required by our software

**Comment by mnewnham** [comment]
As we have not heard from you on this, we assume you have resolved it yourself. Feel free to re-open if you need further assistance
