### ISSUE TITLE
mssqlnative class shut down too early to retrieve error messages

### ISSUE THREAD

**Issue by giopk** [ADOdb/ADOdb#614]
Crazy bug. If you have a statement generating an error, like a key violation, and a subsequent successful statement ErrorLog reports an empty error even if called before the successful statement.
You can replicate it with this code:

		<?php
		/* Create this table:
		CREATE TABLE TEST (
		KEYFIELD VARCHAR(20) NOT NULL,
		PRIMARY KEY (KEYFIELD)
		);
		 */

		require_once 'vendor/adodb/adodb-php/adodb.inc.php';
		$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;
		$ADODB_COUNTRECS = false;
		$conn = adoNewConnection('mssqlnative');
		$conn->PConnect('localhost', 'sa', 'pwd', 'database');
		if (!$conn) {die($conn->ErrorMsg());}

		$sql = 'DELETE FROM TEST';
		$rs = $conn->Execute($sql);
		if (!$rs) {echo 'Error: ' . $conn->ErrorMsg();}

		$sql = 'INSERT INTO TEST VALUES (?)';

		$rs = $conn->Execute($sql, ['test']);
		if (!$rs) {echo 'Error: ' . $conn->ErrorMsg();}

		$rs = $conn->Execute($sql, ['test']);
		if (!$rs) {echo 'Error: ' . $conn->ErrorMsg();}

		// If you remove these two lines you see the difference
		$rs = $conn->Execute($sql, ['test2']);
		if (!$rs) {echo 'Error: ' . $conn->ErrorMsg();}

As a quick fix you can add a coll to ErrorMsg() code at the end of 

		if (!$rez) {
			$rez = false;
			$this->ErrorMsg(); // add this
		}

**Comment by mnewnham** [comment]
Is this master or 5.20?

**Comment by giopk** [comment]
Both. And the (bad) fix is the same for both.

**Comment by mnewnham** [comment]
The problem is actually limited to insert statements. I believe it is associated with the **`select scope_identity`** we append to the statement to retrieve the insert id from stored procedures

**Comment by giopk** [comment]
No, I removed the scope_identity code and nothing changes.
What's disconcerting is that the subsequent statement influences the ErrorMsg call which should have been finished well before the second statement is executed.

**Comment by mnewnham** [comment]
The problem is a combination of 2 things, the first is that the recordset class is being shut down too early to retrieve the messages, see #590, with a combination of the fact that you are using SQL Server auto-commit. If you define a [Transaction Handling Method](http://adodb.org/dokuwiki/doku.php?id=v5:userguide:transactions) your code should work ok

**Comment by giopk** [comment]
> If you define a [Transaction Handling Method](http://adodb.org/dokuwiki/doku.php?id=v5:userguide:transactions) your code should work ok

Nope, my actual code uses transaction handling, I've removed it from the sample to reduce size
