### ISSUE TITLE
Session expiring after 18 hours (Session Management) regardless of ini_settings();

### ISSUE THREAD

**Issue by mariobernheim** [ADOdb/ADOdb#615]
Hi, I'm using:

`[root@www pub]# php -v
PHP 7.2.30 (cli) (built: Apr 15 2020 07:23:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies`

with ADODB

`@version   v5.20.17  31-Mar-2020`

These are the settings:
```
include_once "adodb5/session/adodb-session2.php";
ADOdb_Session::config("mysqli", $config['db_host'], $config['db_user'], $config['db_pass'], $config['db_name'],$options=false);

ADOdb_Session::lifetime(intval('2592000'));
ini_set('session.name', 'myapp');
ini_set('session.use_cookies', 1);
ini_set('session.use_only_cookies', 0);
ini_set('session.gc_maxlifetime', intval('2592000'));
ini_set('session.cookie_lifetime', intval('2592000'));
session_start();
```

however the expiration on the session won't go past 18 hours... causing users to have to sign back in

check image:

![Screen Shot 2020-05-18 at 8 41 40 AM](https://user-images.githubusercontent.com/37424461/82227429-f8103a80-98e4-11ea-8444-95f1c724fba2.png)

**Comment by mnewnham** [comment]
Is this a new implementation or has this behavior changed? 
have you updated your PHP version or anything like that? 
Not sure what the image shows. Is it that the expiry date/time wont go beyond 18 hours or that it is set beyond that but expires anyway.

**Comment by mnewnham** [comment]
As I have not had a response from you on this I assume you have resolved the problem yourself. However feel free to reopen the issue if you need further help
