### ISSUE TITLE
Not catching exception on duplicate entry

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#616]
Not sure what I am doing wrong.  I have an insert that causes a duplicate entry. I get 
Quier failed
1062 Duplicated entry

Perfect, But  is not being catched.   this function returns true like nothing happened,unless I check the ErrorNo() after the call.  Why is not being catched?

I am using composer("adodb/adodb-php": "^5.20",).  Do I need to pass a parameter to get exceptions to work?

 try {
           
            $sql = "";
            $stmt = $this->cn->Prepare($sql);
            $this->cn->Execute($stmt, array());
            $newID = $this->cn->Insert_ID();

          //THIS WORK IF UNCOMMENTED
          // if ($this->cn->ErrorNo() == '1062')
             //   return array(false, '', 'E_DB_DUPLICATE', '');

            return array(true, $newID, '', '');

        } catch (Exception $e) {
             //THIS DOES NOT GET CALLED, WHY????????

               if ($this->cn->ErrorNo() == '1062')
            return array(false, '', 'E_DB_DUPLICATE', $e->getMessage());

       
            return array(false, '', 'E_DB_ERROR', $e->getMessage());
        }

**Comment by mnewnham** [comment]
Easy first question

Are you using **`adodb-exceptions.inc.php`** as your exceptions handler or have you rolled your own?

**Comment by stccorp** [comment]
isnt that file included automatically when you use composer?

**Comment by mnewnham** [comment]
I didn't build the composer distribution and don't use composer myself for distributions but I would say not because It conflicts with the normal error handling. @dregad , can you confirm this?

**Comment by mnewnham** [comment]
Ok, just quickly checked the installation via composer. You've definitely got to maually add **`adodb/adodb-exceptions.inc.php`** to your code, because neither that nor the the more commonly used **`adodb/adodb-errorhandler.inc.php`** are autoloaded via the composer built loaders

**Comment by stccorp** [comment]
Is there a reason why is not being done automatically?  Why will you not use exceptions for error handling?

**Comment by mnewnham** [comment]
If you use composer the correct directory is going to be **`adodb/adodb-php/adodb-exceptions.inc.php`**

The reason that its not done automatically is that ADOdb  is seriously  legacy code (>20 years) and that exceptions handling has been  back-filled in at some point. but many people still use the old style error trapping mechanisms, Exceptions is incompatible with that so you have to manually choose which method you want

**Comment by stccorp** [comment]
Thank you
