### ISSUE TITLE
adodb 5.20.17 - easyphp 5.3.8.1 

### ISSUE THREAD

**Issue by okpapt** [ADOdb/ADOdb#617]
Hello,
Sorry for my poor english.
I have this :
Fatal error: Call to undefined method ADORecordSet_mysql::ADORecordSet() in adodb\drivers\adodb-mysql.inc.php on line 615
database in mysql works fine.
I do not know adodb and do not exactly understand class and object. (I am old, long time ago I learn cobol and qbasic)
I try to use simple agenda 2.2.12.
I have made fews change about date in my langage in index.php, that's all !

**Comment by mnewnham** [comment]
I would recommend reviewing your code against the way the system is setup in [this tutorial](https://adodb.org/dokuwiki/doku.php?id=v5:userguide:learn_abstraction:establishing_connection). 

Its also very helpful if you post PHP version, platform and ADOdb driver

**Comment by okpapt** [comment]
Windows 7
PHP 5.3.8 VC9
Apache 2.2.21 VC9
MySQL 5.5.16
PhpMyAdmin 3.4.5
Xdebug 2.1.2

in title I wrote :
adodb 5.20.17 - easyphp 5.3.8.1

I can connect and make requete "select * from table".

**Comment by mnewnham** [comment]
I'd guess you are using the old 'mysql' driver, not the 'mysqli'. That's what I really meant when I asked you what driver you were using. You could post the section of code where you include the adodb drivers, that might help.  Please recognize that using a version of PHP that was end-of-life 6 years ago makes it difficult to determine solutions. Reviewing the "easyphp" site I notice that the current product devserver version 17 supports PHP7. You should consider using that instead.

**Comment by okpapt** [comment]
If I change to php 7, I need rewrite entire script of  "simple agenda 2.2.12" .
It is too hard for my mind.
https://phpsources.net/phpsources.net_Simple-PHP-Agenda-2.2.12_727-1.zip
or
https://sourceforge.net/projects/php-agenda/files/php-agenda/
Inside this pack is Version 2.1, February 1999 of adodb.
Of course I replace it by adodb 5.20.17.

In index.php 
include ('adodb/adodb.inc.php');
$db = ADONewConnection('mysql');
$db->Connect($dbhost, $dbuser, $dbpass, $dbname);
$db->debug = false;

If you have best agenda and free, I am ok to follow your link.

**Comment by mnewnham** [comment]
please use 
````php
$db = new ADOConnection('mysqli');
````
The old 'mysql' driver is no longer supported by PHP

**Comment by okpapt** [comment]
At line 3 in index.php, 

with original :  $db = ADONewConnection('mysql');
start and show in generated page :
**Fatal error: Call to undefined method ADORecordSet_mysql::ADORecordSet() in D:\EasyPHP-5.3.8.1\www\php-agenda-2.2.12\adodb\drivers\adodb-mysql.inc.php on line 615**

with :  $db = ADONewConnection('mysqli');
only :
**Warning: require(ADODB_mysqli.php) [function.require]: failed to open stream: No such file or directory in D:\EasyPHP-5.3.8.1\www\php-agenda-2.2.12\config.inc.php on line 3
Fatal error: require() [function.require]: Failed opening required 'ADODB_mysqli.php'** 

with :  $db = new ADONewConnection('mysqli');    or    $db = new ADONewConnection('mysql');
only : 
**Warning: require(ADONewConnection.php) [function.require]: failed to open stream: No such file or directory in D:\EasyPHP-5.3.8.1\www\php-agenda-2.2.12\config.inc.php on line 3
Fatal error: require() [function.require]: Failed opening required 'ADONewConnection.php'**


I search in all my computer, I have not theese files : ADODB_mysqli.php , ADONewConnection.php


config.inc.php first lines :
<?php
function __autoload($class_name) {
	require $class_name . '.php';
}
$dbhost = 'localhost';
$dbname = 'mydbname';
$dbuser = 'mynameuser';
$dbpass = 'mypassword';
$dbprefix = 'agenda_';
.../...
?>

**Comment by mnewnham** [comment]
I have no idea how easyphp works, or this bestagenda product, but you cannot autoload ADOdb classes. The autoloading is trying to find ``ADONewConnection.php``  , and that file does not exist, because the actual class is in adodb.inc.php. If ADOdb is already included, you could try changing your code as follows:

````php
function _autoload()
    if (!class_exists($class_name))
        require $class_name . '.php';
}
````

If that does not work, I recommend contacting the easyphp/bestagenda provider. The problem is the way that product is accessing ADOdb, not ADOdb itself.

Good luck with your search to solve this issue
