### ISSUE TITLE
get_magic_quotes_gpc is deprecated since 7.4

### ISSUE THREAD

**Issue by jomiquel** [ADOdb/ADOdb#619]
Source code has several places where get_magic_quotes_gpc function is called, and this function is deprecated since PHP 7.4.
```
adodb/adodb-php/adodb-perf.inc.php:699
adodb/adodb-php/adodb.inc.php:865
adodb/adodb-php/server.php:57
```

Since function returns FALSE since 5.4, I propose code checks the PHP version before call get_magic_quotes_gpc in some way. If PHP version is grater or equals than 5.4 get false, else get get_magic_quotes_gpc().

**Comment by mnewnham** [comment]
will probably add PHP_MAJOR_VERSION to 5.20 and remove from master
