### ISSUE TITLE
5.20.18 wrong link to changelog

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#620]
Maybe because it was released with tag '5.20.18' instead 'v5.20.18'?

Also 'Current Production Release' on adodb.org not yet updated.

**Comment by mnewnham** [comment]
Fixed

**Comment by dregad** [comment]
I retagged [v5.20.18](https://github.com/ADOdb/ADOdb/releases/tag/v5.20.18) with a signature, and removed the invalid _5.20.18_ tag.

@mnewnham For future reference, please note that I have fully [documented the process for new releases](https://adodb.org/dokuwiki/doku.php?id=admin:release_process).

**Comment by mnewnham** [comment]
Unfortunately, these tools require

1. Linux
2. Python
3. Git command line tools

Also, what is the value of continuing to upload to sourceforge?
