### ISSUE TITLE
Connection to SQL DATABASE

### ISSUE THREAD

**Issue by jmldsilva** [ADOdb/ADOdb#621]
Hello 
i have an webserver in OSXCatalinia with PHP 7.4.8 and MSSQLdrivers 5.8.1 and  cannot connect to any MSSQL database, an MYSQL DB everything is OK.
I recive one warning :Warning: sqlsrv_query() expects parameter 1 to be resource, bool given in ......./adodb-mssqlnative.inc.php on line 579;
and the error connection :-14: SQLState: IMSSP Error Code: -14 Message: An invalid parameter was passed to sqlsrv_query. 

In windows IIS server I use php 7.4.1 and mssql drivers 5.8 and everything is ok,
In MAC I use several versions of PHP and Drivers for trying and nothing, still not successful connection

I use your last version 5.20.18, and I used for years, can you help me, please.
 

Regards 

Jorge, Portugal

**Comment by dregad** [comment]
> I use your last version 5.20.18, and I used for years, can you help me, please.

Does this mean that your code was working with earlier versions, and it now fails with 5.20.18 ?

Please provide a code snippet to reproduce the problem.

**Comment by mnewnham** [comment]
As we have not heard from you on this issue, we assume that you have resolved it yourself. If you need help on this, feel free to re-open
