### ISSUE TITLE
mssqlnative: Connect on a specified port.

### ISSUE THREAD

**Issue by sigurdne** [ADOdb/ADOdb#624]
The port information is missing.
One will need to set the port - if anything else than standard.

Something like this in the function ADODB_mssqlnative::_connect()

`		if (!empty($this->port))
		{
			$argHostname .= ", $this->port";
		}
`

Regards

**Comment by dregad** [comment]
This is included in upcoming 5.21.0 release, see #314

**Comment by sigurdne** [comment]
Yes, that is true for ADODB_mssql,  but I can't see it in ADODB_mssqlnative.

Regards

**Comment by dregad** [comment]
Right, sorry... So not a duplicate then.

@mnewnham as I don't use mssql, would appending the port number to the hostname before calling sqlsrv_connect() at line 493, like so, be sufficient ?

```php
if (!empty($this->port)) {
    $argHostname .= "," . $this->port;
}
```

**Comment by mnewnham** [comment]
Yes, absolutely. I think I've done this before. I think I've not done anything official because unlike most connections , its **server,port** instead of **server:port**. It doesn't appear to be a widely used option either.

**Comment by mnewnham** [comment]
Will appear in 5.20.19
