### ISSUE TITLE
PostgreSQL JSON/JSONB datatype support

### ISSUE THREAD

**Issue by Benjaminhu** [ADOdb/ADOdb#626]
> PostgreSQL supports native JSON data type since version 9.2. It provides many functions and operators for manipulating JSON data. ([via](https://www.postgresqltutorial.com/postgresql-json/))

Data Types: [JSON Type](https://www.postgresql.org/docs/9.2/datatype-json.html), [JSON Functions](https://www.postgresql.org/docs/9.2/functions-json.html#FUNCTIONS-JSON-TABLE)

**Comment by mnewnham** [comment]
I have added support for json datatypes in my upcoming enhancements

**Comment by dfaure57** [comment]
Hi Mark,

I'm using 5.23.0. And needed to update JSONB fields, so I modified locally adding a few lines as follow:

/ADOdb-5.23.0/drivers/adodb-postgres64.inc.php, line 1193
			case 'JSON':
			case 'JSONB':
				return 'J';

/adodb/ADOdb-5.23.0/adodb-lib.inc.php
			case "J":
				$val = "'{$arrFields[$fname]}'";
				break;

This supports well JSON made with `json_encode` using `JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_FORCE_OBJECT` flags
