### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#628]
Many thanks for Adodb - it's still so usefull for many of my projects. 
Could you please help me with a question on the repository. 

I have installed Adodb via composer. I am not sure which version was installed - most files are tagged with @version v5.20.0 28-Nov-2015 ... for example adodb.inc.php

Here, on Github - if I check adodb.inc.php it is tagged with "@version v5.21.0-dev ??-???-2016"

So this rises 2 questions for me:

- Which repo should I use to get the latest version
- Is the master branch a production branch (doesn't look like that if I look at the version tags)
- And if not where can I download the latest stable release?

It would be very helpful to have releases on Github
https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by geri777** [comment]
For composer I found a solution. Not really good, but it work as long as there are no breaking changes.

First I install the current version from the repo:

`composer require adodb/adodb-php`

Then I edit my composer.json file and run "`composer update`"

```
{
    "repositories": [
        {
            "url": "https://github.com/ADOdb/ADOdb.git",
            "type": "git"
        }
    ],
    "require": {
        "adodb/adodb-php": ">=5.20",
    }
}
```

**Comment by dregad** [comment]
> I am not sure which version was installed

`composer require adodb/adodb-php` installs 5.20.18, which is the latest stable version.

You can confirm this with

```
$ composer show
adodb/adodb-php v5.20.18 ADOdb is a PHP database abstraction layer library
```

> Then I edit my composer.json file

Not really sure why you would want to do that, but your custom composer.json should still install 5.20.18.

> Which repo should I use to get the latest version

https://github.com/ADOdb/ADOdb is the official repository.
https://packagist.org/packages/adodb/adodb-php links to it.

> Is the master branch a production branch

_master_ is the development branch.

> where can I download the latest stable release

If you mean tarballs, you can download them from SourceForge, see https://adodb.org

> It would be very helpful to have releases on Github

Indeed. And we do have 46 of them right here https://github.com/ADOdb/ADOdb/releases
