### ISSUE TITLE
Transaction Handling doesn't work

### ISSUE THREAD

**Issue by bese1408** [ADOdb/ADOdb#629]
Hi!

I tried to use transaction handling, but when for example my third insert crushes, the previous inserts (or updates) don't rollback.
I use PHP7.1 and Oracle11g.
Sorry my English.
Can anybody help me?

Thanks: Tamás

**Comment by dregad** [comment]
I assume that you closed the issue because you managed to resolve your problem. 

Just in case, and for future reference, here is the documentation explaining how to use transactions with ADOdb
https://adodb.org/dokuwiki/doku.php?id=v5:userguide:transactions

**Comment by bese1408** [comment]
Thank you for the response, it was so helpful. I was a little bit inattentive. Now I'm successfully using transactions.

**Comment by peterdd** [comment]
The **Usage** example on https://adodb.org/dokuwiki/doku.php?id=v5:userguide:transactions seems wrong. Either wrong indentation or missing single statement for the first else. Adding {} for the if and else should clarify the example.

**Comment by dregad** [comment]
> The **Usage** example on https://adodb.org/dokuwiki/doku.php?id=v5:userguide:transactions seems wrong. Either wrong indentation or missing single statement for the first else. Adding {} for the if and else should clarify the example.

Fixed.

**Comment by dregad** [comment]
@peterdd as I recall you have access to the wiki, feel free to make such changes directly.
