### ISSUE TITLE
adodb-memcache.lib.inc.php v5.20.18  // do we have memcache or memcached?

### ISSUE THREAD

**Issue by b247** [ADOdb/ADOdb#631]
Hi, I need to use php-memcache**d** extension but the adodb-memcache.lib.inc.php failed on cacheExecute (no memcache**d** support, only memcache - memcache PECL not found)
I've managed this by using adodb-memcache.lib.inc.php from v5.21 branch, can memcached support be added to 5.20 branch?

**Comment by dregad** [comment]
> can memcached support be added to 5.20 branch?

_memcached_ support has been implemented in #322. There are no plans to backport that to the 5.20.x branch, which only supports _memcache_ (no `d`).

5.21 (master) branch should be pretty stable, so feel free to use that; I've been planning to release 5.21.0 for quite some time now, but never seem to find the time to actually get around to it :weary:
