### ISSUE TITLE
Notice on ADODB_mssqlnative->ErrorNo()

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#637]
I get the following notice when I query for error using the ErrorNo() method in the ADODB_mssqlnative class.

`<b>Notice</b>:  Trying to access array offset on value of type null in <b>\vendor\adodb\adodb-php\drivers\adodb-mssqlnative.inc.php</b> on line <b>468</b><br />`

Looking at that class I see (line 468):

```
	function ErrorNo()
	{
		$err = sqlsrv_errors(SQLSRV_ERR_ALL);
		if($err[0]) return $err[0]['code'];
		else return 0;
	}
```

The notice disapears when I change line 468 to this one:
`
if($err && $err[0]) return $err[0]['code'];
`

**Comment by mnewnham** [comment]
What version of php are you using?

**Comment by geri777** [comment]
Hi Mark, I am using 7.4.6

**Comment by mnewnham** [comment]
Will appear in 5.20.19
