### ISSUE TITLE
Composer reported version

### ISSUE THREAD

**Issue by FrancescoGd** [ADOdb/ADOdb#638]
Hi, I'm a long time user of ADODB, so thank you for many years (something like 15 years) of usefulness 🙂
I get a strange behavior from Composer: when I check for updates it reports an update which isn't really an update, as you can see it only has a 'v' prepended:
![composer_adodb](https://user-images.githubusercontent.com/32357315/96115171-d42e4080-0ee6-11eb-96bf-cf757031fb74.png)
Of course trying to run an update of the package updates nothing.
I'm using "Composer version 1.9.2 2020-01-14 16:30:31"

**Comment by dregad** [comment]
There was a problem with tagging when 5.20.18 was released (see #620), that probably explains it.

The correct version number is `v5.20.18`, the invalid `5.20.18` tag has been removed, and is no longer available on Packagist
https://packagist.org/packages/adodb/adodb-php#v5.20.18

**Comment by FrancescoGd** [comment]
Ah ok, thanks, #620 escaped me because I searched the issues for "composer". So it'll be automatically fixed with the next release, I suppose?

**Comment by dregad** [comment]
There is nothing to be fixed from our end other than what we've already done, and I'm not sure what will or will not happen as the next version is released - that's Packagist / Composer magic over which we have zero control.

As I'm not seeing the behavior you describe, I'm afraid there is not much more I can do unless you can provide steps to reproduce.

**Comment by davidsneighbour** [comment]
Try running `composer clearcache` to force an update from Packagist.

**Comment by FrancescoGd** [comment]
@dregad  the only step to reproduce is running `composer outdated`, at least for me, so I can't be more specific, sorry... thank you for your explanation anyway
@davidsneighbour that didn't work sadly, it doesn't update despite clearing the cache and I still have that behaviour, thank you for having a look
I'll wait for the next release and see what happens, it's not a big deal atm, thank you all.

**Comment by dregad** [comment]
I'm guessing this is behavior caused by your composer.lock file. Maybe you can try to run `composer update --lock` ?

If that does not help, maybe you could post your composer.* files

**Comment by FrancescoGd** [comment]
Sadly it didn't work either... here are my composer files, thanks

[composer-files.zip](https://github.com/ADOdb/ADOdb/files/5408654/composer-files.zip)

**Comment by dregad** [comment]
OK so it is as I thought, you have `"version": "5.20.18"` in the composer.lock file. With this I was able to reproduce the problem:

```console
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing adodb/adodb-php (5.20.18): Loading from cache
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
$ composer outdated adodb*
adodb/adodb-php 5.20.18 v5.20.18 ADOdb is a PHP database abstraction layer library
```

The fix:
- Option 1
    ```console
    $ composer remove adodb/adodb-php
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 0 installs, 0 updates, 1 removal
      - Removing adodb/adodb-php (5.20.18)
    [...]
    $ composer require adodb/adodb-php
    Using version ^5.20 for adodb/adodb-php
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 1 install, 0 updates, 0 removals
      - Installing adodb/adodb-php (v5.20.18): Loading from cache
    [...]
    ```
- Option 2
    ```console
    $ sed -i -r "s/5.20.18/v\0/" composer.lock      # Or manually edit the file to add the `v` before 5.20.18
    $ rm -rf vendor/adodb/
    $ composer install
    Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
    Package operations: 1 install, 0 updates, 0 removals
      - Installing adodb/adodb-php (v5.20.18): Loading from cache
    [...]
    ```

Confirming the problem's gone
```console
$ composer outdated adodb*
$ composer outdated adodb* -a
adodb/adodb-php v5.20.18 v5.20.18 ADOdb is a PHP database abstraction layer library
```

**Comment by FrancescoGd** [comment]
@dregad I went with option 1 because it's similar to when you install it for the first time and I thought it could be more helpful for someone else having the same problem... and it worked fine!
Thank you so much for your patience and support 🙂

Have a nice day,
F.
