### ISSUE TITLE
get_magic_* functions: PHP 7.4 and PHP 8.0 compatibility

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#643]
- get_magic_quotes_runtime(), since PHP 5.4.0 returns always FALSE, deprecated by PHP 7.4, removed by PHP 8.0
- get_magic_quotes_gpc(), since PHP 5.4.0 returns always FALSE, deprecated by PHP 7.4, removed by PHP 8.0

```
# grep -rin get_magic
drivers/adodb-oci8.inc.php:1504:	 * @param bool $magic_quotes if $s is GET/POST var, set to get_magic_quotes_gpc().
drivers/adodb-mssql.inc.php:173:	* @param [magic_quotes]    if $s is GET/POST var, set to get_magic_quotes_gpc().
drivers/adodb-mysqli.inc.php:229:	 *     then pass get_magic_quotes_gpc() as the second parameter. This will
drivers/adodb-mysqli.inc.php:232:	 *     Eg. $s = $db->qstr(_GET['name'],get_magic_quotes_gpc());
adodb-perf.inc.php:699:	if (isset($_GET['sql']) && get_magic_quotes_gpc()) {
adodb-perf.inc.php:1005:	if (get_magic_quotes_gpc()) {
server.php:57:	if (get_magic_quotes_gpc()) {
adodb.inc.php:865:		return $this->qstr($s,get_magic_quotes_gpc());
adodb.inc.php:2067:				if (get_magic_quotes_runtime() && !$this->memCache) {
adodb.inc.php:2975:	 * @param [magic_quotes]	if $s is GET/POST var, set to get_magic_quotes_gpc().
adodb-csvlib.inc.php:251:			if (get_magic_quotes_runtime()) $err .= ". Magic Quotes Runtime should be disabled!";
adodb-xmlschema03.inc.php:1411:		$this->mgq = get_magic_quotes_runtime();
adodb-xmlschema.inc.php:1307:		$this->mgq = get_magic_quotes_runtime();
```

**Comment by peterdd** [comment]
Ups, partly duplicate of #619, but changes required also for xmlschema stuff and not just deprecation anymore.

**Comment by peterdd** [comment]
What is the minimal version current stable ADOdb version wants to work with?

If it is PHP 5.4+, I would like to get rid of magic_quotes stuff in adodb-xmlschema03.inc.php and remove $mgq from class adoSchema.

**Comment by mnewnham** [comment]
Unfortunately the minimum support for 5.20 is still PHP version 5.3, but you could make rlthe changes for the master branch

**Comment by peterdd** [comment]
So could you upgrade php:">=5.4.0" in composer.json of master branch?

**Comment by peterdd** [comment]
Do you prefer another PR that is compatible with PHP 5.3.2 and PHP 8 for 5.20.* (and show no notice on PHP 7.4)?
I could do that, but thought its ok to remove that magic_quotes stuff as cleanup.

**Comment by dregad** [comment]
We should keep the PHP 5.3 minimum requirement in 5.20, but I'm fine with bumping it in 5.21.0. 

A conservative option would be 5.5.9 (bundled in oldest supported Ubuntu LTS release 14.04).

**Comment by peterdd** [comment]
Ok, I do PR for 5.3+

**Comment by dregad** [comment]
I bumped the minimum PHP version to 5.5.9 in master branch, committed just now (see #654).

**Comment by peterdd** [comment]
Ok, so you can commit existing PR #644 to 5.21 master? 
And for 5.20 just patch it to support PHP7.4 (php notice) and PHP8(php error)?

**Comment by peterdd** [comment]
I made two separate PR #657 for 5.20 (PHP5.3-PHP7.4) and PR #658 master branch (>=PHP5.4)

Not sure what  the difference between &$parser and $parser is.
Seems to work both for PHP5.*-PHP7.* . Is PHP figuring it out for us?

**Comment by dregad** [comment]
As the 2 linked PRs have been merged, I believe this can be closed now.
