### ISSUE TITLE
current release 5.20.18 version() still shows 5.20.17

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#645]
from 5.20.18:

adodb.inc.php:227:		$ADODB_vers = 'v5.20.17  31-Mar-2020';

**Comment by pwaring** [comment]
Still an issue in 5.20.19 (noticed it when upgrading today and examining the git diff).

**Comment by dregad** [comment]
@peterdd Unfortunately I cannot go back in time and re-tag 5.20.18, but with 5.20.19 out now, I guess this is no longer an issue.

@pwaring can you please double-check, as I finalized the release on 16-Dec and as far as I can tell everything is in order https://github.com/ADOdb/ADOdb/blob/v5.20.19/adodb.inc.php#L227 (although the initial release preparation from 15-Dec was indeed wrong)

**Comment by pwaring** [comment]
@dregad I downloaded the 5.20.19 zip release on 17th December and it had this problem:

```
ls -l adodb-5.20.19.zip
-rw-rw-r-- 1 paul paul 573326 Dec 17 09:59 adodb-5.20.19.zip
```

```
cat -n includes/adodb5/adodb.inc.php | grep _vers 
    70			$ADODB_vers,		// database version
   198			$ADODB_vers,		// database version
   227			$ADODB_vers = 'v5.20.17  31-Mar-2020';
   544			global $ADODB_vers;
   553			if (!preg_match("/$regex/", $ADODB_vers, $matches)) {
   556				self::outp("Invalid version number: '$ADODB_vers'", 'Version');
   558				preg_match("/$regex/", $ADODB_vers, $matches);
```

All the other references to the version number (e.g. in `@version`) were correct, but `$ADODB_vers` jumped out at me when examining the git diff.

**Comment by pwaring** [comment]
I've also just re-downloaded the zip file now and it still has the same issue.
