### ISSUE TITLE
File moved to subfolder returns blank page in browser

### ISSUE THREAD

**Issue by carvehicledb** [ADOdb/ADOdb#65]
Hello,

I have an issue with adodb that I am not able to resolve for days now. Maybe someone has experienced the same issue:
I need to move a file from the root directory to a subfolder. All code is correct and links to include files work without any issue. There are no php errors either.

However, when I run the file from the new location I just get a blank page.

Any ideas or suggestions?

**Comment by dregad** [comment]
Since you have not responded to my earlier message, I'm closing this issue. Feel free to reopen it with the requested information.
