### ISSUE TITLE
DSN database connection with password containing # fails

### ISSUE THREAD

**Issue by itelligence** [ADOdb/ADOdb#651]
When trying to connect to a MySQL database with password that contain a hash symbol adodb will fail to connect due to parse_url failing to parse the connection string and will return nothing.

vendor/adodb/adodb-php/adodb.inc.php
Line:808
`$dsna = @parse_url($fakedsn);`

e.g. fake://username:Passw#0rd@localhost/db?new will fail as parse_url will fail to parse each part of the given url.

**Comment by peterdd** [comment]
Reproduced it with 5.21.0.dev

Until fixed, you can workaround by using 

```
$driver='mysqli';
$db= adoNewConnection($driver);
$db->connect('localhost', 'user', 'passw#rd', 'adodbtest');
```

instead of 

```
$driver='mysqli';
$dsn = 'user:passw#rd@localhost/adodbtest';
$db = adoNewConnection($driver . '://' . $dsn);
```

**Comment by mnewnham** [comment]
Will appear in hotfix 5.20.19
