### ISSUE TITLE
adodb.org edit history not visible?

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#652]
I miss the edit history of the articles on adodb.org

**Comment by peterdd** [comment]
I mean the 'Recent Changes'.

**Comment by mnewnham** [comment]
Works fine for me. Is there something in particular you can't see

**Comment by peterdd** [comment]
For a visitor it looks like nothing was changed since 2017.

Better would be IMHO if for instance always the last 20 changes are shown.

![adodborg_recentchanges](https://user-images.githubusercontent.com/1839154/101651404-52b5e300-3a3d-11eb-9827-98539af091dc.png)

**Comment by mnewnham** [comment]
Because of the way I am bulk updating pages using both ftp and rpc synchronization the update history is going to be disrupted for the foreseeable future. Sorry about that.
