### ISSUE TITLE
adodb.org documentation close(), question

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#665]
from https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:close

`This function, when called either as $database→close() or $recordset→close(), shuts down the database connection object, which cannot be re-established for the remainder of the script.
`

I think the statement there is not correct. 

$recordset→close() does not close the database connection and should not do it by default.

At least I needed the $recordset->close() for executing different queries as the same variable for testing mysqli #663 ..

(just quick typed to remember before end of year night shift.)

**Comment by dregad** [comment]
I updated the documentation.
