### ISSUE TITLE
Drop the contrib/toxmlrpc.inc.php file

### ISSUE THREAD

**Issue by gggeek** [ADOdb/ADOdb#671]
Original author of that file here.
I think that it is safe to drop it from the library as it has been unmaintained for ages.
Also:
- the current version of the phpxmlrpc library is now at a new major version, and has a different api
- it does not make too much sense to distribute toxmlrpc.inc.php without requiring/distributing phpxmlrpc.inc as well
- for those interested in using adodb as part of xmlrpc servers, or even as a full-fledged proxy driver (similar to the built-in rest proxy one) it might be easier to download the phpxmlrpc/extras package, which has been dormant for a while but is getting refreshed these days. I might even externalize the adodb-phpxmlrpc bridge to its own standalone package :-)

**Comment by dregad** [comment]
@gggeek thanks for the update. 

No objections to remove this from my side. 
@mnewnham thoughts ? Target 5.21 ?

We should also get rid of the [wiki page](https://adodb.org/dokuwiki/doku.php?id=v5:addons:xmlrpc) or at least mention that the feature has been removed.

> I might even externalize the adodb-phpxmlrpc bridge to its own standalone package :-)

Let us know if you do, so we can reference it.

**Comment by gggeek** [comment]
@dregad is there a git repo/branch to update the docs ?

**Comment by gggeek** [comment]
PR: https://github.com/ADOdb/ADOdb/pull/673

**Comment by dregad** [comment]
> is there a git repo/branch to update the docs ?

No, they are maintained in a stand-alone DokuWiki instance, with restricted access.
If you're willing to provide an update, feel free copy/paste your suggested changes here.

**Comment by mnewnham** [comment]
I'll add a note to the page "This feature was removed in version 5.21. This page will be removed 1st May 2021"

**Comment by dregad** [comment]
> I'll add a note to the page "This feature was removed in version 5.21. This page will be removed 1st May 2021"

I took care of it (for v5 - did not touch the v6 version)
