### ISSUE TITLE
Remove all magic quotes related code

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#674]
Let's finally get rid of this.

For backwards compatibility purposes we'll just keep the `$magic_quote` parameter for public methods (e.g. qStr(), addQ(), AutoExecute(), GetUpdateSQL(), GetInsertSQL() ), but it no longer used and is defaulted to _false_, to avoid changing the functions' signature.

Following up on / related to #619, #643, #644, #657, #658.

**Comment by dregad** [comment]
- [ ] Documentation should be reviewed and updated as necessary.

**Comment by mnewnham** [comment]
I'm working on doc at the moment. I'll look at it later this evening

**Comment by mnewnham** [comment]
I've updated the documentation. For getinsertsql and getupdatesql I have updated the documentation with reference to placeholders. For all others, where the argument was both the last and optional, I have removed all reference to the information.

**Comment by dregad** [comment]
Fixed in faf71c5f3ef8823328f4f98e4562744ff04632ee
