### ISSUE TITLE
no date possible after 09-DEC-2220 on oci8 with 5.20.14 and higher

### ISSUE THREAD

**Issue by sondek** [ADOdb/ADOdb#677]
Hi,

all dates after 09-DEC-2220 from my oracle database (oci8 driver) appear as 09-DEC-2220 with adodb 5.20.14 and higher. With 5.20.13 it gives me the correct date stored in the database. I use the 31-DEC-9999 as unlimited for example, but it gets cut to 09-DEC-2220.
All dates below 09-DEC-2220 work fine though.

Thanks,
Sondek

**Comment by mnewnham** [comment]
We'll need to get a little more information on this:

1. Your Oracle version
2. Your server platform
2. Your NLS_DATE_FORMAT
3. What feature in ADOdb is triggering the issue, e.g. getInsertSql, getUpdateSql etc.

**Comment by mnewnham** [comment]
This  is not a problem with the database . There is an enforced 200 year [future cutoff date](https://adodb.org/dokuwiki/doku.php?id=v5:datetime:datetime_index#future_date_cutoff) to prevent DOS attacks. To calculate dates greater than 200 years in the future set the following:

````php
define('ADODB_FUTURE_DATE_CUTOFF_YEARS', 500);
````
**before** you include the ADOdb libraries. This will fix your problem
