### ISSUE TITLE
Call to a member function Execute() on a non-object when trying to execute an SQL statement in PHP

### ISSUE THREAD

**Issue by Pazzesco** [ADOdb/ADOdb#68]
Hello,

I am getting the below error when I try to execute an SQL statement in PHP. Statement works without any issues in phpMyAdmin, only problem is in PHP with ADOdb connenction:

Error:
Call to a member function Execute() on a non-object 

PHP Code:

$sql_query = "SELECT tbl_news_keywords.id, tbl_news_keywords.model_id
		FROM tbl_news_keywords LEFT OUTER JOIN
     		tbl_vehicles
     		ON (tbl_news_keywords.model_id = tbl_vehicles.model)
		WHERE tbl_news_keywords.type = '3'
		GROUP BY tbl_news_keywords.keyword";
						
$rs_query = $db -> Prepare($sql_query);		
$rs_query -> Execute();

Here is my DB connection statements:

if (ADODB_PHPVER >= 0x4300) $this->_connectionID = mysql_connect($argHostname,$argUsername,$argPassword, $this->forceNewConnect,$this->clientFlags);

$db = ADONewConnection('mysql'); $db->Connect(DBHOST,DBUSER,DBPASS,DBNAME) or die();

Any ideas of where the error might be coming from?

**Comment by mnewnham** [comment]
" Call to a member function Execute() on a non-object" implies that your $db object no longer points to an adodb connection, you should check:1. That you have not overwritten your $db object2. That you have not done a $db->close

**Comment by dregad** [comment]
Closing this since no feedback was provided following Mark's comment.
