### ISSUE TITLE
Logs generated by `outp` - $newline set to true is hardcoded

### ISSUE THREAD

**Issue by safjanowski** [ADOdb/ADOdb#681]
How to overwrite property $newline from https://github.com/ADOdb/ADOdb/blob/master/adodb.inc.php#L696 ?

If I'm trying to create logger according to https://adodb.org/dokuwiki/doku.php?id=v5:reference:logging#overriding_the_default_logging_function 

Is this possible to not making echo - if someone is passing ADODB_OUTP lets allow to handle logs only by that method instead of: 
```php
// https://github.com/ADOdb/ADOdb/blob/master/adodb.inc.php#L712-L716
if (isset($_SERVER['HTTP_USER_AGENT']) || !$newline) {
  echo $msg;
} else {
  echo strip_tags($msg);
}
```

**Comment by mnewnham** [comment]
It is indeed very difficult to control the output, The entire logging system needs a rewrite. There is however a reasonably easy solution to your problem. You can assign a global variable **$ADODB_OUTP** to the name of a function that will capture the logging output, replacing the built-in and process it how you want. Here's a simple example that eliminates all the html formattiong ftom the message making it more suitable for text file logging:

````
$ADODB_OUTP = 'coreLogger';

function coreLogger($message,$newline)
{
	$message = strip_tags($message);
	$message = str_replace('&nbsp;',' ',$message);
	$message = htmlspecialchars_decode($message);
	print $message;
}

include 'adodb.inc.php';

````

You can now do whatever you want with the message, for example you could attach it to a monolog stream

**Comment by safjanowski** [comment]
@mnewnham thanks, I’ll do that in that way.
