### ISSUE TITLE
pgsql: `param(0)` returns `$0`, resulting in query execution error

### ISSUE THREAD

**Issue by GN4RK** [ADOdb/ADOdb#682]
Hello, when using ADOdb_Session, there is a bug since the update of the function Param($name,$type='C') (ADOdb_postgres64)
```PHP
function Param($name,$type='C')
{
  if ($name) {
    $this->_pnum++;
  } else {
    // Reset param num if $name is false
    $this->_pnum = 0;
  }
  return '$' . $this->_pnum;
}
```

In the ADOdb_Session (adodb-session2.php), this code will generate a bug :
```PHP
$sql = "SELECT $ADODB_SESSION_SELECT_FIELDS FROM $table WHERE sesskey = $binary ".$conn->Param(0)." AND expiry >= " . $conn->sysTimeStamp;
```

`$conn->Param(0)` will return `$0`. When the query is executed, it will result in a "Query failed" because pg_query_params will only accept argument from `$1`, `$2`, etc.

If I understand it correctly, `$conn->Param(0)` should never return `$0` and should reset param num only `if ($name === false)` since `0`, `'0'` or `"0"` is interpreted like false in this case.

**Comment by dregad** [comment]
Regression introduced by #380

**Comment by dregad** [comment]
@GN4RK please check out PR #683 and let me know if that works for you.

**Comment by GN4RK** [comment]
> 
> 
> @GN4RK please check out PR #683 and let me know if that works for you.

It works, thank you ! =)
