### ISSUE TITLE
PHP 8.0 compatibility: function 'SetCharSet'

### ISSUE THREAD

**Issue by deining** [ADOdb/ADOdb#686]
**Versions:** 
* php 8.0.3
* mysql  Ver 15.1 Distrib 10.5.9-MariaDB
* adodb 5.21.0

After upgrading to php 8, I encountered a fatal error when using my existing code base:

**Stackstrace**:

Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given in /.../adodb/drivers/adodb-mysqli.inc.php:1206
Stack trace:
#0 /../adodb/drivers/adodb-mysqli.inc.php(1206): method_exists()
#1 /../myconnector.php(8):
ADODB_mysqli->SetCharSet()
thrown in /.../adodb/drivers/adodb-mysqli.inc.php on line 1206

My code is as simple as:

```
include('adodb/adodb.inc.php');
$db = ADONewConnection('mysqli');
$db->setCharset('utf-8');
...
```

If I comment out the line `$db->setCharset('utf-8');`, the error goes away.

Underlying reason: in PHP 8 method_exists now throws a Type Error if it encounters an unexpected value, which it didn't do previously.

Thanks for investigating the issue.

**Comment by peterdd** [comment]
Maybe use

https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter

**before** doing the real $db->connect()

instead of $db->setCharSet('utf-8');

I also stumbled over a similiar issue with PHP8, in my case it is get_class_methods() yet undocumented behavior change.

**Comment by dregad** [comment]
Thanks for the bug report, will fix.

As a side note, `$db->setCharset('utf-8');` will never work, because `utf-8` is not a valid MySQL charset (see https://www.php.net/manual/en/mysqlinfo.concepts.charset.php), you should use `utf8` or preferably `utf8mb4` instead.

**Comment by mnewnham** [comment]
As another point, [setCharSet](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setcharset) is "sort of" deprecated. use [setConnectionParameter](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameterl) instead.
