### ISSUE TITLE
Caching in FieldTypesArray() causes problems

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#687]
The static variable added in #367 to cache field information introduces a regression, [as mentioned](https://github.com/ADOdb/ADOdb/pull/367#issuecomment-346954017) by @Mike-Benoit.

This [affects MantisBT](https://mantisbt.org/bugs/view.php?id=28015#c65202), when running on PostgreSQL.

## Reproducing the issue

The following code snippet consistently reproduces the problem (tables are from a fresh install of MantisBT, but results are the same with any 2 distinct SQL statements):

``` php
<?php
include 'adodb.inc.php';

$db = ADONewConnection('pgsql');
$db->connect('localhost', $u, $p, 'bugtracker');

q('SELECT basename, priority, protected FROM m_plugin');
q('SELECT config_id, value FROM m_config');

function q($sql) {
    global $db;
    $rs = $db->execute($sql);
    echo "--------- $sql\n";
    print_r($rs->fieldTypesArray());
}
```

### Actual Output
The 2nd call to _fieldTypesArray()_ returns information about the 1st query's fields.
```
--------- SELECT basename, priority, protected FROM m_plugin
Array
(
    [0] => ADOFieldObject Object
        (
            [name] => basename
            [max_length] => -1
            [type] => varchar
        )

    [1] => ADOFieldObject Object
        (
            [name] => priority
            [max_length] => 4
            [type] => int4
        )

    [2] => ADOFieldObject Object
        (
            [name] => protected
            [max_length] => 1
            [type] => bool
        )

)
--------- SELECT config_id, value FROM m_config
Array
(
    [0] => ADOFieldObject Object
        (
            [name] => basename
            [max_length] => -1
            [type] => varchar
        )

    [1] => ADOFieldObject Object
        (
            [name] => priority
            [max_length] => 4
            [type] => int4
        )

    [2] => ADOFieldObject Object
        (
            [name] => protected
            [max_length] => 1
            [type] => bool
        )

)
```

### Expected output for the 2nd query
```
Array
(
    [0] => ADOFieldObject Object
        (
            [name] => config_id
            [max_length] => -1
            [type] => varchar
        )

    [1] => ADOFieldObject Object
        (
            [name] => value
            [max_length] => -1
            [type] => text
        )

)
```

**Comment by joebordes** [comment]
actually don't remember what the case was back then and we don't seem to have that bottleneck anymore so @peterdd is probably right in saying that there was a better optimization in our code base than in this function, which doesn't mean that this is a bad optimization per se.

if there are plans to adopt some other cache system then this seems like a good place to add it, if not maybe we could find a way to put the cache in function of the query that was launched or do both things.

``` php
if (empty($arr[lastquery])) {
    $arr[lastquery] = array();
    for ...
         $arr[lastquery][] = ...
}
return $arr[lastquery];
```

just an idea.

**Comment by dregad** [comment]
The problem here is caused by using a static variable, as it is shared across all ADORecordset objects. Making the cache an array indexed by the query as @joebordes suggests could work, but I'm concerned about the overhead vs the actual performance benefit.

Considering that a recordset is the result of a query's execution, I'm wondering if instead of using a static variable, we could not simply rely on a class property instead. This way the field metadata would be cached during the recordset's lifecycle and for that individual recordset only, and we don't have to worry about having to invalidate the cache.

Thoughts ?

**Comment by joebordes** [comment]
I don't have enough knowledge of ADODB to be sure, but it sounds correct to me

**Comment by dregad** [comment]
Thanks for the analysis @mnewnham. 

So we already have specific caching solutions using class properties in place for the mssqlnative and oci8 drivers, something I was not aware of. I think it makes sense to standardize this into the parent ADORecordSet class. 

I would propose the following 2-step approach:

1. Fix the regression issue on pgsql in 5.20.1, by replacing the static var with a class property to store the cache, and populate the latter in _initRS() as you suggested, which makes perfect sense since we already loop over fields and call pg_field_type() there. I'll submit a PR for this
2. Adapt mssqlnative and oci8 drivers to store their cache in a property of the parent class. This work item can be targeted at 5.22, and tracked as a separate issue which I'll open later.

**Comment by mnewnham** [comment]
For the purposes of the 5.21 hotfix  pull request #731 , I have made the bare minimum change, simply replacing the static variable with a class variable so that the cached object only exists for the life of the recordset. All other discussion points  (standardize, restructure of _initrs() ) can be delegated to the 5.22 fix. @dregad. do you want to open a separate issue for this or shall I?

**Comment by dregad** [comment]
Hotfix committed in 6301246ccd627c7953368aa687ba61d9f9989e59.

#747 opened for the followup.
