### ISSUE TITLE
Why always updating every file with version bump?

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#688]
Browsing sources we loose the overview when a file had a last **real** edit.

Maybe find another way?
![adodb_versionbumps](https://user-images.githubusercontent.com/1839154/110473439-d0da6200-80de-11eb-96ec-df758aae2dc1.png)

**Comment by dregad** [comment]
> Change only the version if something was changed in the file itself?

I don't like this, because very soon we'll end up with a mix of many different versions over various files, which would be confusing.

**Comment by mnewnham** [comment]
I have no objection on this. I've always accepted any header information that you have put there. I have noticed that many popular packages have a much shorter header. Perhaps something more like this?

````php
/**
* MySQLi driver
*
* This file is part of the ADOdb package.
*
*  @copyright (c) 2000-2013 John Lim (jlim#natsoft.com). All rights reserved.
*  @copyright (c) 2014-2021   Damien Regad, Mark Newnham and the ADOdb community
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/
````

**Comment by dregad** [comment]
Here's my proposal

```
/**
 * <short description, e.g. ADOdb Library main include file.>
 *
 * <optional longer description, if necessary>
 *
 * This file is part of the ADOdb Library, a Database Abstraction layer for PHP
 *
 * @package ADOdb
 * @link https://adodb.org Project's web site and documentation
 * @link https://github.com/ADOdb/ADOdb Source code and issue tracker
 *
 * The ADOdb Library is dual-licensed, released under both the BSD 3-Clause
 * and the GNU Lesser General Public Licence (LGPL) v2.1 or, at your option,
 * any later version. This means you can use it in proprietary products.
 * See the LICENSE.md file distributed with this source code for details.
 * @license BSD-3-Clause
 * @license LGPL-2.1-or-later
 *
 * @copyright 2000-2013 John Lim
 * @copyright 2014 Damien Regad, Mark Newnham and the ADOdb community
 * @author John Lim <jlim@natsoft.com>
 * @author Damien Regad
 * @author Mark Newnham
 */
```

Comments welcome.

**Comment by peterdd** [comment]
`This means you can use it in proprietary products.`

This means you can use it **also** in proprietary products.

Maybe this sentence is not necessary at all here?

@mnewnham Not naming at least the license names n files maybe not allowed for LGPL http://www.gnu.org/licenses/old-licenses/lgpl-2.1 :

To apply these terms, attach the following notices to the library. It is **safest** to attach them to the start of each source file to most effectively convey the exclusion of warranty; and each file **should** have at least the "copyright" line and a pointer to where the full notice is found. 

Ok, I highlighted **safest** and **should**, so it is not a **must**, but I am not a lawyer.

**Comment by mnewnham** [comment]
I cannot comment to the legalese, my suggestion reflected the comments I see attached to major components that I use. The example I provided was,for example based on the source files in the monolog package

**Comment by dregad** [comment]
> This means you can use it also in proprietary products.

That feels redundant, and it does not sound right to me.

> Maybe this sentence is not necessary at all here?

Possibly; I just retained the original wording.

> each file should have at least the "copyright" line and a pointer to where the full notice is found.

I think it's better to be explicit, and include that info even if it's indeed a _should_.
