### ISSUE TITLE
PHP 8.0 compatibility: function 'setConnectionParameter' (mysqli)

### ISSUE THREAD

**Issue by deining** [ADOdb/ADOdb#693]
**Versions:** 
* php 8.0.3
* mysql  Ver 15.1 Distrib 10.5.9-MariaDB
* adodb 5.21.0

Following your advice given in #686, I tried to use function `setConnectionParameter`.
Unfortunately, this leads to another error:

**Stackstrace**:

```
Uncaught TypeError: mysqli_options(): Argument #2 ($option) must be of type int, string given in /my_path/adodb/drivers/adodb-mysqli.inc.php:148
Stack trace:
#0 /my_path/adodb/drivers/adodb-mysqli.inc.php(148): mysqli_options()
#1 /my_path/adodb/adodb.inc.php(705): ADODB_mysqli->_connect()
#2 /my_path/my.php(10): ADOConnection->Connect()
#3 {main}\n  thrown in /my_path/adodb/drivers/adodb-mysqli.inc.php on line 148
```

My code looks like:

```
include('adodb/adodb.inc.php');
$db = ADONewConnection('mysqli');
$db->setConnectionParameter('CharacterSet','utf8mb4');
$db->Connect("host", "user", "passphrase", "database");
```

Thanks for investigating the issue.

**Comment by dregad** [comment]
You need to use the [predefined constants](https://www.php.net/manual/en/mysqli.options.php) to identify the option, and not some arbitrary string. In your case:

```
$db->setConnectionParameter(MYSQLI_SET_CHARSET_NAME,'utf8mb4');
```

MYSQLI_SET_CHARSET_NAME

That said, the code should not choke on this, so I'll keep

**Comment by deining** [comment]
> You need to use the [predefined constants](https://www.php.net/manual/en/mysqli.options.php) to identify the option

Thanks for clarification. It now works as expected.
 
> That said, the code should not choke on this, so I'll keep this open to fix this

I agree. Thanks for your efforts.

Another topic: The [documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter) of the `setConnectionParameter` function mentions usage with DB2 and SQl server databases only. Would be great if usage in case of MySQL (and PostgreSQL) were added, too.

**Comment by dregad** [comment]
> Another topic: The [documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter) of the `setConnectionParameter` function mentions usage with DB2 and SQl server databases only. Would be great if usage in case of MySQL (and PostgreSQL) were added, too.

I was actually updating that as you posted... Please check again
https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter

**Comment by dregad** [comment]
@mnewnham I was wondering why you defined the setConnectionParameter() method as _final_ (see #158, 2e72fe524694d30a97a760a43b6d1554d8d84e0a), this prevents overriding it in a specific driver (mysqli in this case) to add error handling.

Of course we could also do the check in ADODB_mysqli::_connect() as well, but it seems cleaner to me to catch the error early. Thoughts ?

**Comment by mnewnham** [comment]
Clearly a mistake. Please revert

**Comment by dregad** [comment]
> That said, the code should not choke on this, so I'll keep this open to fix this

PR #701 addresses the problem of ADODB_mysqli->_connect() throwing a TypeError (on PHP 8) or a Warning (on earlier PHP versions) when processing an invalid parameter.
