### ISSUE TITLE
sqlite: sqlite driver returns incorrect time when using $sysTimeStamp

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#697]
The sqlite driver returns the UTC time when the $sysTimeStamp value is used. It should return the local time

**Comment by dregad** [comment]
I have not looked into details and don't know your use case and rationale for saying this is a bug, but generally speaking and from my experience it is usually best to keep all database-related time in UTC and let the client deal with translating that to local time zone if and when appropriate.

**Comment by mnewnham** [comment]
I am comparing it against the same value in the mysqli driver which returns localtime

**Comment by mnewnham** [comment]
mssqlnative driver also returns localtime

**Comment by mnewnham** [comment]
@dregad , any thoughts on this? I'd like to push a fix for this.

**Comment by dregad** [comment]
Go ahead. I was just making a general comment and if other drivers are already using local time then we should be consistent.
