### ISSUE TITLE
mysqli: TEXT/BLOB default value differences MariaDB>10.2.1 vs MySQL8

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#704]
Table fields with datatype 'TEXT' can have a default value set since MariaDB 10.2.1

MySQL8 does not allow that.

I stumbled over that because 5.21.0 looks if a $blobAllowsDefaultValue is true and MariaDB now gets no default value for an 'X' datatype table  field of a  xmlschema03 file.

Dunno what to do with it, just wanted let you know.

Now I think of replacing some fields of my schema that was 'X' by 'C' varchars for crossdb compatibility but unsure about pro and contra of that.

Maybe inheritance of datadict-mysql with a datadict-mariadb class?

**Comment by dregad** [comment]
> Maybe inheritance of datadict-mysql with a datadict-mariadb class?

This approach is fine as long as MariaDB is a superset of MySQL; the potential problem could be if there is a feature difference going the other way around, i.e. something in MySQL that does not exist in MariaDB, and would then be inherited but should not. 

Alternatives could be: a new _mariadb_ driver starting as a copy of current _mysqli_, but that's a lot of code duplication meaning  increased maintenance and risk of forgetting to apply a common change to both drivers. Not sure I like that either.

Or probably best but more complex to implement, we have some common base class, and derive individual drivers from it.

**Comment by mnewnham** [comment]
From MySQL 8.0.13, you can add a default value to MySQL TEXT columns
