### ISSUE TITLE
PDO: Bind parameters fail if sent in associative array

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#705]
The ADOdb method **param()** can be used to create database-specific bind parameters for use in portable SQL. The resulting values can then be sent to the execute method in either a numeric or associative arrays. example:

````php
$p1 = $db->param('p0');
$bind = array('p0'=>'somevalue');
$db->execute($somesql,$bind);
````
The PDO driver however requires the bind array to be presented in a numeric array and fails otherwise

**Comment by f7h** [comment]
This change breaks statements with named parameters, e.g. the following worked in 5.21.0:

`$db->execute('SELECT :name FROM table', [':name' => 'value']);`
