### ISSUE TITLE
Undeclared `connection` property in SQLite3 driver

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#713]
ADODB_sqlite3::metaType() [references](https://github.com/ADOdb/ADOdb/blob/3c8d1e5f20aab232a68853f93532a5d840f38e09/drivers/adodb-sqlite3.inc.php#L94) a `connection` property, which only exists in DataDict and RecordSet contexts.

This was introduced by commit 3c8d1e5f20aab232a68853f93532a5d840f38e09.

I guess this could be fixed by replacing `$this->connection->customActualTypes` with `$this->customActualTypes`. But maybe the metaType() method should be declared in the ADORecordset_sqlite3 class ?

@mnewnham can you please check ?

**Comment by mnewnham** [comment]
Will look at it later today

**Comment by mnewnham** [comment]
There is a little inconsistency here,in that metaType for sqlite is declared only in the datadict, and not in the connection driver, unlike most drivers. In the mysqli, metatType is declared in both the connection and the recordset. This is the only driver that features this. I can see no explanation for this difference.

As an added issue, the metatype in mysql/datadict returns ADODB_DEFAULT_METATYPE for the unknown , but both the driver implementations return a hardcoded N.
