### ISSUE TITLE
xmlschema03 query tag table prefix bugs

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#714]
* Fails setting table prefix when no space between mytable and '(': (fix regexp)
```xml
<query>insert into mytable(field1,field2) values(1,2)</query>
```

* no table prefix for multiline queries: (probably add missing 'm' multiline regexp option)
```xml
<query>insert into mytable
(field1,field2)
values(1,2)
</query>
```

* update query regexp for table prefix completely wrong: (probably copy-paste error from the delete table regexp)
```xml
<query>update mytable set field2=4 where field1=1</query>
```

More details and example or PR will follow.

**Comment by dregad** [comment]
@peterdd what is the status of this issue ? Are you planning to submit a PR or additional information as mentioned in your initial posting ?

**Comment by peterdd** [comment]
No progress there. I stopped after finding the third simple issue within <query> section of xmlschema03 in a short time and stick to the use of queries that work at current(5.21.0 in my case) state. https://github.com/Flyspray/flyspray/commit/ade01edf2f764acffd49b076f119cd435c65e37b

More important issue is that it data-dict for postgres is not working with xmlschema03 and have to patch 5.21.0 on install. https://github.com/Flyspray/flyspray/commit/44af76c09a4a9dae2c707f4a3a9d56ea06d531bc
(related #11, #73, #383, #124, #125)

**Comment by mnewnham** [comment]
@peterdd . I have re-tested the issues described above, using MySQL and SQLite. I cannot see any errors generated. This is my xmlschema

````xml
<?xml version="1.0"?>
<schema version="0.3">
  <table name="xml_users">
    <descr>A typical users table for our application.</descr> 
    <field name="userId" type="I">
      <descr>A unique ID assigned to each user.</descr>
      <KEY/>
      <AUTOINCREMENT/>
    </field> 
    <field name="userName" type="C" size="16">
        <NOTNULL/>
    </field>
    <index name="userName">
      <descr>Put a unique index on the user name</descr>
      <col>userName</col>
     
    </index>
  </table>
  <sql>
    <descr>Insert some data into the users table.</descr>
    <query>insert into employees.xml_users 
           (userName) 
           values ( 'admin' )
     </query>
    <query>insert into employees.xml_users(userName) values ( 'Joe' )</query>
  </sql>
</schema>
````
I believe the XML above should address  the issues raised above:

1. Issue with multi-line SQL queries
2. Issue where schema is attached to table name

Is there still a problem here? perhaps the issue has been fixed by other changes.

**Comment by mnewnham** [comment]
As there has been no further discussion on this I am closing it as ``not reproducible``
