### ISSUE TITLE
PageExecute bug - pdo error: [1248: Every derived table must have its own alias]

### ISSUE THREAD

**Issue by lifebbs** [ADOdb/ADOdb#715]
Database: mysql
Driver: pdo
```php
$dbconn->PageExecute("
    select a.*, count(distinct notes.id) as notes_cnt, count(distinct images.id) as images_cnt
                    from locations a
                        left join locations_notes notes
                            on notes.locations_id = a.id
                        left join locations_images images
                            on images.locations_id = a.id
                    where a.status = 'active'
                    group by a.id
", 25, 1);
```

"count" query is transformed into 
```sql
SELECT COUNT(*) FROM (
    select a.*, count(distinct notes.id) as notes_cnt, count(distinct images.id) as images_cnt
                    from locations a
                        left join locations_notes notes
                            on notes.locations_id = a.id
                        left join locations_images images
                            on images.locations_id = a.id
                    where a.status = 'active'
                    group by a.id
)
```
and throws Uncaught ADODB_Exception: pdo error: [1248: Every derived table must have its own alias] in EXECUTE("...")
as you can see - no alias is added

**Comment by mnewnham** [comment]
This would likely be a problem with the native mysql driver as well, any statement which has a format something like this

````php
SELECT column FROM (
     SELECT column FROM table
  )
````
Needs an alias so:
````php
SELECT column FROM (
     SELECT column FROM table
  ) some_alias
````
The alias name is irrelevant, it just needs to be there. So this needs to be part of some driver-specific handling

**Comment by mnewnham** [comment]
In fact this isn't really a pdo error. While the native driver does in fact alias the statement, and making the PDO driver do the same, The problem is that the regexp is failing in **_adodb_getcount()** because there is a **(select count** in the core sql statement that needs to be resolved.

**Comment by mnewnham** [comment]
The statement fails primarily because the source SQL statement contains sub-selects. 
Added support for the PDO/mysql driver into the list of drivers that require an alias for the derived table
