### ISSUE TITLE
$data->FetchRow() does not want to work

### ISSUE THREAD

**Issue by wramirez82** [ADOdb/ADOdb#716]
Hello, I execute the code hiding what it calls / * while ($ data = $ data-> FetchRow ()) {}] * / and if it loads the page but when uncommenting the line does not load

I use debian version 10 with php 7.4

function encabezado($zpdf) 
{
    include('BDD/ConexionBD.php');
	global $posy;
	global $usuario;

    $query_total = "SELECT DATE_FORMAT(d.fecha_inicio,'%d-%m-%Y') inicio, 
	DATE_FORMAT(d.fecha_fin,'%d-%m-%Y') fin FROM  wpucat_periodo d WHERE d.tipo=2 AND estado LIKE  'A'";
	$data=$BDD->Execute($query_total);
	if(!$data->EOF) 
		  {
	        while($dato = $data->FetchRow())
			{
				$inicio = $dato["inicio"];
				$fin  = $dato["fin"];
			}
		  }
.........
..................
}

**Comment by mnewnham** [comment]
1. What driver are you using
2. If you enable debugging, does it provide any information

**Comment by wramirez82** [comment]
ready the problem friends was to change to: $ BDD = NewADOConnection ('mysqli');
