### ISSUE TITLE
db2: Changing ADODB_ASSOC_CASE has no effect on column name casing

### ISSUE THREAD

**Issue by HeshamShahtout** [ADOdb/ADOdb#719]
When trying to fetch columns in DB2 database with the 5.21.0 driver.

The column names are returned in lower case instead of upper case with no way to change it.

**Comment by mnewnham** [comment]
When you say fetch columns, do you mean via **fields()** or **metaColumns()** ? could you provide a short code segment please.

**Comment by HeshamShahtout** [comment]
`function get_user_name($user_id){
                $stmt = "SELECT USR_E_NM FROM USR WHERE USR_ID='".$user_id."'";
		$res = Database::getConnection()->Execute($stmt);

		return $res->fields['USR_E_NM'];
}`

For example inside this code snippet when trying to fetch **USR_E_NM** php throws an error saying the index doesn't exist
when printing the **$res->fields** the field name is shown in lower case as **usr_e_nm** instead of **USR_E_NM**

This issue was not present in the version 5.20.17

**Comment by lkrms** [comment]
Sorry to bump an old discussion, but I haven't been able to find information about ADOdb's release schedule and I'd love to be able to stop patching `vendor/adodb/adodb-php/drivers/adodb-db2.inc.php` after every `composer install` :smile:

Is there any chance #722 could be merged as a hotfix while other 5.21.1 issues are pending? :pray:

**Comment by mnewnham** [comment]
I apologize for the delay on this, unfortunately @dregad ,who is responsible for the releases, is offline at the moment and I don't have the necessary tools to build the release.
