### ISSUE TITLE
debugging levels documentation

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#724]
The different debugging levels (integer 1=true, -1, -99, 99, 2) are only mentioned on

https://adodb.org/dokuwiki/doku.php?id=v5:reference:logging

The other 'debug' documentation wiki pages like 

https://adodb.org/dokuwiki/doku.php?id=v5:userguide:debug
or
https://adodb.org/dokuwiki/doku.php?id=v5:loadbalancer:mysql_replication:debugging
or 
https://adodb.org/dokuwiki/doku.php?id=v5:session:reference:debug

only say `$connection->debug` is a boolean value.

**Comment by dregad** [comment]
Duplicate of #550 (at least you're persistent :wink: )
