### ISSUE TITLE
updated wiki documentation completeTransaction() and commitTrans()

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#726]
Just let you know that I updated return value is bool not void for completeTransaction and commitTrans() on adodb.org according to sources in adodb.inc.php

Also the optional parameter of commitTrans() was not mentioned.

So commitTrans(false) is same as rollBackTrans() ?

**Comment by dregad** [comment]
> I updated return value is bool not void for completeTransaction and commitTrans() 

Thanks !

> commitTrans(false) is same as rollBackTrans()

yes
