### ISSUE TITLE
pdo:  Throws Notice, Returns 0 when rows affected, on Affected_Rows() call

### ISSUE THREAD

**Issue by ooglek** [ADOdb/ADOdb#733]
https://github.com/ADOdb/ADOdb/blob/199391f639a0b3346a80d66c00c87230fa3e6a07/drivers/adodb-pdo.inc.php#L611

Worked in 5.20.18, does not work in 5.21.0.

Error in PHP when attempting to call `$adodb->affected_rows()` after an `$adodb->execute()` call using the pdo_mysql driver.

> PHP Notice:  Undefined property: ADODB_pdo_mysql::$_stmt in /usr/local/apps/include/vendor/adodb/adodb-php/drivers/adodb-pdo.inc.php on line 611

pdo_mysql does NOT have an `_affectedrows()` method, so it attempts to return a value from the `_stmt` but for some reason it doesn't exist:

https://github.com/ADOdb/ADOdb/blob/199391f639a0b3346a80d66c00c87230fa3e6a07/drivers/adodb-pdo.inc.php#L606-L612

I also get a warning when initializing ADOdb.

> PHP Warning:  Declaration of ADODB_pdo::metaIndexes($table, $normalize = true) should be compatible with ADOConnection::MetaIndexes($table, $primary = false, $owner = false) in /usr/home/USER/dev/trunk4/include/vendor/adodb/adodb-php/drivers/adodb-pdo.inc.php on line 0

I can recreate this using `psysh` --

```
>>> $db->execute("select * from numbers limit 3");
=> ADORecordSet_pdo {#2689
     +bind: false,
     +databaseType: "pdo",
     +dataProvider: "pdo",
[... cut ...]
     +sql: "select * from numbers limit 3",
     +connection: ADODB_pdo {#2586
       +databaseType: "pdo",
       +dataProvider: "pdo",
       +fmtDate: "'Y-m-d'",
       +fmtTimeStamp: "'Y-m-d H:i:s'",
       +replaceQuote: "''",
       +hasAffectedRows: true,
       +_bindInputArray: true,
       +_genIDSQL: "UPDATE %s SET id=LAST_INSERT_ID(id+1);",
       +_genSeqSQL: "CREATE TABLE  if NOT EXISTS %s (id int not null)",
       +_dropSeqSQL: "drop table %s",
       +_autocommit: true,
       +_lastAffectedRows: 0,
       +_errormsg: false,
       +_errorno: false,
       +dsnType: "mysql",
       +stmt: false,
       +_driver: ADODB_pdo_mysql {#2588
         +metaTablesSQL: """
           SELECT\n
           \t\t\tTABLE_NAME,\n
           \t\t\tCASE WHEN TABLE_TYPE = 'VIEW' THEN 'V' ELSE 'T' END\n
           \t\tFROM INFORMATION_SCHEMA.TABLES\n
           \t\tWHERE TABLE_SCHEMA=
           """,
         +metaColumnsSQL: "SHOW COLUMNS FROM `%s`",
         +sysDate: "CURDATE()",
         +sysTimeStamp: "NOW()",
         +hasGenID: true,
         +_genIDSQL: "UPDATE %s SET id=LAST_INSERT_ID(id+1);",
         +_genSeqSQL: "CREATE TABLE  if NOT EXISTS %s (id int not null)",
         +_genSeqCountSQL: "SELECT count(*) FROM %s",
         +_genSeq2SQL: "INSERT INTO %s VALUES (%s)",
         +_dropSeqSQL: "drop table %s",
         +fmtTimeStamp: "'Y-m-d H:i:s'",
         +nameQuote: "`",
         +databaseType: "pdo",
         +dataProvider: "pdo",
         +fmtDate: "'Y-m-d'",
         +replaceQuote: "''",
         +hasAffectedRows: true,
         +_bindInputArray: true,
         +_autocommit: true,
         +_lastAffectedRows: 0,
         +_errormsg: false,
         +_errorno: false,
         +dsnType: "",
         +stmt: false,
         +_driver: null,
         +pdoParameters: [],
         +database: "REMOVED_BECAUSE_REASONS",
         +host: "",
         +port: "",
         +user: "",
         +password: "",
         +debug: false,
         +maxblobsize: 262144,
         +concat_operator: "+",
         +substr: "substr",
         +length: "length",
         +random: "rand()",
         +upperCase: "upper",
         +true: "1",
         +false: "0",
         +leftBracket: "[",
         +rightBracket: "]",
         +charSet: false,
         +metaDatabasesSQL: "",
         +uniqueOrderBy: false,
         +emptyDate: "&nbsp;",
         +emptyTimeStamp: "&nbsp;",
         +lastInsID: false,
         +hasInsertID: false,
         +hasTop: false,
         +hasLimit: false,
         +readOnly: false,
         +hasMoveFirst: false,
         +hasTransactions: true,
         +genID: 0,
         +raiseErrorFn: false,
         +isoDates: false,
         +cacheSecs: 3600,
         +memCache: false,
         +memCacheHost: null,
         +memCachePort: 11211,
         +memCacheCompress: false,
         +sysUTimeStamp: false,
         +arrayClass: "ADORecordSet_array",
         +noNullStrings: false,
         +numCacheHits: 0,
         +numCacheMisses: 0,
         +pageExecuteCountRows: true,
         +uniqueSort: false,
         +leftOuter: false,
         +rightOuter: false,
         +ansiOuter: false,
         +autoRollback: false,
         +poorAffectedRows: false,
         +fnExecute: false,
         +fnCacheExecute: false,
         +blobEncodeType: false,
         +rsPrefix: "ADORecordSet_",
         +autoCommit: true,
         +transOff: 0,
         +transCnt: 0,
         +fetchMode: false,
         +null2null: "null",
         +bulkBind: false,
         +_oldRaiseFn: false,
         +_transOK: null,
         +_connectionID: PDO {#2585
           inTransaction: false,
           attributes: {
             CASE: NATURAL,
             ERRMODE: SILENT,
             AUTOCOMMIT: 1,
             PERSISTENT: true,
             DRIVER_NAME: "mysql",
             SERVER_INFO: "Uptime: 32874913  Threads: 21  Questions: 1539537838  Slow queries: 48329819  Opens: 307923  Flush tables: 1  Open tables: 512  Queries per second avg: 46.830",
             ORACLE_NULLS: NATURAL,
             CLIENT_VERSION: "10.2.22",
             SERVER_VERSION: "10.2.22-MariaDB-log",
             STATEMENT_CLASS: [
               "PDOStatement",
             ],
             EMULATE_PREPARES: 1,
             CONNECTION_STATUS: "192.99.147.69 via TCP/IP",
             DEFAULT_FETCH_MODE: BOTH,
           },
         },
         +_errorMsg: false,
         +_errorCode: false,
         +_queryID: false,
         +_isPersistentConnection: false,
         +_evalAll: false,
         +_affected: false,
         +_logsql: false,
         +_transmode: "",
       },
       +pdoParameters: [
         12 => true,
       ],
       +database: "REMOVED_BECAUSE_REASONS",
       +host: "REMOVED_BECAUSE_REASONS",
       +port: "",
       +user: "",
       +password: "",
       +debug: false,
       +maxblobsize: 262144,
       +concat_operator: "+",
       +substr: "substr",
       +length: "length",
       +random: "rand()",
       +upperCase: "upper",
       +true: "1",
       +false: "0",
       +nameQuote: "`",
       +leftBracket: "[",
       +rightBracket: "]",
       +charSet: false,
       +metaDatabasesSQL: "",
       +metaTablesSQL: "",
       +uniqueOrderBy: false,
       +emptyDate: "&nbsp;",
       +emptyTimeStamp: "&nbsp;",
       +lastInsID: false,
       +hasInsertID: true,
       +hasTop: false,
       +hasLimit: false,
       +readOnly: false,
       +hasMoveFirst: false,
       +hasGenID: true,
       +hasTransactions: false,
       +genID: 0,
       +raiseErrorFn: "db_errorHandler",
       +isoDates: false,
       +cacheSecs: 3600,
       +memCache: false,
       +memCacheHost: null,
       +memCachePort: 11211,
       +memCacheCompress: false,
       +sysDate: "CURDATE()",
       +sysTimeStamp: "NOW()",
       +sysUTimeStamp: false,
       +arrayClass: "ADORecordSet_array",
       +noNullStrings: false,
       +numCacheHits: 0,
       +numCacheMisses: 0,
       +pageExecuteCountRows: true,
       +uniqueSort: false,
       +leftOuter: false,
       +rightOuter: false,
       +ansiOuter: false,
       +autoRollback: false,
       +poorAffectedRows: false,
       +fnExecute: false,
       +fnCacheExecute: false,
       +blobEncodeType: false,
       +rsPrefix: "ADORecordSet_",
       +autoCommit: true,
       +transOff: 0,
       +transCnt: 0,
       +fetchMode: 2,
       +null2null: "null",
       +bulkBind: false,
       +_oldRaiseFn: false,
       +_transOK: null,
       +_connectionID: PDO {#2585},
       +_errorMsg: false,
       +_errorCode: false,
       +_queryID: PDOStatement {#2594
         +queryString: "select * from numbers limit 3",
       },
       +_isPersistentConnection: true,
       +_evalAll: false,
       +_affected: false,
       +_logsql: false,
       +_transmode: "",
       +"_stmt": PDOStatement {#2594},
     },
     +_numOfRows: 3,
     +_numOfFields: 17,
     +_queryID: PDOStatement {#2594},
     +_currentRow: 0,
     +_closed: false,
     +_inited: true,
     +_obj: null,
     +_names: null,
     +_currentPage: -1,
     +_atFirstPage: false,
     +_atLastPage: false,
     +_lastPageNo: -1,
     +_maxRecordCount: 0,
     +datetime: false,
     +"adodbFetchMode": 2,
   }
>>> $db->_stmt;
=> PDOStatement {#2594
     +queryString: "select * from numbers limit 3",
   }
>>> $db->affected_rows();
<warning>PHP Notice:  Undefined property: ADODB_pdo_mysql::$_stmt in /usr/home/USER/dev/trunk4/include/vendor/adodb/adodb-php/drivers/adodb-pdo.inc.php on line 611</warning>
=> 0
>>> $db->_stmt->RowCount();
=> 3
>>>
```

I also tried this with an insert and delete query -- still the same Notice/Warning.

PHP 7.3.5
Adodb: 5.21.0
Driver: pdo_mysql
mysqlnd Version => mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
pdo_mysql PDO Driver for MySQL => enabled Client API version => 10.2.22

**Comment by ooglek** [comment]
Further debugging shows that the newly added check of the driver method is causing this failure.

https://github.com/ADOdb/ADOdb/blob/b97ebc5067f6e40c1814654589dad6bfe5ffdde3/drivers/adodb-pdo.inc.php#L631-L637

The `ADODB_pdo_mysql` class extends the `ADODB_pdo` class and has `_affectedrows()` defined. 

When _affectedrows() is called, _affectedrows() calls _affectedrows() which now just breaks everything.

It seems you'd need to do some reflection in order to determine if the ADODB_pdo_mysql driver defined `_affectedrows()` and if not, NOT then call the locally defined version.

I think what you want here is this:

```
         $refl = new \ReflectionMethod($this->_driver, '_affectedrows');
         if ($refl->getDeclaringClass()->getName() == get_class($this->_driver)) {
             return $this->_driver->_affectedrows();
         }
          return ($this->_stmt) ? $this->_stmt->rowCount() : 0;
```

Testing this in place of the `method_exists()` line seems to do what may have been intended -- call the child class if it exists, but execute the PDO version if not.

Since ADODB_pdo_mysql extends ADODB_pdo, `_affectedrows()` will always exist in the child.

**Comment by mnewnham** [comment]
PDO has a database independent  affected_rows()  method called rowCount, which is part of the PDO::_affectedrows(), I'm not sure why this functions attempts to locate a parent method, but simply remarking out the lines that do this should work, so:

````php
function _affectedrows()
{
	//if(method_exists($this->_driver, '_affectedrows'))
	//	return $this->_driver->_affectedrows();
	
	return ($this->_stmt) ? $this->_stmt->rowCount() : 0;
}
````

**Comment by ooglek** [comment]
Yep, that solves my problem. And I had figured this out. I just figured I'd dig into WHEN and WHY it was added, and how the commit from 2019 made it into a 2021 release! :-)

The function attempts to locate the **child** method, but fails miserably due to the fact that method_exists does not consider whether or not the parent or child has the method, just that it exists. Which it always will.

I _believe_ the intent was to call the **child** `_affectedrows()` method IFF it existed, but if not, call the parent PDO version. This way it could be overridden.

However, the implementation did not do what I believe it was attempting to do.

And then broke all my crap.

I've gone back to 5.20.20 for now, nothing in 5.21.0 is vital for me. I hope it gets fixed up in 5.21.0++.

**Comment by ooglek** [comment]
This commit is to `blame` hahah sorry it's late and I have terrible jokes

https://github.com/ADOdb/ADOdb/commit/a2d63609950683652b3b1b7def6dbb13285829f3

**Comment by ooglek** [comment]
Any other comments here? It seems code committed in 2019 that is now breaking ADODB's Affected_Rows() for PDO, and also throwing notices about the `metaIndexes()` function not being the correct format... 

Did someone include too many commits in 5.21.0 without testing? Or did those commits sneak in without anyone noticing? Or was it intentional and the process to test was flawed? 

Either way, 5.21.0 is broken for PDO* AFAICT.

**Comment by ooglek** [comment]
Hey @mnewnham -- This fixes the notice, but does not fix the underlying bug, AFAICT. The original bug report was on `_affectedrows()` being called but not existing.

Unless the lack of `metaIndexes` was the underlying cause of `_affectedrows()` returning 0?

**Comment by mnewnham** [comment]
I'll need to revisit this as it's been a while. I do know that the metaindexes rewrite has been committed to hotfix/5.21

**Comment by ooglek** [comment]
I put together a rough draft PR to start a discussion. https://github.com/ADOdb/ADOdb/pull/744

**Comment by dregad** [comment]
> how the commit from 2019 made it into a 2021 release! :-)

@ooglek for the record that's just me maintaining ADOdb in my spare time, and not having enough of that :wink: 
Expect 5.21.1 release in the next couple days :crossed_fingers:

**Comment by ooglek** [comment]
I appreciate the time and effort @dregad !!! I was surprised that the issue wasn't caught in any tests. Glad to help however I can. Cheers!
