### ISSUE TITLE
pdo: mysql driver missing support for metaindexes

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#734]
The mysql PDO driver lacks  support for the metaIndexes() function

**Comment by dregad** [comment]
Changes in commit e3c6301bff536c3021dfc03ef4286a035820fd0e referenced above were also applied to hotfix/5.21 branch (see c4aadf417b7f2d985e01cead3ca70db07734bb7f, with a few minor differences that I will resolve when merging the hotfix branch into master.

Closing this as duplicate.
