### ISSUE TITLE
Postgres9 databasetype  is not included in $requiresAliasArray

### ISSUE THREAD

**Issue by horaciod** [ADOdb/ADOdb#735]
At https://github.com/ADOdb/ADOdb/blob/e3c6301bff536c3021dfc03ef4286a035820fd0e/adodb-lib.inc.php#L333 
the databasetype postgres9 is not included.
The result is an error
` pg_query(): Query failed: ERROR: subquery in FROM must have an alias`
and consequently a slow count using the alternative method  after   line 408

the $requiresAliasArray must be

```PHP
$requiresAliasArray = array('postgres','postgres7','postgres8,'postgres9','mysql','mysqli','mssql','mssqlnative','sqlsrv');
```

according the drivers like https://github.com/ADOdb/ADOdb/blob/e3c6301bff536c3021dfc03ef4286a035820fd0e/drivers/adodb-postgres9.inc.php

**Comment by horaciod** [comment]
#736 to fix this.

**Comment by mnewnham** [comment]
I have pushed commits into both hotfix/5.21 and master to resolve this. as usual I've messed up  the pull requests by linking it to the wrong issue but you should be good to go.
