### ISSUE TITLE
PHP Notice "Array to string conversion" when using Bulk Insert and debug=true

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#737]
I am using ADOdb Version 5.21.0 with PHP 7.4

When the input array of my prepared statement is of the form array([..], [...], [...]), which should do [bulk binding](https://adodb.org/dokuwiki/doku.php?id=v5:userguide:learn_bind:bulkbinding), and I have debugging enabled I get notices from the following code part:

```
function _adodb_debug_execute(&$zthis, $sql, $inputarr)
{
	$ss = '';
	if ($inputarr) {
		foreach($inputarr as $kk=>$vv) {
			if (is_string($vv) && strlen($vv)>64) $vv = substr($vv,0,64).'...';
			if (is_null($vv)) $ss .= "($kk=>null) ";
			else $ss .= "($kk=>'$vv') ";
		}
		$ss = "[ $ss ]";
	}
```

The problem is in line `else $ss .= "($kk=>'$vv') ";` where the $vv value is used as string.

**Comment by geri777** [comment]
I am closing this issue. I think the reason for this message was, that I forgot to add `$db->bulkBind = true;` before I executed the bulk statement.

**Comment by mnewnham** [comment]
Taking a case where the value in a a bind parameter is itself an array, e.g. in this SQL Server statement

````php
$bind= array(1, 'a' array('b',null,null,SQLSRV_SQLTYPE_NVARCHAR));

$sql = "INSERT INTO TEST(dataint,KEYFIELD,datacol) values (?,?,?)";
$db->execute($sql,$bind);
````
When passed to _adodb_debug_execute(), the values could not be displayed as a string
