### ISSUE TITLE
Bulk Insert into MSSQL Server (mssqlnative) not working

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#738]
I am using ADOdb Version 5.21.0 with PHP 7.4

```
$db=NewADOConnection('mssqlnative')
$dataBulkInsert = [
     [1, 'a', 'b'],
     [2, 'c', 'd'],
     [3, 'e', 'f'],
];
$db->Execute('INSERT INTO table1 (col1, col2, col3) VALUES (?, ?, ?), $dataBulkInsert);
```

As far as I understand it should be possible to bulk insert data into a table (with fallback if database does not support bulk inserts). However when I try the following using **mssqlnative** I get the following error in the debug output:

```
Error Code: -17
Message: An invalid SQL Server type for parameter 1 was specified.
```

**Comment by mnewnham** [comment]
Is this a feature that worked in prior releases of ADOdb?

**Comment by mnewnham** [comment]
I believe you are missing the **connection::bulkBind** parameter, which is required when using bulk binding arrays

````php
$db->connect('192.168.86.100',$user,$password,'NORTHWIND');
$db->bulkBind = true; // <-------- Set this parameter
$db->startTrans();

bindVars = array(array('A','B'),
                  array('D','E'),
                  array('G','H'),
                  array('J','K')
				  );


$sql = "INSERT INTO TEST(a,b) values (?,?)";
$db->execute($sql,$bindVars);
$db->completeTrans();

````

If this parameter is set, then the statement appears to work correctly with SQL server.

**Comment by geri777** [comment]
Hi Mark, thank you for the great support. Sorry for not reading the manual carefully ;-)
I have now added the bulkBind parameter. However I still get an error. It's now -16 instead of -17:

```
Error Code: -16
Message: An invalid PHP type for parameter 1 was specified.
```

**Comment by mnewnham** [comment]
Could you show what type of data types are defined in your table? I ran your program using a table with columns integer,varchar,varchar  on PHP 7.4.13 / Server 2019  and the bulk insert worked fine.   (debug mode works correctly as well).

**Comment by mnewnham** [comment]
Could you take a look at this [Sql Server Issue](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d3517b0b-de32-49c1-9253-1fd389b8d777/php-533-mssql-2008-parameter?forum=sqldriverforphp)?. Is it possible that there is a some kind of Data type / Code page issue at play? A vanilla US english / integer / varchar setup seems to be working fine

**Comment by mnewnham** [comment]
I have added a patch into hotfix/5.21 for the error in _adodb_debug_execute. If you grab the patch and run in debug mode it might provide more insight into the issue.

**Comment by geri777** [comment]
Thank you. I have downloaded the hotfix from https://github.com/ADOdb/ADOdb/tree/hotfix/5.21
Unfortunately there is no new output in the debug log.

I would like to give you more insight in my query. I have renamed the columns, but this is what I am running and what I get:

```
CREATE TABLE "test" (
	"col1" NVARCHAR(20) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col2" NVARCHAR(8) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col3" NVARCHAR(80) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col4" INT DEFAULT NULL,
	"col5" NVARCHAR(8) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col6" NVARCHAR(16) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col7" NVARCHAR(32) COLLATE Latin1_General_CI_AS NOT NULL,
	"col8" NVARCHAR(100) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col9" NVARCHAR(100) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col10" FLOAT DEFAULT NULL,
	"col11" NVARCHAR(16) COLLATE Latin1_General_CI_AS DEFAULT NULL,
	"col12" VARCHAR(7) COLLATE Latin1_General_CI_AS DEFAULT NULL
);


<hr>running query: 'INSERT INTO [XYZ].[dbo].[test] ([col1], [col2], [col3], [col4], [col5], [col6], [col7], [col8], [col9], [col10], [col11], [col12]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); select SCOPE_IDENTITY()'<hr>input array: array (
  0 => 
  array (
    0 => 'Paulchen',
    1 => NULL,
    2 => '',
    3 => 91001,
    4 => NULL,
    5 => 'ME',
    6 => 'IT-EN',
    7 => 'CD TEH Electric',
    8 => 'CD TEH Electric Zahlen',
    9 => 0.0,
    10 => NULL,
    11 => '2021-07',
  ),
)<hr>result: false

-16: SQLState: IMSSP
Error Code: -16
Message: An invalid PHP type for parameter 1 was specified.
```

**Comment by mnewnham** [comment]
I can definitely reproduce this error
````php


-16: SQLState: IMSSP
Error Code: -16
Message: An invalid PHP type for parameter 1 was specified.
````
By not setting **$db->bulkBind=true**

The table and data you have provided work ok. Here is my program:
````php
<?php
include '/dev/github/adodb/adodb.inc.php';
$db = newAdoConnection('mssqlnative');
$user = 'sa';
$password = '####';
$db->port = 1433;
$db->connect('192.168.86.100',$user,$password,'NORTHWIND');

$db->debug = true;
$db->bulkBind = true;
$db->startTrans();

$dataBulkInsert = array(
	array(
    0 => 'Paulchen',
    1 => NULL,
    2 => '',
    3 => 91001,
    4 => NULL,
    5 => 'ME',
    6 => 'IT-EN',
    7 => 'CD TEH Electric',
    8 => 'CD TEH Electric Zahlen',
    9 => 0.0,
    10 => NULL,
    11 => '2021-07'
	),
array(
	0 => 'Paulchen',
    1 => NULL,
    2 => '',
    3 => 91001,
    4 => NULL,
    5 => 'ME',
    6 => 'IT-EN',
    7 => 'CD TEH Electric',
    8 => 'CD TEH Electric Zahlen',
    9 => 0.0,
    10 => NULL,
    11 => '2021-07'
	));
$sql = "INSERT INTO TEST2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12) values (?,?,?,?,?,?,?,?,?,?,?,?)";
$db->execute($sql,$dataBulkInsert);

$db->completeTrans();
````

**Comment by geri777** [comment]
I am very sorry. I have cost you al lot of time. I have now found out that my wrapper class does not pass through the `$db->bulkBind` parameter. After fixing this, the bulk insert works.

**Comment by mnewnham** [comment]
Glad you could resolve your own program issues

**Comment by geri777** [comment]
Do you have a donation site? I would like to send you a Pizza for your great support ;-)

**Comment by mnewnham** [comment]
Thanks for the kind offer. We don't have anything like that but your thanks is appreciated
