### ISSUE TITLE
JSON_Decode and update

### ISSUE THREAD

**Issue by vscode-pmaher** [ADOdb/ADOdb#741]
How does one do the equivalent of the code example below with the ADODB library?: I want to update records in MySQL table from decoded JSON array:

```
$data = json_decode($_POST['data']);

foreach($data as $item) {
	 $sql="UPDATE a_ukcd_manufacturers SET make_order=$item->order where make_id=$item->id";
	 mysqli_query($mysqli, $sql);
}
```

**Comment by mnewnham** [comment]
Simply replace your ``mysqli_query()`` with ``$db->execute()``, assuming that ``$db`` is a valid ADOdb object, so:
````php
$data = json_decode($_POST['data']);

foreach($data as $item) {
	 $sql="UPDATE a_ukcd_manufacturers SET make_order=$item->order where make_id=$item->id";
	 $db->execute($sql);
}
````
But given you are accepting post parameters, it might be better to harden your statement to prevent injection attacks
````php
$data = json_decode($_POST['data']);

 $sql="UPDATE a_ukcd_manufacturers SET make_order=? where make_id=?";

foreach($data as $item) {
        $bind = array($item->order,$item->id);
	$db->execute($sql,$bind);
}

**Comment by vscode-pmaher** [comment]
This doesn't work for some reason thinks $data is empty ....  Returns 'Invalid argument supplied for foreach()' even though data is posted. If I test with simple MySQLi connection all OK ...

**Comment by mnewnham** [comment]
If you are getting ``invalid argument supplied do foreach``, then that's nothing really to do with the database manipulation method. That means that the data that you are providing to the ``foreach`` loop isn't an array, most likely the ``data`` element is empty.

**Comment by mnewnham** [comment]
As you have not commented further on this, I'm guessing that you have resolved your problem. If you need further help on this, feel free to re-open the issue,

**Comment by WebSpectrum** [comment]
Strangely, the ADODB solution you offered does not work for some reason, yet standard MySQLi methods like these both

`$data = json_decode($_POST['data']);

foreach($data as $item) {
	 $sql="UPDATE a_ukcd_manufacturers SET make_order=$item->order where make_id=$item->id";
	 mysqli_query($mysqli, $sql);
}`
or this work as expected:
`$data = json_decode($_POST['data']);

$sql=$mysqli->prepare("UPDATE a_ukcd_manufacturers SET make_order=? where make_id=?");
foreach($data as $item) {
$sql->bind_param('ii', $item->order, $item->id);
$sql->execute();
}`
