### ISSUE TITLE
Critical error in postgres driver in version 5.21.1

### ISSUE THREAD

**Issue by liborm85** [ADOdb/ADOdb#752]
Parameter was renamed in method `fetchField` from `$off` to `$fieldOffset` by commit https://github.com/ADOdb/ADOdb/commit/9f6f327b9d5b29d14565fa0ab4308354bf050d2d, but not in method body:
https://github.com/ADOdb/ADOdb/blob/44237c688cc66045dd266c7865fc7a85ffea833d/drivers/adodb-postgres64.inc.php#L987-L996

Postgres driver now nothing works.

**Comment by dregad** [comment]
Thanks for the report and sorry about that.
