### ISSUE TITLE
Autoexecute does not quote column names (mysql)

### ISSUE THREAD

**Issue by geri777** [ADOdb/ADOdb#754]
I have table field named "longText" in my mySQL table. 
When I do the following, I get a mySQL syntax error, because "longtext" is a reserved word.

`$db->AutoExecute('mytable', ['longText' => 'hello world'], 'INSERT');`

I am using mySQL 5.7.11 and ADOdb 5.21.2

The error message is: 
`SQL 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LONGTEXT='hello world' at line 1`

Not sure if this is a duplicate of https://github.com/ADOdb/ADOdb/issues/390

**Comment by dregad** [comment]
> I have table field named "longText" in my mySQL table.

As a side note, it is not a very good practice to use a reserved keyword as column name.

> The error message is:
> `SQL 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LONGTEXT='hello world' at line 1`

Did you set [$ADODB_QUOTE_FIELDNAMES](https://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_quote_fieldnames) ? If != false, ADOdb will escape the fields as appropriate for the database, which should fix the problem.

```php
$ADODB_QUOTE_FIELDNAMES = true;
$db->AutoExecute('mytable', ['longText' => 'hello world'], 'INSERT');

// Executes INSERT INTO mytable ( `LONGTEXT` ) VALUES ( 'hello world' ) 
```

> Not sure if this is a duplicate of #390

I don't think so; it may however be related to #746, but as you indicated using 5.21.2 hopefully it is not.

**Comment by geri777** [comment]
I have tried `$ADODB_QUOTE_FIELDNAMES = true`. It doesn't seem to have any affect on my problem.
Maybe an important information is, that I am running the script command-line (PHP CLI).

**Comment by dregad** [comment]
Using CLI has nothing to do with it. I tested from CLI myself, and I can both 
- reproduce the error you reported (when $ADODB_QUOTE_FIELDNAMES is not initialized i.e. null), and 
- execute the INSERT statement successfully with `$ADODB_QUOTE_FIELDNAMES = true`.

This demonstrates that using ADODB_QUOTE_FIELDNAMES **does** fix the problem.

So there must be something else on your end, and if you expect further help you'll have to provide additional information to reproduce the problem.

For the record, here's my test case
```
mysql> create database test;
Query OK, 1 row affected (0.10 sec)

mysql> use test;
Database changed
mysql> create table mytable (`longtext` varchar(100));
Query OK, 0 rows affected (0.09 sec)
```

```php
<?php
include 'adodb.inc.php';
$db = ADONewConnection('mysqli');
$db->connect('localhost', 'username', 'password', 'test');
$db->debug = true;
var_dump($ADODB_QUOTE_FIELDNAMES);
$db->autoExecute('mytable', ['longtext' => 'hello world'], 'INSERT');
$ADODB_QUOTE_FIELDNAMES = true;
$db->autoExecute('mytable', ['longtext' => 'hello world'], 'INSERT');
```

Output (trimmed for brevity, `[...]` indicates removed text):
```
NULL
[...]
-----<hr>
Query: INSERT INTO mytable ( LONGTEXT ) VALUES ( 'hello world' ) failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LONGTEXT ) VALUES ( 'hello world' )' at line 1
[...]
-----<hr>
(mysqli): INSERT INTO mytable ( `LONGTEXT` ) VALUES ( 'hello world' ) 
   
-----<hr>
```

**Comment by geri777** [comment]
Hi, I have now found out what my problem was.

I am using a database class like this (pseudocode):

```
class db {
    public function connect() {
         $ADODB_QUOTE_FIELDNAMES = true;
         $this->adodb=NewADOConnection(...);
         ...
    }
}
```

This does not work (which is somehow clear, if I think about it twice). 
The variable has to be defined outside of my class, then it works.

Settings via unscoped variables is a bad thing, imho. 

A good fix would be a method, which sets those global variables. 

For example: 
`adodb->SetOption ('ADODB_QUOTE_FIELDNAMES', true);`
