### ISSUE TITLE
Fatal error in declaration ADODB_pdo::metaIndexes

### ISSUE THREAD

**Issue by richp10** [ADOdb/ADOdb#756]
Bug exists in latest - 5.21.2 - and at least the last three versions - I found this when using phpPgAdmin6 but am pretty certain it is an adoDb BUG

`Fatal error: Declaration of ADODB_pdo::metaIndexes($table, $normalize = true) must be compatible with ADOConnection::MetaIndexes($table, $primary = false, $owner = false) in F:\TOOLS\phpPgAdmin6\vendor\adodb\adodb-php\drivers\adodb-pdo.inc.php on line 276`

Changing that line to:

`	public function metaIndexes($table,$normalize=true, $owner=false)`

Removed the error and the app loaded.

**Comment by dregad** [comment]
This was actually fixed in master branch (see #717) and should have been backported to 5.21 branch, but for some reason this was never done. I'll take care of this now, and close this as duplicate.
