### ISSUE TITLE
$ADODB_COUNTRECS global infects other connections.

### ISSUE THREAD

**Issue by Mike-Benoit** [ADOdb/ADOdb#761]
We recently ran into an issue where at seemingly random times ADODB would return record sets with "_numOfRows=-1". Of course this would break the entire application as all calls checking that a query returned results (ie: "$rs->RecordCount() > 0" ) would fail.

We traced it down to a case where we were using ADODB to access LDAP for authentication purposes, and a separate ADODB connection to PostgreSQL for all database queries, but in some cases an LDAP query would trigger an exception in $db->getRow() during the "Execute()" call in this part of the code:
```
		$crecs = $ADODB_COUNTRECS;
		$ADODB_COUNTRECS = false;

		$rs = $this->Execute($sql,$inputarr);

		$ADODB_COUNTRECS = $crecs;
```

So $ADODB_COUNTRECS is set to false, an exception is triggered when calling $this->Execute(), the application handles it as necessary, but when it later tries to execute queries on the separate database connection, they now all fail because that global never got reset and has now infected all other ADODB connections, resulting in complete failure.

We can work around this relatively easy in our application code since our use of LDAP is quite minimal. But I could see many cases where it wouldn't be practical to do it at all. 

Is there any easy fix that can be implemented in ADODB, short of refactoring out all global variables?

**Comment by dregad** [comment]
@Mike-Benoit without feedback from you I assume you're OK with this. Will merge shortly.
