### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by zidingz** [ADOdb/ADOdb#766]
Hey there!

I belong to an open source security research community, and a member (@meme-lord) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mnewnham** [comment]
@dregad I noticed that what they are actually asking is for us to complete the section at the top of the page in the project, i.e.

**Security -> Security Policy**, which creates an "official" github SECURITY.md

**Comment by JamieSlome** [comment]
@dregad, if you would prefer you can visit the report directly here:

https://huntr.dev/bounties/bdf5f216-4499-4225-a737-b28bc6f5801c/

It is private and only visible to maintainers with repository write permissions.

**Comment by dregad** [comment]
@JamieSlome that's great, thanks - I was able to connect to huntr platform and get the details about the issue. I'll look into it.

I'll create a SECURITY.md and close this issue shortly.
