### ISSUE TITLE
MySQLi not documented

### ISSUE THREAD

**Issue by JVApen** [ADOdb/ADOdb#77]
Hi,

I've been using adodb for a while now, though I still don't completely get it.
Do though some legacy code, I was using the mysqli driver.

Taking the opportunity of cleaning up the code while upgrading to 5.19,
I was looking into the difference between the different mysql-drivers,
e.g. mysqli, mysql, mysqlpo and mysqlt
however when going through the documentation, I've only found some description of mysql and mysqlt.

As a result, I've changed my driver to mysqlt, though I don't know which effects this has on my transactions.

Is is possible to document the difference between the different Mysql versions and tell which one should be used in some classic usecases?

**Comment by dregad** [comment]
- *mysql* is the [original PHP MySQL API](http://php.net/manual/en/book.mysql.php)
- *mysqlt* is derived from mysql, plus transactions;
- *mysqlpo* - generally in ADOdb, "po" denotes a "portable" version, but in this case the file is identical to mysqlt, and TBH I have absolutely no idea why 2 files exists;
- **mysqli** is the [PHP MySQL Improved](http://php.net/manual/en/book.mysqli.php) extension, and what you should be using as *mysql* is deprecated in PHP 5.5
