### ISSUE TITLE
core: Return type of ADODB_Iterator_empty::current() deprecated

### ISSUE THREAD

**Issue by Darksymphony75** [ADOdb/ADOdb#771]
Deprecated: Return type of ADODB_Iterator_empty::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in adodb5\adodb.inc.php on line 3456

Using the ADOdb version 5.21.3 with PHP 8.1

**Comment by Bozosoft** [comment]
Idem on lines 3446, 3448, 3456, 3460, 3512, 3572, 3576, 3580; 3584, 3588, 3672
Using ADOdb version 5.21.3 with PHP 8.1.RC6

**Comment by marinaglancy** [comment]
Hello!The same problem with the class ADODB_Iterator and probably more

**Comment by dregad** [comment]
@marinaglancy b3d9a12bb6104b4859700008bb1c1cccadad564e adds the `#[\ReturnTypeWillChange]` hint to ADODB_Iterator's method too, are you saying you still get the deprecation warning after  that ? If so, could you please be more specific, or even better provide a pull request with the fix ?

**Comment by marinaglancy** [comment]
Hello @dregad  thanks for the replying. I did not check the commit, I was replying to the issue description. I looked at the commit now and the changes match the ones I had in the Moodle branch https://github.com/moodle/moodle/compare/master...marinaglancy:MDL-73016-master (path in Moodle is lib/adodb/adodb.inc.php). Thank you!

**Comment by idontusenumbers** [comment]
Any reason for not annotating the methods of the interface with the proper types instead of using the workaround?

**Comment by dregad** [comment]
> Any reason for not annotating the methods of the interface with the proper types instead of using the workaround?

@idontusenumbers compatiblity with pre-7.0 PHP versions, which we have not yet formally dropped (but will do soon)
