### ISSUE TITLE
[core] Proposal to remove the ADOdb Database Replication add-on

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#780]
The ADOdb_Replicate class (in **_adodb-replicate.inc.php_**) attempts to provide a method for replicating both the structure and data in databases across supported drivers of ADOdb. In light of the following, I propose eliminating this tool from the supported release:

- Unsupported
- Unupdated
- Undocumented
- Does not support more modern, complex datatypes
- Superseded by more sophisticated tools from database manufacturers

**Comment by dregad** [comment]
Fine with me.

**Comment by dregad** [comment]
Shall I mark it as deprecated in 5.22 and remove in 5.23 ? Or remove it immediately ?
