### ISSUE TITLE
Issue While Execute Any Query.

### ISSUE THREAD

**Issue by iamprdpydv** [ADOdb/ADOdb#786]
Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, int given in E:\xampp\php\pear\adodb\drivers\adodb-mysqli.inc.php:896 Stack trace: #0 E:\xampp\php\pear\adodb\drivers\adodb-mysqli.inc.php(896): mysqli_num_rows(-1) #1 E:\xampp\php\pear\adodb\adodb.inc.php(2986): ADORecordSet_mysqli->_initrs() #2 E:\xampp\php\pear\adodb\adodb.inc.php(1091): ADORecordSet->Init() #3 E:\xampp\php\pear\adodb\adodb.inc.php(1049): ADOConnection->_Execute('SELECT VERSION(...', false)

**Comment by dregad** [comment]
Can you clarify which version of ADOdb you're using, and provide a code snippet allowing to reproduce the error please.

**Comment by iamprdpydv** [comment]
i'm using the latest one and using MariaDB.

**Comment by dregad** [comment]
Sorry but you will have to provide more details than this if you expect any help.

Based on your stack trace the error occurs while calling mysqli_num_rows() at line 896, but this function is only ever called in ADORecordSet_mysqli::_initrs() which is at line 1293 in ADOdb 5.21.3 / 1442 in master branch. So again, which version are you using ?

And again, **provide a code snippet allowing to reproduce the error**.

**Comment by mnewnham** [comment]
As we have not heard from you on this issue, we assume you have resolved the issue yourself so are closing it off. If you need assistance on this issue, please re-open, adding the requested code snippet
