### ISSUE TITLE
PDO_ODBC driver support?

### ISSUE THREAD

**Issue by phpcontrols** [ADOdb/ADOdb#799]
Is it not supported because it does not appear on https://adodb.org/dokuwiki/doku.php?id=v5:database:pdo? While ADOdb can connect to IBM-DB2 using the IBM_DB2 driver, IBM is finally adopting PDO and migrating to PDO_ODBC.

**Comment by dregad** [comment]
We currently do not offer a driver for PDO_ODBC. Contributions are welcome.

You can connect to IBM DB2 using the [native *db2* driver](https://adodb.org/dokuwiki/doku.php?id=v5:database:ibm_db2). You can also try the [*odbc_db2* driver](https://adodb.org/dokuwiki/doku.php?id=v5:database:odbc#odbc_db2) but it's not actively supported.

**Comment by dregad** [comment]
@phpcontrols since you did not provide any feedback, I assume you're satisfied with my answer, and will proceed with closing this issue.
