### ISSUE TITLE
Affected_Rows() not returning correct value

### ISSUE THREAD

**Issue by frantique** [ADOdb/ADOdb#800]
Calling:
$adodb->Execute('update table set someting = 1');
$affected = $adodb->Affected_Rows();

Not returning correct value of x rows.

**Comment by mnewnham** [comment]
Driver? Version? Platform?

**Comment by frantique** [comment]
Driver: mysqli, v5.22.0, platform: linux

**Comment by dregad** [comment]
> Not returning correct value of x rows.

I'm not able to reproduce - affected_rows() returns the number of updated records, as expected.
Feel free to reopen the issue if you can provide evidence to the contrary.

**Comment by dregad** [comment]
@frantique please see discussion in #820. It could be that prior execution of a select statement was also what your problem, in that case feel free to test #827 and provide feedback.
