### ISSUE TITLE
[oci8] Oracle driver should support the session mode argument

### ISSUE THREAD

**Issue by eminemma** [ADOdb/ADOdb#801]
Hello,
I need it to support external authentication OCI_CRED_EXT

**Comment by mnewnham** [comment]
``oci_connect`` supports the credential mode as the last argument, but ADOdb only supports up to the penultimate argument (character set). I suggest using the setConnectionParameter feature to pass in this information, e.g.

`````php
$db->setConnectionParameter('session_mode',OCI_CRED_EXT);
$db->connect('blah, blah,blah')
````

Then modify ``ADODB_oci8:_connect()`` to pass in the appropriate argument

**Comment by mnewnham** [comment]
Damn, that was quick!!!

**Comment by dregad** [comment]
> Damn, that was quick!!!

Yeah :wink: that was an easy fix and I had an hour ahead of me, so...

**Comment by eminemma** [comment]
ty dregad!!! so fast!

**Comment by mnewnham** [comment]
Documentation updated with feature
