### ISSUE TITLE
memcached weighted servers not working (never connects)

### ISSUE THREAD

**Issue by setcooki** [ADOdb/ADOdb#807]
the example in https://adodb.org/dokuwiki/doku.php?id=v5:userguide:memcached does not work because of this line =

https://github.com/ADOdb/ADOdb/blob/ded096e9d97a0c06e82b062cfa432c55152293fc/adodb-memcache.lib.inc.php#L189

this will produce: 

```
    [serverControllers:ADODB_Cache_MemCache:private] => Array
        (
            [0] => Array
                (
                    [host] => Array
                        (
                            [host] => 192.168.86.91
                            [port] => 11211
                            [weight] => 70
                        )

                    [port] => 11211
                    [weight] => 0
                    [key] => 
                )

            [1] => Array
                (
                    [host] => Array
                        (
                            [host] => 192.168.86.92
                            [port] => 11211
                            [weight] => 30
                        )

                    [port] => 11211
                    [weight] => 0
                    [key] => 
                )

        )
```

Also this line > https://github.com/ADOdb/ADOdb/blob/ded096e9d97a0c06e82b062cfa432c55152293fc/adodb-memcache.lib.inc.php#L234 makes absolutely no sense since Memcached::getServerList() always returns an array and if no server is present it returns an empty array

**Comment by dregad** [comment]
@mnewnham I actually started working on this yesterday, but got sidetracked and could not finish as planned. I just finalized the fixes and submitted PR #816.

Since you assigned yourself to this, maybe you'd like to review and comment.

**Comment by mnewnham** [comment]
couple of items of note:

1. The code associated with the 'key' parameter is completely missing That portion of the code is associated with the new development path I was working on with the replacement caching and session modules and there has clearly been some mistake on my part that has allowed this to remain in the code base. I would recommend we pull the code associated with this feature from the current release. 
2. I don't quite understand what this is:
````php
			/** @noinspection PhpExpressionResultUnusedInspection */
```` 
Is this some tool you are using that is injecting this into the code? What does it mean?

**Comment by dregad** [comment]
See my answer in https://github.com/ADOdb/ADOdb/pull/816#issuecomment-1074935563
