### ISSUE TITLE
Firebird: undefined offset PHP Notice in _fetchField()

### ISSUE THREAD

**Issue by anton-lar** [ADOdb/ADOdb#808]
maybe this problem applies to another drivers

adodb-firebird.inc.php: 1056
```php
private function _fetchField($fieldOffset = -1)
```
the variable $fieldOffset is used in cycle (line 1076)

```php
for ($fieldOffset = 0; $fieldOffset < $this->_numOfFields; $fieldOffset++) {
```
the function should return array of fields when $fieldOffset = -1

Instead it access the array with last value

line 1113:
```php
if ($fieldOffset == -1) {
   return $this->fieldObjects;
}

return $this->fieldObjects[$fieldOffset];
```
simplest way to fix - use another loop variable

```diff
--- org.php	2022-03-11 19:29:00.426703291 +0300
+++ my.php	2022-03-11 19:29:01.678750758 +0300
@@ -1072,10 +1072,10 @@
 		$this->fieldObjectsHaveBlob = false;
 
 		$this->_numOfFields = fbird_num_fields($this->_queryID);
-		for ($fieldOffset = 0; $fieldOffset < $this->_numOfFields; $fieldOffset++) {
+		for ($_fieldOffset = 0; $_fieldOffset < $this->_numOfFields; $_fieldOffset++) {
 
 			$fld = new ADOFieldObject;
-			$ibf = fbird_field_info($this->_queryID, $fieldOffset);
+			$ibf = fbird_field_info($this->_queryID, $_fieldOffset);
 
 			$name = empty($ibf['alias']) ? $ibf['name'] : $ibf['alias'];
 
@@ -1100,9 +1100,9 @@
 			$fld->has_default = false;
 			$fld->default_value = 'null';
 
-			$this->fieldObjects[$fieldOffset] = $fld;
+			$this->fieldObjects[$_fieldOffset] = $fld;
 
-			$this->fieldObjectsIndex[$fld->name] = $fieldOffset;
+			$this->fieldObjectsIndex[$fld->name] = $_fieldOffset;
 
 			if ($fld->type == 'BLOB') {
 				$this->fieldObjectsHaveBlob = true;
```

**Comment by dregad** [comment]
Technically you're right I guess, but considering that this private function is only called when initializing the recordset (see _initrs()_) to populate the field objects cache and the return value is not used in this case, I fail to see how this could actually be a problem.

Can you provide some context ?

**Comment by anton-lar** [comment]
>

**Comment by anton-lar** [comment]
Actually does not matter what the function returns. It access array out of bounds and crashes.

**Comment by anton-lar** [comment]
I will try to provide stacktrace on Monday.

**Comment by dregad** [comment]
Great, thanks. And a code snippet to reproduce would be nice too

**Comment by dregad** [comment]
Thanks for the details, I see what you mean now ! Will fix.
