### ISSUE TITLE
mysqli remove legacy $optionFlags property

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#814]
mysqli $optionFlags property is ignored by _connect(). It is reset to an empty array, so the subsequent foreach loop never does anything.

https://github.com/ADOdb/ADOdb/blob/d99127b8811a9f949c00ab425065e380dce6bdc1/drivers/adodb-mysqli.inc.php#L182-L186

This change was introduced in 5.21.0-beta.1, commit 0e3d95cc2c38906a39172fcbdf1f4f28c8c955bd, as a fix for #166, but it seems unrelated to the issue being patched. 

@mnewnham can you please have a look ?

**Comment by mnewnham** [comment]
Will do today

**Comment by mnewnham** [comment]
It would appear that the ``optionFlags`` array is a MySQL only option that has been replaced by ``setConnectionParameter()``. Given that it has been non-functional for a substantial period of time, I would suggest scraping all reference to it out of the driver.

**Comment by dregad** [comment]
Thanks for looking into it. I'm fine with your recommended approach.
