### ISSUE TITLE
Affected_Rows() not returning correct value

### ISSUE THREAD

**Issue by beastybeast** [ADOdb/ADOdb#820]
Affected_Rows() is always returning false in my case.

Looks like the same problem as here: https://github.com/ADOdb/ADOdb/issues/800

I upgraded from 

$ADODB_vers = 'v5.20.14  06-Jan-2019';

to

$ADODB_vers = 'v5.22.0  2022-02-08';

And the following code fails 

```
$query = "INSERT INTO `sessions` (`id`, `tag`, `value`, `data`) VALUES (?, 'srpvalues', 'data', ?) ON DUPLICATE KEY UPDATE data = ?";
  $result = $db->Execute($query, array($data->email, $srpvalue, $srpvalue))
  or die(makereply($id, $pcrypt_errorstringarray[4].substr($query, 0, 200)." => ".$db->ErrorMsg(), 4));
/*
  trigger_error("DB: ".print_r($db, true));
  trigger_error("RESULT: ".print_r($result, true));
  trigger_error("AFFECTED: ".print_r($db->Affected_Rows(), true));
  trigger_error("RECORD: ".print_r($result->RecordCount(), true));  
*/
  if($db->Affected_Rows() == 0)
    die(makereply($id, $pcrypt_errorstringarray[4].substr($query, 0, 200)." => ".$db->ErrorMsg(), 4));
```
 if($db->Affected_Rows() == 0) is always true.

If I revert back to the old version everything works fine again?

NB: mysqli used

**Comment by beastybeast** [comment]
Looks as if the error is still there in version 5.22.1 ?

Just downloaded latest stable release from https://adodb.org to test is out

**Comment by dregad** [comment]
@beastybeast I just tried to reproduce this with 5.22.1, as follows

```php
$db = NewADOConnection('mysqli');
$db->connect($host, $user, $password, $database);
$sql = "insert into test (id, data) values (?, ?) on duplicate key update data = ?";
$r = $db->execute($sql, [1, "data",	"update" . time()]);
var_dump($db->affected_rows());
```

Displays `int(2)`, as expected (same results as with 5.20.14). Am I missing something ? Can you provide more information ?

**Comment by beastybeast** [comment]
I am using PHP 8.1 on a Centos 7 platform (Koozali)

This is how I open the DB connection

$db = ADONewConnection(pcrypt::db_system);
$db->PConnect(pcrypt::db_server, pcrypt::db_user, pcrypt::db_password, pcrypt::db_database) or die(makereply($id, $pcrypt_errorstringarray[1], 1));
$db->Execute("SET NAMES 'utf8'");

The only change I do is replace the files (adodb version) that is included like this:

require_once("adodb/adodb.inc.php");

For sure before the above call

**Comment by beastybeast** [comment]
class pcrypt extends pcrypt_online
{
    // deleted text

    const db_system = "mysqli"; // see above
    const db_server = "localhost"; // IP adr. of where database is located
    const db_user = "passwords"; // database user name.
    const db_password = "deleted"; // database password
    const db_database = "pcrypt"; // name of database

    // deleted text
}

**Comment by beastybeast** [comment]
Server: Localhost via UNIX socket
Servertype: MariaDB
Serverforbindelse: SSL benyttes ikke Dokumentation
Serverversion: 5.5.68-MariaDB - MariaDB Server
Protokolversion: 10
Bruger: xxxxx@localhost
Servers tegnsæt: cp1252 West European (latin1)

All DB tables are MyISAM utf8_unicode_ci

**Comment by dregad** [comment]
My setup is PHP 8.1 on Ubuntu 20.04.4, MySQL 8.0.28 instead of MariaDB. My default config is InnoDB, but I tested with MyISAM also with the same results.

What do you get when you run the code snippet I posted above ? 

Can you check the value of [$stmt->affected_rows](https://www.php.net/manual/en/mysqli-stmt.affected-rows.php) in ADODB_mysqli::_query() method (*drivers/adodb-mysqli.inc.php* line 1322)
Is the result consistent with what you get when executingthe same query manually ?

Note: with an UPSERT statement, I *do* get 0 rows affected, if the 3rd parameter's value is identical to the one stored in the DB - this is normal behavior with MySQL, as shown below
```
mysql> insert into test (id, data) values (3, 'data') on duplicate key update data = 'update';
Query OK, 1 row affected (0.02 sec)

mysql> insert into test (id, data) values (3, 'data') on duplicate key update data = 'update';
Query OK, 2 rows affected (0.01 sec)

mysql> insert into test (id, data) values (3, 'data') on duplicate key update data = 'update';
Query OK, 0 rows affected (0.00 sec)
```

**Comment by beastybeast** [comment]
Looks as if the code at (drivers/adodb-mysqli.inc.php line 1322) is never called ??

At least I tried to do this and do not get any output.

```
trigger_error("DEBUG: ".print_r($stmt->affected_rows, true));
      
if ($stmt->affected_rows > -1)
{
  $this->statementAffectedRows = $stmt->affected_rows;
  return true;
}
```

**Comment by beastybeast** [comment]
I know that the UPDATE statement, you do get 0 rows affected, if the 3rd parameter's value is identical to the one stored in the DB - but this is never the case in my code. First of all the record shall not be there to begin with (have tested this) and the 3rd parameter is never the same.

**Comment by beastybeast** [comment]
This code:

```
$dbtest = NewADOConnection('mysqli');
$dbtest->connect('localhost', 'passwords', '641677216150a2f1', 'pcrypt');
$sql = "insert into sessions (id, data) values (?, ?) on duplicate key update data = ?";
$r = $dbtest->execute($sql, [1, "data", "update" . time()]);
trigger_error("TEST: ".print_r($dbtest->Affected_Rows(), true));
```

Get the correct result: PHP Notice:  TEST: 1

**Comment by beastybeast** [comment]
This is very strange........

Changing my init to this

```
$db = NewADOConnection(pcrypt::db_system);
$db->connect(pcrypt::db_server, pcrypt::db_user, pcrypt::db_password, pcrypt::db_database);
```

Does not fix the problem. So what is happening in between ???

**Comment by beastybeast** [comment]
I have now found out the this function ruin it - trying to understand why now.

```
function getuseremail($db, $session, &$sessiondata = "")
{
	$query = "SELECT value, data FROM `sessions` WHERE `id` = ? AND `tag` = 'session'";
	if(false == ($result = $db->Execute($query, array($session))))
		return false;

	if($result->RecordCount() == 1)
  {
    $sessiondata = json_decode($result->fields['data']);
    $ip = getrealipaddr();

    if($sessiondata->iplock && (substr($ip, 0, 9) !== "Local IP:")) // Do not test local IP
    {
      if($sessiondata->ip != $ip)
      {
        if(isset($sessiondata->proxyforwardip))
        {
          if($sessiondata->proxyforwardip != $ip)
          {            
            trigger_error("PCRYPT: getuseremail iplock proxy: " . $ip);
            return false;
          }
        }
        else
        {
          trigger_error("PCRYPT: getuseremail iplock: " . $ip);
          return false;
        }
      }
    }

    return $result->fields['value'];
	}

	return false;
}
```

**Comment by beastybeast** [comment]
In this special case $session is not set and for some reason this breaks it.

So in my view the call:

$query = "SELECT value, data FROM `sessions` WHERE `id` = ? AND `tag` = 'session'";
	if(false == ($result = $db->Execute($query, array($session))))
		return false;

With invalid or not set $session variable breaks the logic later on?

**Comment by beastybeast** [comment]
Looks like that any select query breaks the logic ??

**Comment by dregad** [comment]
> Looks like that any select query breaks the logic ??

Yep, that's it ! Good catch :+1: 
I can now reproduce the problem, will fix.

**Comment by dregad** [comment]
Repro code
```php
$db = NewADOConnection('mysqli');
$db->connect($host, $user, $password, $database);
$db->execute("select * from test"); // sets \ADODB_mysqli::$isSelectStatement = true
$sql = "insert into test (id, data) values (?, ?) on duplicate key update data = ?";
$r = $db->execute($sql, [1, "data", "update" . time()]); // does not reset \ADODB_mysqli::$isSelectStatement
var_dump($db->affected_rows());
```
Displays `bool(false)`

**Comment by dregad** [comment]
@beastybeast your feedback on the proposed fix will be welcomed.

**Comment by beastybeast** [comment]
Downloaded https://github.com/ADOdb/ADOdb/tree/hotfix/5.22

But it still gives me the same error?

**Comment by dregad** [comment]
> Downloaded https://github.com/ADOdb/ADOdb/tree/hotfix/5.22

Wrong branch... see https://github.com/dregad/ADOdb/tree/i820-affected-rows

**Comment by beastybeast** [comment]
Now it seam to work fine :-)

**Comment by xermedia** [comment]
The problem is somewhere along the way they changed "Affected_rows" to "affected_rows". The capital A does not work, it has to be lowercase.

**Comment by beastybeast** [comment]
> The problem is somewhere along the way they changed "Affected_rows" to "affected_rows". The capital A does not work, it has to be lowercase.

It work currently fine

**Comment by dregad** [comment]
> The problem is somewhere along the way they changed "Affected_rows" to "affected_rows". The capital A does not work, it has to be lowercase.

@xermedia That has absolutely nothing to do with it. 

In PHP (quoting [the manual](https://www.php.net/manual/en/functions.user-defined.php)), *Function names are case-insensitive for the ASCII characters A to Z, though it is usually good form to call functions as they appear in their declaration.*

**Comment by xermedia** [comment]
You are correct. Thank you for correcting me. I found my issue. In the software we use, the coders used affected_rows on select statements and it use to work with adodb 5.15 but in version 5.21 it no longer does. Not sure why it ever worked that way in the first place. See here, https://github.com/ADOdb/ADOdb/issues/820
