### ISSUE TITLE
Wrong SQL Statement failed on preparation

### ISSUE THREAD

**Issue by marco-dc** [ADOdb/ADOdb#828]
Hi,

i've encountered a strange error on Sql Statement preparation. The library assert wrongly that query contains not aggregated columns.
Executing the same query on MySQL doesn't shows errors and execute correctly.

Error log
_1055: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'dbName.FIELD_NAME' which is not functionally dependent on columns in GROUP BY clause; this is
incompatible with sql_mode=only_full_group_by_

- ADOdb version: **5.22.1** (same behavior in 5.22.0)
- PHP version: **7.4**
- MySQL version: **5.7.37**

**Comment by dregad** [comment]
Posting the actual SQL statement would help...

**Comment by marco-dc** [comment]
```
SELECT T.*, C.D_CLASS, TD.ID_TEST_DETAIL, MAX_SCORE, TS.NAME TEST_SKILL_NAME, TR.NAME TEST_RATING_NAME,
COUNT(TRES.ID_TEST_RESULT) N_RESULTS, COUNT(TSTU.ID_TEST_STUDENT) N_STUDENTS FROM mng_test T 
JOIN mng_classes C ON C.ID_CLASS = T.ID_CLASS 
LEFT JOIN mng_test_detail TD ON TD.ID_TEST = T.ID_TEST 
LEFT JOIN com_test_skill TS ON TS.ID_TEST_SKILL = TD.ID_TEST_SKILL 
LEFT JOIN com_test_skill_groups TSG ON TSG.ID_TEST_SKILL_GROUP = TS.ID_TEST_SKILL_GROUP 
LEFT JOIN com_test_rating TR ON TR.ID_TEST_RATING = TSG.ID_TEST_RATING LEFT
JOIN mng_test_student TSTU ON TSTU.ID_TEST = T.ID_TEST 
LEFT JOIN mng_test_result TRES ON TRES.ID_TEST_DETAIL = TD.ID_TEST_DETAIL 
AND TRES.ID_TEST_STUDENT = TSTU.ID_TEST_STUDENT 
AND TRES.ID_TEST_RESULT IS NOT NULL 
WHERE T.ID_TEST = 12456187 
GROUP BY TD.ID_TEST_DETAIL 
ORDER BY TS.NAME
```

_1055: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'database_name.T.ID_TEST' which is not functionally dependent on columns in GROUP BY clause; this is
incompatible with sql_mode=only_full_group_by_

T.ID_TEST is foreign-key in mng_test_detail with 1-n relationship

@dregad tell me if you need more information about it

**Comment by mnewnham** [comment]
In this case, the response is correct. When **sql_mode=only_full_group_by** is set, then your group by statement must match the selected fields in the query. Older versions of MySQL differed from both standards and other databases in that you could create a select statement like this:

````php
SELECT a,b,c,SUM(d)
    FROM some_table
  ORDER BY a
   GROUP BY a
````
However, later versions of MySQL set the `sql_mode=only_full_group_by`` by default. This means that the query must be declared as:

````php
SELECT a,b,c,SUM(d)   //<---- Select Fields a,b,c plus a groupable value
    FROM some_table
  ORDER BY a
   GROUP BY a,b,c //<----- Group by a,b,c
````

There is more information [here](https://stackoverflow.com/questions/59536954/sql-mode-only-full-group-by)

 If you are writing purely for MySQL, then you can disable the sql_mode flag and the query will work ok. However you should remember that this format of query is not compatible with other databases. It's a good idea to get into the habit of writing queries that are standards-compliant

**Comment by marco-dc** [comment]
As I wrote in the first post, the query works well if execute directly on MySQL (5.7.37 sql_mode=only_full_group_by as @mnewnham said) and if I execute it on ADOdb v5.21.3 works well in the same way. So I think that the issue isn't related to sql_mode=only_full_group_by.
