### ISSUE TITLE
mssql: Automatic conversion of false to array is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by fluchette** [ADOdb/ADOdb#829]
Hi,

I get the following message with the mssqlnative driver in PHP 8.1 :

PHP Deprecated: Automatic conversion of false to array is deprecated adodb-mssqlnative.inc.php on line 154

Thanks

**Comment by dregad** [comment]
I just found out that the same issue had been [reported on StackOverflow](https://stackoverflow.com/questions/71035322/php-deprecated-automatic-conversion-of-false-to-array-is-deprecated-adodb-mssql) a couple months ago.
