### ISSUE TITLE
PostgreSQL: On PHP 8.1, Affected_Rows() always returns false.

### ISSUE THREAD

**Issue by ReimuHakurei** [ADOdb/ADOdb#833]
On PHP 8.1, Affected_Rows() always returns false when using PostgreSQL.

```
	function _affectedrows()
	{
		if (!is_resource($this->_resultid) || get_resource_type($this->_resultid) !== 'pgsql result') return false;
		return pg_affected_rows($this->_resultid);
	}
```

I'm pretty sure this is because of that get_resource_type check -- On PHP 8.1.0 and above, the 'pgsql result' resource has been replaced by the PgSql\Result class:

https://www.php.net/manual/en/class.pgsql-result.php

I also see a bunch of other similar checks throughout adodb-postgres64.inc.php, which will also all need changing.

**Comment by dregad** [comment]
Thanks for the bug report. I believe your analysis is correct, will look into the PR you submitted.
