### ISSUE TITLE
Is adodb param binding preventing SQL injections?

### ISSUE THREAD

**Issue by coldwinds** [ADOdb/ADOdb#836]
As described in the documentation: 

https://adodb.org/dokuwiki/doku.php?id=v5:userguide:learn_bind:portability

## Hardening SQL Statements Against Injection Attacks

In addition to portability, described above, you can use the method [addQ()](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:addq) to **ensure** that special characters are escaped before use inside string variables.

The following code snippet is compatible across all databases supported by ADOdb

```php
$col1Ph = $db->param('col1');
$col2Ph = $db->param('col2');
$col3Ph = $db->param('col3');
 
 
$bindVars = [array](http://www.php.net/array)('col1'=>$db->addQ($someVariable),
                  'col2'=>$db->addQ($someOtherVariable),
                  'col3'=>$db->addQ($yetAnotherVariable));
 
 
$sql = "SELECT * FROM some_table 
                WHERE col1=$col1Ph 
                  AND col2=$col2Ph 
                  AND col3=$col3Ph";
$result = $db->execute($sql, $bindVars);
```

My question is if adodb param binding preventing SQL injections, why we still need to addQ() to the binding vars?

**Comment by mnewnham** [comment]
Yes, It's easy to see the mechanisms used by the underlying DBMS to bind the statement if you run your query in debug mode. You don't specify your system, but taking an example with MySQL: 

````php
$db->debug = true;

$SQL = "SELECT * FROM emloyees WHERE emp_no=?";

/*
* Using a portability example
*/
$p1 = $db->param('p1');
$bind = array('p1'=>1000);
$db->execute($SQL,$bind);
````
You can see the response:
````
-----<hr>
(mysqli-): SELECT * FROM employees WHERE emp_no=? 
   [ (0=>'i') (1=>'1000')  ]
-----<hr>
````
So why does the documentation suggest using **Quote()**?  There are 2 reasons:

1. Some of the documentation is really old, and some DBMS didn't support parameter binding (20 years ago). 
2. Parameter binding and escaping isn't mutually exclusive. Some good practice documentation recommends escaping string values stll - Personally I don't bother anymore, but some prefer a "belt and braces" approach

**Comment by coldwinds** [comment]
Hello, @mnewnham 

I'm using MySQL with mysqli driver, I run this code in debug mode

```php
$db->debug = true;

$SQL = "SELECT * FROM emloyees WHERE emp_no=?";

$bind = array("11'1");
$db->execute($SQL, $bind);
```

output:

```
-----<hr>
(mysqli): SELECT * FROM emloyees WHERE emp_no='11\'1' 
   
-----<hr>
```

Looks like the binding value was automatically escaped showed in the debug message, is that mean I don't need to addQ() again in this context?

**Comment by mnewnham** [comment]
It looks like you are using an older version of ADOdb which was not binding MySQL parameters correctly. Please update to the latest version (5.22).

**Comment by dregad** [comment]
Since we have not heard back from you, I assume Mark answered your question. If not, feel free to reopen.
