### ISSUE TITLE
Active Record changes the case of class properties

### ISSUE THREAD

**Issue by f7h** [ADOdb/ADOdb#837]
Upgrading from ADOdb 5.20.21 to 5.21.0 - 5.22.2 changes the case of class properties:

```php
include_once __DIR__ . '/../adodb.inc.php';
include_once __DIR__ . '/../adodb-active-record.inc.php';

$ADODB_QUOTE_FIELDNAMES = 'NATIVE';
define('ADODB_ASSOC_CASE', ADODB_ASSOC_CASE_NATIVE);

$db = ADOnewConnection('pdo_mysql://user:pass@localhost/northwind');
ADOdb_Active_Record::SetDatabaseAdapter($db);

$db->Execute("CREATE TEMPORARY TABLE `people` (`idNumber` int(10) unsigned NOT NULL)");
class Person extends ADOdb_Active_Record {}

$person = new Person('people', ['idNumber']);

var_dump(property_exists($person, 'idNumber'));
```

```
Expected:
bool(true)

Actual:
bool(false)
```

Instead, there is a property "IDNUMBER".

ADODB_ASSOC_CASE_UPPER and ADODB_ASSOC_CASE_LOWER work as expected.

It seems that a merge from 5.20 to 5.21 broke it, but I couldn't find the actual change.

**Comment by dregad** [comment]
I just ran git bisect, which identified 4a3676b1 (see #610) as the first bad commit, so this regression was actually introduced in 5.20.17 (not 5.20.21 as stated in your report). 

This seems to be related to issue #792, apparently sharing the same root cause.

**Comment by dregad** [comment]
@f7h could you please test if the following patch fixes your use cases ?

```patch
diff --git a/adodb-active-record.inc.php b/adodb-active-record.inc.php
index ad40640a..5fbe7b90 100644
--- a/adodb-active-record.inc.php
+++ b/adodb-active-record.inc.php
@@ -501,7 +501,8 @@ class ADODB_Active_Record {
            }
            break;
        default:
-           foreach($cols as $name => $fldobj) {
+           foreach($cols as $fldobj) {
+               $name = $fldobj->name;
 
                if ($ADODB_ACTIVE_DEFVALS && isset($fldobj->default_value)) {
                    $this->$name = $fldobj->default_value;
```

**Comment by f7h** [comment]
Hm, it was definitely still working in 5.20.21, must be a combination with another change in 5.21.

But yes, that change fixes it. Thank you! :+1:

**Comment by dregad** [comment]
> Hm, it was definitely still working in 5.20.21, must be a combination with another change in 5.21.

Actually you're right, I re-ran the bisect and the *real* offending commit is in fact 7b0d040355753aa95e6068b54bbaf3014f8da3e8 from **v5.21.0-beta.1**; 4a3676b1628edf248105f8fe2e74dbd7e3645d5d is just its backport to the 5.20 hotfix branch, I must have copy-pasted the wrong SHA.
