### ISSUE TITLE
Source code for the ADOdb C extension

### ISSUE THREAD

**Issue by agwells** [ADOdb/ADOdb#84]
I can't seem to find the source code for the ADOdb C extension anywhere. You can install the binary on Ubuntu with the "php5-adodb" package, and there are still hooks for it in the ADOdb PHP code. And there are older links to it online that point to the sourcecode page, http://adodb.sourceforge.net/#extension, but that URL no longer seems to be correct.

It looks like maybe it got lost in the transition from Sourceforge to Github?

**Comment by dregad** [comment]
Actually, this extension is no longer maintained (since version 5.04 if memory serves), and as far as I know @heyjohnlim never published the source code for it.

**Comment by agwells** [comment]
Well, for anyone who's interested, I've found the source code for the debian-packaged version of it here: http://anonscm.debian.org/cgit/pkg-php/php-adodb.git

It was last updated in 2012. :)
