### ISSUE TITLE
PHP 8.1 : PHP Deprecated: strcmp() null parameter

### ISSUE THREAD

**Issue by fundo-moretti** [ADOdb/ADOdb#844]
Hi,

When using ADOConnection::GetUpdateSQL() with NULL fields, PHP 8.1 output this message:

Deprecated: strcmp(): Passing null to parameter \#1 ($string1) of type string is deprecated in adodb-lib.inc.php on line 753

Thanks

**Comment by dregad** [comment]
I'm not really sure why we're using strcmp() here - using a strict comparison operator (i.e. `$val !== $arrFields[$upperfname]`) would seem more logical and efficient.

@mnewnham thoughts ?
