### ISSUE TITLE
How to include adodb session2 if installed by composer

### ISSUE THREAD

**Issue by dmiepub** [ADOdb/ADOdb#846]
How to include adodb session2 if installed by composer; Pls help

**Comment by dregad** [comment]
@dmiepub Why are you posting the same question both here and on our Gitter chat ?

As already [answered there](https://gitter.im/ADOdb/ADOdb?at=62c81ce4fe909e3ec76f4e0e), please **read the documentation** https://adodb.org/dokuwiki/doku.php?id=project:include_file_guide
