### ISSUE TITLE
Unable to SetCharSet (to utf8) using mysqli driver

### ISSUE THREAD

**Issue by wesyah234** [ADOdb/ADOdb#847]
I have extended characters in my database (Peña) (ie. tilde above the n character), and cannot seem to select them out with adodb:

```
$sql = "select middlename from tblPersons where personid=19095";
$db = newAdoConnection('mysqli');
printf("initial character set %s\n", $db->GetCharSet());
$db->SetCharSet('utf8');
printf("current character set %s\n", $db->GetCharSet());
$return = $db->Connect($servername, $username, $password, $dbname);
$stuff = $db->Execute($sql);
$items = $stuff->getRows();
var_dump($items);
```

output:

initial character set 
current character set 
array(1) {
  [0]=>
  array(2) {
    [0]=>
    string(4) "Pe?a"
    ["middlename"]=>
    string(4) "Pe?a"
  }
}

As a sanity check, I ran the following code bypassing adodb:
```

$sql = "select middlename from tblPersons where personid=19095";

printf("Using direct mysqli methods\n");

$conn = new mysqli($servername, $username, $password, $dbname);
printf("Initial character set: %s\n", $conn->character_set_name());
$result = $conn->query($sql);
// output data of each row
while ($row = $result->fetch_assoc()) {
  var_dump($row);
}

$conn->set_charset("utf8");
printf("After setting to utf8, character set: %s\n", $conn->character_set_name());

$result = $conn->query($sql);
// output data of each row
while ($row = $result->fetch_assoc()) {
  var_dump($row);
}
$conn->close();
```

output:

Using direct mysqli methods
Initial character set: latin1
array(1) {
  ["middlename"]=>
  string(4) "Pe?a"
}
After setting to utf8, character set: utf8
array(1) {
  ["middlename"]=>
  string(5) "Peña"
}

my php version:
> php -v
PHP 7.3.33 (cli) (built: Nov 16 2021 11:18:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group

**Comment by mnewnham** [comment]
Please review documentation for [adoConnection::setConnectionParameter()](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter&s[]=set&s[]=charset)

**Comment by wesyah234** [comment]
Thank you @mnewnham !!
doing:
`$db->setConnectionParameter(MYSQLI_SET_CHARSET_NAME, 'utf8');`
is the solution here for me.

My question now is: what's the purpose of the 
`$db->SetCharSet('utf8');`
method? as it doesn't seem to do what I would expect.  And, if one is converting from native mysqli code, one might try to do what I did to set the charset, since there's the:
`$conn->set_charset("utf8");`
and the SetCharSet seems to be a good equivalent if one is migrating code.

**Comment by mnewnham** [comment]
**setCharSet()** should be marked as deprecated in the documentation, but unfortunately we are behind in all kinds of things. we have replaced it with **setConnectionParameter()** because that method is available for use across almost all the supported databases

**Comment by wesyah234** [comment]
Thanks @dregad ... yes, calling setCharSet after the connect is what fixed it!  It would be helpful if some warning/error were thrown if one called this before a connect.
