### ISSUE TITLE
ubuntu 22.04 PHP  8.1 ADOdb5.22.2 mssqlnative connect fail

### ISSUE THREAD

**Issue by cnjameschan** [ADOdb/ADOdb#857]
err:
Fatal error: Uncaught TypeError: sqlsrv_query(): Argument #1 ($conn) must be of type resource, bool given in /var/www/html/adodb5/drivers/adodb-mssqlnative.inc.php:645 Stack trace: #0 /var/www/html/adodb5/drivers/adodb-mssqlnative.inc.php(645): sqlsrv_query() #1 /var/www/html/adodb5/adodb.inc.php(1550): ADODB_mssqlnative->_query() #2 /var/www/html/adodb5/adodb.inc.php(1527): ADOConnection->_Execute()

**Comment by mnewnham** [comment]
This error simply indicates that you haven't established a database connection. Could you run the same connection in debug mode please.

**Comment by cnjameschan** [comment]
(mssqlnative-): select * from IPLimit  

Fatal error: Uncaught TypeError: sqlsrv_query(): Argument #1 ($conn) must be of type resource, bool given in /var/www/html/adodb5/drivers/adodb-mssqlnative.inc.php:645 Stack trace: #0 /var/www/html/adodb5/drivers/adodb-mssqlnative.inc.php(645): sqlsrv_query() #1 /var/www/html/adodb5/adodb-lib.inc.php(1212): ADODB_mssqlnative->_query() #2 /var/www/html/adodb5/adodb.inc.php(1548): _adodb_debug_execute() #3 /var/www/html/adodb5/adodb.inc.php(1527)

**Comment by cnjameschan** [comment]
![image](https://user-images.githubusercontent.com/3215306/186059956-5464f6f6-8f0f-447b-90fe-a9128b973418.png)
![image](https://user-images.githubusercontent.com/3215306/186059973-52af29ad-a825-48a4-9d26-0f72762f1d39.png)

**Comment by cnjameschan** [comment]
![image](https://user-images.githubusercontent.com/3215306/186060074-8dc15216-3dc5-495e-bda1-4b5be0cbd6ec.png)

**Comment by mnewnham** [comment]
So mssqlnative is the native mode driver. You are showing the PDO driver information. Can you confirm which driver you are using

**Comment by mnewnham** [comment]
As you have not provided any further information on this I'm assuming you have resolved this yourself. Feel free to re-open if you need further help with the problem.
