### ISSUE TITLE
unexpected T_STRING, expecting T_CATCH in adodb.inc.php

### ISSUE THREAD

**Issue by rubo77** [ADOdb/ADOdb#859]
I get this error on my app with php 5:

    Parse error: syntax error, unexpected T_STRING, expecting T_CATCH in /var/www/app/vendors/phpgacl/adodb/adodb.inc.php on line 1955 

If I switch to php8 it is gone. It seems like PHP 5.3 does not understand the code block `finally` in a try-catch statement

**Comment by dregad** [comment]
Php 5.3 is no longer supported 

Please Check http://adodb.org/dokuwiki/doku.php?id=index#system_requirements

**Comment by dregad** [comment]
The _finally_ block was added in ADOdb 5.21.3 (see #761, ac2581aa7f5c264cf0fc996f6774f537e367938f), which requires at least PHP 5.5.9.

**Comment by rubo77** [comment]
Why did you do this change? The try catch finally block is the only code that doesn't work in PHP 5.3.

**Comment by mnewnham** [comment]
The last release of PHP 5.3 was 8 years ago. We, like many others package developers, have to make a judgement about versions of PHP to support. While there is currently only that small piece of non-compatible code, we must face the fact that there is an entire generation of coders who don't know how to code to PHP5.3 standards. PHP7.4 is already end of life and our code maintenance time needs to be spent ensuring compatibility with PHP8.1 and higher.

If you must stay on PHP 5.3, then your options are:

1. ADOdb version 5.21 is compatible, and stable. 
2. Fork 5.22 yourself and remove the non-compatible code. 
3. [Extending the mysql driver](https://adodb.org/dokuwiki/doku.php?id=v5:learn_extensions:extend_existing:modify_existing_driver) is surprisingly easy, and would be a way of taking advantage of our releases
4. Finally, if your business is dependent on our code base, consider entering into a professional services contract with us. You would then have access to our expertise in a way focused entirely on your needs
