### ISSUE TITLE
Refactor _adodb_backtrace() and _adodb_debug_execute()

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#863]
Following up on review comments originally posted by @dregad in https://github.com/ADOdb/ADOdb/pull/856#pullrequestreview-1083295740

Functions are using invalid HTML markup which should be fixed.

The code is also unnecessarily complex and should be refactored.

**Comment by mnewnham** [comment]
Do you want to do this? I've a few hours spare this weekend where I could look at this.

**Comment by dregad** [comment]
Thanks but I already started working on it actually... Most of the coding is done, testing in progress but I had to stop  to take care of the family.

**Comment by Bozosoft** [comment]
Thanks, I'll let you make the small change.
