### ISSUE TITLE
Object of class mysqli_result could not be converted to int

### ISSUE THREAD

**Issue by gavrochelegnou** [ADOdb/ADOdb#867]
Upgrading from 5.22.2 to 5.22.3 caused this error for every query  : 

`Object of class mysqli_result could not be converted to int in .../adodb.inc.php on line 3946 on PHP 8.1
`
the line is : 
`if($this->_queryID != -1) {`

Thanks

**Comment by dregad** [comment]
Yep. This regression was introduced by #851 - Sorry I should have tested this more extensively. 

I'll provide a patch ASAP, but until then as a workaround you can revert the change in ADORecordset::__destruct() :
https://github.com/ADOdb/ADOdb/commit/940dcec049491189102d18f4bc34238e0838a73c#diff-3741a1f8596dfded93640ae99d57f7f5e3a212dcc98a6f8a4dfbbd93241429a8L3941-R3951
