### ISSUE TITLE
Field type LONGVARCHAR from DBISAM database

### ISSUE THREAD

**Issue by rbertoldi** [ADOdb/ADOdb#874]
by ODBC attached a DBISAM database (elevatesoft.com) 

The MEMO/TEXT/CLOB field type is called "LONGVARCHAR".

I added "LONGVARCHAR => 'X' " to the "typeMap" array  in adodb.inc.php
around line 4900

Please add the "LONGVARCHAR"... TIA

--------

If anybody is using it, mask CR/LF/"'"..

example (just the first look) to add some "LONGVARCHAQR":

    public function QuotedSQLString($mystring = '') {
        $mystring = str_replace("\r", '',$mystring);  // CR
        $aStrings = explode("\n",$mystring); // new line
        if ( count( $aStrings) > 1) {
          $i = 0;
          $newString ='';
          foreach ($aStrings as $value) {
              $i++;
              if ($i>1) {
                  $newString .= "+";
              }
              $newString .= $this->SingleQuoteSQLString($value);
              if ($i< count($aStrings)) {
                  $newString .= "+#10";
              }
          }
          return $newString;
        } else {
            return $this->SingleQuoteSQLString($mystring);
        }
    }

    public function SingleQuoteSQLString($myString = '') {
        $myString = str_replace("'","''", $myString);
        return "'".$myString."'";
    }

**Comment by mnewnham** [comment]
Please review the method [setCustomMetaType()](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setcustommetatype). A setup like below should give you what you need:

````php
$db->setCustomMetaType(
             'X',            // <------ Override the X Metatype definition 
             INTERNAL_DEF,   // <------- How the DBISAM recognizes the field type
             'LONGCHARVAR' // <------- How ADOdb recognizes the Actual Type 
);
````

**Comment by mnewnham** [comment]
As you have not responded on this issue, I assume my response was sufficient. If you need further help, feel free to re-open
