### ISSUE TITLE
how do you include adodb-exceptions.inc.php  when using composer

### ISSUE THREAD

**Issue by stccorp** [ADOdb/ADOdb#878]
When using composer the autoload_files.php just include adodb.inc.php and not adodb-exceptions.inc.php, what do I need to do to include both?

Thank you

**Comment by mnewnham** [comment]
Composer will not include the necessary files in your project for you, you have top include them manually yourself [This page in the documentation](https://adodb.org/dokuwiki/doku.php?id=v5:userguide:error_handling&s[]=exception) should help you understand what needs to be done

**Comment by stccorp** [comment]
Thank you
