### ISSUE TITLE
PDO::setAttribute(): Argument #1 ($attribute) must be of type int, string given

### ISSUE THREAD

**Issue by Mecanik** [ADOdb/ADOdb#879]
Hi, this seem to be a problem:

```
$connection = ADONewConnection("pdo");
$connection->setConnectionParameter('CharacterSet', 'UTF-8');
```

Any idea why this is happening? Running latest version with PHP 8.0.

Thanks

**Comment by dregad** [comment]
As mentioned in the [documentation][1], for PDO setConnectionParameter() expects $attribute to be _Any parameter from the PHP [PDO Attribute List](https://www.php.net/manual/en/pdo.setattribute)_. `CharacterSet` is not a valid value.

[1]: https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter#pdo_driver

**Comment by Mecanik** [comment]
> As mentioned in the [documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter#pdo_driver), for PDO setConnectionParameter() expects $attribute to be _Any parameter from the PHP [PDO Attribute List](https://www.php.net/manual/en/pdo.setattribute)_. `CharacterSet` is not a valid value.

Don't you just hate it when someone is trying to be smart without testing...?

`$connection->setConnectionParameter(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);`

Same result wise guy. Also, there is not charset specification in PDO Attribute List. And also, look at your documentation: https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:setconnectionparameter

Specifically:

```
/*
 * Example setting the character set
 */
$db->setConnectionParameter('CharacterSet','UTF-8');
```
