### ISSUE TITLE
GetAssoc: FetchMode ADODB_FETCH_DEFAULT should respect the result from the driver rather than putting values in a numeric array.

### ISSUE THREAD

**Issue by clarumedia** [ADOdb/ADOdb#886]
https://github.com/ADOdb/ADOdb/blob/e3e3d14051dcd4d9203a12de87848a43a0687da4/adodb.inc.php#L4313

ADODB_FETCH_DEFAULT should be included as one of the options to ensure that the recordset is returned in the default provided by the PHP driver as per the documentation https://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_fetch_mode

if ($fetchMode ==  ADODB_FETCH_DEFAULT
      || $fetchMode == ADODB_FETCH_ASSOC
      ||  $fetchMode == ADODB_FETCH_BOTH)
{

Tested using mysqli

**Comment by mnewnham** [comment]
Well spotted, thanks
