### ISSUE TITLE
Object of class mysqli_result could not be converted to int

### ISSUE THREAD

**Issue by AndrewPixel** [ADOdb/ADOdb#888]
I've just updated a project, that's be running without any noticeable errors, from 5.22.2 to 5.22.3 and now get

`Object of class mysqli_result could not be converted to int in   adodb.inc.php   on line 3946`

I reverted back to .2 and the error doesn't appear.

**Comment by dregad** [comment]
Duplicate of https://github.com/ADOdb/ADOdb/issues/867
