### ISSUE TITLE
[session] PHP 7 does not permit non-static methods to be called statically

### ISSUE THREAD

**Issue by clarumedia** [ADOdb/ADOdb#891]
https://github.com/ADOdb/ADOdb/blob/8dafad709ca8951b1b665f2576d4680f7b4ef9b1/session/adodb-session.php#L580

8192:Non-static method ADODB_Session::close() should not be called statically

How about changing all the methods in the class to be:

```public static function```

In my tests, even the private methods need to be called statically and publicly.....

**Comment by dregad** [comment]
As mentioned in the [documentation](https://adodb.org/dokuwiki/doku.php?id=v5:session:session_index), _the original session management routines that use adodb-session.inc.php are deprecated as of ADOdb version 5.20, and will be removed in ADOdb Version 6.0.0._

@clarumedia You should be using adodb-session2.php. Does the problem also exist there ?

@mnewnham Is it really worth patching deprecated code ?

**Comment by clarumedia** [comment]
Fair enough. I will move forwards. Thank you

**Comment by dregad** [comment]
Thanks for your understanding.
