### ISSUE TITLE
 PageExecute trashes recordset _queryID

### ISSUE THREAD

**Issue by clarumedia** [ADOdb/ADOdb#892]
https://github.com/ADOdb/ADOdb/blob/8dafad709ca8951b1b665f2576d4680f7b4ef9b1/adodb.inc.php#L2018

Ubuntu 20.04 PHP 7.4 Apache
Driver: adodb-pdo_sqlsrv.inc.php (Does not seem to affect mysqli)

### Execute

```
$sql="select * from some_table";

$objRS=$oASCDB->Execute($sql);

print_r($objRS->_queryID); 
```

Result:

PDOStatement Object
(
    [queryString] => select * from ASC_PPH_TBL
)

### PageExecute

```
$sql="select * from some_table";

$objRS=$oASCDB->PageExecute($sql, 30, 1, $inputarr=false);

print_r($objRS->_queryID); 
```

Result:

1

-------------------------------

### Analysis

PageExecute uses _rs2rs and so variable _queryID never gets copied to the new recordset object and so cannot be used by anything after that point. However in tests it was also necessary NOT to close the OLD recordset before that point was reached otherwise $rs->_queryID would be empty by the time the copy was made.

**Comment by mnewnham** [comment]
Could you provide more detail please. Platform, PHP Version, ADOdb version.  I cannot duplicate this using the following code with the 5.22 codebase.

````php
define('ADODB_FETCH_MODE', 1);
include '/dev/github/adodb/adodb.inc.php';
$db = newAdoConnection('pdo');
$db->setFetchMode(ADODB_FETCH_ASSOC);

$db->connect('sqlsrv:server=192.168.86.21;database=NORTHWIND;','user','password');

$sql = 'select * from orders'; 

$result = $db->pageExecute($sql,25,1,false);

print_r($result);

````
The result for me is

````
ADORecordSet_array_pdo_sqlsrv Object
(
    [databaseType] => array
    [_array] => Array
        (
            [0] => Array
                (
                    [OrderID] => 10248
                    [CustomerID] => VINET
````

**Comment by mnewnham** [comment]
I get the same result using master with the above program. You will need to provide some more context as to how you get the error, for example:

 - If you run the provided short program above, do you get the error?
 - Are the any ADOdb SQL statements prior to pageexecute call?

A larger code snippet would also help.

**Comment by mnewnham** [comment]
As I have not received any more information on this, I'm assuming you've fixed this issue yourself. If you need further help, feel free to re-open this issue

**Comment by clarumedia** [comment]
@mnewnham So sorry, I had to move on. TBH I ended up writing a small library to emulate the bits of ADODBPHP I need with the RDBMS systems I'm using. Thank you so much for all you have done.
