### ISSUE TITLE
Formatting query in debugging

### ISSUE THREAD

**Issue by nd3w** [ADOdb/ADOdb#893]
I've just upgrade to version 5.22.3. As I often use ADODb debug method, I found out that now if there's an error to my query it'll produce a one liner query like:

    SELECT a.id, a.file, a.author, a.date FROM table a JOIN another_table b ON b.id = a.a_id WHERE id = 3 ORDER BY a.date

In the previous version (5.21.4) I can add a preformatted HTML tag (&lt;pre&gt;) before debug method and it produced a preformatting query which is no longer working at the present stable version.

Is there a way, ADODb can produce a preformatted query?

**Comment by mnewnham** [comment]
Formatting for debugging output in html is now controlled by a style class **adodb-debug**. Unfortunately the documentation has not yet caught up with it. You can see the definitions in ``adodb-lib.inc.php`` in the function ``_adodb_debug_execute``

**Comment by mnewnham** [comment]
Hopefully that answered your question. If you need further help feel free to re-open
