### ISSUE TITLE
[mssqlnative] Affected_Rows() should return false if called after SELECT statement

### ISSUE THREAD

**Issue by devkinetic** [ADOdb/ADOdb#895]
Pretty similar issue to #820 / #821 , except for mssql. When one uses `affected_rows()` on a select statement, the following error gets thrown:

> Uncaught TypeError: sqlsrv_rows_affected(): supplied resource is not a valid ss_sqlsrv_stmt resource in /app/vendor/adodb/adodb-php/drivers/adodb-mssqlnative.inc.php:188

I just started using adodb yesterday, trying to bring an old app up to date. I was able to workaround the issue with this not so elegant code, it should serve as a band-aid until something proper is in place like what was done for mysqli. Note, I'm using the new string functions introduced in PHP8.

```php
if (str_starts_with($stmt, 'Select') || str_starts_with($stmt, 'select') || str_starts_with($stmt, 'SELECT')) {
  $affectedrows = null;
} else {
  $affectedrows = $database->Affected_Rows();
}
```

**Comment by mnewnham** [comment]
An obvious point would be that you do understand that you cannot call ``affected_rows()`` [against a select statement](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:affected_rows) anyway, and that ADOdb is simply returning the error you would get if you used the driver directly.

I guess the question is what would you expect the method to return?

**Comment by devkinetic** [comment]
I do understand that. I did not write the original code, just updated adodb from some ancient version to current. When I look at the mysqli driver, There is code along the lines of:
```php
if ($this->isSelectStatement) {
  // Affected rows works fine against selects, returning
  // the rowcount, but ADOdb does not do that.
  return false;
}
```
There is nothing like that in place for mssqlnative. It just calls `sqlsrv_rows_affected()`.
