### ISSUE TITLE
PHP returning inconsistent type for Int value

### ISSUE THREAD

**Issue by libreajans** [ADOdb/ADOdb#901]
- AdoDB: v5.22.4 via Composer
- PHP: 8.1.7-1ubuntu3.1 (cli)
- RDMS:  MariaDB 10.9.3

Hi, I came across a strange PHP related error on my query. 

I have a table similar to this query.

```SQL
CREATE TABLE `app_content` (
  `content_id` int(11) UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
  `content_title` varchar(256) COLLATE utf8mb4_german2_ci DEFAULT NULL,
  `content_image` varchar(256) COLLATE utf8mb4_german2_ci DEFAULT NULL,
  `content_time` timestamp NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_german2_ci;
```

I have two queries. The first one.

```SQL
SELECT
    content_id as id,
    content_title as title,
    content_image,
    DATE_FORMAT(content_time,"%d.%m.%Y") AS date
FROM app_content
WHERE content_status = 1
AND content_time < "2022-10-10 10:10:10"
AND content_cat = 101
ORDER BY content_time DESC
LIMIT 0,12
```

In this query id values returns as int, mean no problem.

'id' > int : 260
'title' > string > 'Lorem'
'content_image' > string > 'Lorem'
'date' > string > '08.11.2022'

The second query is like this.

```SQL
SELECT
    content_id as id,
    content_title as title,
    content_image,
    DATE_FORMAT(content_time,"%d.%m.%Y") AS date
FROM app_content
WHERE content_status = 1
AND content_id NOT IN (161, 0)
AND content_time < "2022-10-10 10:10:10"
AND content_cat = 101
ORDER BY content_time DESC
LIMIT 0,6
```

This query returning id values as String.

'id' > string : '260'
'title' > string : 'Lorem'
'content_image' > string > 'Lorem'
'date' > string > '08.11.2022'

How I fixed: I simply casted (int) to id key on PHP loop.

```PHP
foreach ($list as $key => $val) {
    $list[$key]['id'] = (int) $val['id'];
}
```

I have no idea why it behaves this way. Queries so similar, the last one only contains ```NOT IN (161, 0)```

**Comment by mnewnham** [comment]
You're going have to provide a little ADOdb context. Here's my test program against MariaDB 10.6

````php

$sql = "drop table if exists app_content";
$db->execute($sql);

$sql = "CREATE TABLE `app_content` (
    `content_id` int(11) UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `content_title` varchar(256) COLLATE utf8mb4_german2_ci DEFAULT NULL,
    `content_image` varchar(256) COLLATE utf8mb4_german2_ci DEFAULT NULL,
    `content_time` timestamp NULL DEFAULT NULL,
    `content_cat` int(4) DEFAULT 101,
    `content_status` int(4) DEFAULT 1
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_german2_ci;";

  $db->execute($sql);

$ar = array();
$ar['content_title'] = 'TITLE_8';
$ar['content_image'] = 'TITLE_8';
$ar['content_time']  = time();

$sql = "SELECT * FROM app_content WHERE content_id=-1";
$template = $db->execute($sql);

$sql = $db->getInsertSql($template,$ar);

$db->execute($sql);

$ar = array();
$ar['content_title'] = 'TITLE_9';
$ar['content_image'] = 'TITLE_9';
$ar['content_time']  = time();

$sql = $db->getInsertSql($template,$ar);

$db->execute($sql);

$sql = 'SELECT
content_id id,
content_title as title,
content_image,
DATE_FORMAT(content_time,"%d.%m.%Y") AS date
FROM app_content
WHERE content_status = 1
AND content_time < "2022-12-10 10:10:10"
AND content_cat = 101
ORDER BY content_time DESC
LIMIT 0,12';

$result = $db->execute($sql);

var_dump($result->fetchRow());
````
No matter how I structure this query, I always return

```
array(4) {
  ["id"]=>
  string(1) "1"
  ["title"]=>
  string(7) "TITLE_8"
  ["content_image"]=>
  string(7) "TITLE_8"
  ["date"]=>
  string(10) "25.11.2022"
}
```
So I need you to show how your query is constructed to return is as an integer

**Comment by libreajans** [comment]
Thanks for answer.

I created an example test case [here](https://github.com/libreajans/adotest)

I simplified the situation. 

The first query returning content_ids as int, the second one returning as string. 

```PHP
$sql1    = 'SELECT content_id
            FROM app_content
            WHERE content_cat = ?';
var_dump($conn->getAll($sql1, [101]));
```

```PHP
$sql2    = 'SELECT content_id
            FROM app_content
            WHERE content_cat = 101';
var_dump($conn->getAll($sql2));
```

![return](https://user-images.githubusercontent.com/6218679/204060244-07f87cc1-0274-487e-9b5f-ea7785a59c35.png)

**Comment by mnewnham** [comment]
When a bound statement is executed, the resulting object is a result from a ``mysqli_stmt::getResult()`` call. A non-bound statement is a resulring object from a ``mysqli_query()`` call. The records from those calls are both returned via a ``mysqli_fetch_array()`` method. Why those two mysql methods return different attributes for the fields isn't something that ADOdb can influence. 

Obviously you can call [fetchfield()](http://adodb.org/dokuwiki/doku.php?id=v5:reference:recordset:fetchfield) on the resulting fields and cast appropriately if you need to have consistent data types

**Comment by libreajans** [comment]
I had no idea. Knowing it's not an ADOdb bug is enough for me. Thanks.
