### ISSUE TITLE
Deprecated: Creation of dynamic property ADORecordSet_mysqli::$adodbFetchMode

### ISSUE THREAD

**Issue by Bozosoft** [ADOdb/ADOdb#903]
In Php 8.2.0RC7 FPM/FastCGI, with the last ADOdb Commits on Nov 23, 2022
 I have the message "Deprecated: Creation of dynamic property ADORecordSet_mysqli::$adodbFetchMode is deprecated in  /adodb/drivers/adodb-mysqli.inc.php on line 1456"
Line 1456 = $this->adodbFetchMode = $mode;
So I add in line 1421 #[\AllowDynamicProperties] and no alert.

**Comment by mnewnham** [comment]
We have not yet qualified ADOdb against PHP 8.2 so you should take care of you are using code in a production environment

**Comment by Bozosoft** [comment]
Yes only for a test but as the files adodb.inc.php and 
adodb-mysqli.inc.php had been modified since version 5.22.4
So it's the same "Deprecated" with the last version v5.22.4 in PHP 8.2.0RC7

**Comment by dregad** [comment]
Thanks, we'll fix that. Feel free to submit a PR against hotfix/5.22 branch if you can spare the time.

**Comment by dregad** [comment]
Duplicate of #911
