### ISSUE TITLE
[mysql] Deprecated: Creation of dynamic property ADODB_mysqli::$databaseName is deprecated in PHP8.2

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#904]
``Deprecated: Creation of dynamic property ADODB_mysqli::$databaseName is deprecated in drivers/adodb-mysqli.inc.php on line 1006``

**Comment by dregad** [comment]
@mnewnham the commit 31b2ccc9 you linked to this issue mentions adodbFetchMode in the description, but the code actually removes `databaseName` property...

**Comment by dregad** [comment]
Fixed in e475b4c610f6ee9cd103ac395ccf562e9b151b93
