### ISSUE TITLE
[core] Deprecated: Creation of dynamic property ADODB2_mysql::$quote is deprecated in adodb.inc.php on line 5790

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#907]

**Comment by mnewnham** [comment]
That may have been my mistake reading the numbers off of a vi session!

**Comment by Bozosoft** [comment]
In /datadict/datadict-mysql.inc.php line:25: class ADODB2_mysql extends ADODB_DataDict {
so add line 24  #[\AllowDynamicProperties]
My test solved the Deprecated

**Comment by dregad** [comment]
Fixed in 5e41924806e5f310d30e203100f0c97cd5e93893 (master) / 8e51a88d5d37e2857298f5fa9c6f56f9b577e86f (5.22.5)
