### ISSUE TITLE
Question on caching behavior when adding new columns to a table, then doing a getRow("select * from table")

### ISSUE THREAD

**Issue by wesyah234** [ADOdb/ADOdb#910]
I don't know for sure if this is caused by ADOdb or not so just checking here first:

I added 2 new columns to a table (faculty) in Oracle.

I ran the following php code:  
 
`$faculty = $dbconn->GetRow("select * from faculty where faculty_id = $id");`
`var_dump($faculty);`

The output of the dump command INTERMITTENTLY changed between including those 2 new fields and NOT including those 2 new fields.

Thinking it was some sort of cache in play, I had my sysadmin restart php-fpm and this resolved the issue, and the subsequent page reloads consistently returned the 2 new fields.

Is this caused by anything in the adodb layers? Or is this something being done by PHP itself? Any thoughts? 

I've been using ADOdb for over 15 years and have never noticed something like this.  But we've been using php-fpm now for only a couple of years so maybe that's where the caching is happening... not sure.

Thank you!

**Comment by dregad** [comment]
The fact that restarting PHP-FPM fixed the issue, leads me to believe that something gets cached in the web server's process. Not sure what or how, I've never experienced anything similar to what you describe.

ADOdb stores a query's fields in the Recordset when initializing it, but to my knowledge this is not cached globally.

**Comment by dregad** [comment]
@wesyah234 you have not provided any feedback, so I'm going to close this issue. Feel free to reopen if necessary.
