### ISSUE TITLE
pgsql: Creation of dynamic property deprecated warning in PHP 8.2

### ISSUE THREAD

**Issue by Bozosoft** [ADOdb/ADOdb#913]
Deprecated: Creation of dynamic property ADORecordSet_postgres9 in lib/adodb/drivers/adodb-postgres64.inc.php on line 952

line 952 $this->adodbFetchMode = $mode;
Add line 931 #[\AllowDynamicProperties]  solved the Deprecated

**Comment by dregad** [comment]
Related to #917 (same issue on PDO driver)

**Comment by Bozosoft** [comment]
I have only in drivers/ adodb-postgres... and adodb-mysqli.inc.php
So the problem is confirmed for me on adodb-postgres64.inc.php

**Comment by dregad** [comment]
My comment was more more a note to myself than anything directed at you, as IMO your proposed fix is not appropriate - see https://github.com/ADOdb/ADOdb/pull/917#discussion_r1071332138
