### ISSUE TITLE
ADODb exception under PHP 8: SQLSTATE[IMSSP]: The active result for the query contains no fields.

### ISSUE THREAD

**Issue by MrJackDuaner** [ADOdb/ADOdb#914]
Hello,

I know the ticket https://github.com/ADOdb/ADOdb/issues/887 is closed but I have the same error with PHP 8.1.13, ADODb 5.22.4 and extension PDO_SQLSRV 5.10.0, and I would like to understand why it doesn't work with ADODb under this version of PHP.

Here is the code to test with PDO and ADODb at same time :

```
<?php
$adodbDir = 'ADOdb-5.22.4';

require $adodbDir . DIRECTORY_SEPARATOR . 'adodb.inc.php';
require $adodbDir . DIRECTORY_SEPARATOR . 'adodb-exceptions.inc.php';

$connectionString = 'sqlsrv:server=LOCALHOST;database=DATABASE;encrypt=true;trustServerCertificate=true';
$user = "USER";
$password = "PASSWORD";
$database = "DATABASE";
$query = "INSERT INTO TABLE (COL1, COL2) VALUES ('VAL1', 'VAL2')";

echo '<p>Test with PDO</p>';
$db = new PDO($connectionString, $user, $password);
try
{
	$db->exec($query);
	echo '<p>PDO OK</p>';
}
catch (PDOException $e) {
	echo '<p>PDO ERROR : ' . $e->GetMessage() . '</p>';
}

echo '<p>Test with NewADOConnection</p>';
$db = NewADOConnection('pdo');
$db->Connect($connectionString, $user, $password, $database);
try
{
	$db->Execute($query);
	echo '<p>NewADOConnection OK</p>';
}
catch (PDOException $e) {
	echo '<p>NewADOConnection ERROR : ' . $e->GetMessage() . '</p>';
}
```

Result for PHP 8.1.13, ADODb 5.22.4 and PDO_SQLSRV 5.10.0 :
```
Test with PDO
PDO OK
Test with NewADOConnection
NewADOConnection ERROR : SQLSTATE[IMSSP]: The active result for the query contains no fields.
```

But if I switch to PHP 7.4.33...

Result for PHP 7.4.33, ADODb 5.22.4 and PDO_SQLSRV 5.10.0 :
```
Test with PDO
PDO OK
Test with NewADOConnection
NewADOConnection OK
```

The Web server is IIS 10 and PHP is running as FastCGI. Both PHP configuration are similar,I always configure PHP the same way since 10 years.

If you need additional information, please let me know.

Best regards.

**Comment by mnewnham** [comment]
If there are no errors thrown when $db->debug = true, and there are no PHP 8 errors, it feels as if you might be better off raising an issue at [microsoft/mssqlphp](https://github.com/microsoft/msphpsql/issues). There has already been quite a [long thread](https://github.com/microsoft/msphpsql/issues/507) about this issue a few years ago

**Comment by dregad** [comment]
@MrJackDuaner you have not provided any feedback, so we assume that we have answered your question and will close this issue. If not, feel free to reopen it.
