### ISSUE TITLE
execute() method returns empty set object instead of boolean

### ISSUE THREAD

**Issue by miken32** [ADOdb/ADOdb#918]
According to [the documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:execute) for the `execute()` method:
>If the statement does not return a recordset, such as in `INSERT` or `UPDATE` statement, it returns true on success or false on failure. 

But this simple code does not give me a boolean result:
```php
<?php

require_once "vendor/autoload.php";

use ADOConnection;

$user = "xxx";
$password = "xxx";
$host = "localhost";
$dbname = "xxx";

$db = NewADOConnection("mysqli://$user:$password@$host/$dbname");
$result = $db->execute("INSERT INTO test VALUES (?, ?)", ["foo", "bar"]);
var_dump($result);
```
Output:
```none
object(ADORecordSet_empty)#4 (6) {
  ["dataProvider"]=>
  string(5) "empty"
  ["databaseType"]=>
  bool(false)
  ["EOF"]=>
  bool(true)
  ["_numOfRows"]=>
  int(0)
  ["fields"]=>
  bool(false)
  ["connection"]=>
  bool(false)
}
```
Same results with both 5.21 and 5.22. I'm just taking over an existing project that uses this library so I'm not super familiar with it but it doesn't seem like I'm making any obvious mistakes here...

**Comment by mnewnham** [comment]
This is a mistake in the [execute()](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:execute) documentation page. The page has been fixed
