### ISSUE TITLE
v5.22.0 + Returning int column data sometimes as string

### ISSUE THREAD

**Issue by Gorkfu** [ADOdb/ADOdb#929]
All versions since v5.22.0, using the MySQLi driver. Columns set as type int are coming back sometimes as int or string when they should always be int.

**Comment by mnewnham** [comment]
Could you provide a little more information please. I believe what you describe relates to the fact that we now use true binding in prepared statements. This means that in this example

````php
$result = $db->execute("SELECT * FROM some_table WHERE rowid=?",array(20));
````
The result set is returned from ``mysqli_stmt_execute()``

But if you do the following
````php
$result = $db->execute("SELECT * FROM some_table WHERE rowid=20");
````
The result set is returned from ``mysqli_query()``

The data types of the returned records appear to be different, and as ADOdb is acting simply as a pass-thru, there seems to be little we can do to control this. 

However, if you feel I am misunderstanding, feel free to post a simple code segment, what you are seeing, and what you are expecting.

**Comment by Gorkfu** [comment]
Thanks for the explanation, this helped track down why this seemed to be random when it's not. I appreciate the help.
