### ISSUE TITLE
No data in results with 5.19 update

### ISSUE THREAD

**Issue by jpSimkins** [ADOdb/ADOdb#93]
I just updated from 5.18. I have a system that already heavily uses this library. I just replaced the files with the new version with the old version and now no queries return values in their data.

Even a simple query like: <code>SELECT count(1) as total FROM tablename</code> returns <code>Array
(
    [total] => 
)</code>

For now, I just reverted back to the older version. Just wanted to report this issue. 

I am using FoxPro. My class setup is:

```

        // Include the adodb library
        require_once(LIBRARY_PATH.'adodb5'.DIRECTORY_SEPARATOR.'adodb.inc.php');

        // Set path
        self::$db_path = DPRODUCE_PATH;

        // Create the instance
        self::$_instance = ADONewConnection('vfp');

        // Set the driver
        $dsn = 'DRIVER={Microsoft Visual FoxPro Driver};SOURCETYPE=dbf;SOURCEDB='.self::$db_path.';EXCLUSIVE=NO;';

        // Set options
        self::$_instance->debug = self::DEBUG_MODE;

        // Connect
        self::$_instance->Connect($dsn);

        // Set default fetch mode
        self::$_instance->SetFetchMode(ADODB_FETCH_ASSOC);
```
I am not having an issue with the connection. It seems that it does the actual query but when it returns the response it has all the proper keys but all values are empty.

I didn't see anything about changing setup for this. So for now I need to stay on the older version.

**Comment by dregad** [comment]
I don't have or use foxpro. Would you be able to run git bisect to identify the commit that introduced the issue ?

**Comment by dregad** [comment]
Possibly caused by #20
