### ISSUE TITLE
Replace deprecated MySQL `BINARY` operator

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#942]
The BINARY operator has been deprecated in MySQL 8.0.27 [[1](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#operator_binary)].

This is used in Sessions management to force a case-sensitive comparison on the Session key.

I noticed this while analyzing #941 (see https://github.com/ADOdb/ADOdb/issues/941#issuecomment-1481638054).

**Comment by dregad** [comment]
@mnewnham I'd like to have your opinion on this please.

I initially thought of simply replacing `BINARY`with `COLLATE utf8mb4_bin`, i.e. `BINARY 'xxx'` => `'xxx' COLLATE utf8mb4_bin`.

The problem is that depending on the environment (table definition, default charset/collation) this may actually fail, for example 
```sql
create table test (key varchar(100) collate utf8mb4;
insert into test ('key'), ('KEY');
select * from test where k = 'key'; /* 2 rows */
select * from test where k = 'key' collate utf8mb4_bin; /* 1 row (OK) */
set collation_connection = utf8mb3_general_ci;:
select * from test where k = 'key'; /* 2 rows */
select * from test where k = 'key' collate utf8mb4_bin; 
/* ERROR 1253 (42000): COLLATION 'utf8mb4_bin' is not valid for CHARACTER SET 'utf8mb3'. */
```

To be safe we would need to first convert to utf8mb4, THEN change collation to ensure case-sensitive comparison... a bit messy.

```sql
select * from test where k = convert('key' using utf8mb4) collate utf8mb4_bin; /* 1 row (OK) */
```

I guess the cleanest way would be to require the *sessions2.sesskey* column to be defined with a case-sensitive or binary collation, so we can simply do `sesskey = 'xxx'` but this could break backwards compatibility.

Keeping in mind that case-insensitive comparison would be only be an issue when php.ini has non-default setting session.sid_bits_per_character = 6.

What do you think ?

**Comment by joebordes** [comment]
[This page in MySQL](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#operator_binary) says

> Use CAST(... AS BINARY) instead.

could that be an alternative?

**Comment by mnewnham** [comment]
Give me a moment to think about this......

**Comment by dregad** [comment]
> [This page in MySQL](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#operator_binary) says
> 
> > Use CAST(... AS BINARY) instead.
> 
> could that be an alternative?

Yes I think that would work, actually. I'll make some tests to confirm.
I did read that page (more than once) and I can't believe I skipped over this... Thanks for the heads up @joebordes !

**Comment by mnewnham** [comment]
What if we just appended the crc of the session_id to the value. Wouldn't that then guarantee uniqueness?

**Comment by dregad** [comment]
> What if we just appended the crc of the session_id to the value. Wouldn't that then guarantee uniqueness?

It would indeed make the key unique, but then we would no longer store the actual session id in the DB, so the composite key with the CRC would have to be recalculated whenever the table needs to be accessed by session id... feels like unnecessary overhead.

**Comment by mnewnham** [comment]
> > What if we just appended the crc of the session_id to the value. Wouldn't that then guarantee uniqueness?
> 
> It would indeed make the key unique, but then we would no longer store the actual session id in the DB, so the composite key with the CRC would have to be recalculated whenever the table needs to be accessed by session id... feels like unnecessary overhead.

In a pure sense, i would agree, but given the nature of session management, where the overhead of aggregating and writing large amounts of data to the session record far outweigh the effort of CRC generation... No matter though, you've found an alternative
