### ISSUE TITLE
ErrorMsg() returns different value on PHP 8x than on older versions.

### ISSUE THREAD

**Issue by NathanGibbs3** [ADOdb/ADOdb#947]
### Description
ErrorMsg() is returning different value on PHP 8x than on older versions.

### Environment
- ADOdb version: All versions between 5..20.12 - 5.22.4 & branch hotfix/5.22
- Driver or Module: mysqli & postgres
- Database type and version: Mysql & PostgreSQL
- PHP version: 5.3x - 8.1x
- Platform: 

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / hotfix/5.22 branch

### Steps to reproduce
````php
$db = ADONewConnection('mysqli');
$db->connect(...);
var_dump($db->execute('SELEXT * FROM table'));
var_dump($$db->ErrorMsg());
$tmp = $db->ErrorMsg();
if ( $tmp ){
print "PHP 8x code path\n";
print "Not supposed to run.\n";
$msg = '<b>'._ERRSQLDB.'</b> ';
}else{
print "PHP legacy code path\n";
print "Supposed to run.\n";
}
````

### Expected behavior
The same code path is followed in all PHP versions.

### Additional context 
On earlier PHP's the code path that accesses the constant `_ERRSQLDB`, is not being run, while on earlier PHP 8x it is being run.

**Comment by NathanGibbs3** [comment]
Here is the latest CI run of my project.
https://app.travis-ci.com/github/NathanGibbs3/BASE

PHP 7.2+ is being built against your latest hotfix/5.22 branch.
Builds OK under PHP 7x, builds break under PHP 8x.

Is this breakage in my project or yours?
I'll look into my project. :smile:

**Comment by NathanGibbs3** [comment]
I **think** it's mine.
https://www.php.net/manual/en/migration80.incompatible.php
>The @ operator will no longer silence fatal errors (E_ERROR, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR, E_PARSE).

and
>A number of warnings have been converted into [Error](https://www.php.net/manual/en/class.error.php) exceptions:
> Attempting to access unqualified constants which are undefined. Previously, unqualified constant accesses resulted in a warning and were interpreted as strings.

These two together, appear to be what is breaking my build.
Upon adjustment & successful verification in my project, I'll close this.

**Comment by dregad** [comment]
This is not reproducible with the given code snippet.

## PHP 7.2
```
 ~/dev/adodb$ /opt/homebrew/Cellar/php@7.2/7.2.34_6/bin/php t947.php
bool(false)
string(165) "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELEXT * FROM table' at line 1"
PHP 8x code path
Not supposed to run.
PHP Warning:  Use of undefined constant _ERRSQLDB - assumed '_ERRSQLDB' (this will throw an Error in a future version of PHP) in /Users/dregad/dev/adodb/t947.php on line 11

Warning: Use of undefined constant _ERRSQLDB - assumed '_ERRSQLDB' (this will throw an Error in a future version of PHP) in /Users/dregad/dev/adodb/t947.php on line 11
```

## PHP 8.1
```
 ~/dev/adodb$ /opt/homebrew/Cellar/php@8.1/8.1.17/bin/php t947.php
/Users/dregad/dev/adodb/t947.php:5:
bool(false)
/Users/dregad/dev/adodb/t947.php:6:
string(165) "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELEXT * FROM table' at line 1"
PHP 8x code path
Not supposed to run.
PHP Fatal error:  Uncaught Error: Undefined constant "_ERRSQLDB" in /Users/dregad/dev/adodb/t947.php:11
Stack trace:
#0 {main}
  thrown in /Users/dregad/dev/adodb/t947.php on line 11

Fatal error: Uncaught Error: Undefined constant "_ERRSQLDB" in /Users/dregad/dev/adodb/t947.php on line 11

Error: Undefined constant "_ERRSQLDB" in /Users/dregad/dev/adodb/t947.php on line 11

Call Stack:
    0.0002     400608   1. {main}() /Users/dregad/dev/adodb/t947.php:0
```

**Comment by NathanGibbs3** [comment]
Confirmed, our issue, not yours.
https://app.travis-ci.com/github/NathanGibbs3/BASE/builds
Sorry about that. ☹️
