### ISSUE TITLE
Deprecated dynamic property assignments

### ISSUE THREAD

**Issue by SUXUMI** [ADOdb/ADOdb#954]
### Description
Please fix deprecated dynamic property assignments:
`$_maxRecordCount` in `/adodb-lib.inc.php:532`
`$rowsPerPage` in `/adodb-lib.inc.php:559`

### Environment
- ADOdb version: 5.22.5
- Driver or Module: MySQL
- Database type and version: MariaDB
- PHP version: 8.2.5
- Platform: Unix

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / **master** branch / **hotfix** branch

### Steps to reproduce
Detailed, step-by-step instructions to reproduce the behavior, including:
- initiate DB connection

**Comment by dregad** [comment]
Thanks for the bug report
