### ISSUE TITLE
ADOConnection::Execute return type too revealing

### ISSUE THREAD

**Issue by Itatsi** [ADOdb/ADOdb#964]
### Description
The return type of the ADOConnection::Execute method is defined as folloing:
https://github.com/ADOdb/ADOdb/blob/928936acf7188678f366516a75c5407d7e866038/adodb.inc.php#L1521

but the [docu](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:execute) says: "If the execution succeeds, it returns a recordset. [...] if the execution fails, it returns false."

In the code I could not find a place which returns true. Is there any particular reason why it can return, as defined by phpdoc, bool and not only false?

### Environment
- ADOdb version: master

### Expected behavior
`* @return ADORecordSet|false

`### Additional context 
the reason I ask is because I usually treat the result as follows:
```
$res = $db->execute($selectSql);
if ($res && $res->RecordCount() >= 1) {
```
Here, however, a code analysis by psalm rightly criticizes that it could also return true according to phpdoc.

**Comment by dregad** [comment]
No reason, just an inconsistency. Thanks for pointing it out.
