### ISSUE TITLE
Remove obsolete Date/Time library

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#970]
It does not make much sense anymore in the age of 64-bit computing, where timestamps will not overflow for 292 billion years, and it relies on use of strftime()/gmstrftime(), which have been deprecated in PHP 8.1.

Follows discussion in https://github.com/ADOdb/ADOdb/issues/963

**Comment by dregad** [comment]
[Documentation has been updated](https://adodb.org/dokuwiki/doku.php?id=v5:datetime:datetime_index) with warning boxes indicating that the library is deprecated in 5.22.6 and removed in 5.23.0.

**Comment by ptdesign** [comment]
adodb_mktime removed unfinished. still adodb_mktime present in adodb.inc.php and adodb-sybase.inc.php

**Comment by dregad** [comment]
> adodb_mktime removed unfinished. still adodb_mktime present in adodb.inc.php and adodb-sybase.inc.php

@ptdesign yes, I noticed that a couple days ago as well. Will fix.

**Comment by ptdesign** [comment]
Hello, any updates?

**Comment by dregad** [comment]
Sorry no, I've been busy and have not been able to work on ADOdb lately... But it's not forgotten and I'll get to it eventually.

**Comment by joebordes** [comment]
Can I try to clean that up?  Make a PR?

**Comment by dregad** [comment]
@joebordes contributions are always welcome, feel free to submit a pull request. Thanks !

**Comment by joebordes** [comment]
Got it! PR on it's way :-)

**Comment by joebordes** [comment]
Can you please add the `hacktoberfest` label to the project?

**Comment by dregad** [comment]
> Can you please add the `hacktoberfest` label to the project?

Done

**Comment by joebordes** [comment]
Looking at the code and the commit where the date/time library was eliminated I found that there were 4 functions being used and not defined:

- adodb_gmdate
- adodb_date2
- adodb_date
- adodb_mktime

I studied a little about the history and the functionality and decided (hopefully correctly) to just use the standard PHP functions.

Then I validated my assumptions by creating an SQLite database and trying to access it. I received the error as expected:

```shell
PHP Fatal error:  Uncaught TypeError: SQLite3::createFunction():
 Argument #2 ($callback) must be a valid callback, function "adodb_date" not found or invalid function name
 in /home/joe/reps/ADOdb/drivers/adodb-sqlite3.inc.php:312
```

I then made the change and created a test file to validate the functionality. This test file is also in the pull request but not integrated into the test suite you have. It is just there as a starting point for future efforts.

```shell
$> php testsqlite.php 
Test sqlite access first 4 rows: select * from testtable order by id limit 4  ✓
Test SQLDate: SELECT strftime('%d-%m-%Y Q %H:%M:%S')  ✓
Test SQLDate: SELECT strftime('%d-%m-%Y Q %H:%M:%S','1974-02-25')  ✓
Test SQLDate: SELECT strftime('%d-%m-%Y Q %H:%M:%S','1474-02-25 05:04:16')  ✓
Test SQLDate: SELECT strftime('%d-%m-%Y Q %H:%M:%S','2474-02-25 05:04:16')  ✓
```

Let me know how it looks and if you need me to change anything.

**Comment by dregad** [comment]
Hello, sorry for the lack of response, I've been busy...

You mentioned a pull request, but you never actually created one... Anyway I had a quick look at the commit in your fork and it looks good.

My only concern is the continued use of strftime() which has been deprecated in PHP 8.1. I know it's somewhat outside the scope of this issue and I have not analyzed the implications, but maybe this would be an opportunity to consider implementing an alternative (maybe as a 2nd PR).

Thanks

**Comment by joebordes** [comment]
this one:  https://github.com/ADOdb/ADOdb/pull/1002

**Comment by joebordes** [comment]
I had a look at that strftime comment but I think it doesn't apply. That specific strftime is not evaluated by PHP but by SQLite: https://www.sqlite.org/lang_datefunc.html

I eliminated the createfunction call and I am using native SQLite.

Let me know

**Comment by dregad** [comment]
> this one: #1002

Sorry I missed it as it was not referenced from here and was looking from my phone. Thanks 

> That specific strftime is not evaluated by PHP but by SQLite

Right, I missed the quotes when reviewing... Ignore me 😉

**Comment by dregad** [comment]
Many thanks for your contribution

**Comment by joebordes** [comment]
my pleasure :-)
