### ISSUE TITLE
Feature Request: Function to return semantic ADOdb Version.

### ISSUE THREAD

**Issue by NathanGibbs3** [ADOdb/ADOdb#976]
### Description
Request for a function to be added to the core ADOdb library that would return an array representing the semantic version of ADOdb in the form of `Array( Major, Minor, Revision )`

### Environment
- ADOdb version: Any version > 5.22.5
- Driver or Module: All
- Database type and version: All
- PHP version: All
- Platform: All

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest)
N/A

### Steps to reproduce
Detailed, step-by-step instructions to reproduce the behavior, including:
- N/A

### Expected behavior
The end goal is to allow an application the uses ADOdb to modify it's behavior on the fly based on installed ADOdb version, which could vary widely between installations of the application.
Although this can be done currently, it is not a straightforward process and the functionality has to be built into the application.
Adding this functionality to ADOdb would make that easier.

### Additional context 
Here is a function that I use in an application to implement this.
```php
function GetDALSV (){ // Returns ADOdb Semantic Version Array
    GLOBAL $ADODB_vers;
    $DALV = $ADODB_vers;
    $DALV = explode('.', $DALV, 3);
    // Strip leading V or v in Major.
    $DALV[0] = preg_replace('/^(v|V)/', '', $DALV[0]);
    if( preg_match('/^\d+/', $DALV[1], $tmp) ){ // Normalize Minor.
        $DALV[1] = $tmp[0];
    }
    if( preg_match('/^\d+/', $DALV[2], $tmp) ){ // Normalize Rev.
        $DALV[2] = $tmp[0];
    }
    if( !is_numeric($DALV[2]) ){ // Legacy ADOdb Versions
        $DALV[2] = '0';
    }
    return $DALV; // Array of ( Major, Minor, Revision ).
}
```

**Comment by dregad** [comment]
I'm not sure why you would want this as an array. Given your requirement to

> allow an application the uses ADOdb to modify it's behavior on the fly based on installed ADOdb version

I think it would be easier to just use a *version_compare()* call on the version string, e.g.

```php
if (version_compare(ADOConnection::version(), '5.22.5', '>=')) 
    // ...

$db = ADONewConnection($driver);
if (version_compare($db->version(), '5.22.5') >= 0) 
    // ...
```

This has the added benefit of working with pre-release versions as well.

If you *must* have it as an array, then you should still prefer *ADOConnection::version()* over *$ADODB_vers* to get the ADOdb version number, and you could probably simplify your code to use a single regex, e.g.
```php
preg_match('/(\d+)\.(\d+)\.(\d+)/', ADOConnection::Version(), $matches);
array_shift($matches);
return $matches;
```
Note: using *preg_match()* instead of *explode()*, as in the case of a pre-release version the 3rd element would include the suffix (`-dev` or `-beta.1`)

Also, do you *really* need compatibility with legacy, pre-5.20 versions ? If so, you should probably not always set patch to 0 as there is sometimes an `a` suffix which should be considered as `.1` (e.g. 5.08a)

**Comment by NathanGibbs3** [comment]
Oh, ADOdb already has a Version function! Disregard this then. :smile:
I did look for it in your [Reference Manual](https://adodb.org/dokuwiki/doku.php?id=v5:reference:reference_index) before submitting this. Didn't see it in there. You may want to fix that.

**Comment by NathanGibbs3** [comment]
> Also, do you _really_ need compatibility with legacy, pre-5.20 versions ?

Believe it or not, the maintained application initially required ADOdb 1.2+ in 2004.
The application that it was forked from required ADOdb 0.93+ as early as January of 2001.
There is anecdotal evidence of it being run on everything from there to ADOdb 4.90+
It has been definitely confirmed that it can run on ADOdb 5.01beta to ADOdb 5.22.5 via CI, of course dependent on PHP version being tested on.
Along with maintaining compatibility with PHP 4.0.4+ to 8x, we try to do the same for required libraries.

As a a maintainer of an Open Source project, I try not to engage in, "blocking the user's freedom", especially on a project that was around before I even knew what Open Source was.

If an end user wants to run it on PHP 4x with ADOdb 1x, the app should work if possible.
If an end user wants to run it on PHP 8x, then of necessity, they will need to use a newer version of ADOdb; and the app should work if possible.

My responsibility as an Open Source maintainer is to make sure that it does work, if possible.
I have no knowledge of, or control of, the installation configuration that and end user will deploy it in.

**Comment by dregad** [comment]
Its very noble of you, to go to such extent to maintain backwards compatibility. So you're actually still supporting PHP 4 😱 ?

In an ideal world I would probably try to do the same, but considering that I do this on my spare time and only have a finite amount of that to spend on open source, it's not worth the effort (not to mention sometimes even not technically possible) to ensure an application work on legacy PHP versions and software components that have been out of support for so many years. Dropping compatibility with old PHP was a choice we made so we could leverage new language features and make use of 3rd party libraries, and reduce maintenance effort at the same time.

Anyway, nice to hear you're such an old and faithful customer 😃 
Out of curiosity, what is that application you're maintaining ?

> I did look for it in your [Reference Manual](https://adodb.org/dokuwiki/doku.php?id=v5:reference:reference_index) before submitting this. Didn't see it in there. You may want to fix that.

Absolutely. Tracked in #977.

**Comment by NathanGibbs3** [comment]
I completely understand the challenges of Open Source Development, limited time, limited resources, incomplete documentation, being buried under bug reports, the amount of effort & time needed to maintain a project, and the technical impossibility of some things, etc.
I did not intend to & do not intend to disrespect the ADOdb dev team's decisions to drop support for older PHP versions, or DB drivers.  You simply cannot do everything, especially if the ADOdb dev "team" is just you. I apologize if I came across like that.

The application that I maintain is [BASE](https://github.com/NathanGibbs3/BASE). Basic Analysis and Security Engine, originally by @secureideas. BASE is a fork from the [ACID](https://www.andrew.cmu.edu/user/rdanyliw/snort/snortacid.html) project by Roman Danyliw.

ACID originally required ADOdb 0.93+ in 2001.
The initial release of BASE required ADOdb 1.2+ in 2004.

As the core functionality of the application has not changed, I've been able to maintain backward compatibility, while leveraging functionality of newer versions of PHP or other components, such as ADOdb.
The day may come when it becomes necessary to drop support for older versions of things, but at the moment, we have been able to keep backward compatibility in place.

This [page from our wiki](https://github.com/NathanGibbs3/BASE/wiki/ADOdb-version-requirements-by-PHP-Version) documentst our experience with ADOdb in CI tests and provides some anecdotal historic documentation.

**Comment by dregad** [comment]
Nice ! Thanks for the info, it's always interesting to know a bit more about who is using your project 😃 

And don't worry there was no offense taken, I was just explaining why I cannot afford the same level of support / backwards compatibility. 

ADOdb is just me, Mark (who is quite busy at the moment) and occasional contributors, so indeed resources are scarce...
