### ISSUE TITLE
mysqli: metacolumns() returning different info.

### ISSUE THREAD

**Issue by NathanGibbs3** [ADOdb/ADOdb#980]
### Description
The `metacolumns()` function is returning different info in the master branch compared to the last release.

### Environment
- ADOdb version: d4f9f45737830b90ea69df9bbf9a340618dd7d22
- Driver or Module: mysqli
- Database type and version: MySQL 10.3.23 - 14.14
- PHP version: 7.0.25 - 8.1.12
- Platform: Linux

* [X] I have tested that the problem is reproducible in the **master** branch 

### Steps to reproduce
Detailed, step-by-step instructions to reproduce the behavior, including:
- Code to reproduce & compare with 5.22.5
```php
$lib = 0; // 0 use 5.22.5 release 1 use snapshot of master branch.
$driver = 'mysqli';

$svr = 'db';
$usr = 'test';
$pwd = 'password';

$DB = 'test';
$tbl = 'test';
$fld = 'test';

if ( $lib == 0 ){
    include('../../ADOdb-5.22.5/adodb.inc.php');
}else{
    include('../../ADOdb/adodb.inc.php');
}

$db = newAdoConnection($driver);
$db->connect($svr, $usr, $pwd, $DB);
$mctmp = $db->metacolumns($tbl);

print $db->Version()."\n";
print $db->isConnected()."\n";
print $db->ErrorMsg()."\n";
var_dump($mctmp[strtoupper($fld)]->max_length);
```
- SQL to create and populate database objects used by the code snippet
```
CREATE TABLE test ( test VARCHAR(255) );
```

### Expected behavior
master branch code returns 255.

### Additional context 
Found this while working on #978 
Reproduced locally and in CI.

**Comment by dregad** [comment]
Thanks for the bug report. 

According to git bisect, the culprit is 5c9e24cf98409004da2a5e5bd80eeec82c5a3997. I'll look into it.

**Comment by dregad** [comment]
So the problem is caused by using $mode parameter instead of class property $adodbFetchMode (set by parent constructor). Problem is also present in other drivers, will add relevant tags.

**Comment by dregad** [comment]
Removing the 5.23.0 milestone, since the commit that introduced the regression was never part of an official release.

**Comment by NathanGibbs3** [comment]
> Thanks for the bug report.
> 
> According to git bisect, the culprit is [5c9e24c](https://github.com/ADOdb/ADOdb/commit/5c9e24cf98409004da2a5e5bd80eeec82c5a3997). I'll look into it.

Oh, one of those. :smile:
Fix an overarching issue in the app's architecture; then the wheels fall off everywhere else.
Usually because the app made assumptions based on the now corrected bug, or compensated for it in some way that is no longer applicable.
I've done it too, fix one bug, find 10 more. as a result.  In the end the codebase gets better. 👍

**Comment by NathanGibbs3** [comment]
It looks like the parent class `$fetchMode` variable is not propagating down to the drivers.
Probably this at the beginning of the drivers will set things right.
```php
if ($mode === false) {
	$mode = $this->fetchMode;
}
```

Unless the `$mode` flag for the drivers doesn't need to be passed anymore in which case, simply
```php
$mode = $this->fetchMode;
```
without the if block should do it.

**Comment by NathanGibbs3** [comment]
Verified locally, both approaches to this issue correct it.
If you want, I'll go through and add the fix to the drivers changed in the git bisect above & put it together into a PR for you.
Would you want the single line or if block fix?

If you want the single line fix, is the `$mode` parameter for the drivers even necessary anymore?

**Comment by dregad** [comment]
Thanks for the offer, I have a patch ready that I'll push shortly. Got sidetracked as I started looking at your other issue 😉
