### ISSUE TITLE
mysqli: Insert_ID() - Return value clarification.

### ISSUE THREAD

**Issue by NathanGibbs3** [ADOdb/ADOdb#989]
### Description
Documentation says "If no such insertion has occurred or the database does not support the operation, the function returns false."
Calling `Insert_ID` where no such insertion has occurred returns zero.

### Environment
- ADOdb version:  5.22.6
- Driver or Module: mysqli
- Database type and version: MariaDB
- PHP version: 7.3.31
- Platform: Linux

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / **master** branch 

### Steps to reproduce
Detailed, step-by-step instructions to reproduce the behavior, including:
- Initialize an ADOdb object connected to a MySQL/MariaDB DB using the mysqli driver.
- Call `Insert_ID()`.

### Expected behavior
Would expect `Insert_ID()` to return false as per the [documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:insert_id).

### Additional context 
I was tightening up a project's code to follow the ADODB documentation more closely, when some Unit Tests blew.
the old code used the `==` operator.
The new code used the `===` operator.
 `if( $Ret === false ){ // No Insert or DB does not support InsertID.`

Solutions:
1. Tighten up the ADOdb code to return false in no insertion situations.
2.  Loosen up the documentation. Maybe something like `If no such insertion has occurred or the database does not support the operation, the function returns a value that evaluates to false.`

Not sure which way you would want to go on this, if 1, I'm willing to dive into the code. and put together a PR.

**Comment by dregad** [comment]
In an ideal world I would probably go for 2, but considering that 

- _insertID() is currently implemented in most drivers using a getOne() call with some DB-specific query to get the last ID
- getOne()'s return value will be _false_ if the query fails (call errorMsg() for details)
- if the query succeeds but last ID can't be determined, the return value is driver-specific.

The PR might be more involved than what you'd expect, because all drivers implementing Insert_ID() should be updated accordingly to be consistent.

So it's probably better to just relax the documentation, unless you really want to do the legwork. There's nothing wrong with `if (!$Ret)` IMO.

**Comment by NathanGibbs3** [comment]
> The PR might be more involved than what you'd expect, because all drivers implementing Insert_ID() should be updated accordingly to be consistent.
> 

I thought about that, and also realize that there would be no way to test all drivers and verify that the changes worked as expected.
We'd change & wait for bug reports on the drivers we couldn't test.
Also we run the small risk of breaking code that depends on the current behavior of getting a driver specific return in a no insertion situation.

> So it's probably better to just relax the documentation, unless you really want to do the legwork. There's nothing wrong with `if (!$Ret)` IMO.

I agree, relaxing the documentation is the easiest solution at the moment.

That being said, if you would like the ADOdb code to be more strict in what is returned for no insert situations, I have no issue with doing the legwork to figure it out.
However, I don't want to submit PR's that you won't or can't use.
