### ISSUE TITLE
oci8: Automatic conversion of false to array is deprecated with PHP 8.1

### ISSUE THREAD

**Issue by wesyah234** [ADOdb/ADOdb#998]
### Description
Getting adodb-oci8.inc.php:1314 Automatic conversion of false to array is deprecated
when the _query method is called.

### Environment
- ADOdb version: 5.22.6
- Driver or Module: oci8
- PHP version: 8.2
- Platform: linux

Solved by changing:
	var $_bind = false;
to:
	var $_bind = array();

though I'm not sure that's the solution you'd like to go with so I'll just let you decide how to handle.

Thanks!

**Comment by dregad** [comment]
Your proposed fix was spot on, thanks !
